roles-checking
saltastroops/salt-api pull request #109
Opened 2022-11-03 10:51 UTC by mofokeng-chaka

Use Role for permission checking

2022-11-04 14:04 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 8 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/permission_service.py` line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1teH05JjLirP9FsYz:-NG1teH05JjLirP9FsZ-:b-7p4g0z) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L8)):*
> ```Python
> from saltapi.repository.user_repository import UserRepository
> from saltapi.service.user import Role, User
> from saltapi.service.user_role_service import UserRoleService
> ```

Do you really need a separate service for user roles?
___
*[`saltapi/service/permission_service.py` line 11 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1tThgEJOnozfRtv4H:-NG1tThgEJOnozfRtv4I:ba6tiih) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L11)):*
> ```Python
> 
> 
> def has_permissions(user_roles: List[Role], permitted_user_roles: List[Role]) -> None:
> ```

The name `has_permission` suggests that you return a boolean.
___
*[`saltapi/service/permission_service.py` line 234 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1vDE842kVD2PTt3UP:-NG1vDE842kVD2PTt3UQ:b-tl6pdp) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L234)):*
> ```Python
>         * an administrator
>         """
>         self.check_permission_to_update_proposal_status(user)
> ```

If you make this change, you should update the docstring accordingly.
___
*[`saltapi/service/permission_service.py` line 260 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1vhWM4L9pOJtkmDmB:-NG1vhWM4L9pOJtkmDmC:b-tl6pdp) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L260)):*
> ```Python
>         details.
>         """
>         self.check_permission_to_view_user(user, updated_user_id)
> ```

If you make this change, you should update the docstring accordingly.
___
*[`saltapi/service/permission_service.py` line 268 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1w4Ca2ebUII5nRXdg:-NG1w4Ca2ebUII5nRXdh:bkyaynw) ([raw file](https://github.com/saltastroops/salt-api/blob/412895f62a9da44f373ab1718ca5a97d7179d566/saltapi/service/permission_service.py#L268)):*
> ```Python
>             raise AuthorizationError()
> 
>     def check_permission_to_view_mos_metadata(self, user: User) -> None:
> ```

I guess the method name should be `check_permission_to_view_mos_mask_metadata`, and that engineers are allowed to view the data as well.
___
*[`saltapi/service/permission_service.py` line 283 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1vws-0YT4d__F2AFJ:-NG1vws-0YT4d__F2AFK:b-xnnhio) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L283)):*
> ```Python
>     def check_permission_to_update_mos_mask_metadata(self, user: User) -> None:
>         """
>         Check whether the user can update a slit mask.
> ```

Maybe better: Check whether the user can update a MOS mask metadata.
___
*[`saltapi/service/permission_service.py` line 306 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1wVaq0LDNc09700my:-NG1wVaq0LDNc09700mz:ba0jc0v) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L306)):*
> ```Python
>     ) -> None:
>         """
>         Check whether the user can update proposal progress.
> ```

progress > progress details
___
*[`saltapi/service/user_role_service.py` line 27 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1whQEDJFdJnHVSvAc:-NG1whQEDJFdJnHVSvAd:bhh3mrg) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/user_role_service.py#L27)):*
> ```Python
>         """
>         roles = []
>         if self.user_repository.is_administrator(self.username):
> ```

This is somewhat inefficient: You are always evaluating all roles, which means there are quite a few unnecessary database queries.


<!-- Sent from Reviewable.io -->

2022-11-07 12:17 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1teH05JjLirP9FsYz:-NGGwLHi4kbuNIF-6Rho:b-m69ent) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you really need a separate service for user roles?
</blockquote></details>

Not really, I have moved this logic to the permission service file.
___
*[`saltapi/service/permission_service.py` line 11 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1tThgEJOnozfRtv4H:-NGGvCryBTqMLu2KEsFW:b-6bt5kg) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name `has_permission` suggests that you return a boolean.
</blockquote></details>

I have removed this function.
___
*[`saltapi/service/permission_service.py` line 234 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1vDE842kVD2PTt3UP:-NGGxE-862UgZkDBLOtj:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L234)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you make this change, you should update the docstring accordingly.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 260 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1vhWM4L9pOJtkmDmB:-NGGxE_LB7MbMXbCAcPq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L260)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you make this change, you should update the docstring accordingly.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 268 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1w4Ca2ebUII5nRXdg:-NGGxgng6jxoDCViBGf1:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/412895f62a9da44f373ab1718ca5a97d7179d566/saltapi/service/permission_service.py#L268)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess the method name should be `check_permission_to_view_mos_mask_metadata`, and that engineers are allowed to view the data as well.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 283 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1vws-0YT4d__F2AFJ:-NGGxylI58_7CFLJzd4k:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L283)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: Check whether the user can update a MOS mask metadata.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 306 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1wVaq0LDNc09700my:-NGGy3sk6V2WZG807K23:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L306)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

progress > progress details
</blockquote></details>

Done.
___
*[`saltapi/service/user_role_service.py` line 27 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1whQEDJFdJnHVSvAc:-NGGy9EDBA4tJsahBWVP:blrqaz1) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/user_role_service.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is somewhat inefficient: You are always evaluating all roles, which means there are quite a few unnecessary database queries.
</blockquote></details>

That's true and I have removed this code.


<!-- Sent from Reviewable.io -->

2022-11-07 17:05 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 6 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/permission_service.py` line 208 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGI0MfJ1x6lESO6dej8:-NGI0MfJ1x6lESO6dej9:b-9kfnsy) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L208)):*
> ```Python
>         * an administrator
>         """
>         self.check_permission_to_update_proposal_status(user)
> ```

Actually I think this is incorrect. The PI and PC should be able to put a block on and off hold. Incidentally, toggling between `Active` and `On hold` is all the API should allow.
___
*[`saltapi/service/permission_service.py` line 234 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1vDE842kVD2PTt3UP:-NGI1o3K6LC4o_RgpheB:b-x77lt4) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L234)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thinking about it, I'm not entirely convinced you should assume that the permissions for changing a proposal status and a block visit status are necessarily the same.
___
*[`saltapi/service/permission_service.py` line 268 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1w4Ca2ebUII5nRXdg:-NGI1WcJ5aWkqdn4SEEa:b-m02ykz) ([raw file](https://github.com/saltastroops/salt-api/blob/412895f62a9da44f373ab1718ca5a97d7179d566/saltapi/service/permission_service.py#L268)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think you aded the engineers?
___
*[`saltapi/service/permission_service.py` line 283 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1vws-0YT4d__F2AFJ:-NGI2Ad96DhZRB_iWCKx:b-2lx24m) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L283)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops. "update a MOS mask metadata" should have read "update MOS mail metadata" (no "a").
___
*[`saltapi/service/permission_service.py` line 21 at r2](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGHyqWK7-1r60MtjfN_:-NGHyqWK7-1r60MtjfNa:b2yp943) ([raw file](https://github.com/saltastroops/salt-api/blob/654332f812248f25269c1c5652d602125ccae4c8/saltapi/service/permission_service.py#L21)):*
> ```Python
>         self.block_repository = block_repository
> 
>     def user_has_role(
> ```

I'd suggest to use `None` as default value for `proposal_code` and `role`, so that you don't have to pass them when they are irrelevant.
___
*[`saltapi/service/permission_service.py` line 86 at r2](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGHzH33-yCSWhCW7Ku3:-NGHzH33-yCSWhCW7Ku4:b-6nra0f) ([raw file](https://github.com/saltastroops/salt-api/blob/654332f812248f25269c1c5652d602125ccae4c8/saltapi/service/permission_service.py#L86)):*
> ```Python
>     ) -> None:
>         """
>         Check whether the user has permissions to perform a specific action
> ```

I'd argue that both the name and the docstring would suggest that the user needs to have _all_ of the roles. Also, "permitted" might not be the best word. Just `roles` might do, perhaps. Also, I' suggest not to use `permissions` in the name -- the function is rather checking whether the user has a role.
___
*[`saltapi/service/permission_service.py` line 90 at r2](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGI-kgZ4f6C5PzDZ24a:-NGI-kgZ4f6C5PzDZ24b:brw3wf6) ([raw file](https://github.com/saltastroops/salt-api/blob/654332f812248f25269c1c5652d602125ccae4c8/saltapi/service/permission_service.py#L90)):*
> ```Python
>         """
>         has_permissions = []
>         for role in permitted_user_roles:
> ```

You can make the slightly better performing if you return `True` immediately if you find a role the user has.
___
*[`saltapi/service/permission_service.py` line 91 at r2](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGI-5CxAky3R9qrdxYb:-NGI-5CxAky3R9qrdxYc:b-8ht7ds) ([raw file](https://github.com/saltastroops/salt-api/blob/654332f812248f25269c1c5652d602125ccae4c8/saltapi/service/permission_service.py#L91)):*
> ```Python
>         has_permissions = []
>         for role in permitted_user_roles:
>             has_permission = self.user_has_role(username, proposal_code, role)
> ```

See remark on permissions above.


<!-- Sent from Reviewable.io -->

2022-11-08 06:24 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 208 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGI0MfJ1x6lESO6dej8:-NGKlN2N4YRnd7-QKmj0:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L208)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Actually I think this is incorrect. The PI and PC should be able to put a block on and off hold. Incidentally, toggling between `Active` and `On hold` is all the API should allow.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 234 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1vDE842kVD2PTt3UP:-NGKmBTIEMkrM1mhPGfa:b-j3hnl9) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L234)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thinking about it, I'm not entirely convinced you should assume that the permissions for changing a proposal status and a block visit status are necessarily the same.
</blockquote></details>

I have updated it accordingly.
___
*[`saltapi/service/permission_service.py` line 268 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1w4Ca2ebUII5nRXdg:-NGKmjiEDqfocR4a9uFG:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/412895f62a9da44f373ab1718ca5a97d7179d566/saltapi/service/permission_service.py#L268)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you aded the engineers?
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 283 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG1vws-0YT4d__F2AFJ:-NGKmtqR-PzCuS7Zghjt:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L283)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oops. "update a MOS mask metadata" should have read "update MOS mail metadata" (no "a").
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 21 at r2](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGHyqWK7-1r60MtjfN_:-NGKjMPo5lzq3plTnOiQ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/654332f812248f25269c1c5652d602125ccae4c8/saltapi/service/permission_service.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to use `None` as default value for `proposal_code` and `role`, so that you don't have to pass them when they are irrelevant.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 86 at r2](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGHzH33-yCSWhCW7Ku3:-NGKjNGh1rElcdrtB9vv:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/654332f812248f25269c1c5652d602125ccae4c8/saltapi/service/permission_service.py#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd argue that both the name and the docstring would suggest that the user needs to have _all_ of the roles. Also, "permitted" might not be the best word. Just `roles` might do, perhaps. Also, I' suggest not to use `permissions` in the name -- the function is rather checking whether the user has a role.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 90 at r2](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGI-kgZ4f6C5PzDZ24a:-NGKjQKY9a0l8ZHLd4KB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/654332f812248f25269c1c5652d602125ccae4c8/saltapi/service/permission_service.py#L90)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You can make the slightly better performing if you return `True` immediately if you find a role the user has.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 91 at r2](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGI-5CxAky3R9qrdxYb:-NGKjRotC2s43n7gVuG3:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/654332f812248f25269c1c5652d602125ccae4c8/saltapi/service/permission_service.py#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See remark on permissions above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-08 07:58 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/permission_service.py` line 208 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGI0MfJ1x6lESO6dej8:-NGLDNuB8TfNNGIJaq6x:b-gc6ufz) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L208)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not quite. :) You still allow any block status change. But no status other than `Active` or `On Hold` should be allowed, at least for now.
___
*[`saltapi/service/permission_service.py` line 90 at r2](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGI-kgZ4f6C5PzDZ24a:-NGLBGO205hu6qBeF7Tq:b-lg5s62) ([raw file](https://github.com/saltastroops/salt-api/blob/654332f812248f25269c1c5652d602125ccae4c8/saltapi/service/permission_service.py#L90)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You misunderstood me (and my comment was not 100 % correct). My issue is that you always check all roles, even if you could be done after the first check. But yiu could avoid this by doing something like:

```
has_role = False
for role in roles:
    if self.user_has_role(username, role, proposal_code):
        has_role = True
        break
if not has_role:
    raise AuthorizationError()
````
___
*[`saltapi/service/permission_service.py` line 89 at r3](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGLAeSp3UNl1DWnmdK3:-NGLAeSq2Ie4ufGz4OIT:b-7ewp68) ([raw file](https://github.com/saltastroops/salt-api/blob/cdcfb3f9bf6b04edec95e865e327223de035e989/saltapi/service/permission_service.py#L89)):*
> ```Python
>     ) -> None:
>         """
>         Check whether the user has a role.
> ```

How about: Check whether the user has at least one of a given list of roles.


<!-- Sent from Reviewable.io -->

2022-11-08 10:02 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 208 at r1](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGI0MfJ1x6lESO6dej8:-NGLPn0ZDYP9ai82Ut8V:b-76zhl8) ([raw file](https://github.com/saltastroops/salt-api/blob/cc43361587a6db953561ff7d1c82f0f3836e1b74/saltapi/service/permission_service.py#L208)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Not quite. :) You still allow any block status change. But no status other than `Active` or `On Hold` should be allowed, at least for now.
</blockquote></details>

I have added this functionality to block service.
___
*[`saltapi/service/permission_service.py` line 90 at r2](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGI-kgZ4f6C5PzDZ24a:-NGLM7nFCrcJFKhnqRr9:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/654332f812248f25269c1c5652d602125ccae4c8/saltapi/service/permission_service.py#L90)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You misunderstood me (and my comment was not 100 % correct). My issue is that you always check all roles, even if you could be done after the first check. But yiu could avoid this by doing something like:

```
has_role = False
for role in roles:
    if self.user_has_role(username, role, proposal_code):
        has_role = True
        break
if not has_role:
    raise AuthorizationError()
````
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 89 at r3](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGLAeSp3UNl1DWnmdK3:-NGLMFsX7E6K7tXa12T7:b-qrdnhx) ([raw file](https://github.com/saltastroops/salt-api/blob/cdcfb3f9bf6b04edec95e865e327223de035e989/saltapi/service/permission_service.py#L89)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about: Check whether the user has at least one of a given list of roles.
</blockquote></details>

I have updated the docstring now.


<!-- Sent from Reviewable.io -->

2022-11-08 12:15 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 6 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/block_repository.py` line 161 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM85tJ6fxjAaC_U0qm:-NGM85tJ6fxjAaC_U0qn:bnxlac6) ([raw file](https://github.com/saltastroops/salt-api/blob/d2ddaa3690896ed63b8a90671edfc6d257664eb5/saltapi/repository/block_repository.py#L161)):*
> ```Python
>         Update the status of a block.
>         """
>         if value == "On hold":
> ```

These lines are necessary, I think; there is a mismatch between the API and the database.

And the mismatch should be handled here, as this is the only place where database internals should be of concern.
___
*[`saltapi/service/block_service.py` line 35 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM8kaB68lD-0uIppqH:-NGM8kaC3MGcAE7660p4:bjftldt) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/saltapi/service/block_service.py#L35)):*
> ```Python
>         """
> 
>         allowed_status_list = ["Active", "On Hold"]
> ```

"On Hold" > "On hold"
___
*[`saltapi/service/block_service.py` line 36 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM8cNMBi5k3lY0O3ZS:-NGM8cNMBi5k3lY0O3ZT:b-18liq1) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/saltapi/service/block_service.py#L36)):*
> ```Python
> 
>         allowed_status_list = ["Active", "On Hold"]
>         if status == "On hold":
> ```

See comment on `block_repository.py`.
___
*[`saltapi/service/block_service.py` line 39 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM8rZZ2dZmXk4mivyN:-NGM8rZZ2dZmXk4mivyO:b-emoqfw) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/saltapi/service/block_service.py#L39)):*
> ```Python
>             status = "On Hold"
>         if status not in allowed_status_list:
>             raise NotFoundError(f"Unknown block status: {status}")
> ```

"Unknown" might be misleading. Maybe better: "You are not allowed to set the block status to {status}."
___
*[`tests/service/test_block_service.py` line 42 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM9F3a0LA7YkYpUc3q:-NGM9F3a0LA7YkYpUc3r:b-18liq1) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/tests/service/test_block_service.py#L42)):*
> ```Python
>     def get_block_status(self, block_id: int) -> BlockStatus:
>         if block_id == VALID_BLOCK_ID:
>             if self.block_status["value"] == "On hold":
> ```

See comment on `block_repository.py`.
___
*[`tests/service/test_block_service.py` line 51 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM9NRJ7k3QOKmvJz0S:-NGM9NRJ7k3QOKmvJz0T:b-18liq1) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/tests/service/test_block_service.py#L51)):*
> ```Python
>     ) -> None:
>         if block_id == VALID_BLOCK_ID:
>             if value == "On hold":
> ```

See comment on `block_repository.py`.


<!-- Sent from Reviewable.io -->

2022-11-08 20:04 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 7 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/block_service.py` line 40 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGNpkne4nGjyy2mDrOx:-NGNpkne4nGjyy2mDrOy:b-d6yshd) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/saltapi/service/block_service.py#L40)):*
> ```Python
>         if status not in allowed_status_list:
>             raise NotFoundError(f"Unknown block status: {status}")
>         return self.block_repository.update_block_status(block_id, status, reason)
> ```

Also, it's not a 404 but rather a 400 error.

And a test for it would be good to have...


<!-- Sent from Reviewable.io -->

2022-11-09 10:50 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: 6 of 9 files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/block_repository.py` line 161 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM85tJ6fxjAaC_U0qm:-NGQpLLK-d1AmAwQbdQl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d2ddaa3690896ed63b8a90671edfc6d257664eb5/saltapi/repository/block_repository.py#L161)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

These lines are necessary, I think; there is a mismatch between the API and the database.

And the mismatch should be handled here, as this is the only place where database internals should be of concern.
</blockquote></details>

Done.
___
*[`saltapi/service/block_service.py` line 35 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM8kaB68lD-0uIppqH:-NGQpLzY8gmKGHX4arWy:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/saltapi/service/block_service.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"On Hold" > "On hold"
</blockquote></details>

Done.
___
*[`saltapi/service/block_service.py` line 36 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM8cNMBi5k3lY0O3ZS:-NGQpOCnDAjoifSVB8Ga:b-pkr2z7) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/saltapi/service/block_service.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment on `block_repository.py`.
</blockquote></details>

I have removed this logic and put it in the repository.
___
*[`saltapi/service/block_service.py` line 39 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM8rZZ2dZmXk4mivyN:-NGQq1juC3vwVANJ42vV:bbrsgor) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/saltapi/service/block_service.py#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Unknown" might be misleading. Maybe better: "You are not allowed to set the block status to {status}."
</blockquote></details>

That is true, as per our agreement, I am not raising AuthorizationError.
___
*[`saltapi/service/block_service.py` line 40 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGNpkne4nGjyy2mDrOx:-NGQqANX0TMs9OgWeXzZ:bloz0ef) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/saltapi/service/block_service.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Also, it's not a 404 but rather a 400 error.

And a test for it would be good to have...
</blockquote></details>

I agree with you. I have added a test as well.
___
*[`tests/service/test_block_service.py` line 42 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM9F3a0LA7YkYpUc3q:-NGQzP3pATcqhq30PKS7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/tests/service/test_block_service.py#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment on `block_repository.py`.
</blockquote></details>

Done.
___
*[`tests/service/test_block_service.py` line 51 at r4](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGM9NRJ7k3QOKmvJz0S:-NGQzPbR66nu6rc_zjDd:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/504c69e4975c1e48c512ebfcaf1c260a8acdf566/tests/service/test_block_service.py#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment on `block_repository.py`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-10 14:13 UTC, hettlage requested changes
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`tests/service/test_block_service.py` line 136 at r5](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGWsSAC83XcTMRKCTkY:-NGWsSAC83XcTMRKCTkZ:bm3l44o) ([raw file](https://github.com/saltastroops/salt-api/blob/099730328fa29466f8d029abec79ff6a61fdbe9e/tests/service/test_block_service.py#L136)):*
> ```Python
> 
> 
> def test_update_block_status_raises_error_for_wrong_block_status() -> None:
> ```

I think you should test against all the forbidden values -- poarametrizing is in order here, I think.

But more importantly, aren't you effectively testing the mock repository? So adding an integration test might be a good idea.


<!-- Sent from Reviewable.io -->

2022-11-11 06:37 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`tests/service/test_block_service.py` line 136 at r5](https://reviewable.io/reviews/saltastroops/salt-api/109#-NGWsSAC83XcTMRKCTkY:-NG_MdkI1XaVou7rP19y:b-pyckfz) ([raw file](https://github.com/saltastroops/salt-api/blob/099730328fa29466f8d029abec79ff6a61fdbe9e/tests/service/test_block_service.py#L136)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you should test against all the forbidden values -- poarametrizing is in order here, I think.

But more importantly, aren't you effectively testing the mock repository? So adding an integration test might be a good idea.
</blockquote></details>

I am now testing against all forbidden values.

I have also included integration testing.


<!-- Sent from Reviewable.io -->

2022-11-11 09:28 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`tests/integration/blocks/test_update_block_status.py` line 99 at r6](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG_zX2KBpygFl1JDM9X:-NG_zX2KBpygFl1JDM9Y:bdq0bd2) ([raw file](https://github.com/saltastroops/salt-api/blob/8f1ec59d01380ba8bac25160311e6e52fad2da78/tests/integration/blocks/test_update_block_status.py#L99)):*
> ```Python
>     new_block_status = response.json()
> 
>     assert new_block_status["value"] == block_status
> ```

It might be even better to explicitly download the updated block (status) for the checking rather than relying on the response by the PUT request.


<!-- Sent from Reviewable.io -->

2022-11-11 09:35 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/integration/blocks/test_update_block_status.py` line 99 at r6](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG_zX2KBpygFl1JDM9X:-NGa1HLz5CH58mLtKre5:b-gjlq6f) ([raw file](https://github.com/saltastroops/salt-api/blob/8f1ec59d01380ba8bac25160311e6e52fad2da78/tests/integration/blocks/test_update_block_status.py#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be even better to explicitly download the updated block (status) for the checking rather than relying on the response by the PUT request.
</blockquote></details>

I don't think it will be necessary because the endpoint is set up to do this already. After a put request, the updated block status is downloaded.


<!-- Sent from Reviewable.io -->

2022-11-11 09:50 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`tests/integration/blocks/test_update_block_status.py` line 99 at r6](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG_zX2KBpygFl1JDM9X:-NGa4Cny8hXzSulyP8JJ:b-evmdpw) ([raw file](https://github.com/saltastroops/salt-api/blob/8f1ec59d01380ba8bac25160311e6e52fad2da78/tests/integration/blocks/test_update_block_status.py#L99)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I don't think it will be necessary because the endpoint is set up to do this already. After a put request, the updated block status is downloaded.
</blockquote></details>

This may be a bit of a cheeky comment, but: You are effectively saying "I don't need to test this because I trust the endpoint code."


<!-- Sent from Reviewable.io -->

2022-11-11 10:24 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/integration/blocks/test_update_block_status.py` line 99 at r6](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG_zX2KBpygFl1JDM9X:-NGaBR_J3XznuYn1iFt5:bdbtugl) ([raw file](https://github.com/saltastroops/salt-api/blob/8f1ec59d01380ba8bac25160311e6e52fad2da78/tests/integration/blocks/test_update_block_status.py#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This may be a bit of a cheeky comment, but: You are effectively saying "I don't need to test this because I trust the endpoint code."
</blockquote></details>

I didn't mean it that way. What I mean is that I will be making two HTTP requests that do the same thing, so the second request is somehow not needed. But I will add the test.


<!-- Sent from Reviewable.io -->

2022-11-11 11:35 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/integration/blocks/test_update_block_status.py` line 99 at r6](https://reviewable.io/reviews/saltastroops/salt-api/109#-NG_zX2KBpygFl1JDM9X:-NGaSzZ80YThk8BviFDS:bub11pd) ([raw file](https://github.com/saltastroops/salt-api/blob/8f1ec59d01380ba8bac25160311e6e52fad2da78/tests/integration/blocks/test_update_block_status.py#L99)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I didn't mean it that way. What I mean is that I will be making two HTTP requests that do the same thing, so the second request is somehow not needed. But I will add the test.
</blockquote></details>

I have now tested that the endpoint does the update by doing another request.


<!-- Sent from Reviewable.io -->

2022-11-13 10:44 UTC, hettlage approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2022-11-13 10:44 UTC, merged