Permission checking
saltastroops/salt-api pull request #123
Opened 2022-11-14 12:19 UTC by mofokeng-chaka

2022-11-15 20:21 UTC, hettlage requested changes
> Reviewed 1 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/permission_service.py` line 327 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwsXPP5YU6GwWSXzn4:-NGwsXPP5YU6GwWSXzn5:bl4dzcu) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L327)):*
> ```Python
>     def check_permission_to_view_users(self, user: User) -> None:
>         """
>         Check whether the user may update a user.
> ```

Sorry, I hadn't spotted this before, but this docstring is incorrect.
___
*[`saltapi/service/permission_service.py` line 329 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwsiVvEPYroOTB0uQh:-NGwsiVvEPYroOTB0uQi:b-a2wvgr) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L329)):*
> ```Python
>         Check whether the user may update a user.
> 
>         This is the case if the user may update a user.
> ```

According to the code, this should read: This is the case if the user is an administrator.
___
*[`saltapi/service/permission_service.py` line 414 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwwMf203dNRjbSpRtu:-NGwwMf203dNRjbSpRtv:b-o1v6du) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L414)):*
> ```Python
> 
>         roles = [
>             Role.PRINCIPAL_INVESTIGATOR,
> ```

The roles are incorrect (see the docstriong; the roles should be SA, SO and admin).


<!-- Sent from Reviewable.io -->

2022-11-15 20:21 UTC, hettlage requested changes
> Reviewed 1 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/permission_service.py` line 327 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwsXPP5YU6GwWSXzn4:-NGwsXPP5YU6GwWSXzn5:bl4dzcu) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L327)):*
> ```Python
>     def check_permission_to_view_users(self, user: User) -> None:
>         """
>         Check whether the user may update a user.
> ```

Sorry, I hadn't spotted this before, but this docstring is incorrect.
___
*[`saltapi/service/permission_service.py` line 329 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwsiVvEPYroOTB0uQh:-NGwsiVvEPYroOTB0uQi:b-a2wvgr) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L329)):*
> ```Python
>         Check whether the user may update a user.
> 
>         This is the case if the user may update a user.
> ```

According to the code, this should read: This is the case if the user is an administrator.
___
*[`saltapi/service/permission_service.py` line 414 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwwMf203dNRjbSpRtu:-NGwwMf203dNRjbSpRtv:b-o1v6du) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L414)):*
> ```Python
> 
>         roles = [
>             Role.PRINCIPAL_INVESTIGATOR,
> ```

The roles are incorrect (see the docstriong; the roles should be SA, SO and admin).


<!-- Sent from Reviewable.io -->

2022-11-15 20:21 UTC, hettlage requested changes
> Reviewed 1 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/permission_service.py` line 327 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwsXPP5YU6GwWSXzn4:-NGwsXPP5YU6GwWSXzn5:bl4dzcu) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L327)):*
> ```Python
>     def check_permission_to_view_users(self, user: User) -> None:
>         """
>         Check whether the user may update a user.
> ```

Sorry, I hadn't spotted this before, but this docstring is incorrect.
___
*[`saltapi/service/permission_service.py` line 329 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwsiVvEPYroOTB0uQh:-NGwsiVvEPYroOTB0uQi:b-a2wvgr) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L329)):*
> ```Python
>         Check whether the user may update a user.
> 
>         This is the case if the user may update a user.
> ```

According to the code, this should read: This is the case if the user is an administrator.
___
*[`saltapi/service/permission_service.py` line 414 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwwMf203dNRjbSpRtu:-NGwwMf203dNRjbSpRtv:b-o1v6du) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L414)):*
> ```Python
> 
>         roles = [
>             Role.PRINCIPAL_INVESTIGATOR,
> ```

The roles are incorrect (see the docstriong; the roles should be SA, SO and admin).


<!-- Sent from Reviewable.io -->

2022-11-15 20:28 UTC, hettlage requested changes
> Reviewed 1 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/permission_service.py` line 414 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwwMf203dNRjbSpRtu:-NGwwMf203dNRjbSpRtv:b3nf4cb) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L414)):*
> ```Python
> 
>         roles = [
>             Role.PRINCIPAL_INVESTIGATOR,
> ```

The roles are incorrect (see the docstring; the roles should be SA, SO and admin).

And the fact that all tests are passing suggests that tests are missing for this method (or, more importantly, the endpoint using it).


<!-- Sent from Reviewable.io -->

2022-11-16 05:34 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 327 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwsXPP5YU6GwWSXzn4:-NGyn2YFEHE4rm-MZvLa:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L327)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, I hadn't spotted this before, but this docstring is incorrect.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 329 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwsiVvEPYroOTB0uQh:-NGyn6tB84qVNArhQTp8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L329)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

According to the code, this should read: This is the case if the user is an administrator.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 414 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwwMf203dNRjbSpRtu:-NGynhVA6kVgKm28Ya5v:b-b8jk09) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L414)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The roles are incorrect (see the docstring; the roles should be SA, SO and admin).

And the fact that all tests are passing suggests that tests are missing for this method (or, more importantly, the endpoint using it).
</blockquote></details>

Not all tests are passing, in fact, only one test is being run in the workflow and that test doesn't depend on this method. 
However, I have updated the tox.ini file to run all the tests and I can confirm that they are all passing. 


<!-- Sent from Reviewable.io -->

2022-11-16 09:25 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/permission_service.py` line 414 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwwMf203dNRjbSpRtu:-NGzk7OG054uwmYjHKm5:b-li5u4l) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L414)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Not all tests are passing, in fact, only one test is being run in the workflow and that test doesn't depend on this method. 
However, I have updated the tox.ini file to run all the tests and I can confirm that they are all passing. 
</blockquote></details>

Fair point. But they also pass with the wrong roles, and hence there must be some test missing...
___
*[`saltapi/service/permission_service.py` line 327 at r3](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGzjsiU0hqTf5rfL7ym:-NGzjsiU0hqTf5rfL7yn:bggvln0) ([raw file](https://github.com/saltastroops/salt-api/blob/4d743a541ebecae93fd633a5a5f01ba0fce33b4a/saltapi/service/permission_service.py#L327)):*
> ```Python
>     def check_permission_to_view_users(self, user: User) -> None:
>         """
>         Check whether the user may view a list of users.
> ```

view a > view the ?


<!-- Sent from Reviewable.io -->

2022-11-18 09:16 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 414 at r2](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGwwMf203dNRjbSpRtu:-NH8tcISBqBdIlCoQdE5:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8895a37c0b21f4b43799008b98ec2751d39f36a9/saltapi/service/permission_service.py#L414)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Fair point. But they also pass with the wrong roles, and hence there must be some test missing...
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 327 at r3](https://reviewable.io/reviews/saltastroops/salt-api/123#-NGzjsiU0hqTf5rfL7ym:-NH8sEI45Cdmc7ppllRg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d743a541ebecae93fd633a5a5f01ba0fce33b4a/saltapi/service/permission_service.py#L327)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

view a > view the ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-18 12:39 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`tests/integration/blocks/test_get_current_block.py` line 158 at r4](https://reviewable.io/reviews/saltastroops/salt-api/123#-NH9jK8B5ZCZi9IoBTQr:-NH9jK8D6m5eCkNd-1Ia:b-6y4p0n) ([raw file](https://github.com/saltastroops/salt-api/blob/45485062b1f4ff3fb3be38593d6a49d312be34a4/tests/integration/blocks/test_get_current_block.py#L158)):*
> ```Python
>     authenticate(username, client)
> 
>     monkeypatch.setattr(
> ```

I don't think mocking is necessary here.
___
*[`tests/integration/blocks/test_get_next_scheduled_block.py` line 160 at r4](https://reviewable.io/reviews/saltastroops/salt-api/123#-NH9jp2QDGFc3lK_FqVm:-NH9jp2QDGFc3lK_FqVn:b-6y4p0n) ([raw file](https://github.com/saltastroops/salt-api/blob/45485062b1f4ff3fb3be38593d6a49d312be34a4/tests/integration/blocks/test_get_next_scheduled_block.py#L160)):*
> ```Python
>     authenticate(username, client)
> 
>     monkeypatch.setattr(
> ```

I don't think mocking is necessary here.


<!-- Sent from Reviewable.io -->

2022-11-18 13:06 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`tests/integration/blocks/test_get_current_block.py` line 158 at r4](https://reviewable.io/reviews/saltastroops/salt-api/123#-NH9jK8B5ZCZi9IoBTQr:-NH9pCip75XPFNgx_bJG:bqmtj4w) ([raw file](https://github.com/saltastroops/salt-api/blob/45485062b1f4ff3fb3be38593d6a49d312be34a4/tests/integration/blocks/test_get_current_block.py#L158)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think mocking is necessary here.
</blockquote></details>

I think it is because the service depends on external requests that get the XML file from which the block_id is extracted.
___
*[`tests/integration/blocks/test_get_next_scheduled_block.py` line 160 at r4](https://reviewable.io/reviews/saltastroops/salt-api/123#-NH9jp2QDGFc3lK_FqVm:-NH9pbgR4_K3x5JR6Txa:b-bsc80q) ([raw file](https://github.com/saltastroops/salt-api/blob/45485062b1f4ff3fb3be38593d6a49d312be34a4/tests/integration/blocks/test_get_next_scheduled_block.py#L160)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think mocking is necessary here.
</blockquote></details>

Probably true, how would I then deal with the case of no scheduled block? Wouldn't that make our tests a bit flaky since we are not certain that at a given moment there is a block in the scheduler.


<!-- Sent from Reviewable.io -->

2022-11-18 14:09 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`tests/integration/blocks/test_get_current_block.py` line 158 at r4](https://reviewable.io/reviews/saltastroops/salt-api/123#-NH9jK8B5ZCZi9IoBTQr:-NHA01WF0b4gsGTY8yHH:b-g7gvvb) ([raw file](https://github.com/saltastroops/salt-api/blob/45485062b1f4ff3fb3be38593d6a49d312be34a4/tests/integration/blocks/test_get_current_block.py#L158)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I think it is because the service depends on external requests that get the XML file from which the block_id is extracted.
</blockquote></details>

Ah, yes, good point. But then you should rather mock that external request, using the responses packages (there are examples in other files). It might be a good idea to trim down the XML returned by that mock to the absolute bare minimum necessary.
___
*[`tests/integration/blocks/test_get_next_scheduled_block.py` line 160 at r4](https://reviewable.io/reviews/saltastroops/salt-api/123#-NH9jp2QDGFc3lK_FqVm:-NHA0rBqEVrMDi0h1Lmn:b-brl3fx) ([raw file](https://github.com/saltastroops/salt-api/blob/45485062b1f4ff3fb3be38593d6a49d312be34a4/tests/integration/blocks/test_get_next_scheduled_block.py#L160)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Probably true, how would I then deal with the case of no scheduled block? Wouldn't that make our tests a bit flaky since we are not certain that at a given moment there is a block in the scheduler.
</blockquote></details>

As above, you are right and I was wrong; mocking might be necessary. But even so, you should consider mocking something else: You could have a separate method `get_scheduled_block_id` in the block repository and mock just that function.

Alternatively, without mocking, you could update the `schedule` table entry before the test, run the test, and restore the table afterwards. (This isn't ideal, of course; but it is a bit closer to reality than the mocking.)

Note that you aren't testing the case of no scheduled block, are you?


<!-- Sent from Reviewable.io -->

2022-11-21 11:04 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`tests/integration/blocks/test_get_current_block.py` line 158 at r4](https://reviewable.io/reviews/saltastroops/salt-api/123#-NH9jK8B5ZCZi9IoBTQr:-NHOm6zn9-nS6pOyBcqx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/45485062b1f4ff3fb3be38593d6a49d312be34a4/tests/integration/blocks/test_get_current_block.py#L158)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, yes, good point. But then you should rather mock that external request, using the responses packages (there are examples in other files). It might be a good idea to trim down the XML returned by that mock to the absolute bare minimum necessary.
</blockquote></details>

Done.
___
*[`tests/integration/blocks/test_get_next_scheduled_block.py` line 160 at r4](https://reviewable.io/reviews/saltastroops/salt-api/123#-NH9jp2QDGFc3lK_FqVm:-NHOoD-MBlaK776NT92S:b-yp59yw) ([raw file](https://github.com/saltastroops/salt-api/blob/45485062b1f4ff3fb3be38593d6a49d312be34a4/tests/integration/blocks/test_get_next_scheduled_block.py#L160)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As above, you are right and I was wrong; mocking might be necessary. But even so, you should consider mocking something else: You could have a separate method `get_scheduled_block_id` in the block repository and mock just that function.

Alternatively, without mocking, you could update the `schedule` table entry before the test, run the test, and restore the table afterwards. (This isn't ideal, of course; but it is a bit closer to reality than the mocking.)

Note that you aren't testing the case of no scheduled block, are you?
</blockquote></details>

Done, but I still opted for mocking because I am running away from updating the `schedule` table since this would require updating other columns in that table.

I have also added a test case for no scheduled block.


<!-- Sent from Reviewable.io -->

2022-11-21 11:56 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 8 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/block_repository.py` line 860 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOtAal3BDtUHzjyRr-:-NHOtAal3BDtUHzjyRr0:b-he5cj2) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/saltapi/repository/block_repository.py#L860)):*
> ```Python
>     def get_scheduled_block_id(self) -> Optional[int]:
>         """
>         Get next scheduled block id.
> ```

Maybe better: Get the id of the block scheduled next.

Also, should this perhaps be a private method (i,e. `_get_next_scheduled_block_id`)?
___
*[`saltapi/repository/block_repository.py` line 864 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOtWen0Mmbgs3wOumb:-NHOtWen0Mmbgs3wOumc:b-ydnsfj) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/saltapi/repository/block_repository.py#L864)):*
> ```Python
>         stmt = text("SELECT Block_Id FROM schedule")
>         result = self.connection.execute(stmt)
>         return cast(int, result.one_or_none())
> ```

You are potentially casting `None` to `int` here, which doesn't look right to me.
___
*[`saltapi/repository/block_repository.py` line 868 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOtssB800gcBRn8Row:-NHOtssB800gcBRn8Rox:b-rksj13) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/saltapi/repository/block_repository.py#L868)):*
> ```Python
>     def get_next_scheduled_block(self) -> Optional[Block]:
>         """
>         Get next scheduled block.
> ```

Maybe better: Get the block scheduled next.
___
*[`saltapi/web/api/blocks.py` line 31 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOuWhCDY_fXhvbubiv:-NHOuWhCDY_fXhvbubiw:bafcxpx) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/saltapi/web/api/blocks.py#L31)):*
> ```Python
> 
> @router.get(
>     "/next-scheduled-block", summary="Scheduled block", response_model=Optional[Block]
> ```

Hmmmm... Returning `None` looks a bit odd to me. Might the truth be that if there is no scheduled block, this means the requested resource does not exist and the appropriate reply would be a 404 error?

The same is true for the currently observed block, of course.
___
*[`tests/integration/blocks/test_get_current_block.py` line 59 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOvmfm0CcRcUd46HHK:-NHOvmfm0CcRcUd46HHL:bnciu6p) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_current_block.py#L59)):*
> ```Python
>         class MockResponse:
>             text = """
> <Cluster>
> ```

I would remove the parts which aren't necessary.
___
*[`tests/integration/blocks/test_get_current_block.py` line 79 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOwRXl3blny6oYK2V6:-NHOwRXl3blny6oYK2V7:b-fw7y7k) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_current_block.py#L79)):*
> ```Python
> 
>     monkeypatch.setattr(
>         requests,
> ```

I'd suggest that rather than manually monkey patching `requests` you use the `responses` library (https://github.com/getsentry/responses).
___
*[`tests/integration/blocks/test_get_current_block.py` line 93 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOxItZ13oRPIl2nQPR:-NHOxItZ13oRPIl2nQPS:bdzb457) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_current_block.py#L93)):*
> ```Python
>     "username",
>     [
>         find_username("SALT Astronomer"),
> ```

I don't think you have to test various users here -- this test is not about permissions, after call.
___
*[`tests/integration/blocks/test_get_next_scheduled_block.py` line 79 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOy746-lSAX62OV1zt:-NHOy746-lSAX62OV1zu:b-z9ev3o) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_next_scheduled_block.py#L79)):*
> ```Python
>     "username",
>     [
>         find_username("SALT Astronomer"),
> ```

I don't think you have to test various users -- this test is not about permissions, after all.


<!-- Sent from Reviewable.io -->

2022-11-21 14:02 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/block_repository.py` line 860 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOtAal3BDtUHzjyRr-:-NHPHXR67S8PR0kw9VLd:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/saltapi/repository/block_repository.py#L860)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: Get the id of the block scheduled next.

Also, should this perhaps be a private method (i,e. `_get_next_scheduled_block_id`)?
</blockquote></details>

Done.
___
*[`saltapi/repository/block_repository.py` line 864 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOtWen0Mmbgs3wOumb:-NHPI56DAFybCYVDADSP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/saltapi/repository/block_repository.py#L864)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are potentially casting `None` to `int` here, which doesn't look right to me.
</blockquote></details>

Done.
___
*[`saltapi/repository/block_repository.py` line 868 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOtssB800gcBRn8Row:-NHPI5UX9uySLmYGFCcP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/saltapi/repository/block_repository.py#L868)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: Get the block scheduled next.
</blockquote></details>

Done.
___
*[`saltapi/web/api/blocks.py` line 31 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOuWhCDY_fXhvbubiv:-NHPUbqQ98cjD48QqcrC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/saltapi/web/api/blocks.py#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Hmmmm... Returning `None` looks a bit odd to me. Might the truth be that if there is no scheduled block, this means the requested resource does not exist and the appropriate reply would be a 404 error?

The same is true for the currently observed block, of course.
</blockquote></details>

Done.
___
*[`tests/integration/blocks/test_get_current_block.py` line 59 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOvmfm0CcRcUd46HHK:-NHPUcRPCHkQBT9-cjSC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_current_block.py#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would remove the parts which aren't necessary.
</blockquote></details>

Done.
___
*[`tests/integration/blocks/test_get_current_block.py` line 79 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOwRXl3blny6oYK2V6:-NHPUdS05YKxl-b8niiP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_current_block.py#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest that rather than manually monkey patching `requests` you use the `responses` library (https://github.com/getsentry/responses).
</blockquote></details>

Done.
___
*[`tests/integration/blocks/test_get_current_block.py` line 93 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOxItZ13oRPIl2nQPR:-NHPRTuX5SShtbkrqYcg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_current_block.py#L93)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you have to test various users here -- this test is not about permissions, after call.
</blockquote></details>

Done.
___
*[`tests/integration/blocks/test_get_next_scheduled_block.py` line 79 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHOy746-lSAX62OV1zt:-NHPRTBe2EwAeTgsjvdy:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_next_scheduled_block.py#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you have to test various users -- this test is not about permissions, after all.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-21 14:20 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`tests/integration/blocks/test_get_current_block.py` line 43 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHPX7YT2WlTRI81z_IR:-NHPX7YT2WlTRI81z_IS:b-jl1f1w) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_current_block.py#L43)):*
> ```Python
>     "username",
>     [
>         find_username("SALT Astronomer"),
> ```

I'm not sure you should have removed the usernames for this test as well. (You want to test permissions for SO and SA somewhere, I'd guess. Maybe have a separate test function for this?)
___
*[`tests/integration/blocks/test_get_current_block.py` line 60 at r6](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHPWt_L6ReCLBfMeC-Y:-NHPWt_L6ReCLBfMeC-Z:b-ibnbia) ([raw file](https://github.com/saltastroops/salt-api/blob/13cf570daaac4fa3c2a84862da4a8024f6b83103/tests/integration/blocks/test_get_current_block.py#L60)):*
> ```Python
>             body=text,
>             status=200,
>             content_type="application/json",
> ```

The content type is incorrect. XML is returned.
___
*[`tests/integration/blocks/test_get_current_block.py` line 83 at r6](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHPXy3B1Flh8Kc8b8uv:-NHPXy3B1Flh8Kc8b8uw:b-jliiy7) ([raw file](https://github.com/saltastroops/salt-api/blob/13cf570daaac4fa3c2a84862da4a8024f6b83103/tests/integration/blocks/test_get_current_block.py#L83)):*
> ```Python
>             body=text,
>             status=404,
>             content_type="application/json",
> ```

The content type is incorrect; XML is returned.
___
*[`tests/integration/blocks/test_get_next_scheduled_block.py` line 44 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHPYPCnCrYnwuubqnBT:-NHPYPCnCrYnwuubqnBU:bab9bhf) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_next_scheduled_block.py#L44)):*
> ```Python
> 
> 
> @pytest.mark.parametrize(
> ```

I'm not sure you should have removed the usernames for this test as well. (You want to test permissions for SA and admin somewhere, I'd guess. Maybe have a separate test function for this?)


<!-- Sent from Reviewable.io -->

2022-11-21 14:36 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`tests/integration/blocks/test_get_current_block.py` line 43 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHPX7YT2WlTRI81z_IR:-NHPb9wu8THsttjOkMmp:b-7834no) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_current_block.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure you should have removed the usernames for this test as well. (You want to test permissions for SO and SA somewhere, I'd guess. Maybe have a separate test function for this?)
</blockquote></details>

I have added this functionality back.
___
*[`tests/integration/blocks/test_get_current_block.py` line 60 at r6](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHPWt_L6ReCLBfMeC-Y:-NHPaY8k8xUexi12WGtP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/13cf570daaac4fa3c2a84862da4a8024f6b83103/tests/integration/blocks/test_get_current_block.py#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The content type is incorrect. XML is returned.
</blockquote></details>

Done.
___
*[`tests/integration/blocks/test_get_current_block.py` line 83 at r6](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHPXy3B1Flh8Kc8b8uv:-NHPaYc1C_uC9PXRuKpi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/13cf570daaac4fa3c2a84862da4a8024f6b83103/tests/integration/blocks/test_get_current_block.py#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The content type is incorrect; XML is returned.
</blockquote></details>

Done.
___
*[`tests/integration/blocks/test_get_next_scheduled_block.py` line 44 at r5](https://reviewable.io/reviews/saltastroops/salt-api/123#-NHPYPCnCrYnwuubqnBT:-NHPbG-mCKowbOZk5vvw:b-7834no) ([raw file](https://github.com/saltastroops/salt-api/blob/bf364106d304ab2e109a9bb68624782ab39adc09/tests/integration/blocks/test_get_next_scheduled_block.py#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure you should have removed the usernames for this test as well. (You want to test permissions for SA and admin somewhere, I'd guess. Maybe have a separate test function for this?)
</blockquote></details>

I have added this functionality back.


<!-- Sent from Reviewable.io -->

2022-11-21 15:28 UTC, hettlage approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2022-11-21 21:07 UTC, hettlage approved these changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2022-11-21 21:08 UTC, merged