Proprietary period
saltastroops/salt-api pull request #124
Opened 2022-11-24 17:10 UTC by Eb-Zeero

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/salt-api/124)

2022-11-25 10:59 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 38 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 401 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHi82im8_uPaPD64QEY:-NHi82im8_uPaPD64QEZ:bg0pwpl) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L401)):*
> ```Python
>         return db_proposal_type
> 
>     def _data_release_date(
> ```

Can we have a quick chat regarding testing this function (and similar functions)?
___
*[`saltapi/repository/proposal_repository.py` line 1752 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhmk3h74Tugu5JZUrj:-NHhmk3h74Tugu5JZUrk:bw19mor) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1752)):*
> ```Python
>         username: str,
>     ) -> None:
>         istmt = text(
> ```

Why "istmt" (rather than "stmt")?
___
*[`saltapi/repository/proposal_repository.py` line 1755 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhrG296U5DnDuMlNym:-NHhrG296U5DnDuMlNyn:b-8asi8q) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1755)):*
> ```Python
>             """
> INSERT INTO ProprietaryPeriodExtensionRequest(
>     MadeAt,
> ```

`MadeAt` is a TIMESTAMP, so it is set automatically.

If you want to set it explicitly, you probably should use `date time.now` rather than `date.today`.
___
*[`saltapi/repository/proposal_repository.py` line 1783 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhllSDC_B0cbUvdDPR:-NHhllSDC_B0cbUvdDPS:bw19mor) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1783)):*
> ```Python
> 
>     def update_proprietary_period(self, proposal_code: str, proprietary_period: int) -> None:
>         istmt = text(
> ```

Why "istmt" (rather than "stmt")?
___
*[`saltapi/repository/proposal_repository.py` line 1803 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhlGgeCmwFzQ5frlLw:-NHhlGgeCmwFzQ5frlLx:b9rl7oi) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1803)):*
> ```Python
>         )
> 
>     def _latest_observation_datetime(self, proposal_code: str) -> datetime:
> ```

The name is misleading; you are returning a date, not a datetime.
___
*[`saltapi/repository/proposal_repository.py` line 1806 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHiR09v-0RdhmulFZSX:-NHiR09v-0RdhmulFZSY:b-kkf3vx) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1806)):*
> ```Python
> 
>         # find the latest observation
>         latest_observation = self._first_submission_date(proposal_code)
> ```

Can we discuss this? I don't think is the best way of handling no observations.
___
*[`saltapi/repository/proposal_repository.py` line 1808 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhkhLZBKJi6kZ9IgBw:-NHhkhLZBKJi6kZ9IgBx:b-zgf6bp) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1808)):*
> ```Python
>         latest_observation = self._first_submission_date(proposal_code)
>         for observation in self._block_visits(proposal_code):
>             if type(latest_observation) == date:
> ```

Isn't `latest_observation` always a `date`? So shouldn't you rather check it is not `None`?
___
*[`saltapi/repository/proposal_repository.py` line 1813 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhlOmV9kxs2_OFiRoC:-NHhlOmV9kxs2_OFiRoD:bqppb4m) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1813)):*
> ```Python
>                 latest_observation = observation["night"]
> 
>         # find the end of the semester when the latest observation was made
> ```

The comment is misleading; you are finding the noon of the day the the observation was made. Note that for an observation, say, on 4 June 2022 at 23:59 and 5 June 2022 at 00:01 you would return different dates, which is probably not what you intended. 
___
*[`saltapi/repository/proposal_repository.py` line 1821 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhkTjRBwvxP2EQtaq9:-NHhkTjRBwvxP2EQtaqA:b-lgp8ku) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1821)):*
> ```Python
>             0,
>             0,
>             0,
> ```

You might have forgotten to set the milliseconds (or is it microseconds) to 0.
___
*[`saltapi/repository/proposal_repository.py` line 1825 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHfPnrP1HGjEdm0eXxH:-NHfPnrP1HGjEdm0eXxI:b-flwzlb) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1825)):*
> ```Python
>         )
> 
>     def _maximum_proprietary_period(
> ```

The rules are more complicated than this; the proposal type is relevant as well.

Here is the code from the old WM. (Note that the comment and code are slightly inconsistent -- you should use the code.)

```
	/**
	 * Get the maximum proprietary period for a proposal.
	 *
	 * The maximum proprietary periods are as follows:
	 *
	 * Commissioning proposals: 36 months
	 * DDT proposals: 6 months
	 * Engineering proposals: 0 months
	 * Gravitational wave proposals: 1200 months
	 * Science verification: 12 months
	 * Other proposals:
	 * - With time from South Africa: 24 months
	 * - Without time from South Africa: 36 months
	 *
	 * SAs and full administrators can override these maximum values.
	 *
	 * @param $proposal TableProposal proposal
	 * @return int the maximum proprietary period
	 * @throws DBException
	 */
	public static function maximumProprietaryPeriod($proposal)
	{
		// get user
		$user = Authentication::getUser();

		// is the user on the proposal?
		$notOnProposal =  !$proposal->isUserInvestigator($user);

		// non-investigator SAs and full administrators can override maximum proprietary periods
		if ($notOnProposal && ($user->isAstronomer() || $user->getSetting("RightAdmin") > 1)) {
			return 100000;
		}

		switch ($proposal->getProposalType()) {
		case "Commissioning":
			return 36;
		case "Director Discretionary Time (DDT)":
			return 6;
		case "Engineering":
			return 0;
		case "Gravitational Wave Event":
			return 1200;
		case "Key Science Program":
		case "Large Science Proposal":
		case "Science":
		case "Science - Long Term":
			if ($proposal->hasAllocatedTime("RSA")) {
				return 24;
			}
			else {
				return 100000;
			}
		case "Science Verification":
			return 12;
		case "OPTICON-Radionet Pilot":
			return 24;
		default:
			throw new Exception("Unsupported proposal type: " + $proposal.getProposalType());
		}
	}
}
```
___
*[`saltapi/service/permission_service.py` line 434 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHi8oU6A4Idky4rMJtz:-NHi8oU6A4Idky4rMJu-:b-x3io7u) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/service/permission_service.py#L434)):*
> ```Python
> 
>     def check_permission_to_check_permission_to_update_proprietary_period(
>         self, user: User, proposal_code: str
> ```

check_permission_to_check_permission_to_update_proprietary_period > check_permission_to_update_proprietary_period
___
*[`saltapi/service/permission_service.py` line 4 [...]

2022-11-28 13:56 UTC, Eb-Zeero reviewed
> Dismissed @hettlage from a discussion.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: 3 of 9 files reviewed, 37 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1752 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhmk3h74Tugu5JZUrj:-NHxesMO23EMFGFE04Ar:b-a8c1xn) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1752)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why "istmt" (rather than "stmt")?
</blockquote></details>

I meant insert statement
___
*[`saltapi/repository/proposal_repository.py` line 1755 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhrG296U5DnDuMlNym:-NHxg2dz4wlfsjdIgdRw:b-5dfryo) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1755)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`MadeAt` is a TIMESTAMP, so it is set automatically.

If you want to set it explicitly, you probably should use `date time.now` rather than `date.today`.
</blockquote></details>

removed it
___
*[`saltapi/repository/proposal_repository.py` line 1783 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhllSDC_B0cbUvdDPR:-NHxgGMPEesSRezw1I3b:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1783)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why "istmt" (rather than "stmt")?
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1808 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhkhLZBKJi6kZ9IgBw:-NHxh-i0-yM4buaXAE5l:bdrn5u6) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1808)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't `latest_observation` always a `date`? So shouldn't you rather check it is not `None`?
</blockquote></details>

No not always, I had failing tests on this
___
*[`saltapi/repository/proposal_repository.py` line 1825 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHfPnrP1HGjEdm0eXxH:-NHxRlfC6XalC1H6--lK:b88kl32) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1825)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The rules are more complicated than this; the proposal type is relevant as well.

Here is the code from the old WM. (Note that the comment and code are slightly inconsistent -- you should use the code.)

```
	/**
	 * Get the maximum proprietary period for a proposal.
	 *
	 * The maximum proprietary periods are as follows:
	 *
	 * Commissioning proposals: 36 months
	 * DDT proposals: 6 months
	 * Engineering proposals: 0 months
	 * Gravitational wave proposals: 1200 months
	 * Science verification: 12 months
	 * Other proposals:
	 * - With time from South Africa: 24 months
	 * - Without time from South Africa: 36 months
	 *
	 * SAs and full administrators can override these maximum values.
	 *
	 * @param $proposal TableProposal proposal
	 * @return int the maximum proprietary period
	 * @throws DBException
	 */
	public static function maximumProprietaryPeriod($proposal)
	{
		// get user
		$user = Authentication::getUser();

		// is the user on the proposal?
		$notOnProposal =  !$proposal->isUserInvestigator($user);

		// non-investigator SAs and full administrators can override maximum proprietary periods
		if ($notOnProposal && ($user->isAstronomer() || $user->getSetting("RightAdmin") > 1)) {
			return 100000;
		}

		switch ($proposal->getProposalType()) {
		case "Commissioning":
			return 36;
		case "Director Discretionary Time (DDT)":
			return 6;
		case "Engineering":
			return 0;
		case "Gravitational Wave Event":
			return 1200;
		case "Key Science Program":
		case "Large Science Proposal":
		case "Science":
		case "Science - Long Term":
			if ($proposal->hasAllocatedTime("RSA")) {
				return 24;
			}
			else {
				return 100000;
			}
		case "Science Verification":
			return 12;
		case "OPTICON-Radionet Pilot":
			return 24;
		default:
			throw new Exception("Unsupported proposal type: " + $proposal.getProposalType());
		}
	}
}
```
</blockquote></details>

Thank you done
___
*[`saltapi/service/permission_service.py` line 434 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHi8oU6A4Idky4rMJtz:-NHxT0ty3mXKy04VFq0O:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/service/permission_service.py#L434)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

check_permission_to_check_permission_to_update_proprietary_period > check_permission_to_update_proprietary_period
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 293 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHiBRG-255Ws7ChC1Vp:-NHxaFksCt1XpQO3qpBI:b-hff6wv) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/service/proposal_service.py#L293)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be called `create_proprietary_period_extension_request`?
</blockquote></details>

renamed
___
*[`saltapi/web/api/proposals.py` line 219 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHiI-3G4dvuVIDnaS5H:-NHxaPu3E8OvRAm84u_X:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/web/api/proposals.py#L219)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This endpoint is not updating the release date but the proprietary period, and the name should reflect this:

`/{proposal_code}/proprietary_period`
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 224 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHiKkJn2U2LTRm-_9V1:-NHxaV-yDAW7GxTO3Yyu:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/web/api/proposals.py#L224)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Bretter: update_proprietary_period
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 233 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHiL6Gp40_egWD-nGcc:-NHxadFL2EkdsN-puDff:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/web/api/proposals.py#L233)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

proprietary_period_update: ProprietaryPeriodUpdate
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 235 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHiLR8t85tW3qMWZZvp:-NHxaj_C5vk-AXeumIU7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/web/api/proposals.py#L235)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"The details for proprietary period update."
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 236 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHiLdYUCSxyGEwg9ifq:-NHxarwP25aqiNtB55Vh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/web/api/proposals.py#L236)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"The requested proprietary period in months and a motivation. The motivation is only  [...]

2022-11-28 15:09 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 16 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1808 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhkhLZBKJi6kZ9IgBw:-NHyfxDs0LMJHyv2od6T:b-nn2v9) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1808)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

No not always, I had failing tests on this
</blockquote></details>

Actually it should always be a `date time`, so there seems to be an issue.
___
*[`saltapi/repository/proposal_repository.py` line 1862 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHygUn40gL-68FUI7SK:-NHygUn40gL-68FUI7SL:bswa0tw) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/repository/proposal_repository.py#L1862)):*
> ```Python
>             if self.is_partner_allocated(proposal_code, "RSA"):
>                 return 24
>         return None
> ```

It might one a good idea to raise an exception if the proposal type is not covered.
___
*[`saltapi/service/permission_service.py` line 445 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyh75h8uLRAoeAjYu9:-NHyh75h8uLRAoeAjYuA:b-vnuczd) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/service/permission_service.py#L445)):*
> ```Python
>         self.check_role(username, roles, proposal_code)
> 
>     def need_motivation_to_update_proprietary_period(
> ```

The previous name might have been better, given the method returns a boolean/.
___
*[`saltapi/service/permission_service.py` line 449 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyhOSe05ALkNYDT6xT:-NHyhOSe05ALkNYDT6xU:bb2x8x8) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/service/permission_service.py#L449)):*
> ```Python
>     ) -> bool:
>         proposal_code = proposal["proposal_code"]
>         if self.check_role(username, [Role.ADMINISTRATOR], proposal_code):
> ```

This doers not included checking whether the admin is an investigator.
___
*[`saltapi/web/api/proposals.py` line 233 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHiL6Gp40_egWD-nGcc:-NHyhv6z3uvBCkeUFJ0n:bvtwlm2) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/web/api/proposals.py#L233)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks -- but the variable name is still unchanged. :-)
___
*[`saltapi/web/api/proposals.py` line 235 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyiBVf9LmI39_v2lRP:-NHyiBVf9LmI39_v2lRQ:bdpo65o) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/web/api/proposals.py#L235)):*
> ```Python
>     release_date_update: ProprietaryPeriodUpdateRequest = Body(
>         ...,
>         title="The details for proprietary period update.",
> ```

for ``. for the
___
*[`saltapi/web/schema/proposal.py` line 232 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyiqbkAhI8UTYAvh8W:-NHyiqbkAhI8UTYAvh8X:bs2k4or) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/web/schema/proposal.py#L232)):*
> ```Python
> 
> class ProprietaryPeriodUpdateRequest(BaseModel):
>     """A request to update the data proprietary period."""
> ```

Maybe remove the "data"?
___
*[`tests/repository/test_proposal_repository.py` line 11 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyj-ED1RpRnM-nFQNB:-NHyj-ED1RpRnM-nFQNC:b-kztopr) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/tests/repository/test_proposal_repository.py#L11)):*
> ```Python
> from tests.conftest import find_username
> from tests.markers import nodatabase
> #
> ```

Why did you add comments here?
___
*[`tests/repository/test_proposal_repository.py` line 489 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyl0Yw1IUKtV8GioMl:-NHyl0Yw1IUKtV8GioMm:bz97luo) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/tests/repository/test_proposal_repository.py#L489)):*
> ```Python
>     "proposal_code,maximum_period",
>     [
>         ("2020-1-SCI-005", 24),  # RSA allocated
> ```

Tests missing for

* Engineering proposals
* Opticon proposals


<!-- Sent from Reviewable.io -->

2022-11-28 15:28 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 18 unresolved discussions (waiting on @Eb-Zeero)

___
*[`tests/repository/test_proposal_repository.py` line 489 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyqLWi3YORy05qhTjJ:-NHyqLWj4FFIM1mSoJLO:b-9x9bf7) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/tests/repository/test_proposal_repository.py#L489)):*
> ```Python
>     "proposal_code,maximum_period",
>     [
>         ("2020-1-SCI-005", 24),  # RSA allocated
> ```

Maybe better "RSA allocated time"
___
*[`tests/repository/test_proposal_repository.py` line 491 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyqRj7E9v9MiEF17Vg:-NHyqRj7E9v9MiEF17Vh:bfi0v8e) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/tests/repository/test_proposal_repository.py#L491)):*
> ```Python
>         ("2020-1-SCI-005", 24),  # RSA allocated
>         ("2018-2-LSP-001", 24),  # RSA Allocated
>         ("2020-1-SCI-003", None),  # None RSA Allocated
> ```

Maybe better: "RSA allocated no time"


<!-- Sent from Reviewable.io -->

2022-11-28 17:09 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 18 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1862 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHygUn40gL-68FUI7SK:-NHzAznR42e6CYpZOZ0V:b-s23po9) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/repository/proposal_repository.py#L1862)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might one a good idea to raise an exception if the proposal type is not covered.
</blockquote></details>

now raised
___
*[`saltapi/service/permission_service.py` line 449 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHfQDNcDXU4oByH_gwa:-NHz0Qsc1aT5vc1KUuQu:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/service/permission_service.py#L449)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The rules are more complicated than this; the proposal type is relevant as well.

Also, administrators (ideally administrators who are not an investigator) should be allowed to update the proprietary period without a motivation.

Finally, I think you can significantly simplify the logic here; you only have to check whether the requested proprietary period is longer than the maximum one. This is true irrespective of the partners contributing time.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 445 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyh75h8uLRAoeAjYu9:-NHzCCRn8_bhkIcIlheX:b-u0jc0j) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/service/permission_service.py#L445)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The previous name might have been better, given the method returns a boolean/.
</blockquote></details>

new name given
___
*[`saltapi/service/permission_service.py` line 449 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyhOSe05ALkNYDT6xT:-NHzCO_w798_eINLtOam:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/service/permission_service.py#L449)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This doers not included checking whether the admin is an investigator.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 233 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHiL6Gp40_egWD-nGcc:-NHz1sNi3xKhL7lzhHYm:b5zvfxn) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/web/api/proposals.py#L233)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thanks -- but the variable name is still unchanged. :-)
</blockquote></details>

missed it
___
*[`saltapi/web/api/proposals.py` line 235 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyiBVf9LmI39_v2lRP:-NHz2A5P8I_iN4gbHnRp:bw7cf52) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/web/api/proposals.py#L235)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

for ``. for the
</blockquote></details>

Done. If I understood what you meant
___
*[`saltapi/web/schema/proposal.py` line 94 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHiEuVK4GtcVuDUKeAq:-NHz4LVD2a8lJ6NJcV2V:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/web/schema/proposal.py#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this should inherit from `ProprietaryPeriod`. The only relevant field from that type is the 
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 232 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyiqbkAhI8UTYAvh8W:-NHz4Y_xAatj6eDrl1TU:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/web/schema/proposal.py#L232)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe remove the "data"?
</blockquote></details>

removed
___
*[`tests/repository/test_proposal_repository.py` line 11 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyj-ED1RpRnM-nFQNB:-NHz4n5mCefIcE_jX_DB:b-ht17if) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/tests/repository/test_proposal_repository.py#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why did you add comments here?
</blockquote></details>

mistake
___
*[`tests/repository/test_proposal_repository.py` line 489 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyqLWi3YORy05qhTjJ:-NHz53zxCmdeCYxuEW8P:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/tests/repository/test_proposal_repository.py#L489)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better "RSA allocated time"
</blockquote></details>

Done.
___
*[`tests/repository/test_proposal_repository.py` line 489 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyl0Yw1IUKtV8GioMl:-NHzCfc76wuDwMiTBAg6:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/tests/repository/test_proposal_repository.py#L489)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Tests missing for

* Engineering proposals
* Opticon proposals
</blockquote></details>

Done.
___
*[`tests/repository/test_proposal_repository.py` line 491 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyqRj7E9v9MiEF17Vg:-NHz54Of9TxSopz14UhN:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/tests/repository/test_proposal_repository.py#L491)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: "RSA allocated no time"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-29 10:59 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1862 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1M2b36Ukro7YaH0uD:-NI1M2b36Ukro7YaH0uE:b6zqfwi) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/repository/proposal_repository.py#L1862)):*
> ```Python
>             if self.is_partner_allocated(proposal_code, "RSA"):
>                 return 24
>             return 100000
> ```

Actually, the values for Gravitational Wave Events and non -SA KSP/Science/LSP should be the same. Maybe 100 years is a reasonable choice here.

Also, if you decide not to use `None` any longer, you should change the return type of this method from `Optional[int]` to `int`. 
___
*[`saltapi/service/permission_service.py` line 450 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1NF1S-_97EmiDvbFw:-NI1NF1S-_97EmiDvbFx:b-g66cim) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/service/permission_service.py#L450)):*
> ```Python
>         proposal_code = proposal["proposal_code"]
>         if self.check_role(username, [Role.ADMINISTRATOR], proposal_code) and\
>                 not self.check_role(username, [Role.PRINCIPAL_INVESTIGATOR], proposal_code):
> ```

You are checking whether the user is PI, not whether they are an investigator...
___
*[`saltapi/service/permission_service.py` line 454 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1N_0G670GcwoI0EVo:-NI1N_0G670GcwoI0EVp:bfwenuq) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/service/permission_service.py#L454)):*
> ```Python
> 
>         maximum_period = self.proposal_repository.maximum_proprietary_period(proposal_code)
>         if maximum_period > proprietary_period_update.proprietary_period:
> ```

Can be simplified:

```
return maximum_period > proprietary_period_update.proprietary_period
```

But isn't the logic wrong? Shouldn't it be

```
return proprietary_period_update.proprietary_period > maximum_period`
```

?
___
*[`saltapi/web/api/proposals.py` line 235 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyiBVf9LmI39_v2lRP:-NI20rgnDb_LB-8GztMU:b-mgxkoj) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/web/api/proposals.py#L235)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done. If I understood what you meant
</blockquote></details>

Oops, sorry. Yes, that's what I meant.
___
*[`saltapi/web/schema/proposal.py` line 97 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI219_kA9PvEOjCoKNW:-NI219_kA9PvEOjCoKNX:b-j683gg) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/web/schema/proposal.py#L97)):*
> ```Python
>     period: int = Field(
>         ...,
>         title="Current proprietary period",
> ```

Maybe better "Requested proprietary period"?


<!-- Sent from Reviewable.io -->

2022-11-30 11:01 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 11 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 401 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHi82im8_uPaPD64QEY:-NI7A9lL4PEr-omzzb2G:b-k8fqx6) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L401)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we have a quick chat regarding testing this function (and similar functions)?
</blockquote></details>

tested
___
*[`saltapi/repository/proposal_repository.py` line 1803 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhlGgeCmwFzQ5frlLw:-NI7AC5RDDyfVlfw2Iae:b-ll5uis) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1803)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name is misleading; you are returning a date, not a datetime.
</blockquote></details>

new method done
___
*[`saltapi/repository/proposal_repository.py` line 1806 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHiR09v-0RdhmulFZSX:-NI7AH0-Ez4i7FkT55I7:bf1p477) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1806)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss this? I don't think is the best way of handling no observations.
</blockquote></details>

removed handled differently else where
___
*[`saltapi/repository/proposal_repository.py` line 1808 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhkhLZBKJi6kZ9IgBw:-NI7AN2xBQzbwLaHV-VH:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1808)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Actually it should always be a `date time`, so there seems to be an issue.
</blockquote></details>

fixed
___
*[`saltapi/repository/proposal_repository.py` line 1813 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhlOmV9kxs2_OFiRoC:-NI7AntZ8VQ2UW3AaKNG:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1813)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The comment is misleading; you are finding the noon of the day the the observation was made. Note that for an observation, say, on 4 June 2022 at 23:59 and 5 June 2022 at 00:01 you would return different dates, which is probably not what you intended. 
</blockquote></details>

removed
___
*[`saltapi/repository/proposal_repository.py` line 1821 at r1](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHhkTjRBwvxP2EQtaq9:-NI7AquXBPkGCIAqKAlr:b-1r0vbi) ([raw file](https://github.com/saltastroops/salt-api/blob/851bdf5913a187f11084bbec6ada1a6d8ea9668c/saltapi/repository/proposal_repository.py#L1821)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might have forgotten to set the milliseconds (or is it microseconds) to 0.
</blockquote></details>

no longer needed
___
*[`saltapi/repository/proposal_repository.py` line 1862 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1M2b36Ukro7YaH0uD:-NI7AuKYAnzVG7Y0TpOK:brl64te) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/repository/proposal_repository.py#L1862)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Actually, the values for Gravitational Wave Events and non -SA KSP/Science/LSP should be the same. Maybe 100 years is a reasonable choice here.

Also, if you decide not to use `None` any longer, you should change the return type of this method from `Optional[int]` to `int`. 
</blockquote></details>

now return 1200
___
*[`saltapi/service/permission_service.py` line 450 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1NF1S-_97EmiDvbFw:-NI7B-4k1_4i3dwZPLY0:b-2i8kdc) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/service/permission_service.py#L450)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are checking whether the user is PI, not whether they are an investigator...
</blockquote></details>

Now checking investigator
___
*[`saltapi/service/permission_service.py` line 454 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1N_0G670GcwoI0EVo:-NI7BIaPARcesgXBJz_E:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/service/permission_service.py#L454)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can be simplified:

```
return maximum_period > proprietary_period_update.proprietary_period
```

But isn't the logic wrong? Shouldn't it be

```
return proprietary_period_update.proprietary_period > maximum_period`
```

?
</blockquote></details>

fixed
___
*[`saltapi/web/api/proposals.py` line 235 at r2](https://reviewable.io/reviews/saltastroops/salt-api/124#-NHyiBVf9LmI39_v2lRP:-NI7BLMrAnIRb3j-_rYM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b5781fec4c9d4eec29cd5d0d2390ecfbe8b87b2c/saltapi/web/api/proposals.py#L235)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oops, sorry. Yes, that's what I meant.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 97 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI219_kA9PvEOjCoKNW:-NI7Bg5SDOobJGXbB1SC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/web/schema/proposal.py#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better "Requested proprietary period"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-30 11:58 UTC, hettlage requested changes
There are no tests for the endpoints you have added.

> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124#-:-NI7OGjU-QNwIjZ-m6cs:b-9ryrhw)* status: 8 of 9 files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1765 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7MnH_6_tev4-bEX2X:-NI7MnHaAWRAtLP0dIFY:b-pzizku) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/saltapi/repository/proposal_repository.py#L1765)):*
> ```Python
> 
>         proprietary_period_start = semester_end(
>             semester_of_datetime(pytz.utc.localize(self._first_submission_date(proposal_code)))
> ```

I still maintain that using the end of the current semester makes more sense if there are no observations.
___
*[`saltapi/repository/proposal_repository.py` line 1768 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7JqqKBKgxE3OXZszQ:-NI7JqqKBKgxE3OXZszR:b-vax9o4) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/saltapi/repository/proposal_repository.py#L1768)):*
> ```Python
>         )
>         for observation in block_visits:
>             observation_semester_end = semester_end(
> ```

This is a bit ineffective, as you have to calculate the semester end for every block visit.  Thus it might be better to compare the observation dates and only get the semester end for the latest date.
___
*[`saltapi/repository/proposal_repository.py` line 1770 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7Kh9UBCcKUTvFia7q:-NI7Kh9UBCcKUTvFia7r:b-2seeap) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/saltapi/repository/proposal_repository.py#L1770)):*
> ```Python
>             observation_semester_end = semester_end(
>                 semester_of_datetime(
>                     datetime.combine(observation["night"], time.min, tzinfo=pytz.utc)
> ```

I think you would end up with the wrong semester for observations taken on, say, 1 May.
___
*[`saltapi/repository/proposal_repository.py` line 1780 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7Oggo2wLrpvXWULhz:-NI7Oggp-Yd3NdmjNo7L:b7z64h4) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/saltapi/repository/proposal_repository.py#L1780)):*
> ```Python
>             self,
>             proposal_code: str,
>             proprietary_period: Optional[int],
> ```

Is the proprietary period really `Optional`?
___
*[`saltapi/repository/proposal_repository.py` line 1782 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7OS55A0M47V_8qcVc:-NI7OS55A0M47V_8qcVd:b-pompo7) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/saltapi/repository/proposal_repository.py#L1782)):*
> ```Python
>             proprietary_period: Optional[int],
>             block_visits: List[dict[str, any]]
>     ) -> Optional[date]:
> ```

Is the return value really `Optional`?
___
*[`saltapi/service/permission_service.py` line 454 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1N_0G670GcwoI0EVo:-NI7Lmy28R_3m3GeE00l:baz2fpj) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/service/permission_service.py#L454)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

You can still simplify it, though... :-/
___
*[`tests/repository/test_proposal_repository.py` line 511 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7Ma6aDdNdru1TkJI8:-NI7Ma6aDdNdru1TkJI9:b4rcx2) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/tests/repository/test_proposal_repository.py#L511)):*
> ```Python
> 
> @pytest.mark.parametrize(
>     "proposal_code,block_visits,expected_date",
> ```

You are only testing the case of a single block visit; but you should test no and multiple visits as well.

Also, testing for 30 April and 31 October might be a good idea.
___
*[`tests/repository/test_proposal_repository.py` line 514 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7NANH9821y39AQFTs:-NI7NANH9821y39AQFTt:b-pnaoci) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/tests/repository/test_proposal_repository.py#L514)):*
> ```Python
>     [
>         ("2020-2-SCI-005", [{"night": date(2021, 2, 1)}], datetime(2021, 5, 1, 12, tzinfo=pytz.utc)),
>         ("2020-2-SCI-005", [{"night": date(2021, 5, 1)}], datetime(2021, 5, 1, 12, tzinfo=pytz.utc)),
> ```

This is incorrect. The night of 1 May 2021 belongs to 2021-1, and hence the start date would be 1 November 2021.
___
*[`tests/repository/test_proposal_repository.py` line 516 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7Ni-FDJr5iGTtKTzw:-NI7Ni-FDJr5iGTtKTzx:b-2utj67) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/tests/repository/test_proposal_repository.py#L516)):*
> ```Python
>         ("2020-2-SCI-005", [{"night": date(2021, 5, 1)}], datetime(2021, 5, 1, 12, tzinfo=pytz.utc)),
>         ("2020-2-SCI-005", [{"night": date(2021, 5, 2)}], datetime(2021, 11, 1, 12, tzinfo=pytz.utc)),
>         ("2020-2-SCI-005", [{"night": date(2021, 5, 2)}], datetime(2021, 11, 1, 12, tzinfo=pytz.utc)),
> ```

Duplicate line?
___
*[`tests/repository/test_proposal_repository.py` line 518 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7NXKKA5qmDvKYqZFO:-NI7NXKKA5qmDvKYqZFP:b-klf4tw) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/tests/repository/test_proposal_repository.py#L518)):*
> ```Python
>         ("2020-2-SCI-005", [{"night": date(2021, 5, 2)}], datetime(2021, 11, 1, 12, tzinfo=pytz.utc)),
>         ("2020-2-SCI-005", [{"night": date(2021, 8, 15)}], datetime(2021, 11, 1, 12, tzinfo=pytz.utc)),
>         ("2020-2-SCI-005", [{"night": date(2021, 11, 1)}], datetime(2021, 11, 1, 12, tzinfo=pytz.utc)),
> ```

This is incorrect. The night of 1 November 2021 belongs to 2021-2, and hence the start date would be 1 May 2022.
___
*[`tests/repository/test_proposal_repository.py` line 522 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7O2YuDGVDrmZLF06i:-NI7O2YuDGVDrmZLF06j:b-96rjx) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/tests/repository/test_proposal_repository.py#L522)):*
> ```Python
>     ],
> )
> def test_proprietary_period_start_date_returns_correct_start_date(
> ```

Again, including a test for no and for multiple block visits would do no harm. :-)


<!-- Sent from Reviewable.io -->

2022-12-01 17:09 UTC, Eb-Zeero reviewed
added

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124#-:-NIDeZJL4z8nemmlVzdl:b-7tfmjp)* status: 8 of 9 files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1765 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7MnH_6_tev4-bEX2X:-NI8QTLV22DVPfZDkb_8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/saltapi/repository/proposal_repository.py#L1765)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I still maintain that using the end of the current semester makes more sense if there are no observations.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1768 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7JqqKBKgxE3OXZszQ:-NI8QVZX-buAIZ9Ug1W8:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/saltapi/repository/proposal_repository.py#L1768)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is a bit ineffective, as you have to calculate the semester end for every block visit.  Thus it might be better to compare the observation dates and only get the semester end for the latest date.
</blockquote></details>

fixed
___
*[`saltapi/repository/proposal_repository.py` line 1770 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7Kh9UBCcKUTvFia7q:-NI8QYS21rvU5aoKC7O2:bqetged) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/saltapi/repository/proposal_repository.py#L1770)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you would end up with the wrong semester for observations taken on, say, 1 May.
</blockquote></details>

now fixed
___
*[`saltapi/repository/proposal_repository.py` line 1780 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7Oggo2wLrpvXWULhz:-NI7zJJc4hLJCouGXuVx:b-7pleid) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/saltapi/repository/proposal_repository.py#L1780)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is the proprietary period really `Optional`?
</blockquote></details>

no it is now not sorry
___
*[`saltapi/repository/proposal_repository.py` line 1782 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7OS55A0M47V_8qcVc:-NI7zhJ4AZGb61W0Hx8J:bvbqnob) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/saltapi/repository/proposal_repository.py#L1782)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is the return value really `Optional`?
</blockquote></details>

Not any more
___
*[`saltapi/service/permission_service.py` line 454 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1N_0G670GcwoI0EVo:-NI8SrffBS7EO1oHbmD3:brprpy6) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/service/permission_service.py#L454)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You can still simplify it, though... :-/
</blockquote></details>

help me here
___
*[`tests/repository/test_proposal_repository.py` line 511 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7Ma6aDdNdru1TkJI8:-NI8R-pE7HvL0H7Dt3Kz:b-7tfmjp) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/tests/repository/test_proposal_repository.py#L511)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are only testing the case of a single block visit; but you should test no and multiple visits as well.

Also, testing for 30 April and 31 October might be a good idea.
</blockquote></details>

added
___
*[`tests/repository/test_proposal_repository.py` line 514 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7NANH9821y39AQFTs:-NI82f_v-6QeABpzmhNj:bp8m7gb) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/tests/repository/test_proposal_repository.py#L514)):*
>fixed
___
*[`tests/repository/test_proposal_repository.py` line 516 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7Ni-FDJr5iGTtKTzw:-NI82hy64SRwyGYY46Sa:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/tests/repository/test_proposal_repository.py#L516)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Duplicate line?
</blockquote></details>

removed
___
*[`tests/repository/test_proposal_repository.py` line 518 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7NXKKA5qmDvKYqZFO:-NI82vxO51QP5npfRCYi:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/tests/repository/test_proposal_repository.py#L518)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is incorrect. The night of 1 November 2021 belongs to 2021-2, and hence the start date would be 1 May 2022.
</blockquote></details>

fixed
___
*[`tests/repository/test_proposal_repository.py` line 522 at r4](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI7O2YuDGVDrmZLF06i:-NI83BB_4sCzj4Noof1P:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/98a16ba058b8f59dadb28f604875349ffbea3eb4/tests/repository/test_proposal_repository.py#L522)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Again, including a test for no and for multiple block visits would do no harm. :-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-02 10:06 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 31 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1745 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGrl4M-Mb9kh2Jh9Dw:-NIGrl4M-Mb9kh2Jh9Dx:binzmt5) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1745)):*
> ```Python
>     (SELECT ProposalCode_Id FROM ProposalCode WHERE Proposal_Code = :proposal_code),
>     :reason,
>     (SELECT PiptUser_Id FROM PiptUser WHERE Username = :username),
> ```

Oh... Good catch!
___
*[`saltapi/repository/proposal_repository.py` line 1760 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGyd6M0u7vSF78keXP:-NIGyd6M0u7vSF78keXQ:b67clqs) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1760)):*
> ```Python
>         )
> 
>     def proprietary_period_start_date(self, proposal_code: str, block_visits: List[Dict[str, Any]]):
> ```

The return type is missing.
___
*[`saltapi/repository/proposal_repository.py` line 1760 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIH6DTH84GqoJN8z426:-NIH6DTH84GqoJN8z427:btumvlo) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1760)):*
> ```Python
>         )
> 
>     def proprietary_period_start_date(self, proposal_code: str, block_visits: List[Dict[str, Any]]):
> ```

`proposal_code` isa not used.
___
*[`saltapi/repository/proposal_repository.py` line 1770 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGsP4C0medFpn5Ec4N:-NIGsP4C0medFpn5Ec4O:b7tjgki) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1770)):*
> ```Python
>                 observation_night = observation["night"]
>         if not observation_night:
>             observation_night = datetime.now(tz=pytz.utc)
> ```

`observation_night` should rather be a `date`, to be consistent. (Isn't there a `date.today` function?)
___
*[`saltapi/repository/proposal_repository.py` line 1772 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGt2yiDnXiUpAPxXXz:-NIGt2yiDnXiUpAPxXY-:brru6rg) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1772)):*
> ```Python
>             observation_night = datetime.now(tz=pytz.utc)
>         if type(observation_night) == date:
>             observation_night = datetime(
> ```

That is probably correct. But given that noon is right at the border between two days (as seen from `semester_end`'s point of view, there might be no harm in choosing a later time. You never know...
___
*[`saltapi/repository/proposal_repository.py` line 1773 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGtd-8BlUiuJoC7gM7:-NIGtd-945c9SMFdkRYc:b-prkghu) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1773)):*
> ```Python
>         if type(observation_night) == date:
>             observation_night = datetime(
>                 observation_night.year,
> ```

Wasn't there a `combine` method for joining date and time. (I learned that from *you* the other day, I think... :-) )
___
*[`saltapi/repository/proposal_repository.py` line 1777 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGzOcEAJWW71PvgHBe:-NIGzOcEAJWW71PvgHBf:bqok5oi) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1777)):*
> ```Python
>                 observation_night.day,
>                 12, 0, 0, 0, tzinfo=pytz.utc)
>         return semester_end(semester_of_datetime(observation_night))
> ```

Actually, I don't think this function should return a datetime. A date is probably more meaningful, not least that is what the data_elease_date function will return.
___
*[`saltapi/service/permission_service.py` line 454 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1N_0G670GcwoI0EVo:-NIGu41RDaBq8k_FpD0T:b1zlocl) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/service/permission_service.py#L454)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

help me here
</blockquote></details>

All I meant is that

```
        if maximum_period <= proprietary_period_update.proprietary_period:
            return True

        return False
```

can be simplified to

```
      return maximum_period <= proprietary_period_update.proprietary_period
```
___
*[`tests/conftest.py` line 154 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGvipU3Xqh0Ch4Xiob:-NIGvipU3Xqh0Ch4Xioc:bc9apxv) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/conftest.py#L154)):*
> ```Python
>         return cast(str, users[normalized_user_type + "s"][partner_code])
> 
>     if normalized_user_type == "administrator_investigator":
> ```

Maybe `administrator_and_investigator` might be clearer. Also, I think you should pass a proposal code, as this is a proposal-specific role.
___
*[`tests/conftest.py` line 155 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGwDyY81EIsZp8Ktbi:-NIGwDyY81EIsZp8Ktbj:b-4w2zxb) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/conftest.py#L155)):*
> ```Python
> 
>     if normalized_user_type == "administrator_investigator":
>         print(users)
> ```

Unnecessary print statement.
___
*[`tests/integration/proposals/test_update_propriotory_period.py` line 1 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIHG5wT79NFExmYAxdb:-NIHG5wT79NFExmYAxdc:bp6pyig) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/integration/proposals/test_update_propriotory_period.py#L1)):*
> ```Python
> from typing import Dict, Any
> ```

The filename should be test_update_proprietary_period.py
___
*[`tests/integration/proposals/test_update_propriotory_period.py` line 70 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIH7gRKB2z4HOdJXH0_:-NIH7gRKB2z4HOdJXH0a:b9punrg) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/integration/proposals/test_update_propriotory_period.py#L70)):*
> ```Python
>         ("2016-1-COM-001", {"proprietary_period": 5, "motivation": None}),
>         ("2016-1-SVP-001", {"proprietary_period": 5, "motivation": None}),
>         ("2019-1-GWE-005", {"proprietary_period": 5, "motivation": None}),
> ```

I wouldn't include the GWE proposal.
___
*[`tests/integration/proposals/test_update_propriotory_period.py` line 82 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIH8oS2-wrQTteIl7oj:-NIH8oS2-wrQTteIl7ok:bd0p6zi) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/integration/proposals/test_update_propriotory_period.py#L82)):*
> ```Python
>     authenticate(pi, client)
>     response = client.put(_url(proposal_code), json=proprietary_period_update)
>     assert response.status_code == status.HTTP_202_ACCEPTED
> ```

The status code is incorrect. It rather should be a 200, as the request has been completed. You still need the 202 for the case that a motivation is required, though. As a consequence, there is no need for the status any longer. However, you might test that the correct requested periods is returned.
___
*[`tests/integration/proposals/test_update_propri [...]

2022-12-05 13:27 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 23 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1745 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGrl4M-Mb9kh2Jh9Dw:-NII1VBw2F3I0fpUOsXR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1745)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh... Good catch!
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1760 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGyd6M0u7vSF78keXP:-NII2DtP4G0xnE-jCHRq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1760)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The return type is missing.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1760 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIH6DTH84GqoJN8z426:-NII2Ejy828WkpC1Zr5k:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1760)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`proposal_code` isa not used.
</blockquote></details>

removed
___
*[`saltapi/repository/proposal_repository.py` line 1770 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGsP4C0medFpn5Ec4N:-NII2Q769ZlahxFhFibQ:bj4y5nt) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1770)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`observation_night` should rather be a `date`, to be consistent. (Isn't there a `date.today` function?)
</blockquote></details>

today Doesn't include time zone it is a date
___
*[`saltapi/repository/proposal_repository.py` line 1772 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGt2yiDnXiUpAPxXXz:-NII30aaELNb3Ori45Xy:bienug1) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1772)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That is probably correct. But given that noon is right at the border between two days (as seen from `semester_end`'s point of view, there might be no harm in choosing a later time. You never know...
</blockquote></details>

using 1 second after 12
___
*[`saltapi/repository/proposal_repository.py` line 1773 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGtd-8BlUiuJoC7gM7:-NII4DWu0yRbR4dAMMY4:bpkta4q) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1773)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wasn't there a `combine` method for joining date and time. (I learned that from *you* the other day, I think... :-) )
</blockquote></details>

Combine doesn't combine with time zone
___
*[`saltapi/repository/proposal_repository.py` line 1777 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGzOcEAJWW71PvgHBe:-NII4zs53462JegrZ8rv:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1777)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Actually, I don't think this function should return a datetime. A date is probably more meaningful, not least that is what the data_elease_date function will return.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 454 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1N_0G670GcwoI0EVo:-NII5HwP9qWnpkPTIQUr:b-xqo39p) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/service/permission_service.py#L454)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

All I meant is that

```
        if maximum_period <= proprietary_period_update.proprietary_period:
            return True

        return False
```

can be simplified to

```
      return maximum_period <= proprietary_period_update.proprietary_period
```
</blockquote></details>

I feel so stupid  U+1F605
___
*[`tests/conftest.py` line 154 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGvipU3Xqh0Ch4Xiob:-NIHKuex-GvOdwnFnefz:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/conftest.py#L154)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe `administrator_and_investigator` might be clearer. Also, I think you should pass a proposal code, as this is a proposal-specific role.
</blockquote></details>

Done.
___
*[`tests/conftest.py` line 155 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGwDyY81EIsZp8Ktbi:-NIHKuzO7K9wFGhONsBD:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/conftest.py#L155)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary print statement.
</blockquote></details>

removed
___
*[`tests/integration/proposals/test_update_propriotory_period.py` line 1 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIHG5wT79NFExmYAxdb:-NIHLD3b45RWJOFIW9TK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/integration/proposals/test_update_propriotory_period.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The filename should be test_update_proprietary_period.py
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_propriotory_period.py` line 70 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIH7gRKB2z4HOdJXH0_:-NIHLzmFCBgSTxrJJ1aJ:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/integration/proposals/test_update_propriotory_period.py#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wouldn't include the GWE proposal.
</blockquote></details>

removed
___
*[`tests/integration/proposals/test_update_propriotory_period.py` line 82 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIH8oS2-wrQTteIl7oj:-NIIFu1--NO34BAjtsrd:b-cyquhh) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/integration/proposals/test_update_propriotory_period.py#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The status code is incorrect. It rather should be a 200, as the request has been completed. You still need the 202 for the case that a motivation is required, though. As a consequence, there is no need for the status any longer. However, you might test that the correct requested periods is returned.
</blockquote></details>

Done.
but I kept the status it does no harm
___
*[`tests/integration/proposals/test_update_propriotory_period.py` line 86 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIHAXx36GT8Yz7gfuoW:-NIHXwk_6hxFhN6TSe2Q:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/integration/proposals/test_update_propriotory_period.py#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are not testing the case that a PI or PC tries to update a proprietary period (beyond the maximum) without a motivation.

And maybe the name coul [...]

2022-12-05 13:28 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 23 unresolved discussions (waiting on @hettlage)

___
*[`tests/integration/proposals/test_update_propriotory_period.py` line 133 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIHGsUd772cZwHfWWrk:-NIXTLON-tkQUVlTGMR-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/tests/integration/proposals/test_update_propriotory_period.py#L133)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It should be made clear somewhere that this refers to investigators who aren't PI or PI.

Also you should test that, say, a PI cannot update someone else's proposal.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-06 10:28 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 16 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/util.py` line 183 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIaogXS2NylsMkci9UF:-NIaogXT-90PH3-cRcSE:bvci2g) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/util.py#L183)):*
> ```Python
> 
> 
> def now() -> datetime:
> ```

Yes, I know I suggested this. But I think your suggested approach is the better option. This function is unnecessary.
___
*[`saltapi/repository/proposal_repository.py` line 1770 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGsP4C0medFpn5Ec4N:-NIapRwv2LpVJKWCNhv6:b-t2fvy7) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1770)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

today Doesn't include time zone it is a date
</blockquote></details>

But the observation night really is a date.

It might make more sense to directly handle the case of having no observation:

```
if not observation_night:
    return semester_end(semester_of_datetime(observation_night))
```

___
*[`saltapi/repository/proposal_repository.py` line 1772 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGt2yiDnXiUpAPxXXz:-NIaqRalD0fw0Z5F44L-:b3lm0f7) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1772)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

using 1 second after 12
</blockquote></details>

I don't see the 1 second.
___
*[`saltapi/repository/proposal_repository.py` line 1773 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGtd-8BlUiuJoC7gM7:-NIaqo3t8YiJf6j5Jf_E:b-5hynej) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1773)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Combine doesn't combine with time zone
</blockquote></details>

Ah, thanks.
___
*[`saltapi/repository/proposal_repository.py` line 23 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIaosn4-MBVSa6Nqto8:-NIaosn4-MBVSa6Nqto9:b7qs9as) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/repository/proposal_repository.py#L23)):*
> ```Python
>     semester_of_datetime,
>     semester_start,
>     tonight, now,
> ```

Unnecessary import
___
*[`saltapi/repository/proposal_repository.py` line 1764 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIaqWBN-pwtc3SGACn7:-NIaqWBN-pwtc3SGACn8:b-xf8m2r) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/repository/proposal_repository.py#L1764)):*
> ```Python
>         # find the latest observation
> 
>         observation_night = None
> ```

I think you have to add a type hint here:

```
observation_night: Optional[date] = None
```
___
*[`saltapi/repository/proposal_repository.py` line 1771 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIaoyNC4b-99hb3BCbo:-NIaoyNC4b-99hb3BCbp:b-x83fmf) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/repository/proposal_repository.py#L1771)):*
> ```Python
>                 observation_night = observation["night"]
>         if not observation_night:
>             observation_night = now()
> ```

Should use the `datetime.now` method, as before.
___
*[`saltapi/repository/proposal_repository.py` line 1772 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIap25n5TGb9_UGWpc5:-NIap25n5TGb9_UGWpc6:b-4w2zxb) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/repository/proposal_repository.py#L1772)):*
> ```Python
>         if not observation_night:
>             observation_night = now()
>             print(">>>: ", now(), observation_night)
> ```

Unnecessary print statement.
___
*[`saltapi/service/permission_service.py` line 454 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1N_0G670GcwoI0EVo:-NIarJSFAYW2-55FSaJo:b-bgyqsa) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/service/permission_service.py#L454)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I feel so stupid  U+1F605
</blockquote></details>

Oh dear. Please don't report me to HR for making you feel stupid... ;-)
___
*[`saltapi/web/api/proposals.py` line 240 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIarloG8EplbeD8gLGN:-NIarloG8EplbeD8gLGO:b-jvgkt6) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/web/api/proposals.py#L240)):*
> ```Python
>     ),
>     user: User = Depends(get_current_user),
> ) -> NewProprietaryPeriod or JSONResponse:
> ```

Wouldn't that be `Union[..., ...]` rather than `... or ...`?

But you return a `JSONTResponse` all the time, don't you?
___
*[`saltapi/web/api/proposals.py` line 256 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIasqP5EVmXBnvhFTLi:-NIasqP5EVmXBnvhFTLj:b-3esyla) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/web/api/proposals.py#L256)):*
> ```Python
>         proposal_service = services.proposal_service(unit_of_work.connection)
>         proposal = proposal_service.get_proposal(proposal_code)
>         if permission_service.is_motivation_needed_to_update_proprietary_period(
> ```

In the interest of avoiding code duplication (in particular duplicating the `unit_of_work.commit`), you might consider just setting a status_code and a content variable in the if / else, and commit / return outside it.
___
*[`tests/repository/test_proposal_repository.py` line 16 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIawKVi3p-U4cTRHlf0:-NIawKVi3p-U4cTRHlf1:b-l3x9n6) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/tests/repository/test_proposal_repository.py#L16)):*
> ```Python
> 
> 
> def mock_now():
> ```

Coul. be a constant rather than a function.
___
*[`tests/repository/test_proposal_repository.py` line 542 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIawvTA08KpiOtknEMS:-NIawvTA08KpiOtknEMT:b-ih2jbi) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/tests/repository/test_proposal_repository.py#L542)):*
> ```Python
>         monkeypatch
> ) -> None:
>     monkeypatch.setattr(util, 'now', mock_now())
> ```

Here is how you can mock the `datetime.now` method with the `patch` function from `unittest.mock`:

```
    with patch("saltapi.repository.proposal_repository.datetime") as mock_datetime:
        mock_datetime.now.return_value = mock_now()
        mock_datetime.side_effect = lambda *args, **kwargs: datetime(*args, **kwargs)
        proposal_repository = ProposalRepository(db_connection)
        assert (
            proposal_repository.proprietary_period_start_date(block_visits)
            == expected_date
        )
```
___
*[`tests/integration/proposals/test_update_proprietary_period.py` line 1 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIav-wWELKKYQieS94h:-NIav-wWELKKYQieS94i:b-v069zb) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/tests/integration/proposals/test_update_proprietary_period.py#L1)):*
> ```Python
> from typing import Dict, Any
> ```

I think you are missing tests for PCs  [...]

2022-12-06 16:46 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 16 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/util.py` line 183 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIaogXS2NylsMkci9UF:-NIc7bsK4XgC2T-82u1D:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/util.py#L183)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes, I know I suggested this. But I think your suggested approach is the better option. This function is unnecessary.
</blockquote></details>

removed
___
*[`saltapi/repository/proposal_repository.py` line 1770 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGsP4C0medFpn5Ec4N:-NIcIrolBgRx-QviQqGG:bkx99go) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1770)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But the observation night really is a date.

It might make more sense to directly handle the case of having no observation:

```
if not observation_night:
    return semester_end(semester_of_datetime(observation_night))
```

</blockquote></details>

doing differently 
___
*[`saltapi/repository/proposal_repository.py` line 1772 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGt2yiDnXiUpAPxXXz:-NIc4hVn975iezN5Smk2:bicaju5) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1772)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see the 1 second.
</blockquote></details>

sorry undid it
___
*[`saltapi/repository/proposal_repository.py` line 1773 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGtd-8BlUiuJoC7gM7:-NIc4lrk24sa6vxrvkcE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1773)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, thanks.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 23 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIaosn4-MBVSa6Nqto8:-NIc7hsp1X3wLGSeo21z:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/repository/proposal_repository.py#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary import
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1764 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIaqWBN-pwtc3SGACn7:-NIc48hG3QMHTD7TrJ0K:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/repository/proposal_repository.py#L1764)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you have to add a type hint here:

```
observation_night: Optional[date] = None
```
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1771 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIaoyNC4b-99hb3BCbo:-NIc8ycVD02cZkj3TyLE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/repository/proposal_repository.py#L1771)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should use the `datetime.now` method, as before.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1772 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIap25n5TGb9_UGWpc5:-NIc4ZWiEeWB_T26r7lo:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/repository/proposal_repository.py#L1772)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary print statement.
</blockquote></details>

removed
___
*[`saltapi/service/permission_service.py` line 454 at r3](https://reviewable.io/reviews/saltastroops/salt-api/124#-NI1N_0G670GcwoI0EVo:-NIc4pVU8NFl60RyrJSQ:bl8jhuk) ([raw file](https://github.com/saltastroops/salt-api/blob/037c1d6d86374bf2ee8128e6198495a4c6414fae/saltapi/service/permission_service.py#L454)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh dear. Please don't report me to HR for making you feel stupid... ;-)
</blockquote></details>

U+1F605 => suppose to be a laughing emoji 😂
___
*[`saltapi/web/api/proposals.py` line 240 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIarloG8EplbeD8gLGN:-NIc58SqCLiZxOAIh1vq:b4aj01r) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/web/api/proposals.py#L240)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't that be `Union[..., ...]` rather than `... or ...`?

But you return a `JSONTResponse` all the time, don't you?
</blockquote></details>

for got to remove nice catch
___
*[`saltapi/web/api/proposals.py` line 256 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIasqP5EVmXBnvhFTLi:-NIcK6VA-dbfYMMSQZdP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/saltapi/web/api/proposals.py#L256)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

In the interest of avoiding code duplication (in particular duplicating the `unit_of_work.commit`), you might consider just setting a status_code and a content variable in the if / else, and commit / return outside it.
</blockquote></details>

Done.
___
*[`tests/repository/test_proposal_repository.py` line 16 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIawKVi3p-U4cTRHlf0:-NIcISf87eMkx4JG63bb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/tests/repository/test_proposal_repository.py#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Coul. be a constant rather than a function.
</blockquote></details>

Done.
___
*[`tests/repository/test_proposal_repository.py` line 542 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIawvTA08KpiOtknEMS:-NIcIUly4ppJRuyiS5gr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/tests/repository/test_proposal_repository.py#L542)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Here is how you can mock the `datetime.now` method with the `patch` function from `unittest.mock`:

```
    with patch("saltapi.repository.proposal_repository.datetime") as mock_datetime:
        mock_datetime.now.return_value = mock_now()
        mock_datetime.side_effect = lambda *args, **kwargs: datetime(*args, **kwargs)
        proposal_repository = ProposalRepository(db_connection)
        assert (
            proposal_repository.proprietary_period_start_date(block_visits)
            == expected_date
        )
```
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_proprietary_period.py` line 1 at r6](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIav-wWELKKYQieS94h:-NIcHpkECy5FhBTuQcm9:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3941bafab5ca1d413cce1a6e140004aee04300c8/tests/integration/proposals/test_update_proprietary_period.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you are missing tests for PCs being allowed to request without a motivation?

Also, I'd suggest to order the test functions, grouping the admin ones, the PI ones, the PC ones and the others together.
</blockquote></details>

Done.
___
*[`tests/integration/pro [...]

2022-12-07 12:21 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1770 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGsP4C0medFpn5Ec4N:-NIg4Hzo847gLKBLF4Y1:b-3jcdv6) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1770)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

doing differently 
</blockquote></details>

There is a small problem, though. Assume the current time is 03:00 at night on 1 May. The your approach will give a start date of 1 November, whereas it should be 1 May.

My suggested code had a bug, of course; it was supposed to be

```
if not observation_night:
    return semester_end(semester_of_datetime(date time.now()))
```


<!-- Sent from Reviewable.io -->

2022-12-08 13:10 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1770 at r5](https://reviewable.io/reviews/saltastroops/salt-api/124#-NIGsP4C0medFpn5Ec4N:-NIlGs4ZBfnvzXVrEIuU:bd260eg) ([raw file](https://github.com/saltastroops/salt-api/blob/5ab5dc84d3ed54e455fdfb09229c503321424d47/saltapi/repository/proposal_repository.py#L1770)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a small problem, though. Assume the current time is 03:00 at night on 1 May. The your approach will give a start date of 1 November, whereas it should be 1 May.

My suggested code had a bug, of course; it was supposed to be

```
if not observation_night:
    return semester_end(semester_of_datetime(date time.now()))
```
</blockquote></details>

I am no longer using datetime but date.


<!-- Sent from Reviewable.io -->

2022-12-19 11:10 UTC, hettlage reviewed
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2022-12-19 11:11 UTC, hettlage approved these changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2023-01-23 17:04 UTC, merged