Phase one Data
saltastroops/salt-api pull request #127
Opened 2023-01-12 08:28 UTC by Eb-Zeero

2023-01-23 18:15 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: all files reviewed, 27 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/util.py` line 213 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMU_jbk2isjlEhBg7Ai:-NMU_jbk2isjlEhBg7Aj:b-co1bme) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/util.py#L213)):*
> ```Python
> 
> 
> def target_type(row: Any) -> Optional[str]:
> ```

I think the type and subtype should be kept separate.

But this is a feature request, and I' ve raised an issue.
___
*[`saltapi/repository/proposal_repository.py` line 505 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUb7h4-JFDKLiCw9sS:-NMUb7h4-JFDKLiCw9sT:bh8tnu4) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L505)):*
> ```Python
>             "total_requested_time": row.total_requested_time,
>             "proprietary_period": row.proprietary_period,
>             "is_time_restricted": row.is_time_restricted > 0,
> ```

Nitpicking, I know, but given this is a boolean `!= 0` rather than `> 0` would make more sense to me.
___
*[`saltapi/repository/proposal_repository.py` line 506 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUbKdc-tOSgdRmcWaM:-NMUbKdc-tOSgdRmcWaN:bh8tnu4) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L506)):*
> ```Python
>             "proprietary_period": row.proprietary_period,
>             "is_time_restricted": row.is_time_restricted > 0,
>             "is_p4": row.is_p4 > 0,
> ```

Nitpicking, I know, but given this is a boolean `!= 0` rather than `> 0` would make more sense to me.
___
*[`saltapi/repository/proposal_repository.py` line 1811 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUbwcOC9KpOvwCYT_u:-NMUbwcOC9KpOvwCYT_v:bso1sqt) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1811)):*
> ```Python
>                 TB.Time_Base                                    AS period_time_base,
>                 HT.Identifier                                   AS horizons_identifier,
>                 IF((MT1.Target_Id IS NOT NULL
> ```

But if there is a Horizons identifier, the target should non-sidereal as well.
___
*[`saltapi/repository/proposal_repository.py` line 1901 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUeZkc8gWqv2UcRkQH:-NMUeZkc8gWqv2UcRkQI:b84yz0v) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1901)):*
> ```Python
>         return req_time
> 
>     def _get_configurations(self, proposal_code) -> Optional[List[Dict[str, Any]]]:
> ```

_get_configurations  > _get_instrument_configurations
___
*[`saltapi/repository/proposal_repository.py` line 1901 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUfQAw5mZZGjvjqdvR:-NMUfQAw5mZZGjvjqdvS:b94y4j0) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1901)):*
> ```Python
>         return req_time
> 
>     def _get_configurations(self, proposal_code) -> Optional[List[Dict[str, Any]]]:
> ```

Why do you return None rather than an empty array?
___
*[`saltapi/repository/proposal_repository.py` line 1949 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUd8cPDCZ4x3SEB1C0:-NMUd8cPDCZ4x3SEB1C1:b-qi8wyg) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1949)):*
> ```Python
>             elif row.hrs:
>                 instrument = "HRS"
>                 mode = row.hrs_mode
> ```

I think this is in all caps in the database, but it shouldn't be in the API. (I think we are only using a capital for the first letter, such as "Low resolution".) Similar concerns might apply top other modes. (There should be a way of handling this already, though?)
___
*[`saltapi/repository/proposal_repository.py` line 1964 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUf6wx4pL4oguu7MxL:-NMUf6wx4pL4oguu7MxM:bef83ps) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1964)):*
> ```Python
>                 simulations = row.scam_simulation
>             else:
>                 raise NotFoundError(f"No instrument configuration was found for proposal: {proposal_code}")
> ```

The error message is misleading, as configurations were found. Maybe better:

"Unknown instrument configuration found for proposal: {proposal_code}"
___
*[`saltapi/web/schema/proposal.py` line 133 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUdr6F9uXJi0cZYp3E:-NMUdr6F9uXJi0cZYp3F:bo75hbc) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L133)):*
> ```Python
>     is_time_restricted: bool = Field(
>         ...,
>         title="Is the proposal time restricted?",
> ```

"Are there restrictions for the observing times?"
___
*[`saltapi/web/schema/proposal.py` line 135 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUeBW2CX4Mk0ec_jtk:-NMUeBW2CX4Mk0ec_jtl:bo75hbc) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L135)):*
> ```Python
>         title="Is the proposal time restricted?",
>         description=(
>             "Is the proposal time restricted?"
> ```

"Are there restrictions for the observing times?"
___
*[`saltapi/web/schema/proposal.py` line 140 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUeEnx64ZLj5OgDVXs:-NMUeEnx64ZLj5OgDVXt:bnjcr3m) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L140)):*
> ```Python
>     is_p4: bool = Field(
>         ...,
>         title="Is it priority 4 proposal?",
> ```

Is the proposal a priority 4 proposal?
___
*[`saltapi/web/schema/proposal.py` line 142 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUeUNM-1z7C7AAsA_w:-NMUeUNM-1z7C7AAsA_x:bzct1g9) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L142)):*
> ```Python
>         title="Is it priority 4 proposal?",
>         description=(
>             "Is the proposal only requesting a priority 4 time?"
> ```

"Is the proposal only requesting priority 4 time?"
___
*[`saltapi/web/schema/proposal.py` line 277 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUflQw5UFFfWKGlhoy:-NMUflQw5UFFfWKGlhoz:b-vdstgi) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L277)):*
> ```Python
> 
> 
> class Configuration(BaseModel):
> ```

Configuration > InstrumentConfiguration
___
*[`saltapi/web/schema/proposal.py` line 278 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUfc_R4J4UYy3tls_H:-NMUfc_R4J4UYy3tls_I:b-qyl3sx) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L278)):*
> ```Python
> 
> class Configuration(BaseModel):
>     observation_id: int = Field(
> ```

The observation_id is not required, I think.

I've raised an issue for this.
___
*[`saltapi/web/schema/proposal.py` line 290 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUm0aJ3r3TG7bi5DTB:-NMUm0aJ3r3TG7bi5DTC:bpqq2vx) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af9826080 [...]

2023-01-24 16:49 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: 3 of 6 files reviewed, 27 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 505 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUb7h4-JFDKLiCw9sS:-NMY8bFfC4DBj39j1mC0:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L505)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nitpicking, I know, but given this is a boolean `!= 0` rather than `> 0` would make more sense to me.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 506 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUbKdc-tOSgdRmcWaM:-NMY8bYn3K-VWlLapKoJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L506)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nitpicking, I know, but given this is a boolean `!= 0` rather than `> 0` would make more sense to me.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1811 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUbwcOC9KpOvwCYT_u:-NMY96E_BnGaqe_wClj9:b-wnyv9p) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1811)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But if there is a Horizons identifier, the target should non-sidereal as well.
</blockquote></details>

Can we discuss this.
___
*[`saltapi/repository/proposal_repository.py` line 1901 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUfQAw5mZZGjvjqdvR:-NMYANL-C-W47DDmXE0i:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1901)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you return None rather than an empty array?
</blockquote></details>

fixed
___
*[`saltapi/repository/proposal_repository.py` line 1901 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUeZkc8gWqv2UcRkQH:-NMYIwnF4VcOBfrAfa5Y:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1901)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

_get_configurations  > _get_instrument_configurations
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1949 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUd8cPDCZ4x3SEB1C0:-NMYDL28-WXem10uYN0O:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1949)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this is in all caps in the database, but it shouldn't be in the API. (I think we are only using a capital for the first letter, such as "Low resolution".) Similar concerns might apply top other modes. (There should be a way of handling this already, though?)
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1964 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUf6wx4pL4oguu7MxL:-NMYDVCGCTgChytqpbTx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1964)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The error message is misleading, as configurations were found. Maybe better:

"Unknown instrument configuration found for proposal: {proposal_code}"
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 133 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUdr6F9uXJi0cZYp3E:-NMYDppS7nziVu3D43qj:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L133)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Are there restrictions for the observing times?"
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 135 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUeBW2CX4Mk0ec_jtk:-NMYDq6c4qaCkLwBB0Eo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L135)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Are there restrictions for the observing times?"
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 140 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUeEnx64ZLj5OgDVXs:-NMYE6ZT4QOnay9chXQg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L140)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is the proposal a priority 4 proposal?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 142 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUeUNM-1z7C7AAsA_w:-NMYE70AEi4AZnEC2mMf:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L142)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Is the proposal only requesting priority 4 time?"
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 277 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUflQw5UFFfWKGlhoy:-NMYEGRvDHE1sibFGtDT:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L277)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Configuration > InstrumentConfiguration
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 290 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUm0aJ3r3TG7bi5DTB:-NMYERxB-5oxWphW8TmH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L290)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Mode > mode
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 291 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUm4bcBf1SR4aYTyPK:-NMYEWGt29sajk-9jx-y:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L291)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The configuration mode. This is the filter for BVIT, the exposure mode for HRS, the grating for RSS and NIR, and the detector mode for Salticam.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 294 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUmYfOAl9RP4z4fQ-K:-NMYJ1dh98F-FDBygyzx:b-7d9vnb) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L294)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A simulation is made up of a title, a description and a link to the simulation file. The `simulations` fields should new a non-optional list of simulations (which may be empty, though).
</blockquote></details>

can you explain this further please
___
*[`saltapi/web/schema/proposal.py` line 323 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUmvMb40yTC [...]

2023-01-25 09:30 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: all files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/util.py` line 245 at r3](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMbww-Z5IeHON-dZ616:-NMbww-_-M4psS-nQYpq:bz3eoye) ([raw file](https://github.com/saltastroops/salt-api/blob/0c7752019d7a7cd890348f4d66e77537e5e42865/saltapi/util.py#L245)):*
> ```Python
> 
> 
> def hrs_mode_name_corrector(mode: str) -> str:
> ```

Maybe better "normalised_hrs_mode"?
___
*[`saltapi/repository/proposal_repository.py` line 1946 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMcEQsk8cCZHJ6uCa0H:-NMcEQsk8cCZHJ6uCa0I:bbjswrz) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1946)):*
> ```Python
>                 instrument = "BVIT"
>                 mode = row.bvit_filter
>                 simulations = None
> ```

There can be more than one simulation, and I don't think the code is handling that case.
___
*[`saltapi/repository/proposal_repository.py` line 1884 at r3](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMcCywtEVbJyZHx48W4:-NMcCywtEVbJyZHx48W5:b-8v82tn) ([raw file](https://github.com/saltastroops/salt-api/blob/0c7752019d7a7cd890348f4d66e77537e5e42865/saltapi/repository/proposal_repository.py#L1884)):*
> ```Python
>         """
>         )
>         sem_req_time = []
> ```

Maybe better `see_req_times`, given it's an array? (And maybe just `req_times`?)
___
*[`saltapi/web/schema/proposal.py` line 436 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUnQ3g0aibh-ARI_d1:-NMcFU2k7dDuKyPo7tmf:bdmc1jn) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L436)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this is for phase 1 only for p2 we have an instrument
</blockquote></details>

Yes, but when there are a separate types for Phase 1 and 2, "Phase 1" becomes obsolete.


<!-- Sent from Reviewable.io -->

2023-01-26 19:44 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: all files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/util.py` line 245 at r3](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMbww-Z5IeHON-dZ616:-NMcLbTH1V7Slhn9ZMI2:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/0c7752019d7a7cd890348f4d66e77537e5e42865/saltapi/util.py#L245)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better "normalised_hrs_mode"?
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1946 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMcEQsk8cCZHJ6uCa0H:-NMcnyaQ6qHqEBC56BZk:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/repository/proposal_repository.py#L1946)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There can be more than one simulation, and I don't think the code is handling that case.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1884 at r3](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMcCywtEVbJyZHx48W4:-NMcLrbH0so2czZVIItr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/0c7752019d7a7cd890348f4d66e77537e5e42865/saltapi/repository/proposal_repository.py#L1884)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better `see_req_times`, given it's an array? (And maybe just `req_times`?)
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 278 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUfc_R4J4UYy3tls_H:-NMcoQpj9185OZRiUd0m:b-kk3ut2) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L278)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The observation_id is not required, I think.

I've raised an issue for this.
</blockquote></details>

solved
___
*[`saltapi/web/schema/proposal.py` line 371 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUn5fADH3S7Kr5HUN3:-NMjauyi6WtJ1b4uvJWy:bb6un1j) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L371)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As for the frontend, I think Phase 1 and 2 warrant different types.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-27 11:53 UTC, hettlage requested changes
> Reviewed 8 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: 10 of 11 files reviewed, 27 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1922 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmtDrl2ymvru-Hd5rX:-NMmtDrl2ymvru-Hd5rY:bsyaa3) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/repository/proposal_repository.py#L1922)):*
> ```Python
>             simulations.append({
>                 "name": row.name,
>                 "path": row.path,
> ```

It might be better to return the URL for accessing the file, not least because the file path is an implementation detail.

The same of course applies to the other methods for getting simulations.
___
*[`saltapi/repository/proposal_repository.py` line 2085 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmyLv7BsCgNfrO_4F_:-NMmyLv7BsCgNfrO_4Fa:bx1yx0h) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/repository/proposal_repository.py#L2085)):*
> ```Python
>             """
> SELECT
> 	FirstName		AS given_name,
> ```

This query maybe should rather be included in the query for the proposal investigators.
___
*[`saltapi/repository/proposal_repository.py` line 2111 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmuZhrETpJfBKuusWB:-NMmuZhrETpJfBKuusWC:b2bavgl) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/repository/proposal_repository.py#L2111)):*
> ```Python
>         stmt = text(
>             """
> SELECT
> ```

Why do you need a separate query for this?
___
*[`saltapi/service/proposal_service.py` line 90 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmurqO8kt6tM0fz5S5:-NMmurqO8kt6tM0fz5S6:bo6pj94) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/service/proposal_service.py#L90)):*
> ```Python
>         return path
> 
>     def get_proposal(self, proposal_code: str) -> Union[P1Proposal, P2Proposal]:
> ```

I don't think we use API schema classes at the service level (and I don't think we should).

This implies that the P1/2 logic has to move to the API level.
___
*[`saltapi/web/schema/P1Proposal.py` line 1 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn28xCBrJ7Z7OF-t4l:-NMn28xCBrJ7Z7OF-t4m:b-qxd6hz) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L1)):*
> ```Python
> from typing import Optional, List
> ```

The file should be called p1_proposal.py, I'd say,
___
*[`saltapi/web/schema/P1Proposal.py` line 19 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmsjDNBJ7BDaH_QkPV:-NMmsjDOBee987myXQDF:bwfrpmq) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L19)):*
> ```Python
>         description="The simulation name."
>     )
>     path: str = Field(
> ```

The type should not contain the path (which would be a file path), but a URL for accessing the simulation file.
___
*[`saltapi/web/schema/P1Proposal.py` line 27 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmvz5g2dXAboXLYBdl:-NMmvz5g2dXAboXLYBdm:bgulv7) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L27)):*
> ```Python
>         ...,
>         title="Description",
>         description="The PI's Comment."
> ```

"A Description of the simulation."
___
*[`saltapi/web/schema/P1Proposal.py` line 31 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmwYNF3UrZXJJ6jWji:-NMmwYNF3UrZXJJ6jWjj:b-emoj2) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L31)):*
> ```Python
> 
> 
> class ThesisStudent(BaseModel):
> ```

Calling this type "StudentThesis" might be better.
___
*[`saltapi/web/schema/P1Proposal.py` line 35 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmwqTB08E79ETC4nD1:-NMmwqTB08E79ETC4nD2:bckt5pn) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L35)):*
> ```Python
>         ...,
>         title="Student",
>         description="The student doing thesis"
> ```

The student working on the thesis.

But there is a problem. The thesis is linked to a student, and this is not entirely reflected in the schema. (What would happen if the proposal contained two students with the sane name?)

So I guess the thesis should rather be part of the proposal investigator type.
___
*[`saltapi/web/schema/P1Proposal.py` line 37 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmzQxMBCB9UlsZLcq8:-NMmzQxMBCB9UlsZLcq9:bpar672) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L37)):*
> ```Python
>         description="The student doing thesis"
>     )
>     thesis_type: str = Field(
> ```

This isn't a string -- it can only be Masters or PhD.
___
*[`saltapi/web/schema/P1Proposal.py` line 42 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmzok109nXRMq7EJdo:-NMmzok109nXRMq7EJdp:b-lv7ba7) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L42)):*
> ```Python
>         description="The thesis type"
>     )
>     thesis_description: str = Field(
> ```

Maybe better: relevance_of_proposal
___
*[`saltapi/web/schema/P1Proposal.py` line 44 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-72V2KT3r6BoFvf3:-NMn-72V2KT3r6BoFvf4:beale4v) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L44)):*
> ```Python
>     thesis_description: str = Field(
>         ...,
>         title="Thesis description",
> ```

Relevance of proposal
___
*[`saltapi/web/schema/P1Proposal.py` line 45 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-HOq9wrMzghQQv9e:-NMn-HOq9wrMzghQQv9f:b-9u0n3l) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L45)):*
> ```Python
>         ...,
>         title="Thesis description",
>         description="Importance and contribution to the thesis"
> ```

Importance and contribution of the proposal too the thesis.

This field is optional.
___
*[`saltapi/web/schema/P1Proposal.py` line 47 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-OOP4--Z1Cd2IOc3:-NMn-OOP4--Z1Cd2IOc4:b-x1wedn) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L47)):*
> ```Python
>         description="Importance and contribution to the thesis"
>     )
>     completion_year: str = Field(
> ```

Maybe better: year_of_completion
___
*[`saltapi/web/schema/P1Proposal.py` line 49 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-RltDIwhSmR8Zjt9:-NMn-RltDIwhSmR8ZjtA:b-b6huk9) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L49)):*
> ```Python
>     completion_year: str = Field(
>         ...,
>         title="Completion year",
> ```

Year of completion
___
*[`saltapi/web/schema/P1Proposal.py` line 50 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-Ufr7jFM4eItduTJ:-NMn-Ufr7jFM4eItduTK:btxvkez) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L50)):*
> ```Python
>         ...,
>         title="Completion year",
> [...]

2023-01-30 07:20 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: 10 of 11 files reviewed, 27 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/proposal_service.py` line 90 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmurqO8kt6tM0fz5S5:-NMnar6W-yKKnHWZXxPA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/service/proposal_service.py#L90)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think we use API schema classes at the service level (and I don't think we should).

This implies that the P1/2 logic has to move to the API level.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 1 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn28xCBrJ7Z7OF-t4l:-NMnbEDa6ec9ZodXJAMI:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The file should be called p1_proposal.py, I'd say,
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 27 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmvz5g2dXAboXLYBdl:-NMnbhUh-xbq_IeAjmnC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"A Description of the simulation."
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 31 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmwYNF3UrZXJJ6jWji:-NMnbogN2UAWLEsSOo5x:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Calling this type "StudentThesis" might be better.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 35 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmwqTB08E79ETC4nD1:-NMndQvX6szApjFnoPVG:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The student working on the thesis.

But there is a problem. The thesis is linked to a student, and this is not entirely reflected in the schema. (What would happen if the proposal contained two students with the sane name?)

So I guess the thesis should rather be part of the proposal investigator type.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 37 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmzQxMBCB9UlsZLcq8:-NMndhtIDyYnRwgzQajA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This isn't a string -- it can only be Masters or PhD.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 42 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmzok109nXRMq7EJdo:-NMne6jR9vPBi3sf3BSt:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: relevance_of_proposal
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 44 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-72V2KT3r6BoFvf3:-NMneHpe6viifOZrHn3n:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Relevance of proposal
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 45 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-HOq9wrMzghQQv9e:-NMneIUx0nQKTTAQcVUr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Importance and contribution of the proposal too the thesis.

This field is optional.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 47 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-OOP4--Z1Cd2IOc3:-NMnf08JDx5WUx-mJ-Ll:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: year_of_completion
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 49 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-RltDIwhSmR8Zjt9:-NMnfAF6397SFSAEmI38:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Year of completion
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 50 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-Ufr7jFM4eItduTJ:-NMnfAc4EvZ1HxD5Ahhc:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The year when the thesis is expected to be completed.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 106 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn1yIp5SHSCp4d31za:-NMnfRY854Gzed9FPb8u:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L106)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The simulations for the proposal.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 110 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn24-WDg4xDp85awdj:-NMnfWYB6wVud-oc9Gfb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L110)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A phase 1 proposal.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 112 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn2h9p4tMT3SCiFYSu:-NMnhjIA58bni59pIa6_:b-114urf) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L112)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you redefine fields which are defined for the base class already?
</blockquote></details>

I missed them
___
*[`saltapi/web/schema/P2Proposal.py` line 1 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn2s1p3DPEy0ZUaawQ:-NMnhwfgAwx1gkiSXa4l:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P2Proposal.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The file should be called p2_proposal.py, I'd say,
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P2Proposal.py` line 15 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn2vZ7AOzORdezRNbD:-NMni7f40QCJ5Q9KkfO5:b-896fix) ([raw fil [...]

2023-01-30 12:37 UTC, hettlage requested changes
> Reviewed 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: 10 of 11 files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 493 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1Ydip6bB6Rr0_N8_S:-NN1Ydip6bB6Rr0_N8_T:b-4w2zxb) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/repository/proposal_repository.py#L493)):*
> ```Python
>         )
>         row = result.one()
>         print("####: ", row.submission_number)
> ```

Unnecessary print statement.
___
*[`saltapi/repository/proposal_repository.py` line 1923 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1cD3zEBDVqh7I2zsv:-NN1cD3zEBDVqh7I2zsw:btju4vs) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/repository/proposal_repository.py#L1923)):*
> ```Python
>             simulations.append({
>                 "name": row.name,
>                 "path": f"/instrument-simulation/hrs/{row.id}.hsim",
> ```

Should be instrument-simulations (i.e. plural).
___
*[`saltapi/web/api/proposals.py` line 2 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1cUAa7IZ7ki2oAwE9:-NN1cUAa7IZ7ki2oAwEA:b-3r7g2o) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/web/api/proposals.py#L2)):*
> ```Python
> from datetime import date
> from pprint import pprint
> ```

pprint should not be necessary.
___
*[`saltapi/web/schema/P1Proposal.py` line 45 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-HOq9wrMzghQQv9e:-NN1dAQG4NrPvYBC7rLO:bav95v3) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L45)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

too > to (Sorry!)
___
*[`saltapi/web/schema/P1Proposal.py` line 69 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-kZ02JCZJOW6ygNM:-NN1eCTtCrni2Kj-3wdn:b-gdjdpr) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

is_self_activable is a Phase 2 property.
</blockquote></details>

Isn't the is_self_activatable field included in GeneralProposalInfo already?
___
*[`saltapi/web/schema/P2Proposal.py` line 61 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1f1216vd7_uIbRZDT:-NN1f1216vd7_uIbRZDU:b-65c9sw) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P2Proposal.py#L61)):*
> ```Python
>         description="General proposal information for a semester",
>     )
>     investigators: List[Investigator] = Field(
> ```

Shouldn't this be a field for Phase 1 and 2, i.e. defined on Proposal?
___
*[`saltapi/web/schema/P2Proposal.py` line 64 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1f1kI9D8eru50jxRm:-NN1f1kI9D8eru50jxRn:b-65c9sw) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P2Proposal.py#L64)):*
> ```Python
>         ..., title="Investigators", description="Investigators on the proposal"
>     )
>     requested_times: List[RequestedTime] = Field(
> ```

Shouldn't this be a field for Phase 1 and 2, i.e. defined on Proposal?
___
*[`saltapi/web/schema/P2Proposal.py` line 84 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1f6_L0ioSkSDArE77:-NN1f6_L0ioSkSDArE78:b-65c9sw) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P2Proposal.py#L84)):*
> ```Python
>         description="Charged time, by priority, for the semester",
>     )
>     time_allocations: List[TimeAllocation] = Field(
> ```

Shouldn't this be a field for Phase 1 and 2, i.e. defined on Proposal?
___
*[`saltapi/web/schema/p1_proposal.py` line 123 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1eiRI3lxjrnDARQ8I:-NN1eiRI3lxjrnDARQ8J:b-65c9sw) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/web/schema/p1_proposal.py#L123)):*
> ```Python
>         description="General proposal information for a semester",
>     )
>     investigators: List[Investigator] = Field(
> ```

Shouldn't this be a field for Phase 1 and 2, i.e. defined on Proposal?
___
*[`saltapi/web/schema/p1_proposal.py` line 133 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1eUoC0hTw4fsa9hlW:-NN1eUoC0hTw4fsa9hlX:b-65c9sw) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/web/schema/p1_proposal.py#L133)):*
> ```Python
>         ),
>     )
>     requested_times: List[RequestedTime] = Field(
> ```

Shouldn't this be a field for Phase 1 and 2, i.e. defined on Proposal?
___
*[`saltapi/web/schema/p1_proposal.py` line 140 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1ednO12MMYzLFsoYw:-NN1ednPCR1xjb66JIIb:b-65c9sw) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/web/schema/p1_proposal.py#L140)):*
> ```Python
>         ),
>     )
>     time_allocations: List[TimeAllocation] = Field(
> ```

Shouldn't this be a field for Phase 1 and 2, i.e. defined on Proposal?


<!-- Sent from Reviewable.io -->

2023-01-30 12:52 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: 10 of 11 files reviewed, 17 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1922 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmtDrl2ymvru-Hd5rX:-NN1YbTL730pcaC4f1vs:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/repository/proposal_repository.py#L1922)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be better to return the URL for accessing the file, not least because the file path is an implementation detail.

The same of course applies to the other methods for getting simulations.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2085 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmyLv7BsCgNfrO_4F_:-NN1hg2E3lcw8rfeSxpI:b-7mmp82) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/repository/proposal_repository.py#L2085)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This query maybe should rather be included in the query for the proposal investigators.
</blockquote></details>

moved
___
*[`saltapi/repository/proposal_repository.py` line 2111 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmuZhrETpJfBKuusWB:-NN1T9xj2wbzJVMT2KWT:b-1dsl2w) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/repository/proposal_repository.py#L2111)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need a separate query for this?
</blockquote></details>

it was big before removed.
___
*[`saltapi/repository/proposal_repository.py` line 493 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1Ydip6bB6Rr0_N8_S:-NN1hI6g9WA66ZgYiC6R:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/repository/proposal_repository.py#L493)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary print statement.
</blockquote></details>

removed
___
*[`saltapi/repository/proposal_repository.py` line 1923 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1cD3zEBDVqh7I2zsv:-NN1heny5tL27RVkpqDA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/repository/proposal_repository.py#L1923)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be instrument-simulations (i.e. plural).
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 2 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1cUAa7IZ7ki2oAwE9:-NN1hhud9z-pRID3J6mB:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/web/api/proposals.py#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

pprint should not be necessary.
</blockquote></details>

removed
___
*[`saltapi/web/schema/proposal.py` line 436 at r1](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMUnQ3g0aibh-ARI_d1:-NN1i-6gCqFoOseELVJU:b5y9c4y) ([raw file](https://github.com/saltastroops/salt-api/blob/f652fbff3da740af982608061d55c01eed4e8afc/saltapi/web/schema/proposal.py#L436)):*
> Yes, 
if you mean I use a phase 2 instrument on phase 1.
I can't.
for the information I need to display for phase 1, this is enough and if I were to use a phase 2 instrument there would be a lot of data cleaning and some stuff are not available like the telescope config.
Keeping phase one and phase 2 separate is the motive here.  
___
*[`saltapi/web/schema/P1Proposal.py` line 19 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMmsjDNBJ7BDaH_QkPV:-NN1Y449DeTO_k0fPK_W:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The type should not contain the path (which would be a file path), but a URL for accessing the simulation file.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 45 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-HOq9wrMzghQQv9e:-NN1g_vSB7JYqH890f7K:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

too > to (Sorry!)
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P1Proposal.py` line 69 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-kZ02JCZJOW6ygNM:-NN1Y7IQ31dryw3FfA4e:b-9gh6rm) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

is_self_activable is a Phase 2 property.
</blockquote></details>

it is for both
___
*[`saltapi/web/schema/P1Proposal.py` line 77 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NMn-tMp6A8rhGlNFn1e:-NN1gcbxAo4qV4p5Nceq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P1Proposal.py#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As mentioned elsewhere, the thesis should be included with the investigator details.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P2Proposal.py` line 61 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1f1216vd7_uIbRZDT:-NN1hlGY1wOXJqPT1Q5M:b-yzybyd) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P2Proposal.py#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be a field for Phase 1 and 2, i.e. defined on Proposal?
</blockquote></details>

fixed it should have been
___
*[`saltapi/web/schema/P2Proposal.py` line 64 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1f1kI9D8eru50jxRm:-NN1h4eU0DUW8hpCvbbH:b5sa82y) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P2Proposal.py#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be a field for Phase 1 and 2, i.e. defined on Proposal?
</blockquote></details>

yes it should
___
*[`saltapi/web/schema/P2Proposal.py` line 84 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1f6_L0ioSkSDArE77:-NN1h6_t5bBx9DcbN-PN:b5sa82y) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P2Proposal.py#L84)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be a field for Phase 1 and 2, i.e. defined on Proposal?
</blockquote></details>

yes it should
___
*[`saltapi/web/schema/p1_proposal.py` line 123 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1eiRI3lxjrnDARQ8I:-NN1gnwK5NLVh3QuKq1u:bkq0nqc) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/web/schema/p1_proposal.py#L123)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be a field for Phase 1 and 2, i.e. defined on Proposal?
</blockquote></details>

Yes it should.
___
*[`saltapi/web/schema/p1_proposal.py` line 133 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1eUoC0hTw4fsa9hlW:-NN1gyO_AKEFpn333p_Y:b-emd7j1) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/web/schema/p1_proposal.py# [...]

2023-01-30 14:57 UTC, hettlage requested changes
> Reviewed 5 of 8 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 528 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN26qyiEAr-1wH9b6_U:-NN26qyiEAr-1wH9b6_V:bv9ub5b) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/repository/proposal_repository.py#L528)):*
> ```Python
>     JOIN InstituteName `IN` ON I2.InstituteName_Id = `IN`.InstituteName_Id
>     JOIN ProposalCode PC ON PI.ProposalCode_Id = PC.ProposalCode_Id
>     LEFT JOIN P1Thesis PT  ON PC.ProposalCode_Id = PT.ProposalCode_Id 
> ```

There is a space too many between "PT" and "ON"
___
*[`saltapi/repository/proposal_repository.py` line 570 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN27x_Q9D2DNJBxHYgc:-NN27x_Q9D2DNJBxHYgd:b-7wgj8a) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/repository/proposal_repository.py#L570)):*
> ```Python
> 
>             del investigator["approved"]
>             del investigator["approval_code"]
> ```

I would suggest that the investigator has a thesis field, rather than separate fields for each of the thesis details.
___
*[`saltapi/repository/proposal_repository.py` line 2112 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN27Z3a0ff5zUc_B0rx:-NN27Z3a0ff5zUc_B0ry:b-oodh84) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/repository/proposal_repository.py#L2112)):*
> ```Python
>         # There are no BVIT simulations
> 
> #         stmt = text(
> ```

You should remove the commented out code, I think.
___
*[`saltapi/web/schema/proposal.py` line 347 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN29gYSDesszt6CfEZ1:-NN29gYSDesszt6CfEZ2:bbv5qb2) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/web/schema/proposal.py#L347)):*
> ```Python
>         ),
>     )
>     blocks: List[BlockSummary] = Field(
> ```

I think various fields in this class are unnecessary, as they are defined in the child class(es)?
___
*[`saltapi/web/schema/proposal.py` line 182 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN291zTCBbF9w36FSI2:-NN291zTCBbF9w36FSI3:bs2ohmv) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/web/schema/proposal.py#L182)):*
> ```Python
>         ),
>     )
>     thesis_type: Optional[ThesisType] = Field(
> ```

There should be a thesis field, I'd say.
___
*[`saltapi/web/schema/P2Proposal.py` line 84 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1f6_L0ioSkSDArE77:-NN28fCK0xQBqNOmTBN9:b4phqgi) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P2Proposal.py#L84)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

yes it should
</blockquote></details>

But it hasn't been moved?
___
*[`saltapi/web/schema/p1_proposal.py` line 25 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN28Gxa4VNeCUsdjlgI:-NN28Gxa4VNeCUsdjlgJ:b48fkvn) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/web/schema/p1_proposal.py#L25)):*
> ```Python
>     url: str = Field(
>         ...,
>         title="Simulation path",
> ```

Simulation URL.
___
*[`saltapi/web/schema/p1_proposal.py` line 26 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN28LPiErt5h6d6XWw8:-NN28LPiErt5h6d6XWw9:b-781dfg) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/web/schema/p1_proposal.py#L26)):*
> ```Python
>         ...,
>         title="Simulation path",
>         description="The path to the simulation file."
> ```

The URL for the simulation file.


<!-- Sent from Reviewable.io -->

2023-01-30 15:25 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 528 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN26qyiEAr-1wH9b6_U:-NN2F4CO5fJFX_Fxu0BJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/repository/proposal_repository.py#L528)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a space too many between "PT" and "ON"
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 570 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN27x_Q9D2DNJBxHYgc:-NN2GfFyALXdb1YdlnV8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/repository/proposal_repository.py#L570)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest that the investigator has a thesis field, rather than separate fields for each of the thesis details.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2112 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN27Z3a0ff5zUc_B0rx:-NN2Gu-h4j5eug6ic7ff:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/repository/proposal_repository.py#L2112)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should remove the commented out code, I think.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 347 at r5](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN29gYSDesszt6CfEZ1:-NN2Efys70v2egD7M7kH:b5q935b) ([raw file](https://github.com/saltastroops/salt-api/blob/ccef274a26571db917b0df68ee7ab5b3fa73b66d/saltapi/web/schema/proposal.py#L347)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think various fields in this class are unnecessary, as they are defined in the child class(es)?
</blockquote></details>

I think the pull massed the classes up
___
*[`saltapi/web/schema/proposal.py` line 182 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN291zTCBbF9w36FSI2:-NN2ESQC5g3QlwsmTnML:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/web/schema/proposal.py#L182)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be a thesis field, I'd say.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/P2Proposal.py` line 84 at r4](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN1f6_L0ioSkSDArE77:-NN2DkKM-qgr87vBk1_y:bfzqrt8) ([raw file](https://github.com/saltastroops/salt-api/blob/985c7c8bacd1ba273661835a9b764e94cc30d1db/saltapi/web/schema/P2Proposal.py#L84)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But it hasn't been moved?
</blockquote></details>

copy not cut sorry
___
*[`saltapi/web/schema/p1_proposal.py` line 25 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN28Gxa4VNeCUsdjlgI:-NN2H3PI34g_YANZqrWj:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/web/schema/p1_proposal.py#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Simulation URL.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/p1_proposal.py` line 26 at r7](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN28LPiErt5h6d6XWw8:-NN2H3jA8BpEVshC_409:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/7f89967812ea11fb668acebfd7d108741fb97749/saltapi/web/schema/p1_proposal.py#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The URL for the simulation file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-30 17:45 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2156 at r8](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN2lPXh2qmY2yh6SJ_A:-NN2lPXh2qmY2yh6SJ_B:b-73s55e) ([raw file](https://github.com/saltastroops/salt-api/blob/66c3489b89ab3088f6f0317c997e0665eca71b40/saltapi/repository/proposal_repository.py#L2156)):*
> ```Python
>                 instrument = "BVIT"
>                 mode = row.bvit_filter
>                 simulations = []
> ```

Maybe add the comment from the function you've removed:

"There are no BVIT simulations"
___
*[`saltapi/web/schema/proposal.py` line 383 at r6](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN2lvUC4-v9pbyg7q4F:-NN2lvUC4-v9pbyg7q4G:b-n084lh) ([raw file](https://github.com/saltastroops/salt-api/blob/4651668abc5408f08437ab0899e98dc121ca276d/saltapi/web/schema/proposal.py#L383)):*
> ```Python
>         description="Semester for which the proposal details are given",
>     )
>     general_info: GeneralProposalInfo = Field(
> ```

Do you actually need the `general_info` field here -- you are overriding it for both phases anyway?


<!-- Sent from Reviewable.io -->

2023-01-30 17:49 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2156 at r8](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN2lPXh2qmY2yh6SJ_A:-NN2n4qU-u5YVsFLNsbv:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/66c3489b89ab3088f6f0317c997e0665eca71b40/saltapi/repository/proposal_repository.py#L2156)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add the comment from the function you've removed:

"There are no BVIT simulations"
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 383 at r6](https://reviewable.io/reviews/saltastroops/salt-api/127#-NN2lvUC4-v9pbyg7q4F:-NN2n4Mv4qk_uCtq7YaR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4651668abc5408f08437ab0899e98dc121ca276d/saltapi/web/schema/proposal.py#L383)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you actually need the `general_info` field here -- you are overriding it for both phases anyway?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-30 17:51 UTC, hettlage approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2023-01-30 17:51 UTC, merged