Auth service tests
saltastroops/salt-api pull request #15
Opened 2021-08-19 07:27 UTC by Eb-Zeero

2021-08-20 09:39 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/15)* status: all files reviewed, 24 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/settings.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXZEGa8d5kTsLHzTUb:-MhXZEGa8d5kTsLHzTUc:bebz1hk) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/settings.py#L36)):*
> ```Python
> 
>     # Hashing algorithm.
>     algorithm: str
> ```

As discussed, should be removed.
___
*[saltapi/service/authentication_service.py, line 16 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXZOlQ9R1REtAzTnJs:-MhXZOlQ9R1REtAzTnJt:b2j3yy2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/service/authentication_service.py#L16)):*
> ```Python
> from saltapi.settings import Settings
> 
> ALGORITHM = Settings().algorithm
> ```

As discussed, should not be a setting.
___
*[saltapi/service/authentication_service.py, line 26 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXkJQRBswA7-dA6FQ-:-MhXkJQS1XeflTeFQzPA:bk9vj5o) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/service/authentication_service.py#L26)):*
> ```Python
>         self.user_repository = user_repository
> 
>     def access_token(self, user: User, token_lifetime_days: Optional[int] = None) -> AccessToken:
> ```

I'd rather choose hours (or even minutes).
___
*[saltapi/service/authentication_service.py, line 26 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXoS8MAubIw09jDtb-:-MhXoS8MAubIw09jDtb0:b-wtp6ri) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/service/authentication_service.py#L26)):*
> ```Python
>         self.user_repository = user_repository
> 
>     def access_token(self, user: User, token_lifetime_days: Optional[int] = None) -> AccessToken:
> ```

Can be a static method.
___
*[tests/repository/fake_user_repository.py, line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXkn62CgzAY7uzKiBI:-MhXkn636hEZvVPVKKr0:bxu1t5c) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/repository/fake_user_repository.py#L8)):*
> ```Python
> 
> 
> class FakeUserRepository(UserRepository):
> ```

I'd rather include this in the test file itself.
___
*[tests/repository/fake_user_repository.py, line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXr88r4O40VEBom1qr:-MhXr88r4O40VEBom1qs:b-u141hv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/repository/fake_user_repository.py#L8)):*
> ```Python
> 
> 
> class FakeUserRepository(UserRepository):
> ```

FakeUserRepository should not inherit from UserRepository.

If you want to enforce consistency between the two, they should both inherit from a common interface instead. (I'm not sure that is necessary, but I'm open to discussing it.)
___
*[tests/service/authentication_service.yaml, line 0 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXkvP_A78GINT9N5oD:-MhXkvPaBYvwAligXmtZ:bppfyoe) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a1ef4ead745d0b72311bfad576b2de508fec4cb/tests/service/authentication_service.yaml#L0)):*
The file should be removed.
___
*[tests/service/test_authentication_service.py, line 2 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXs49K6y-q3wzk91hr:-MhXs49K6y-q3wzk91hs:b-3skkzu) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L2)):*
> ```Python
> from datetime import datetime, timedelta
> from typing import Any, Callable
> ```

General note: If a test its using the dbconnection fixture, it should be decorated with the no database decorator.

 ut I think no test in this file needs the dbconnection fixture. :-)
___
*[tests/service/test_authentication_service.py, line 28 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXlbR855nFFlb7U1s0:-MhXlbR93HoK7oPZFy97:bjnh217) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L28)):*
> ```Python
> )
> 
> # tested by mypy
> ```

Should be removed
___
*[tests/service/test_authentication_service.py, line 39 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXlkbM2K7Fd-_SkA-w:-MhXlkbM2K7Fd-_SkA-x:bv7z0lt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L39)):*
> ```Python
> 
> 
> def test_access_token_expire_in_seven_days_default(
> ```

test_access_token_expire_in_seven_days_default --->  test_access_token_by_default_expires_in_seven_days
___
*[tests/service/test_authentication_service.py, line 42 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXmDXH5onBZmVChFBF:-MhXmDXH5onBZmVChFBG:bn57xui) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L42)):*
> ```Python
>         dbconnection: Connection
> ) -> None:
>     freezer = freeze_time("2021-10-17 12:00:01")
> ```

freezegun comes with a context manager, which would be the better way, in case there are unexpected exceptions:

```
with freezegun.freeze_time("2021-10-17 12:00:01"):
    ...
```
___
*[tests/service/test_authentication_service.py, line 49 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXn7xF732A_fqSs1Zm:-MhXn7xG5FSge-MTvNsx:b-fu5wtl) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L49)):*
> ```Python
>     today = datetime.today()
>     # you can use something like freeze gut to set a time static
>     assert access_token.expires_at.date() == (today + timedelta(days=7)).date()
> ```

exppires_at should be a datetime, not a date,
___
*[tests/service/test_authentication_service.py, line 53 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXodQq4_J4Es0qJ0xD:-MhXodQq4_J4Es0qJ0xE:bcs03i0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L53)):*
> ```Python
> 
> 
> def test_access_token_expire_in_given_days(
> ```

expire ---> expires

And if you make the suggested change regarding the access_token method: days ---> hours
___
*[tests/service/test_authentication_service.py, line 60 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXozCH7f5j_2lNMJEr:-MhXozCH7f5j_2lNMJEs:b-b1bj52) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L60)):*
> ```Python
>     today = datetime.today()
>     user_repository = FakeUserRepository(dbconnection)
>     authentication_service = AuthenticationService(user_repository)
> ```

No need for instantiating an AuthenticationService object if access_token is static
___
*[tests/service/test_authentication_service.py, line 61 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXnfKUBTLQKJnRuhlm:-MhXnfKUBTLQKJnRuhln:b-zf4vzk) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L61)):*
> ```Python
>     user_repository = FakeUserRepository(dbconnection)
>     authentication_service = AuthenticationService(user_repository)
>     access_token = authentication_service.access_token(USER, 10)
> ```

As the code is the same for every ti [...]

2021-08-24 12:29 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/15)* status: all files reviewed, 24 unresolved discussions (waiting on @hettlage)

___
*[saltapi/settings.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXZEGa8d5kTsLHzTUb:-MhrvA29CshqT1-I77gO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/settings.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As discussed, should be removed.
</blockquote></details>

Done.
___
*[saltapi/service/authentication_service.py, line 16 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXZOlQ9R1REtAzTnJs:-MhrvDNV6MB7wv-1pPX5:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/service/authentication_service.py#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As discussed, should not be a setting.
</blockquote></details>

Done.
___
*[saltapi/service/authentication_service.py, line 26 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXkJQRBswA7-dA6FQ-:-MhrvTDf7NUhBrbcbRfH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/service/authentication_service.py#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd rather choose hours (or even minutes).
</blockquote></details>

Done.
___
*[saltapi/service/authentication_service.py, line 26 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXoS8MAubIw09jDtb-:-Mhrv_Qp6RF3Zl-UDu2E:b-e1nyq2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/service/authentication_service.py#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can be a static method.
</blockquote></details>

No it is using self.jwt_token
___
*[tests/repository/fake_user_repository.py, line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXkn62CgzAY7uzKiBI:-MhrwPbpCJckJbVA_1u8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/repository/fake_user_repository.py#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd rather include this in the test file itself.
</blockquote></details>

Done.
___
*[tests/repository/fake_user_repository.py, line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXr88r4O40VEBom1qr:-Mhrwv6HEP1YU7tF-g8O:bi667hm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/repository/fake_user_repository.py#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

FakeUserRepository should not inherit from UserRepository.

If you want to enforce consistency between the two, they should both inherit from a common interface instead. (I'm not sure that is necessary, but I'm open to discussing it.)
</blockquote></details>

AuthenticationService require UserRepository if I do not inherit I get type issues
___
*[tests/service/authentication_service.yaml, line  at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXkvP_A78GINT9N5oD:-MhrxJQW4z7nP7ZBUfTs:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a1ef4ead745d0b72311bfad576b2de508fec4cb/tests/service/authentication_service.yaml#L)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The file should be removed.
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 2 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXs49K6y-q3wzk91hr:-Mhrz2KIBHi47uCsxWuX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

General note: If a test its using the dbconnection fixture, it should be decorated with the no database decorator.

 ut I think no test in this file needs the dbconnection fixture. :-)
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 28 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXlbR855nFFlb7U1s0:-Mhrz3bq9CY_C0LZw4zN:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be removed
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 39 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXlkbM2K7Fd-_SkA-w:-Mhs-mceDaZKBheCkadg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

test_access_token_expire_in_seven_days_default --->  test_access_token_by_default_expires_in_seven_days
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 42 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXmDXH5onBZmVChFBF:-Mhs0EY8CXhgVbNcONNx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

freezegun comes with a context manager, which would be the better way, in case there are unexpected exceptions:

```
with freezegun.freeze_time("2021-10-17 12:00:01"):
    ...
```
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 49 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXn7xF732A_fqSs1Zm:-Mhs1Nrp0OWLSk-Lw4DX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

exppires_at should be a datetime, not a date,
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 53 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXodQq4_J4Es0qJ0xD:-Mhs1bbJ-ET2y9ebF9xu:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

expire ---> expires

And if you make the suggested change regarding the access_token method: days ---> hours
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 60 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXozCH7f5j_2lNMJEr:-Mhs1xIe4ba5fDSioLg3:bp0evfe) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No need for instantiating an AuthenticationService object if access_token is static
</blockquote></details>

method can not be static.
___
*[tests/service/test_authentication_service.py, line 61 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXnfKUBTLQKJnRuhlm:-Mhs3xGlDRyJX60LcQXt:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As the code is the same for every  [...]

2021-08-24 14:57 UTC, hettlage requested changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/15)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/service/authentication_service.py, line 26 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXoS8MAubIw09jDtb-:-MhsZDJa3NMHg1OBgWUb:bodd6b5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/service/authentication_service.py#L26)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

No it is using self.jwt_token
</blockquote></details>

But jwt_token is a static method as well.
___
*[saltapi/service/authentication_service.py, line 28 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhsDRsY39riFd-L-24j:-MhsDRsY39riFd-L-24k:b-mtbphs) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/service/authentication_service.py#L28)):*
> ```Python
>     def access_token(self, user: User, token_lifetime_days: Optional[int] = None) -> AccessToken:
>         """Generate an authentication token."""
>         if token_lifetime_days or token_lifetime_days == 0:
> ```

Maybe better:

```if token_lifetime_hours is not None:```
___
*[tests/service/test_authentication_service.py, line 47 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-Mhs_2T7-iISVFGU5_ys:-Mhs_2T85voPaZmDuWD5:b-b66zlv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L47)):*
> ```Python
>     authentication_service = AuthenticationService(user_repository)
>     access_token = authentication_service.access_token(USER)
>     today = datetime.today()
> ```

Why are you using today rather than now?
___
*[tests/service/test_authentication_service.py, line 48 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhsZfam6vDtURzjmAhH:-MhsZfam6vDtURzjmAhI:b-ymsngo) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L48)):*
> ```Python
>     access_token = authentication_service.access_token(USER)
>     today = datetime.today()
>     # you can use something like freeze gut to set a time static
> ```

gut --> gun

I'm not sure the comment necessary, but if you include it, I'd rather say something like: # freezegun is used to ensure the current time is always the same
___
*[tests/service/test_authentication_service.py, line 60 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXozCH7f5j_2lNMJEr:-Mhsa8Qy1meVAvQ2pF_k:b-5vbf5b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L60)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

method can not be static.
</blockquote></details>

It actually can.. :-)
___
*[tests/service/test_authentication_service.py, line 67 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXnYvj0mt6Myg2mPQ7:-Mhsar-RDkU7N0hiIzZI:b-sz4ff1) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L67)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
does the methot return a expired token?
</blockquote></details>

Seems so, given the test is passing,... :-)
___
*[tests/service/test_authentication_service.py, line 76 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXp9VPEmsT0J_esp4o:-Mhsb1jA4Pf3SDbjmvQ5:b-iiy7pz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L76)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

can't be static
</blockquote></details>

It actually can. :-)
___
*[tests/service/test_authentication_service.py, line 121 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXuHGQBzs72nSqIMrg:-MhsbeZe-zdl53GtcXVm:b4if4xv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L121)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It might still be a good idea to check the case of the username / password being None in the respective tests
___
*[tests/service/test_authentication_service.py, line 70 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-Mhs_h5uCfuh5h7g6bnQ:-Mhs_h5uCfuh5h7g6bnR:bs266q7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L70)):*
> ```Python
> "user, token_lifetime_hours",
>     [
>         (USER, 10),
> ```

Why do you include USER in the parameters?
___
*[tests/service/test_authentication_service.py, line 76 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-Mhs_qBA5p00oTsIR8TQ:-Mhs_qBA5p00oTsIR8TR:b-80mhjz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L76)):*
> ```Python
>     ]
> )
> def test_access_token_expire_in_given_hours(user: User, token_lifetime_hours: int) -> None:
> ```

expire ---> expires
___
*[tests/service/test_authentication_service.py, line 78 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-Mhs_xHu6nZGVYPzb4cx:-Mhs_xHu6nZGVYPzb4cy:b-bamtwp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L78)):*
> ```Python
> def test_access_token_expire_in_given_hours(user: User, token_lifetime_hours: int) -> None:
>     with freeze_time("2021-10-17 12:00:01"):
>         today = datetime.today()
> ```

Why do you use today rather than now>?
___
*[tests/service/test_authentication_service.py, line 126 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhsbT5AEchmgoIEVePd:-MhsbT5AEchmgoIEVePe:blqog0t) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L126)):*
> ```Python
>     ]
> )
> def test_authenticate_user_raise_error_for_wrong_password(
> ```

raise ---> raises


<!-- Sent from Reviewable.io -->

2021-09-01 13:48 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/15)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/service/authentication_service.py, line 26 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXoS8MAubIw09jDtb-:-MiWZdm20fh883JwrqTi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/service/authentication_service.py#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But jwt_token is a static method as well.
</blockquote></details>

Done.
___
*[saltapi/service/authentication_service.py, line 28 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhsDRsY39riFd-L-24j:-MiWZe7l6AxhegIULxlN:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/saltapi/service/authentication_service.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better:

```if token_lifetime_hours is not None:```
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 47 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-Mhs_2T7-iISVFGU5_ys:-MiWZvVt-bVyUATBqA3Z:by4g5r2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why are you using today rather than now?
</blockquote></details>

no any reason done.
___
*[tests/service/test_authentication_service.py, line 48 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhsZfam6vDtURzjmAhH:-MiW_CetEZgEGJ6UB2pM:b-q9pzt8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

gut --> gun

I'm not sure the comment necessary, but if you include it, I'd rather say something like: # freezegun is used to ensure the current time is always the same
</blockquote></details>

this was my notes not a comment removed
___
*[tests/service/test_authentication_service.py, line 60 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXozCH7f5j_2lNMJEr:-MiW_s9UAvTCMst9WiIq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It actually can.. :-)
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 76 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXp9VPEmsT0J_esp4o:-MiWa60S6BECtJah9uuf:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It actually can. :-)
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 121 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXuHGQBzs72nSqIMrg:-MiWb4tOAnoWBzsHL4Z8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L121)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might still be a good idea to check the case of the username / password being None in the respective tests
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 70 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-Mhs_h5uCfuh5h7g6bnQ:-MiWbU753vcca9UCJk2Z:b24i4uf) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you include USER in the parameters?
</blockquote></details>

Didn't thought of this .
thanks and Done
___
*[tests/service/test_authentication_service.py, line 76 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-Mhs_qBA5p00oTsIR8TQ:-MiW_U6c2ntO1-yZ8laA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

expire ---> expires
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 78 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-Mhs_xHu6nZGVYPzb4cx:-MiW_bCr32TgzT3KlTp3:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you use today rather than now>?
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 126 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhsbT5AEchmgoIEVePd:-MiWa8kM5k8JQ8uX5u-H:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L126)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

raise ---> raises
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-01 13:51 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/15)* status: 6 of 8 files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[tests/service/test_authentication_service.py, line 67 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MhXnYvj0mt6Myg2mPQ7:-MiWcIeO3G8wKoW1XL-h:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1ead9ebd05bc76fe7d62f31a1dbf8438912e37fd/tests/service/test_authentication_service.py#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Seems so, given the test is passing,... :-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-01 20:38 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/15)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

*[a discussion](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MiY4Hlk-6Bnv1y9_Boj:-MiY4Hlk-6Bnv1y9_Bok:b-o51vys) (no related file):*
There are some mypy and flake8 issues.

---
___
*[tests/service/test_authentication_service.py, line 78 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MiY08YDAsNYyiD-3VIG:-MiY08YDAsNYyiD-3VIH:b-3na6vv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L78)):*
> ```Python
> def test_access_token_expire_in_given_hours(user: User, token_lifetime_hours: int) -> None:
>     with freeze_time("2021-10-17 12:00:01"):
>         today = datetime.today()
> ```

I'd rename `today` to `now`.
___
*[tests/service/test_authentication_service.py, line 81 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MiY3JqDB-xgrZH9_WmG:-MiY3JqDB-xgrZH9_WmH:brbjkes) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L81)):*
> ```Python
>         authentication_service = AuthenticationService(user_repository)
>         access_token = authentication_service.access_token(USER,  token_lifetime_hours)
>         assert access_token.expires_at == (today + timedelta(hours=token_lifetime_hours))
> ```

The (outer) parentheses aren't necessary.


<!-- Sent from Reviewable.io -->

2021-09-02 12:11 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/15)* status: 6 of 11 files reviewed, 3 unresolved discussions (waiting on @hettlage)

*[a discussion](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MiY4Hlk-6Bnv1y9_Boj:-Mia9FiR4cRA_ppcMlIW:bb7f2mf) (no related file):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There are some mypy and flake8 issues.
</blockquote></details>

done

---
___
*[tests/service/test_authentication_service.py, line 78 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MiY08YDAsNYyiD-3VIG:-Mia7Klk7sr8-bbij9Aw:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd rename `today` to `now`.
</blockquote></details>

Done.
___
*[tests/service/test_authentication_service.py, line 81 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/15#-MiY3JqDB-xgrZH9_WmG:-Mia7Y55Cgh99JlaYrFj:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/7e6bd5da63dc05185260a148c43cec20d6778ab3/tests/service/test_authentication_service.py#L81)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The (outer) parentheses aren't necessary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-02 15:14 UTC, hettlage reviewed
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/15)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)



<!-- Sent from Reviewable.io -->

2021-09-02 15:15 UTC, merged