Adding end-point to update self activatable proposals
saltastroops/salt-api pull request #177
Opened 2023-02-16 18:02 UTC by Eb-Zeero

2023-02-20 14:31 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: all files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero)

*[a discussion](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjAR6I0ofZ7RWt_7Zu:-NOjAR6I0ofZ7RWt_7Zv:byxzzvc) (no related file):*
Tests are missing.

___
___
*[`saltapi/repository/proposal_repository.py` line 2340 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOj9IumBQQ1zDHOzfhs:-NOj9IumBQQ1zDHOzfht:b-95itgr) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/repository/proposal_repository.py#L2340)):*
> ```Python
> 
>     def update_is_self_activatable(self, proposal_code, is_self_activatable) -> None:
>         stmt = text(
> ```

I would suggest you get the proposal id in a separate query. Yes, it is almost undoubtedly less efficient, but it allows you to throw a more meaningful error (namely a NotFoundError). Otherwise you get an error "Column 'ProposalCode_Id' cannot be null", which is more cryptic.

(And there should be a comment highlighting why this is done...)
___
*[`saltapi/repository/proposal_repository.py` line 2356 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOj9tBgDAeiTTxUIR-n:-NOj9tBgDAeiTTxUIR-o:b-p8qh1q) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/repository/proposal_repository.py#L2356)):*
> ```Python
>             stmt, {
>                 "proposal_code": proposal_code,
>                 "is_self_activatable": is_self_activatable,
> ```

is_self_activatable is a boolean, but the DB expects an int. While there might be an automatic conversion, I think an explicit conversion makes sense (i.e. `1 if is_self_activatable` else 0`).
___
*[`saltapi/service/permission_service.py` line 435 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjAGI50WcNHxVMlI3B:-NOjAGI6Dj9jADAoo46J:b-cq12ng) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/service/permission_service.py#L435)):*
> ```Python
>         return maximum_period <= proprietary_period_update.proprietary_period
> 
>     def check_permission_to_change_self_Activatable(self, user: User):
> ```

Activatable ~ activatable (lower case 'a')
___
*[`saltapi/web/api/proposals.py` line 470 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjCRv1-0MXIvQwcINu:-NOjCRv1-0MXIvQwcINv:b5abrga) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/web/api/proposals.py#L470)):*
> ```Python
> 
> @router.put(
>     "/{proposal_code}/self-activatable",
> ```

In the RESTful view of things, I'd argue, you are updating a resource. But that means that you should use a noun to refer to the resource: `/{proposal_code}/self-activation`. Then of course the question is what is the content of that resource. I guess it might just be a propery `allowed`. I would not include the proposal code, which from all I can see is not included for the proposal status either.
___
*[`saltapi/web/api/proposals.py` line 471 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjBNqp-lY7MSS7m7o2:-NOjBNqp-lY7MSS7m7o3:b-kn0ivh) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/web/api/proposals.py#L471)):*
> ```Python
> @router.put(
>     "/{proposal_code}/self-activatable",
>     summary="Create an observation comment",
> ```

"Change the status whether the proposal may be activated by the Principal Investigator and Principal Contact"
___
*[`saltapi/web/api/proposals.py` line 473 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjBfK4D9u5IfjzFUol:-NOjBfK4D9u5IfjzFUom:b-elwylb) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/web/api/proposals.py#L473)):*
> ```Python
>     summary="Create an observation comment",
>     response_model=ProposalSelfActivatable,
>     status_code=201,
> ```

The status code probably should be 200?
___
*[`saltapi/web/api/proposals.py` line 483 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjCMW-1VCLHdxFsqYG:-NOjCMW-1VCLHdxFsqYH:b6kxckt) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/web/api/proposals.py#L483)):*
> ```Python
>             ),
>         ),
>         is_self_activatable: bool = Body(..., title="Comment", description="Text of the comment."),
> ```

The title and description are wrong... ;-)
___
*[`saltapi/web/schema/proposal.py` line 631 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjDLeGCPjr1SbmDIaX:-NOjDLeGCPjr1SbmDIaY:b68cfel) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/web/schema/proposal.py#L631)):*
> ```Python
> 
> 
> class ProposalSelfActivatable(BaseModel):
> ```

See the comment for the API endpoint.

I don't think the proposal code should be part of the type, the type name should be a noun (`SelfActivation`) and the single property should be something like `allowed`.


<!-- Sent from Reviewable.io -->

2023-02-21 12:14 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: all files reviewed, 9 unresolved discussions (waiting on @hettlage)

*[a discussion](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjAR6I0ofZ7RWt_7Zu:-NOnsyN55mKvOX0PqiBg:b-896fix) (no related file):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Tests are missing.
</blockquote></details>

Done.

___
___
*[`saltapi/repository/proposal_repository.py` line 2340 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOj9IumBQQ1zDHOzfhs:-NOjfQUsDEQWtpbI_iUJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/repository/proposal_repository.py#L2340)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest you get the proposal id in a separate query. Yes, it is almost undoubtedly less efficient, but it allows you to throw a more meaningful error (namely a NotFoundError). Otherwise you get an error "Column 'ProposalCode_Id' cannot be null", which is more cryptic.

(And there should be a comment highlighting why this is done...)
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2356 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOj9tBgDAeiTTxUIR-n:-NOjfnX220fhm18aw8NX:b8s1uex) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/repository/proposal_repository.py#L2356)):*
> 1 if is_self_activatable else 0  -> true/false
Done.
the reason there is an automatic conversion is to make coding much easy. and it is much easy to read that boolean is passed in, not a small-int
___
*[`saltapi/service/permission_service.py` line 435 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjAGI50WcNHxVMlI3B:-NOjgTEM9X_8PsJCudds:b-ho00rd) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/service/permission_service.py#L435)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Activatable ~ activatable (lower case 'a')
</blockquote></details>

yes thanks.



_Code quote:_
```Python
e
```
___
*[`saltapi/web/api/proposals.py` line 470 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjCRv1-0MXIvQwcINu:-NOjhzD7B6P2xP-qJKKw:bb6un1j) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/web/api/proposals.py#L470)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

In the RESTful view of things, I'd argue, you are updating a resource. But that means that you should use a noun to refer to the resource: `/{proposal_code}/self-activation`. Then of course the question is what is the content of that resource. I guess it might just be a propery `allowed`. I would not include the proposal code, which from all I can see is not included for the proposal status either.
</blockquote></details>

Done
___
*[`saltapi/web/api/proposals.py` line 471 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjBNqp-lY7MSS7m7o2:-NOji6TP4aZZ_ywtpj5b:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/web/api/proposals.py#L471)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Change the status whether the proposal may be activated by the Principal Investigator and Principal Contact"
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 473 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjBfK4D9u5IfjzFUol:-NOji5s9EXGlA3IKeDEM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/web/api/proposals.py#L473)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The status code probably should be 200?
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 483 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjCMW-1VCLHdxFsqYG:-NOjiGGC3hRl6UiHYrYX:b-tkwbxb) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/web/api/proposals.py#L483)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The title and description are wrong... ;-)
</blockquote></details>

copy and paste sorry
___
*[`saltapi/web/schema/proposal.py` line 631 at r1](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOjDLeGCPjr1SbmDIaX:-NOjju5J26SS1dwi3qi4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/858ec0b41e17d49920288ae1bb717550d9fe0c21/saltapi/web/schema/proposal.py#L631)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See the comment for the API endpoint.

I don't think the proposal code should be part of the type, the type name should be a noun (`SelfActivation`) and the single property should be something like `allowed`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-21 13:57 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: all files reviewed, 34 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2355 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOoFGCt3GzpPVS-Dx8J:-NOoFGCu8LpeV3_BFZvk:b-ts4950) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2355)):*
> ```Python
>         return cast(int, proposal_code_id[0])
>     def update_is_self_activatable(self, proposal_code, is_self_activatable) -> None:
>         proposal_code_id = self._get_proposal_code_id(proposal_code)  # To throw a more meaningful error.
> ```

You could be a bit more explicit, like:

# The id could be evaluated in the INSERT query, but this would lead to more cryptic errors for a non-existing proposal code.
___
*[`saltapi/repository/proposal_repository.py` line 2382 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo82d66d7_vyJE2ykd:-NOo82d66d7_vyJE2yke:bnyk27f) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2382)):*
> ```Python
> FROM ProposalContact PCon
>     JOIN Investigator I ON I.Investigator_Id = PCon.Astronomer_Id
>     JOIN ProposalCode PC ON PC.ProposalCode_Id = PCon.ProposalCode_Id
> ```

In principle you should link back to the Investigator table via PC.Investigator_Id to get the preferred details...
___
*[`saltapi/repository/proposal_repository.py` line 2396 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo78om9PzqbqBy2q5_:-NOo78on7AFG2XspC53c:bu7j3if) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2396)):*
> ```Python
>         sa = result.one_or_none()
>         if not sa:
>             raise NotFoundError(f"No liaison astronomer for proposal code `{proposal_code}`")
> ```

There is a bit of a problem here: Is this because of a wrong proposal code or because of liaison astronomer having been set?

But you might not need this function (which might be worth discussing).
___
*[`saltapi/repository/proposal_repository.py` line 2405 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo8N2t3hdGxeaXZOrW:-NOo8N2t3hdGxeaXZOrX:b-lgdi3n) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2405)):*
> ```Python
>     def update_liaison_astronomer(self, proposal_code, liaison_astronomer_id) -> None:
> 
>         investigator_id = self.get_investigator_id(user_id=liaison_astronomer_id)
> ```

Maybe add a comment like:

```
# The ids could be retrieved within the SQL statement, but then a wrong proposal code or liaison id would lead to more cryptic errors.
```

More importantly, a wrong liaison astronomer id should probably lead to a `ValidationError`.
___
*[`saltapi/repository/proposal_repository.py` line 2436 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo9T2A6FMaXS2IPSi6:-NOo9T2A6FMaXS2IPSi7:b96lehk) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2436)):*
> ```Python
>         investigator_id = result.one_or_none()
>         if not investigator_id:
>             raise NotFoundError(f"Couldn't found the investigator with id `{user_id}`")
> ```

found > find
the investigator with id > an investigator for the user id

But maybe just simpler:

User id not found: {user_id}
___
*[`saltapi/web/api/proposals.py` line 469 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo2gbhDv_6lYwKzCKa:-NOo2gbhDv_6lYwKzCKb:b-pao1u) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L469)):*
> ```Python
> 
> @router.put(
>     "/{proposal_code}/self-activation/{allowed}",
> ```

I'm really skeptical about `allowed` being a path variable. You are updating a resource, and the properties of the resource would be expected to be passed in the body.
___
*[`saltapi/web/api/proposals.py` line 472 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo3Ito-7DU0YvGL41B:-NOo3Ito-7DU0YvGL41C:bldrz8i) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L472)):*
> ```Python
>     summary="Change the status whether the proposal may be activated by the Principal Investigator and Principal Contact",
>     response_model=SelfActivation,
>     status_code=200,
> ```

A status code of 200 doesn't have to be specified.
___
*[`saltapi/web/api/proposals.py` line 484 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo2Vbh6HIaBTo4dqID:-NOo2Vbh6HIaBTo4dqIE:b9p7g98) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L484)):*
> ```Python
>         allowed: bool = Path(
>             ...,
>             title="Allowed",
> ```

Allowed to self-activate
___
*[`saltapi/web/api/proposals.py` line 486 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo6YvzEA0GaYx1RkMO:-NOo6YvzEA0GaYx1RkMP:bipolly) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L486)):*
> ```Python
>             title="Allowed",
>             description=(
>                     "is the Principal Investigator or Principal Contact allowed to activate proposal."
> ```

activate proposal > activate the proposal
___
*[`saltapi/web/api/proposals.py` line 492 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo301EBlt-THRoxizn:-NOo301EBlt-THRoxizo:b-s77qt2) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L492)):*
> ```Python
> ) -> SelfActivation:
>     """
>     Adds a new comment related to an observation. The user submitting the request is
> ```

"""
Change the self-activation status of the proposal.

A proposal is self-activatable if the Principal Investigator or Principal Contact are allowed to activate it.
"""
___
*[`saltapi/web/api/proposals.py` line 509 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo0Yyn0oZEwVwDJfjm:-NOo0Yyn0oZEwVwDJfjn:b-dg713s) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L509)):*
> ```Python
> 
> @router.put(
>     "/{proposal_code}/liaison-astronomer/{liaison_astronomer_id}",
> ```

I don't think the id should be part of the URL.

And actually you must be able to "unset" the saison astronomer, so you probably need to allow `null` for the id. (Unless you handled this case via a `DELETE` endpoint. But that's probably not such a good idea.)
___
*[`saltapi/web/api/proposals.py` line 510 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOoAh2L2hf200C7Q6fA:-NOoAh2L2hf200C7Q6fB:b-91cbbb) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L510)):*
> ```Python
> @router.put(
>     "/{proposal_code}/liaison-astronomer/{liaison_astronomer_id}",
>     summary="Create an observation comment",
> ```

Set the liaison astronomer for the proposal
___
*[`saltapi/web/api/proposals.py` line 511 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo12TU6XO3SyJjm6QE:-NOo12TU6XO3SyJjm6QF:b-ubwo7t) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L511)):*
> ```Python
>     "/{proposal_code}/liaison-astronomer/{liaison_astronomer_id}",
>     summary="Create an observation comment",
>     response_model=UserListItem,
> ```

Wouldn' [...]

2023-02-22 20:05 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: 2 of 8 files reviewed, 34 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2355 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOoFGCt3GzpPVS-Dx8J:-NOuS2K79G3reqwCOHMV:b-vr4436) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2355)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could be a bit more explicit, like:

# The id could be evaluated in the INSERT query, but this would lead to more cryptic errors for a non-existing proposal code.
</blockquote></details>

#  Done.
___
*[`saltapi/repository/proposal_repository.py` line 2382 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo82d66d7_vyJE2ykd:-NOuSzZaDNIrppOjFR6x:b4fwqru) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2382)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

In principle you should link back to the Investigator table via PC.Investigator_Id to get the preferred details...
</blockquote></details>

what is wrong with this?
Just that I do not understand this comment
___
*[`saltapi/repository/proposal_repository.py` line 2396 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo78om9PzqbqBy2q5_:-NOuTmK88mezYaq0Y_WB:b6q3nhu) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2396)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a bit of a problem here: Is this because of a wrong proposal code or because of liaison astronomer having been set?

But you might not need this function (which might be worth discussing).
</blockquote></details>

let's discuss.

the method gets the liaison SA for a given proposal.
what if there is no SA
___
*[`saltapi/repository/proposal_repository.py` line 2405 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo8N2t3hdGxeaXZOrW:-NOuUFy1BelnPzm75lUi:b-doya6i) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2405)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add a comment like:

```
# The ids could be retrieved within the SQL statement, but then a wrong proposal code or liaison id would lead to more cryptic errors.
```

More importantly, a wrong liaison astronomer id should probably lead to a `ValidationError`.
</blockquote></details>

Validation error how
___
*[`saltapi/repository/proposal_repository.py` line 2436 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo9T2A6FMaXS2IPSi6:-NOuUqbJCQrqYgcFptA0:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2436)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

found > find
the investigator with id > an investigator for the user id

But maybe just simpler:

User id not found: {user_id}
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 469 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo2gbhDv_6lYwKzCKa:-NOuIeMw8OxaBsU-VP2J:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L469)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm really skeptical about `allowed` being a path variable. You are updating a resource, and the properties of the resource would be expected to be passed in the body.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 472 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo3Ito-7DU0YvGL41B:-NOuIf797GI5_bDrBWHJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L472)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A status code of 200 doesn't have to be specified.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 484 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo2Vbh6HIaBTo4dqID:-NOuUwwf9oonEFwknDbq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L484)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Allowed to self-activate
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 486 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo6YvzEA0GaYx1RkMO:-NOuJe3K6pnpYHAly8nJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L486)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

activate proposal > activate the proposal
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 492 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo301EBlt-THRoxizn:-NOuJeQnA8O7ltmd5ZMr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L492)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"""
Change the self-activation status of the proposal.

A proposal is self-activatable if the Principal Investigator or Principal Contact are allowed to activate it.
"""
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 509 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo0Yyn0oZEwVwDJfjm:-NOuPWqb84gse4UHytC6:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L509)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the id should be part of the URL.

And actually you must be able to "unset" the saison astronomer, so you probably need to allow `null` for the id. (Unless you handled this case via a `DELETE` endpoint. But that's probably not such a good idea.)
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 510 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOoAh2L2hf200C7Q6fA:-NOuPazIEmZnxGRCHyaY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L510)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Set the liaison astronomer for the proposal
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 511 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo12TU6XO3SyJjm6QE:-NOuQFj2EvC0uTQqrQil:b-r5nur) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L511)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't it be more natural to return a `User` -- this is not a list item, after all?
</blockquote></details>

No it is not the user Or I would need to redefine the same object with a different name from this query I just need to know if it is updated or not
___
*[`saltapi/web/api/proposals.py` line 519 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo1FI3ELkOaxG-7ua5:-NOuRSoG9Na-y_NyaG48:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/web/api/proposals.py#L519)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

for which the liaison astronomer is updated
 [...]

2023-02-24 14:44 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: all files reviewed, 21 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/api/proposals.py` line 542 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzpfSzBoZY9RLAPGKV:-NOzpfT--48MroPwsQ8z:b-ej8r22) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/api/proposals.py#L542)):*
> ```Python
>             )
>             unit_of_work.commit()
>             return Message(message="Successful")
> ```

I think this is inconsistent. In other cases we return the updated object, 
___
*[`saltapi/web/api/proposals.py` line 543 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzqFVKEgJ64KCehbM-:-NOzqFVKEgJ64KCehbM0:b2rmg41) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/api/proposals.py#L543)):*
> ```Python
>             unit_of_work.commit()
>             return Message(message="Successful")
>         except ValueError:
> ```

The error should be handled in `exceptions_handler.py`.
___
*[`saltapi/web/schema/user.py` line 133 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzqYCACIwz5e60HICb:-NOzqYCACIwz5e60HICc:b-ujwhra) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/schema/user.py#L133)):*
> ```Python
> 
> class LiaisonAstronomerId(BaseModel):
>     """Item in a list of users."""
> ```

As there is nothing specifically related to liaison astronomers in this type, it might as well be called `UserId`.

And the docstring probably should read something like """A user id.""".
___
*[`saltapi/web/schema/user.py` line 137 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzr2s_Aqc55HVQz9qU:-NOzr2s_Aqc55HVQz9qV:b-wjul2o) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/schema/user.py#L137)):*
> ```Python
>     id: Optional[int] = Field(
>         ...,
>         title="Liaison astronomer user id",
> ```

Liaison astronomer user id > User id
___
*[`saltapi/web/schema/user.py` line 138 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzr9CI8LfQEQ-qCvOj:-NOzr9CI8LfQEQ-qCvOk:bqxc9vu) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/schema/user.py#L138)):*
> ```Python
>         ...,
>         title="Liaison astronomer user id",
>         description="The iaison astronomer user id."
> ```

The iaison astronomer user id. > A user id,.
___
*[`tests/integration/proposals/test_self_activation_update.py` line 56 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo4X4P7Q4kISmCCOAr:-NOzsVRv1XEzeww2SMDo:b-wnyv98) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/tests/integration/proposals/test_self_activation_update.py#L56)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we discuss this?
___
*[`tests/integration/proposals/test_self_activation_update.py` line 108 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo58qW5y5k3Syqot_M:-NOzspvX49Z2juRJT5Zj:b-wnyv98) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/tests/integration/proposals/test_self_activation_update.py#L108)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

My test will then start to have conditions on the args
</blockquote></details>

Can we discuss this?
___
*[`tests/integration/proposals/test_self_activation_update.py` line 27 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzroN8A_IWI-QRWoIO:-NOzroN8A_IWI-QRWoIP:b-nljbo6) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/tests/integration/proposals/test_self_activation_update.py#L27)):*
> ```Python
>     proposal_code = "2020-1-SCI-005"
>     response = client.put(
>         _url(proposal_code), json=False
> ```

Doesn't the endpoint expect a JSON object `{"allowed": False}`?
___
*[`tests/integration/proposals/test_self_activation_update.py` line 38 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzs4Gb-phDEp6jl0b6:-NOzs4Gb-phDEp6jl0b7:b-nljbo6) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/tests/integration/proposals/test_self_activation_update.py#L38)):*
> ```Python
>     proposal_code = "2020-1-SCI-005"
>     response = client.put(
>         _url(proposal_code), json=False
> ```

Doesn't the endpoint expect a JSON object `{"allowed": False}`?
___
*[`tests/integration/proposals/test_self_activation_update.py` line 64 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzsiYD0XH6Owxw-bqW:-NOzsiYD0XH6Owxw-bqX:bb1sw11) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/tests/integration/proposals/test_self_activation_update.py#L64)):*
> ```Python
>     sa = find_username("SALT Astronomer")
>     authenticate(sa, client)
>     response = client.put(_url(proposal_code), json=allowed)
> ```

Doesn't the endpoint expect a JSON object `{"allowed": allowed}`?
___
*[`tests/integration/proposals/test_self_activation_update.py` line 76 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzseVg6HrnK1qjfNa_:-NOzseVg6HrnK1qjfNaa:b8z8plp) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/tests/integration/proposals/test_self_activation_update.py#L76)):*
> ```Python
>     authenticate(user, client)
> 
>     response = client.put(_url(proposal_code), json=True)
> ```

Doesn't the endpoint expect a JSON object `{"allowed": True}`?
___
*[`tests/integration/proposals/test_self_activation_update.py` line 88 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzt2u59i0Iix1IFNaf:-NOzt2u59i0Iix1IFNag:b-ahqlje) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/tests/integration/proposals/test_self_activation_update.py#L88)):*
> ```Python
>     ]
> )
> def test_update_is_self_activatable_return_403_for_pi_pc_and_investigator(
> ```

return > returns
___
*[`tests/integration/proposals/test_self_activation_update.py` line 94 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzstvp26Y1oJhryiP_:-NOzstvp26Y1oJhryiPa:bhsa5z) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/tests/integration/proposals/test_self_activation_update.py#L94)):*
> ```Python
>     authenticate(user, client)
>     response = client.put(
>         _url(proposal_code), json=True
> ```

Here and in the following:

Doesn't the endpoint expect a JSON object `{"allowed": True}`?
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 55 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo5cXI04W4rC06J28n:-NOztN0p8iThmeeMfNLn:b-wnyv98) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/tests/integration/proposals/test_update_liaison_astronomer.py#L55)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

added another test in its place
</blockquote></details>

Can we discuss this?
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 114 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOztuRFBmbV-sVikVZn:-NOztuRFBmbV-sVikVZo:bswdkc8) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/tests/integration/proposals/test_update_liaison_astronomer.py#L114)):*
> ```Python
>     ]
> )
> def test_update_liaison_astronomer_return_403_for_pi_pc_and_investi [...]

2023-02-27 19:47 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: 4 of 11 files reviewed, 21 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/web/api/proposals.py` line 542 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzpfSzBoZY9RLAPGKV:-NPJMDA35dri5LaZN6Nw:b-qssebl) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/api/proposals.py#L542)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this is inconsistent. In other cases we return the updated object, 
</blockquote></details>

fixed.
___
*[`saltapi/web/api/proposals.py` line 543 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzqFVKEgJ64KCehbM-:-NPJJSDTCDklMUNLiT-l:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/api/proposals.py#L543)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The error should be handled in `exceptions_handler.py`.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/user.py` line 133 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzqYCACIwz5e60HICb:-NPJJupT5S9VkdH9LVJw:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/schema/user.py#L133)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As there is nothing specifically related to liaison astronomers in this type, it might as well be called `UserId`.

And the docstring probably should read something like """A user id.""".
</blockquote></details>

Done.
___
*[`saltapi/web/schema/user.py` line 137 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzr2s_Aqc55HVQz9qU:-NPJJv6M6Bk5zqvpvdp5:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/schema/user.py#L137)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Liaison astronomer user id > User id
</blockquote></details>

Done.
___
*[`saltapi/web/schema/user.py` line 138 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzr9CI8LfQEQ-qCvOj:-NPJJyh7ElbW0JFx2dGi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/schema/user.py#L138)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The iaison astronomer user id. > A user id,.
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_self_activation_update.py` line 64 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzsiYD0XH6Owxw-bqW:-NPJLoJc0P5VBGAXm4Is:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/tests/integration/proposals/test_self_activation_update.py#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Doesn't the endpoint expect a JSON object `{"allowed": allowed}`?
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_self_activation_update.py` line 76 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzseVg6HrnK1qjfNa_:-NPJLpsqDYg7tnuMh81C:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/tests/integration/proposals/test_self_activation_update.py#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Doesn't the endpoint expect a JSON object `{"allowed": True}`?
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_self_activation_update.py` line 88 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzt2u59i0Iix1IFNaf:-NPJM-3F3wextEoxMwd3:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/tests/integration/proposals/test_self_activation_update.py#L88)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

return > returns
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_self_activation_update.py` line 94 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzstvp26Y1oJhryiP_:-NPJM35i0YzWGN7u4irz:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/tests/integration/proposals/test_self_activation_update.py#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Here and in the following:

Doesn't the endpoint expect a JSON object `{"allowed": True}`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-28 11:51 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: all files reviewed, 16 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1287 at r5](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPMn0iSAR6l1oLTljUL:-NPMn0iSAR6l1oLTljUM:boowh92) ([raw file](https://github.com/saltastroops/salt-api/blob/5033ddb00dfcbb197e985299b4ab9a842b4bd7b3/saltapi/repository/proposal_repository.py#L1287)):*
> ```Python
>             status_id = self._proposal_status_id(status)
>         except NoResultFound:
>             raise ValueError(f"Unknown proposal status: {status}")
> ```

Maybe rather raise a ValidationError?
___
*[`saltapi/repository/proposal_repository.py` line 1292 at r5](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPMmt-Z6M0LLgRTRHlB:-NPMmt-Z6M0LLgRTRHlC:boowh92) ([raw file](https://github.com/saltastroops/salt-api/blob/5033ddb00dfcbb197e985299b4ab9a842b4bd7b3/saltapi/repository/proposal_repository.py#L1292)):*
> ```Python
>             proposal_code_id = self._get_proposal_code_id(proposal_code)
>         except NoResultFound:
>             raise ValueError(f"Unknown proposal code: {proposal_code}")
> ```

Maybe rather raise a ValidationError?
___
*[`saltapi/repository/proposal_repository.py` line 2354 at r5](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPMmgEn4UCXpSBXXi-P:-NPMmgEn4UCXpSBXXi-Q:b-52w1u) ([raw file](https://github.com/saltastroops/salt-api/blob/5033ddb00dfcbb197e985299b4ab9a842b4bd7b3/saltapi/repository/proposal_repository.py#L2354)):*
> ```Python
>         proposal_code_id = result.one_or_none()
>         if not proposal_code_id:
>             raise NotFoundError(f"Couldn't found  proposal code `{proposal_code}`")
> ```

found > find
___
*[`saltapi/web/api/proposals.py` line 542 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzpfSzBoZY9RLAPGKV:-NPMo2yB8oJmiCXvbPMO:b-sbz8ny) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/api/proposals.py#L542)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

fixed.
</blockquote></details>

I don't see any change?


<!-- Sent from Reviewable.io -->

2023-03-07 12:02 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: 7 of 11 files reviewed, 16 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1287 at r5](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPMn0iSAR6l1oLTljUL:-NPpvQ1G2x-szToMYuw9:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5033ddb00dfcbb197e985299b4ab9a842b4bd7b3/saltapi/repository/proposal_repository.py#L1287)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe rather raise a ValidationError?
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1292 at r5](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPMmt-Z6M0LLgRTRHlB:-NPpvQgC1GOFzL-fyR6e:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5033ddb00dfcbb197e985299b4ab9a842b4bd7b3/saltapi/repository/proposal_repository.py#L1292)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe rather raise a ValidationError?
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2354 at r5](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPMmgEn4UCXpSBXXi-P:-NPpvaBCCXdQcsOp11Mv:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5033ddb00dfcbb197e985299b4ab9a842b4bd7b3/saltapi/repository/proposal_repository.py#L2354)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

found > find
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 542 at r4](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOzpfSzBoZY9RLAPGKV:-NPqqtSPDe8zbJE3ew_T:b-62ol7b) ([raw file](https://github.com/saltastroops/salt-api/blob/a408c24957001c66d439940539352fa0f7924326/saltapi/web/api/proposals.py#L542)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see any change?
</blockquote></details>

I used message but now back to UserGivenAndFamilyName
___
*[`tests/integration/proposals/test_self_activation_update.py` line 56 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo4X4P7Q4kISmCCOAr:-NPvwQM-9HP5TzZW8yg3:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/tests/integration/proposals/test_self_activation_update.py#L56)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss this?
</blockquote></details>

fixed
___
*[`tests/integration/proposals/test_self_activation_update.py` line 108 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo58qW5y5k3Syqot_M:-NPvkhLCE8MqyP4Nsn9U:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/tests/integration/proposals/test_self_activation_update.py#L108)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss this?
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 55 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo5cXI04W4rC06J28n:-NPvwSytC0NOtrSuQbG-:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/tests/integration/proposals/test_update_liaison_astronomer.py#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss this?
</blockquote></details>

fixed
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 61 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo5kLJ00YvSMkoPtCB:-NPvw6980od239ehNdVO:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/tests/integration/proposals/test_update_liaison_astronomer.py#L61)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Can you please explain more
</blockquote></details>

fixed
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 114 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOztuRFBmbV-sVikVZn:-NPvw3KjALS_Q4FuKrbM:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/tests/integration/proposals/test_update_liaison_astronomer.py#L114)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss these tests?
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2023-03-07 12:38 UTC, hettlage requested changes
> Reviewed 1 of 4 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: all files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2405 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo8N2t3hdGxeaXZOrW:-NPvzIbo5FeMArc7IUxq:b-6gthcm) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2405)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Validation error how
</blockquote></details>

A 404 error suggests that the resource cannot be found. I'd argue that in this case this means that the But if you pass an invalid user id, that rather means that you have supplied incorrect data, which is more of a validation error.
___
*[`saltapi/service/user.py` line 37 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw-CEe2zHTrh3kCRbz:-NPw-CEe2zHTrh3kCRc-:bqvr6l2) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/saltapi/service/user.py#L37)):*
> ```Python
> 
> @dataclass()
> class UserGivenAndFamilyName:
> ```

I think the name should be something like LiaisonAstronomer (or whatever the type is for....).
___
*[`tests/integration/proposals/test_self_activation_update.py` line 55 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw-zcKCY3diG4a7o2d:-NPw-zcKCY3diG4a7o2e:b2v6mqf) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L55)):*
> ```Python
>     proposal_code = "2020-2-SCI-039"
> 
>     # Test self activation part 1. Setting to `true`
> ```

:"Setting too true." is a bit of a duplication, given. the next sentence in this comment.
___
*[`tests/integration/proposals/test_self_activation_update.py` line 58 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw0Uyv9Gh2rOSttib5:-NPw0Uyv9Gh2rOSttib6:b-jqwstx) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L58)):*
> ```Python
>     # Set self activation allowed to true
>     response = client.put(_url(proposal_code), json={'allowed': True})
>     # Check status to be 200 OK
> ```

I'm not sure this comment is necessary?
___
*[`tests/integration/proposals/test_self_activation_update.py` line 61 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw0bTqBAHIIQTnGlBG:-NPw0bTqBAHIIQTnGlBH:b-jqwstx) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L61)):*
> ```Python
>     assert response.status_code == status.HTTP_200_OK
>     new_self_activation = response.json()
>     # Check response value to be `true`
> ```

I'm not sure this comment is necessary?
___
*[`tests/integration/proposals/test_self_activation_update.py` line 79 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw23wEB__SNRsNV1uC:-NPw23wEB__SNRsNV1uD:bankjw9) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L79)):*
> ```Python
> 
> 
> def test_update_is_self_activatable_should_not_allow_for_a_wrong_proposal_code(
> ```

not_allow > not_be)_allowed
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 57 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw19a-DW3lj27nYxQc:-NPw19a-DW3lj27nYxQd:blfm4vu) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_update_liaison_astronomer.py#L57)):*
> ```Python
>     new_liaison_astronomer = response.json()
>     assert new_liaison_astronomer["id"] == 494
>     proposal_response = client.get("proposals/" + proposal_code)
> ```

You should set two different values, as you don't know what the initial value is.
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 75 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw3O5B3BoV0NAIbTVD:-NPw3O5B3BoV0NAIbTVE:b-2j8mvk) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_update_liaison_astronomer.py#L75)):*
> ```Python
>     authenticate(username, client)
>     proposal_code = "2022-2-SCI-039"
>     response = client.put(_url(proposal_code), json={'id': None})
> ```

You should first set the liaison astronomer to a non-None value.
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 105 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw3f2e86MlXoo9k4BA:-NPw3f2e86MlXoo9k4BB:b-i8iwui) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_update_liaison_astronomer.py#L105)):*
> ```Python
>     [
>         find_username("Principal Investigator", "2018-1-SCI-037"),
>         find_username("Principal Investigator", "2020-1-MLT-005"),
> ```

I think only one PI needs to be checked?
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 114 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw3Z7R0k1OR8kNxbKU:-NPw3Z7R0k1OR8kNxbKV:b-ahqlje) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_update_liaison_astronomer.py#L114)):*
> ```Python
>     ]
> )
> def test_update_liaison_astronomer_return_403_for_unauthorized_users(
> ```

return > returns


<!-- Sent from Reviewable.io -->

2023-03-08 08:00 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: all files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2405 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo8N2t3hdGxeaXZOrW:-NQ-DoADEIr_0InvZSt_:bgn87io) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2405)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A 404 error suggests that the resource cannot be found. I'd argue that in this case this means that the But if you pass an invalid user id, that rather means that you have supplied incorrect data, which is more of a validation error.
</blockquote></details>


I think this was because of lousy naming
___
*[`saltapi/service/user.py` line 37 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw-CEe2zHTrh3kCRbz:-NQ-BPJ-5GSFfvhI09Ty:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/saltapi/service/user.py#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the name should be something like LiaisonAstronomer (or whatever the type is for....).
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_self_activation_update.py` line 55 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw-zcKCY3diG4a7o2d:-NQ-Bkwg-IRw453XfRVo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

:"Setting too true." is a bit of a duplication, given. the next sentence in this comment.
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_self_activation_update.py` line 58 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw0Uyv9Gh2rOSttib5:-NQ-C-2g-6QoiDlF10vM:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L58)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure this comment is necessary?
</blockquote></details>

removed
___
*[`tests/integration/proposals/test_self_activation_update.py` line 61 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw0bTqBAHIIQTnGlBG:-NQ-C0Hp90LK6G6FxZgn:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure this comment is necessary?
</blockquote></details>

removed
___
*[`tests/integration/proposals/test_self_activation_update.py` line 79 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw23wEB__SNRsNV1uC:-NQ-ByqgAv7PBjFHPXL5:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

not_allow > not_be)_allowed
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 57 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw19a-DW3lj27nYxQc:-NQ-CnwY11ciCUbq8mUV:bb6un1j) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_update_liaison_astronomer.py#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should set two different values, as you don't know what the initial value is.
</blockquote></details>

Done
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 75 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw3O5B3BoV0NAIbTVD:-NQ-CqQA6fEcjt77ZAF8:b-7rl0jd) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_update_liaison_astronomer.py#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should first set the liaison astronomer to a non-None value.
</blockquote></details>

done.
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 105 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw3f2e86MlXoo9k4BA:-NQ-D-UgB1HtHoyuGNyT:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_update_liaison_astronomer.py#L105)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think only one PI needs to be checked?
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 114 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw3Z7R0k1OR8kNxbKU:-NQ-D2UsATqeH0C6kZ_i:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_update_liaison_astronomer.py#L114)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

return > returns
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-08 08:56 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: all files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2405 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo8N2t3hdGxeaXZOrW:-NQ-MmXSCd49H_ZYPv1O:b-tx1by) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2405)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I think this was because of lousy naming
</blockquote></details>

Renaming was a good idea, but no, it doesn't solve the issue. :(
___
*[`saltapi/repository/proposal_repository.py` line 2468 at r8](https://reviewable.io/reviews/saltastroops/salt-api/177#-NQ-NQvTCa3j_Uvsj5w6:-NQ-NQvTCa3j_Uvsj5w7:b-bc9wd5) ([raw file](https://github.com/saltastroops/salt-api/blob/ecef6f525f0053d0fb1481721cb3491b52adeef8/saltapi/repository/proposal_repository.py#L2468)):*
> ```Python
>         )
> 
>     def get_salt_astronomer_id(self, user_id: int):
> ```

Three suggestions:

* Rename this to `_salt_astronomer_investigator_id`. (Yes, with the initial underscore; I think the method should be private.)
* Add a docstring like "Return the id of the preferred investigator entry for a SALT Astronomer/"
* Rename user_id to salt_astronomer_user_id.

What makes me feel uneasy is that this method plays two roles, namely getting an investigator id and checking whether the user is a SALT Astronomer. Might be worth a quick chat.
___
*[`tests/integration/proposals/test_self_activation_update.py` line 55 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw-zcKCY3diG4a7o2d:-NQ-Pk417JQccUYOccMS:b3jupdc) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L55)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If you delete "Test self activation part 1", part 2 further down makes no sense any more...
___
*[`tests/integration/proposals/test_self_activation_update.py` line 79 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw23wEB__SNRsNV1uC:-NQ-Q7tH7NNmxnMH61qK:brwxfbw) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L79)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

be_allow > be_allowed
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 69 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NQ-QTvP5-1vQhfaRykf:-NQ-QTvP5-1vQhfaRykg:bgoq8ir) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_update_liaison_astronomer.py#L69)):*
> ```Python
>     ],
> )
> def test_update_liaison_astronomer_should_allow_admins_and_salt_astronomers_to_remove_liaison_astronomer(
> ```

But now you are not (fully) testing removing any longer.


<!-- Sent from Reviewable.io -->

2023-03-08 15:44 UTC, Eb-Zeero reviewed
will count down from 14 next time

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177#-:-NQ0sgN63K_54YznWD54:bdyqbe7)* status: 10 of 12 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2405 at r3](https://reviewable.io/reviews/saltastroops/salt-api/177#-NOo8N2t3hdGxeaXZOrW:-NQ0pzI0706uVKSWIrSi:b-u6bifc) ([raw file](https://github.com/saltastroops/salt-api/blob/4d5ce51a75850bd637ec1fb2fe89e7c4b0c3701e/saltapi/repository/proposal_repository.py#L2405)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Renaming was a good idea, but no, it doesn't solve the issue. :(
</blockquote></details>

maybe I do not get this can we discuss 
___
*[`saltapi/repository/proposal_repository.py` line 2468 at r8](https://reviewable.io/reviews/saltastroops/salt-api/177#-NQ-NQvTCa3j_Uvsj5w6:-NQ0rf739XzEW4bHh3_1:b-e00qz2) ([raw file](https://github.com/saltastroops/salt-api/blob/ecef6f525f0053d0fb1481721cb3491b52adeef8/saltapi/repository/proposal_repository.py#L2468)):*
> Rename this to _salt_astronomer_investigator_id. (Yes, with the initial underscore; I think the method should be private.)
Done.
> Add a docstring like "Return the id of the preferred investigator entry for a SALT Astronomer/"
Done.
> Rename user_id to salt_astronomer_user_id.
And done.

I only see it as trying to find SA and cry if not.
But we can discuss it.
___
*[`tests/integration/proposals/test_self_activation_update.py` line 55 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw-zcKCY3diG4a7o2d:-NQ0s4QL4fMghF1U2Qfc:b-ortr2l) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you delete "Test self activation part 1", part 2 further down makes no sense any more...
</blockquote></details>

Yes Yes, I missed it...
plus 5 more counts :+1:  :)
___
*[`tests/integration/proposals/test_self_activation_update.py` line 79 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NPw23wEB__SNRsNV1uC:-NQ0saBP36kzqmVp5iOm:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_self_activation_update.py#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

be_allow > be_allowed
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_liaison_astronomer.py` line 69 at r7](https://reviewable.io/reviews/saltastroops/salt-api/177#-NQ-QTvP5-1vQhfaRykf:-NQ0t4Gl5RTqjUpT0tLX:b6vq5z5) ([raw file](https://github.com/saltastroops/salt-api/blob/2a48e0596f8db0eef6fdbef536f21c6bdc633cd9/tests/integration/proposals/test_update_liaison_astronomer.py#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But now you are not (fully) testing removing any longer.
</blockquote></details>

We need to discuss this 
count down 15


<!-- Sent from Reviewable.io -->

2023-03-08 20:48 UTC, hettlage reviewed
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2023-03-10 14:13 UTC, hettlage approved these changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/177)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2023-03-10 14:33 UTC, merged