Blocks endpoints and unit tests
saltastroops/salt-api pull request #18
Opened 2021-08-25 05:41 UTC by mofokeng-chaka

2021-08-25 20:03 UTC, hettlage requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/18)* status: all files reviewed, 19 unresolved discussions (waiting on @mofokeng-chaka)

___
*[saltapi/repository/block_repository.py, line 148 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhy-1PREJuxp29crM_u:-Mhy-1PREJuxp29crM_v:b5coty6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/repository/block_repository.py#L148)):*
> ```Python
>         stmt = text(
>             """
> UPDATE BlockStatus
> ```

You have to update the block status id in the block table, not the value in the BlockStatus table.
___
*[saltapi/repository/block_repository.py, line 367 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhys4QKEOcasjn1wpJC:-Mhys4QKEOcasjn1wpJD:b-ok5bix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/repository/block_repository.py#L367)):*
> ```Python
>                 ),
>                 "observation_time": pointing_rows[0].observation_time,
>                 "overhead_time": pointing_rows[0].overhead_time if pointing_rows[0].overhead_time else None,
> ```

Ah, I see where you are coming from. But let's discuss this.
___
*[saltapi/service/block_service.py, line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhyt7WJ-lSc5HyB_5Ve:-Mhyt7WJ-lSc5HyB_5Vf:b4vmu71) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/service/block_service.py#L1)):*
> ```Python
> from saltapi.repository.block_repository import BlockRepository
> ```

(Unit tests are missing.)
___
*[saltapi/service/block_service.py, line 3 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxrXYUCobly67HGXQE:-MhxrXYUCobly67HGXQF:bq4qg7a) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/service/block_service.py#L3)):*
> ```Python
> from saltapi.repository.block_repository import BlockRepository
> from saltapi.service.block import Block
> from saltapi.web.schema.block import BlockStatus
> ```

I think we should be careful with using schema types at the service level, as they constitute a safeguard against leaking information that shouldn't be exposed.
___
*[saltapi/service/block_service.py, line 16 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxsSM59KtJdwToHris:-MhxsSM59KtJdwToHrit:b-uneyxy) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/service/block_service.py#L16)):*
> ```Python
> 
>         return self.block_repository.get(block_id)
> ```

A set_block_status method is missing.
___
*[saltapi/service/block_service.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhxs9Ee0Vaa8gsX8cGv:-Mhxs9Ee0Vaa8gsX8cGw:b2d7ig3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/service/block_service.py#L17)):*
> ```Python
>         return self.block_repository.get(block_id)
> 
>     def get_block_status(self, block_id: int) -> BlockStatus:
> ```

The block status consists of two values, really: the status value and the status comment.

To be consistent with other service methods, the return type probably should be a dict then.
___
*[saltapi/web/api/blocks.py, line 37 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxwMvN9WLFGVXcAiiu:-MhxwMvN9WLFGVXcAiiv:b-dmybvt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L37)):*
> ```Python
> 
> @router.get("/{block_id}/status", summary="Get a block status", response_model=BlockStatus)
> def get_block_status(
> ```

See the remarks on the block status in the block_service.py file.
___
*[saltapi/web/api/blocks.py, line 49 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhxxgio4M0mOoTqVLeR:-Mhxxgio4M0mOoTqVLeS:bi009qc) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L49)):*
> ```Python
>     Status | Description
>     --- | ---
>     Active | The block is active
> ```

Full stop missing after "active".
___
*[saltapi/web/api/blocks.py, line 53 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhxxmg59tj3GVzGN5SW:-Mhxxmg59tj3GVzGN5SX:b-r7g1fd) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L53)):*
> ```Python
>     Deleted | The block has been deleted.
>     Expired | The block was submitted in a previous semester and will not be observed any longer.
>     Not set | The block currently is not in the queue and will not be observed.
> ```

The comment for Not set seems incorrect.
___
*[saltapi/web/api/blocks.py, line 54 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxyIQN82O1fJDXnMw5:-MhxyIQN82O1fJDXnMw6:bljit8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L54)):*
> ```Python
>     Expired | The block was submitted in a previous semester and will not be observed any longer.
>     Not set | The block currently is not in the queue and will not be observed.
>     On Hold | The block is currently on hold.
> ```

For consistency, "On Hold" should be "On hold". The case will have to be handled in the repository (the database wants "On Hold", after all), and it should be unit-tested.
___
*[saltapi/web/api/blocks.py, line 61 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxwweR4bfC-Jt6XZQd:-MhxwweSEdVSm_4awNm0:bh64r5v) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L61)):*
> ```Python
>         instrument_repository = InstrumentRepository(unit_of_work.connection)
>         target_repository = TargetRepository(unit_of_work.connection)
>         block_repository = BlockRepository(
> ```

It might be worth extracting the block repository creation into a helper function everywhere.
___
*[saltapi/web/api/blocks.py, line 66 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhytv4q6hOeAw-87z91:-Mhytv4q6hOeAw-87z92:b-ki0x0r) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L66)):*
> ```Python
>             connection=unit_of_work.connection,
>         )
>         return block_repository.get_block_status(block_id)
> ```

The block repository should not be used in endpoint functions; they should call service methods.
___
*[saltapi/web/api/blocks.py, line 79 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhxwf8U6SvvMTMbeBkl:-Mhxwf8U6SvvMTMbeBkm:brngg0c) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L79)):*
> ```Python
> ) -> None:
>     """
>     Updates the status of the block with the given the block id. See the
> ```

I'd suggest to have the second sentence in a new paragraph.
___
*[saltapi/web/api/blocks.py, line 91 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhyuC6b1-5G_r35gqCc:-MhyuC6b1-5G_r35gqCd:b-ki0x0r) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L91)):*
> ```Python
>             connection=unit_of_work.connection,
>         )
>         return block_repository.update_block_status(block_id, block_status)
> ```

The block repository should not be used in endpoint functions; they should call service methods.
___
*[saltapi/web/schema/block.py, line 79 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxuPMSADD7KfjV5aLm:-MhxuP [...]

2021-08-26 07:54 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/18)* status: all files reviewed, 20 unresolved discussions (waiting on @mofokeng-chaka)

___
*[tests/conftest.py, line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mi0R0TD1ekl8kVEo_d2:-Mi0R0TECBt-_O7kBCDA:bxoq5dv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/tests/conftest.py#L8)):*
> ```Python
> # IMPORTANT: These lines must be executed before any server-related package is imported.
> 
> os.environ["DOTENV_FILE"] = os.path.join(os.path.dirname(__file__), ".env.test")
> ```

Could it be that you have the .env.test file in the tests folder rather than the project root?


<!-- Sent from Reviewable.io -->

2021-09-06 14:35 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/18)* status: 2 of 9 files reviewed, 20 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/block_repository.py, line 148 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhy-1PREJuxp29crM_u:-Mi-y92H38xmFWw4aN_B:bnypndx) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/repository/block_repository.py#L148)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You have to update the block status id in the block table, not the value in the BlockStatus table.
</blockquote></details>

Yep, I was confused here. Thanks, that clears it.
___
*[saltapi/repository/block_repository.py, line 367 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhys4QKEOcasjn1wpJC:-Mi-yZ-L6El803WYmRab:bqerwvv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/repository/block_repository.py#L367)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, I see where you are coming from. But let's discuss this.
</blockquote></details>

The reason I went this way had to do with the fact that some values were null values from the database, and the code wasn't happy about this. 
___
*[saltapi/service/block_service.py, line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhyt7WJ-lSc5HyB_5Ve:-Miv3vT51VKw3D7igYOY:b-7ndrom) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/service/block_service.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

(Unit tests are missing.)
</blockquote></details>

I have now added the tests, however, I am not sure if I am doing the right thing, especially the get method of the FakeBlockRepository
___
*[saltapi/service/block_service.py, line 3 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxrXYUCobly67HGXQE:-Mi-zCI73DdjeVe_jdl2:bsruclw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/service/block_service.py#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think we should be careful with using schema types at the service level, as they constitute a safeguard against leaking information that shouldn't be exposed.
</blockquote></details>

Noted, it was not clear to me why we were not using schema types here.
___
*[saltapi/service/block_service.py, line 16 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxsSM59KtJdwToHris:-MiLZsvhBNajcE_g_eR-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/service/block_service.py#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A set_block_status method is missing.
</blockquote></details>

Done.
___
*[saltapi/service/block_service.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhxs9Ee0Vaa8gsX8cGv:-MiUhKCx2YYxjY_LwbtO:btckwec) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/service/block_service.py#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The block status consists of two values, really: the status value and the status comment.

To be consistent with other service methods, the return type probably should be a dict then.
</blockquote></details>

Done; however, now I am facing an error saying the value is not a valid enumeration member. Looking into it, please let me know if you see anything wrong with the code.
___
*[saltapi/web/api/blocks.py, line 37 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxwMvN9WLFGVXcAiiu:-MiUhMZ9EWQy264hJ-rB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See the remarks on the block status in the block_service.py file.
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 49 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhxxgio4M0mOoTqVLeR:-Mi6-iakDMclmBGFOSOZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Full stop missing after "active".
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 53 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhxxmg59tj3GVzGN5SW:-Mi6-g5gElknGrcQ_wSU:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The comment for Not set seems incorrect.
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 54 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxyIQN82O1fJDXnMw5:-MiVBB5P3ib9Y_42UQNO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency, "On Hold" should be "On hold". The case will have to be handled in the repository (the database wants "On Hold", after all), and it should be unit-tested.
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 61 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxwweR4bfC-Jt6XZQd:-MiLYk039wusXF6IIox9:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be worth extracting the block repository creation into a helper function everywhere.
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 66 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhytv4q6hOeAw-87z91:-Mi01UNr1Iz8KLFa5Wl8:b-po3q52) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L66)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The block repository should not be used in endpoint functions; they should call service methods.
</blockquote></details>

Noted, thanks
___
*[saltapi/web/api/blocks.py, line 79 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhxwf8U6SvvMTMbeBkl:-MiLYwaA8k1O950jCIsU:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to have the second sentence in a new paragraph.
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 91 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhyuC6b1-5G_r35gqCc:-MiLYnfT5MdK78CTdvJH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The block repository should not be used in endpoint functions; they should call service methods.
</blockquote></details>

Done.
___
*[saltapi/web/schema/block.py, line 79 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxuPMSADD7KfjV5aLm:-MiUkquv7k4Ww7CbKrzd:b-v2ss2s) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/schema/block. [...]

2021-09-07 14:30 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/18)* status: all files reviewed, 26 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[saltapi/repository/block_repository.py, line 367 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhys4QKEOcasjn1wpJC:-Mj-2bMy1_pk6cLpUwI-:beei3w8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/repository/block_repository.py#L367)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

The reason I went this way had to do with the fact that some values were null values from the database, and the code wasn't happy about this. 
</blockquote></details>

That sounds a bit odd, as OverheadTime is NOT NULL in the database (and I don't see why NULL values would be handled differently here). Maybe we should have a chat about this?
___
*[saltapi/repository/block_repository.py, line 104 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-1T750gMy5AAZF1VS:-Mj-1T750gMy5AAZF1VT:b-hjm15g) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/repository/block_repository.py#L104)):*
> ```Python
>             "submission_date": pytz.utc.localize(row.submission_date),
>             "semester": row.semester,
>             "status": {"value": row.status, "comment": ""},
> ```

comment should be the BlockStatusReason value from the Block table.

(Hmm, which suggests to call it "reason" rather than comment...)
___
*[saltapi/repository/block_repository.py, line 123 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-1Cu410g5e8hd9eqI:-Mj-1Cu410g5e8hd9eqJ:bxnof8p) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/repository/block_repository.py#L123)):*
> ```Python
>         return block
> 
>     def get_block_status(self, block_id: int) -> Dict:
> ```

Dict requires the types of the key and value: Dict[str, Any]
___
*[saltapi/repository/block_repository.py, line 139 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MizzyhE6X72OF9d2pQ3:-MizzyhE6X72OF9d2pQ4:b-hjm15g) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/repository/block_repository.py#L139)):*
> ```Python
>         row = result.one()
> 
>         status = {"value": row.BlockStatus, "comment": ""}
> ```

comment should be the BlockStatusReason value from the Block table.

(Hmm, which suggests to call it "reason" rather than comment...)
___
*[saltapi/repository/block_repository.py, line 150 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-1jpB6dEARHBycNBm:-Mj-1jpB6dEARHBycNBn:boejnde) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/repository/block_repository.py#L150)):*
> ```Python
>             """
> UPDATE Block
> JOIN BlockStatus BS on Block.BlockStatus_Id = BS.BlockStatus_Id
> ```

You also have to update the status comment/reason.
___
*[saltapi/service/block_service.py, line 25 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-6s4m24MsOeMJbvFn:-Mj-6s4m24MsOeMJbvFo:bjba5ea) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/service/block_service.py#L25)):*
> ```Python
>         return self.block_repository.get_block_status(block_id)
> 
>     def set_block_status(self, block_id: int, status: str) -> Block:
> ```

I'd suggest to call the method update_block_status -- and it should update the status reason as well. (I know I know, I suggested "set", but "update" seems more consistent.

Also, I don't think the method should return anything.
___
*[saltapi/web/api/blocks.py, line 37 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxwMvN9WLFGVXcAiiu:-Mj-3b9iEjoWyN1TjbK2:b-mcr1kj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L37)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. But here an explicit block status type would be better than a Dict...
___
*[saltapi/web/api/blocks.py, line 61 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxwweR4bfC-Jt6XZQd:-Mj-6h6448xLfzpmmA-F:bydo7at) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L61)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks - but this is not exactly what I meant... :-/
___
*[saltapi/web/api/blocks.py, line 52 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-3xyBCQD3KxkIzYMd:-Mj-3xyBCQD3KxkIzYMe:b4d6tfq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L52)):*
> ```Python
>     Returns the status of the block with a given block id.
> 
>     The following status values are possible.
> ```

The status is described by a status value and a reason for that value. The following status values are possible.
___
*[saltapi/web/api/blocks.py, line 60 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-4D-z8WZ8s3prKpC4:-Mj-4D0-3qujsJfw_VN9:b-peu3c) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L60)):*
> ```Python
>     Deleted | The block has been deleted.
>     Expired | The block was submitted in a previous semester and will not be observed any longer.
>     Not set | The block currently is not set.
> ```

block currently ---> block status currently
___
*[saltapi/web/api/blocks.py, line 61 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-4M_0EIELeNB50o6V:-Mj-4M_19v8_MRZAcEl1:b301v8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L61)):*
> ```Python
>     Expired | The block was submitted in a previous semester and will not be observed any longer.
>     Not set | The block currently is not set.
>     On hold | The block status is currently on hold.
> ```

block status ---> block
___
*[saltapi/web/api/blocks.py, line 75 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-5_su7w4wa5zFI8kL:-Mj-5_su7w4wa5zFI8kM:b-xpt60v) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L75)):*
> ```Python
> 
> 
> @router.put("/{block_id}/status", summary="Update a block status", response_model=Block)
> ```

I'd suggest the method returns the BlockStatus rather than the Block.
___
*[saltapi/web/api/blocks.py, line 98 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-67Zf0oCNEa44ACLh:-Mj-67Zf0oCNEa44ACLi:b-kw2ogg) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L98)):*
> ```Python
>             user_repository = UserRepository(unit_of_work.connection)
>             block_service = BlockService(block_repository)
>             permission_service = PermissionService(user_repository)
> ```

I'd suggest to check the permission even before creating the block repository/service.
___
*[saltapi/web/api/blocks.py, line 100 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-58JN4sa0dB4qZWhd:-Mj-58JO2Im35RdyaBGl:bbb3on) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L100)):*
> ```Python
>             permission_service = PermissionService(user_repository)
>     [...]

2021-09-09 06:31 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/18)* status: 2 of 9 files reviewed, 26 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[saltapi/repository/block_repository.py, line 367 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhys4QKEOcasjn1wpJC:-Mj3mlZq3r5WKDjlaqQ4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/repository/block_repository.py#L367)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That sounds a bit odd, as OverheadTime is NOT NULL in the database (and I don't see why NULL values would be handled differently here). Maybe we should have a chat about this?
</blockquote></details>

Done.
___
*[saltapi/repository/block_repository.py, line 104 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-1T750gMy5AAZF1VS:-Mj38TIs3hN7H3wIN3JD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/repository/block_repository.py#L104)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

comment should be the BlockStatusReason value from the Block table.

(Hmm, which suggests to call it "reason" rather than comment...)
</blockquote></details>

Done.
___
*[saltapi/repository/block_repository.py, line 123 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-1Cu410g5e8hd9eqI:-Mj396PQ9WBtweYuWHVg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/repository/block_repository.py#L123)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Dict requires the types of the key and value: Dict[str, Any]
</blockquote></details>

Done.
___
*[saltapi/repository/block_repository.py, line 139 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MizzyhE6X72OF9d2pQ3:-Mj39a0iCjCrRKsaCzyR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/repository/block_repository.py#L139)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

comment should be the BlockStatusReason value from the Block table.

(Hmm, which suggests to call it "reason" rather than comment...)
</blockquote></details>

Done.
___
*[saltapi/repository/block_repository.py, line 150 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-1jpB6dEARHBycNBm:-Mj3Edka2Fb2PoZfnONq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/repository/block_repository.py#L150)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You also have to update the status comment/reason.
</blockquote></details>

Done.
___
*[saltapi/service/block_service.py, line 25 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-6s4m24MsOeMJbvFn:-Mj3A3W958jcp-kaOaWZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/service/block_service.py#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to call the method update_block_status -- and it should update the status reason as well. (I know I know, I suggested "set", but "update" seems more consistent.

Also, I don't think the method should return anything.
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 37 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxwMvN9WLFGVXcAiiu:-Mj8Aj6m2cInOp7pHjlE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/saltapi/web/api/blocks.py#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thanks. But here an explicit block status type would be better than a Dict...
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 52 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-3xyBCQD3KxkIzYMd:-Mj3ASTE8cQz7_i1noxb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The status is described by a status value and a reason for that value. The following status values are possible.
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 60 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-4D-z8WZ8s3prKpC4:-Mj3AeQa9UOx42AF_0Ko:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

block currently ---> block status currently
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 61 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-4M_0EIELeNB50o6V:-Mj3Ai5cALE-GaSei6Uh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

block status ---> block
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 75 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-5_su7w4wa5zFI8kL:-Mj3pElOCOMeOilBUMre:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest the method returns the BlockStatus rather than the Block.
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 98 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-67Zf0oCNEa44ACLh:-Mj3pfdTEQ9MyW-7wi03:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to check the permission even before creating the block repository/service.
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 100 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-58JN4sa0dB4qZWhd:-Mj3ph--EHnRiUsStfvH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L100)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Your might (for consistency) consider calling the service method "update_block_status" rather than "set_block_status".
</blockquote></details>

Done.
___
*[saltapi/web/api/blocks.py, line 102 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mj-6Jly4qYY_oBfhQUR:-Mj3u4lO4oOt3lsnonVV:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2647912f1a2d436f8cf3b4e91939a409197dda63/saltapi/web/api/blocks.py#L102)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is potentially misleading. as the exception you catch isn't necessarily caused by an authentication error.
</blockquote></details>

Done.
___
*[tests/conftest.py, line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-MhxzQXC2tjkWEhQSWeW:-Mj3BQWi61_DmwFc0R5o:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/686481e2dccaa003726a609beabe63595f8e2dd7/tests/conftest.py#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I still see it...
</blockquote></details>

Done.
___
*[tests/repository/test_block_repository.py, line 358 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-Mhwd4i4D6ympvPu5T5O:-Mj8ARKW [...]

2021-09-13 10:26 UTC, mofokeng-chaka reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/18#-:-MjTgLgYDYKQNvRTZg-H:bnfp4nl)* status: 2 of 11 files reviewed, 26 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2021-09-13 10:32 UTC, hettlage approved these changes
> Reviewed 7 of 7 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2021-09-13 10:33 UTC, merged