Reset password
saltastroops/salt-api pull request #19
Opened 2021-09-03 08:10 UTC by Eb-Zeero

2021-09-06 10:21 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: all files reviewed, 23 unresolved discussions (waiting on @Eb-Zeero)

*[a discussion](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuXuls1M6Lvf9Dskst:-MiuXult2K8xqUwa3OZR:b6hrn0g) (no related file):*
Unit tests are missing... :-)

---
___
*[saltapi/settings.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuYMm5EdYF8kM3V39k:-MiuYMm5EdYF8kM3V39l:b-7yp1by) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/settings.py#L36)):*
> ```Python
> 
>     # Email sender
>     email: Optional[str]
> ```

email and saao_smtp shouldn't be optional.
___
*[saltapi/settings.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuYk_mBInYGVAwL6gU:-MiuYk_mBInYGVAwL6gV:b-528qu3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/settings.py#L36)):*
> ```Python
> 
>     # Email sender
>     email: Optional[str]
> ```

I'm not convinced this has to be an environment variable.

How about defining a MailService and have it as a constant in there? (A MailService class might also make unit testing the UserService easier.)
___
*[saltapi/settings.py, line 39 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuYZJZ1nHC8ANix7-B:-MiuYZJZ1nHC8ANix7-C:btthohs) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/settings.py#L39)):*
> ```Python
> 
>     # SAAO SMTP
>     saao_smtp: Optional[str]
> ```

# SMTP server for sending emails
smtp_server: str
___
*[saltapi/repository/user_repository.py, line 271 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Miu_v-132l2qjrrxYuO:-Miu_v-132l2qjrrxYuP:b-ueh9po) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/repository/user_repository.py#L271)):*
> ```Python
>         )
> 
>     def update_password(self, username: str, password: str) -> None:
> ```

I don't think this should be a public method; changing the password should be part of changing the user details.
___
*[saltapi/service/user_service.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuPl5uELs4WAXj6-dv:-MiuPl5uELs4WAXj6-dw:bn9n1z6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L17)):*
> ```Python
>         return self.repository.get(username)
> 
>     def email_token(self, user: User):
> ```

I'd suggest to slightly refactor the code:

* Have a function `password_reset_url`
* Have a function `send_password_reset_email`
___
*[saltapi/service/user_service.py, line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Miu_BucDs0BdYVW6mh9:-Miu_BucDs0BdYVW6mhA:b-brjyed) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L29)):*
> ```Python
>         self.send_reset_token_email(reset_token, user)
> 
>     def reset_password(self, password: str, user: User):
> ```

I guess this function is not necessary at the moment.
___
*[saltapi/service/user_service.py, line 34 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuVhmwBE5XWCcgvUoW:-MiuVhmwBE5XWCcgvUoX:bbod0h1) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L34)):*
> ```Python
> 
>     @staticmethod
>     def send_reset_token_email(token: str, user: User):
> ```

You should include both a plain text and a html version in the email.
___
*[saltapi/service/user_service.py, line 34 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiubkjkEia9TWvsxJgS:-MiubkjkEia9TWvsxJgT:b-a7vosk) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L34)):*
> ```Python
> 
>     @staticmethod
>     def send_reset_token_email(token: str, user: User):
> ```

send_reset_token_email ---> send_password_reset_email
___
*[saltapi/service/user_service.py, line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiubAat1ySJuSnaaOxx:-MiubAat1ySJuSnaaOxy:b-dshltj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L35)):*
> ```Python
>     @staticmethod
>     def send_reset_token_email(token: str, user: User):
>         reset_token = Settings().frontend_uri + "/reset-password/" + token
> ```

I wonder whether the token shouldn't be a query parameter rather than a path parameter.
___
*[saltapi/service/user_service.py, line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiubdsiDK0DNJynueir:-MiubdsiDK0DNJynueis:bcjbrjg) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L35)):*
> ```Python
>     @staticmethod
>     def send_reset_token_email(token: str, user: User):
>         reset_token = Settings().frontend_uri + "/reset-password/" + token
> ```

reset_token ---> reset_url
___
*[saltapi/service/user_service.py, line 37 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuRIN5Bbx3bjVGveb8:-MiuRIN5Bbx3bjVGveb9:b-6paexj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L37)):*
> ```Python
>         reset_token = Settings().frontend_uri + "/reset-password/" + token
> 
>         message = """From: SALT Team <{sender}>
> ```

Here is my suggestion:

```
        message = """From: SALT Team <{sender}>
To: {user} <{receiver}>
Subject: WEB Manager password reset

Dear {user},

Someone (probably you) has requested to reset your SALT Web Manager password.

Please click on the link below to reset your password:

{reset_token}

Alternatively you can copy the link into the address bar of your browser.

If you have not requested ton reset your password, you can just ignore this email.

Kind regards,

SALT Team
        """.format(
```
___
*[saltapi/service/user_service.py, line 42 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiubYqKAS8uyzbtS7H3:-MiubYqKAS8uyzbtS7H4:b-wfwa7z) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L42)):*
> ```Python
> 
> Please click on the link below to reset your password:
> {reset_token}
> ```

reset_token --> reset_url
___
*[saltapi/service/user_service.py, line 48 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuWPVpD1buVPDSL8bU:-MiuWPVpD1buVPDSL8bV:bkvduwu) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L48)):*
> ```Python
>         """.format(
>             sender=Settings().email,
>             user="{family_name} {given_name}".format(
> ```

{family_name} {given_name} ---> {given_name} {family_name}
___
*[saltapi/service/user_service.py, line 61 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuR5wp4RqoX4vUtF5G:-MiuR5wp4RqoX4vUtF5H:b-brjyed) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L61)):*
> ```Python
> 
>     @staticmethod
>     def send_successful_password_rest_email(user: User):
> ```

I guess this function is not necessary at the moment.
___
*[saltapi/web/api/user.py, line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuM5Kg2U85TIoyTblF:-MiuM5Kg2U85TIoyTblG:b-dnf63l) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/ [...]

2021-09-06 17:01 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: all files reviewed, 23 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/settings.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuYMm5EdYF8kM3V39k:-MiukgRw74s0sVPi-swo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/settings.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

email and saao_smtp shouldn't be optional.
</blockquote></details>

Done.
___
*[saltapi/settings.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuYk_mBInYGVAwL6gU:-MivCOL31pf7o7g8iCIP:brryorr) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/settings.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced this has to be an environment variable.

How about defining a MailService and have it as a constant in there? (A MailService class might also make unit testing the UserService easier.)
</blockquote></details>

Can't none SAAO people can use it for none Saao purposes
___
*[saltapi/settings.py, line 39 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuYZJZ1nHC8ANix7-B:-MiulDHQ6opj5WX4pIba:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/settings.py#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

# SMTP server for sending emails
smtp_server: str
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 271 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Miu_v-132l2qjrrxYuO:-Miw0cdh9GdwyqqI1_hs:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/repository/user_repository.py#L271)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this should be a public method; changing the password should be part of changing the user details.
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuPl5uELs4WAXj6-dv:-Miw1js7EGlpZGJH0VmK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to slightly refactor the code:

* Have a function `password_reset_url`
* Have a function `send_password_reset_email`
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Miu_BucDs0BdYVW6mh9:-Miw1qCL67oBj7cFM8Me:b-hfyyrj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess this function is not necessary at the moment.
</blockquote></details>

remaned
___
*[saltapi/service/user_service.py, line 34 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiubkjkEia9TWvsxJgS:-MiuqRU40nnIepPuRTV-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

send_reset_token_email ---> send_password_reset_email
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiubdsiDK0DNJynueir:-Miv1uvXDt1mj8Pm_xhn:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reset_token ---> reset_url
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 37 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuRIN5Bbx3bjVGveb8:-Miv27U73LIOUn7-OGmK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Here is my suggestion:

```
        message = """From: SALT Team <{sender}>
To: {user} <{receiver}>
Subject: WEB Manager password reset

Dear {user},

Someone (probably you) has requested to reset your SALT Web Manager password.

Please click on the link below to reset your password:

{reset_token}

Alternatively you can copy the link into the address bar of your browser.

If you have not requested ton reset your password, you can just ignore this email.

Kind regards,

SALT Team
        """.format(
```

</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 42 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiubYqKAS8uyzbtS7H3:-Miv2hC6-AbbFjkNoUfs:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reset_token --> reset_url
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 48 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuWPVpD1buVPDSL8bU:-Miv2hUi7PszuW6Bch1k:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

{family_name} {given_name} ---> {given_name} {family_name}
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 61 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuR5wp4RqoX4vUtF5G:-Miw2D0UBe2YRiiuXsFk:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess this function is not necessary at the moment.
</blockquote></details>

removed
___
*[saltapi/web/api/user.py, line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuM5Kg2U85TIoyTblF:-Miv3FfV5IqzLFEL4Fov:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/web/api/user.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency with the other API modules, the file should be called `users.py`.
</blockquote></details>

Done.
___
*[saltapi/web/api/user.py, line 11 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuMXLzBBV3dnSynbYI:-Miv3XJk61-nLxWGF8Yo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/web/api/user.py#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The prefix should be `/users`.
</blockquote></details>

Done.
___
*[saltapi/web/api/user.py, line 15 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MifMsr0Dmm_6i_W6BqH:-Miw2JmO07fBvAv2LZg5:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/web/api/user.py#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better /send-password-reminder?
</blockquote></details>

Done.
___
*[saltapi/web/api/user.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuMyTp-NwBat8JLIAH:-Miv3m1wDLELvbytYvLL:b-896fix [...]

2021-09-08 08:39 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: 0 of 7 files reviewed, 23 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/service/user_service.py, line 34 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuVhmwBE5XWCcgvUoW:-Mj3Yv-_5eeVJ8zOvtxo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should include both a plain text and a html version in the email.
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiubAat1ySJuSnaaOxx:-Mj3YxjU9zm-4PcVt4ca:b-b9td2u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wonder whether the token shouldn't be a query parameter rather than a path parameter.
</blockquote></details>

no change
___
*[saltapi/web/api/user.py, line 20 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuN5hc8Uj8mUr2tixK:-MizM5Y840lL9Ur-ZqfJ:b-iek7at) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/web/api/user.py#L20)):*
> Ask g the user for the email address might be the better choice.
check both email and username
___
*[saltapi/web/api/user.py, line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuOH_HEmF6J8_DqXjP:-Mj3YtAJAJn5OuGS14EO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/web/api/user.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is potentially misleading - it might be an exception not related to authentication.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-08 17:47 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: 0 of 8 files reviewed, 23 unresolved discussions (waiting on @hettlage)

*[a discussion](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuXuls1M6Lvf9Dskst:-Mj5W6Mb3Cv7WmCM-dmQ:b9rkovv) (no related file):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unit tests are missing... :-)
</blockquote></details>

I have waisted to much time on this.
please help me with testing mail_servise

---


<!-- Sent from Reviewable.io -->

2021-09-09 15:47 UTC, hettlage requested changes
> Reviewed 2 of 7 files at r2, 5 of 5 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: all files reviewed, 30 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/settings.py, line 38 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj50Iwa8An48pwkQDLI:-Mj50Iwa8An48pwkQDLJ:bkurvb9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/settings.py#L38)):*
> ```Python
>     from_email: str
> 
>     # SMTP server fro sending emails
> ```

fro > for
___
*[saltapi/repository/user_repository.py, line 44 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj52q4M1vbM-UfnNfi9:-Mj52q4M1vbM-UfnNfiA:brm78i5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L44)):*
> ```Python
>         user = result.one_or_none()
>         if not user:
>             raise NotFoundError("Unknown user id")
> ```

user id > username
___
*[saltapi/repository/user_repository.py, line 49 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj50aHA-3mPPP6t3ga2:-Mj50aHA-3mPPP6t3ga3:bb5aaq1) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L49)):*
> ```Python
>     def get_by_email(self, email: str) -> User:
>         """
>         Returns the user with a given username.
> ```

username > email address
___
*[saltapi/repository/user_repository.py, line 51 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj50d97-Gdk60i7jUDz:-Mj50d97-Gdk60i7jUE-:b-vlcg0b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L51)):*
> ```Python
>         Returns the user with a given username.
> 
>         If the username does not exist, a NotFoundError is raised.
> ```

username > email
___
*[saltapi/repository/user_repository.py, line 62 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj52wVP1ZPLtXxLMv5h:-Mj52wVP1ZPLtXxLMv5i:b32rr0x) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L62)):*
> ```Python
>        Username        AS username
> FROM PiptUser PU
>          JOIN Investigator I ON (PU.Investigator_Id = I.Investigator_Id)
> ```

As a user may have multiple Investigator entries, you should join PiptUser and Investigator on the PiptUser_Id (not the Investigator_Id, which only gives you the preferred contact details).,
___
*[saltapi/repository/user_repository.py, line 69 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj53Li42h76lLnB7L6s:-Mj53Li42h76lLnB7L6t:b-edbbxj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L69)):*
> ```Python
>         user = result.one_or_none()
>         if not user:
>             raise NotFoundError("Unknown user id")
> ```

user id > email address
___
*[saltapi/repository/user_repository.py, line 310 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj53t_FDDk11sch3WWS:-Mj53t_FDDk11sch3WWT:b-ki6rt2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L310)):*
> ```Python
>         )
> 
>     def update_user_details(self, user_to_update: UserToUpdate, user: User) -> None:
> ```

I'm tempted to suggest to omit the method while we aren't updating the user details yet.
___
*[saltapi/service/mail_service.py, line 10 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj563ts9MYXLWgITjK5:-Mj563ts9MYXLWgITjK6:b3ddi2y) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/mail_service.py#L10)):*
> ```Python
> 
> 
> class EmailMessagePart:
> ```

Not used anywhere, it seems.
___
*[saltapi/service/mail_service.py, line 20 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj567Kh4xW9AerKjFGg:-Mj567KiA2WxOd3UhFuT:btz9zjx) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/mail_service.py#L20)):*
> ```Python
>             emails_to: List[str],
>             email_from: str,
>             email_message: MIMEMultipart,
> ```

It might be better to pass the text for the plain text and the html text as strings and hide all the MIME complexity within this function.
___
*[saltapi/service/mail_service.py, line 27 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj54Fg45muZ8kP-z2BB:-Mj54Fg45muZ8kP-z2BC:bftopit) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/mail_service.py#L27)):*
> ```Python
>             smtp_obj.sendmail(email_from, emails_to, email_message.as_string())
>         except:
>             raise ValueError("Failed to send reset password from_email.")
> ```

"Failed to send email"

Also, you are losing the error information. So something like this might be better: f"Failed to send email: {e}" (where e is the exception you are catching here).
___
*[saltapi/service/mail_service.py, line 31 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj9oMLJ0-kab2ozXvKv:-Mj9oMLJ0-kab2ozXvKw:b81lsjc) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/be6f0bce9cf18119f64e18b0aac70f965c2e2b43/saltapi/service/mail_service.py#L31)):*
> ```Python
>     @staticmethod
>     def generate_email(
>             email_to: str,
> ```

I'd suggest to use names without email_.
___
*[saltapi/service/user.py, line 13 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj57Jk33fZ0xLn1C2kE:-Mj57Jk33fZ0xLn1C2kF:b-5nlviq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/user.py#L13)):*
> ```Python
> 
> 
> class UserToUpdate(NamedTuple):
> ```

What about the username?

I'm tempted to suggest to omit the class while we aren't updating the user details yet.
___
*[saltapi/service/user_service.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuPl5uELs4WAXj6-dv:-MjAA6rwCQDDusxPTjhb:bqjg1sk) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L17)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. But I'd still suggest to call this method send_password_reset_email.
___
*[saltapi/service/user_service.py, line 28 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj58oBZ2aoXrOJW0g-l:-Mj58oBZ2aoXrOJW0g-m:bbmfsze) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/user_service.py#L28)):*
> ```Python
>             timedelta(hours=24)
>         )
>         user_txt = "{given_name} {family_name}".format(
> ```

Maybe better user_full_name?

And you could use an f-string (f"{user.given_name}...".
___
*[saltapi/service/user_service.py, line 31 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjA976811qhH5X6LyJp:-MjA976811qhH5X6LyJq:b-5ip05z) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/user_service.py#L31)):*
> ```Python
>                 family_name=user.family_name, given_name=user.given_name),
>         message = MIMEMultipart('alternative')
>         message['Subject'] = 'WEB Manager password reset'
> ```

How about: WEB Manager ---> SALT Web Manager
___
*[saltapi/service/user_service.py, line 35 at r3](https://reviewable.io/reviews/saltast [...]

2021-09-13 13:32 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: 1 of 10 files reviewed, 30 unresolved discussions (waiting on @hettlage)

___
*[saltapi/settings.py, line 38 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj50Iwa8An48pwkQDLI:-MjTBtgh4ltdiw0NwvGk:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/settings.py#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

fro > for
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 44 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj52q4M1vbM-UfnNfi9:-MjTC5FZ6dUWwFQnhboL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

user id > username
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 49 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj50aHA-3mPPP6t3ga2:-MjTC7dz5eEsyLez9L3v:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

username > email address
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 51 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj50d97-Gdk60i7jUDz:-MjTCDsQ1O8wPQHeehhq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

username > email
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 62 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj52wVP1ZPLtXxLMv5h:-MjTCUme3WUKbdpkFlVx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L62)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As a user may have multiple Investigator entries, you should join PiptUser and Investigator on the PiptUser_Id (not the Investigator_Id, which only gives you the preferred contact details).,
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 69 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj53Li42h76lLnB7L6s:-MjTCWGpDoc5UwotB-ky:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

user id > email address
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 310 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj53t_FDDk11sch3WWS:-MjTCeMA29QAOVACV2my:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/repository/user_repository.py#L310)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm tempted to suggest to omit the method while we aren't updating the user details yet.
</blockquote></details>

Done.
___
*[saltapi/service/mail_service.py, line 10 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj563ts9MYXLWgITjK5:-MjTCjLGBUgviLY03-Q0:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/mail_service.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Not used anywhere, it seems.
</blockquote></details>

Done.
___
*[saltapi/service/mail_service.py, line 20 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj567Kh4xW9AerKjFGg:-MjTI0HwEQZQPlXL3ZhO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/mail_service.py#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be better to pass the text for the plain text and the html text as strings and hide all the MIME complexity within this function.
</blockquote></details>

Done.
___
*[saltapi/service/mail_service.py, line 27 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj54Fg45muZ8kP-z2BB:-MjTDL139vnfmk1lb7we:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/mail_service.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Failed to send email"

Also, you are losing the error information. So something like this might be better: f"Failed to send email: {e}" (where e is the exception you are catching here).
</blockquote></details>

Done.
___
*[saltapi/service/mail_service.py, line 31 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj9oMLJ0-kab2ozXvKv:-MjTI1pQEfMV05ARnr5l:bb6un1j) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/be6f0bce9cf18119f64e18b0aac70f965c2e2b43/saltapi/service/mail_service.py#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to use names without email_.
</blockquote></details>

Done
___
*[saltapi/service/user.py, line 13 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj57Jk33fZ0xLn1C2kE:-MjTJ-2s72r4U6wtjiY3:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/user.py#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about the username?

I'm tempted to suggest to omit the class while we aren't updating the user details yet.
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MiuPl5uELs4WAXj6-dv:-MjTJD2B1ZZDkaUYhq60:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0c2a613d460d4c776c5d07850244107ba7791327/saltapi/service/user_service.py#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thanks. But I'd still suggest to call this method send_password_reset_email.
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 28 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj58oBZ2aoXrOJW0g-l:-MjTJvl_5gN45SkCcBv1:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/user_service.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better user_full_name?

And you could use an f-string (f"{user.given_name}...".
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 31 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjA976811qhH5X6LyJp:-MjTK32_8eROQydc7vdQ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/user_service.py#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about: WEB Manager ---> SALT Web Manager
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 35 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mj585SBEMuKSeUF9U8i:-MjTOEab3n6uN7YvHrgH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/1b465b37f4288ac512311f38394755a9e71d5d9d/saltapi/service/user_service.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Calling the constructor is in efficient, as you have to read in the .env f [...]

2021-09-14 08:52 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: all files reviewed, 15 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/service/mail_service.py, line 28 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYQLxz-lY5C-YD4xET:-MjYQLxz-lY5C-YD4xEU:b-j7bt2a) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/service/mail_service.py#L28)):*
> ```Python
>                 for u in to
>             )
>             to = [u.email for u in to]
> ```

You are assigning a list of strings to a list of users here...
___
*[saltapi/service/mail_service.py, line 37 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYRAyN9wODMyQx8OwX:-MjYRAyN9wODMyQx8OwY:b-z2rdte) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/service/mail_service.py#L37)):*
> ```Python
>             message.attach(MIMEText(html_body, 'html'))
>             smtp_obj = SMTP(settings.smtp_server)
>             smtp_obj.sendmail(
> ```

You could consider using send_message rather than sendmail.
___
*[saltapi/service/mail_service.py, line 43 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYROJZ9Q5HZkncyH51:-MjYROJZ9Q5HZkncyH52:b-81pcoc) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/service/mail_service.py#L43)):*
> ```Python
>             )
>         except Exception as e:
>             raise ValueError(f"Failed to send email: {e}")
> ```

This isn't a ValueError. 
___
*[saltapi/service/user_service.py, line 25 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYRlGX3VocLD2L8W4M:-MjYRlGX3VocLD2L8W4N:bb8qcnm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/service/user_service.py#L25)):*
> ```Python
>         user_full_name = f"{user.given_name} {user.family_name}"
> 
>         plain_body = f'''Dear {user_full_name[0]},
> ```

user_full_name[0] ---> user_full_name
___
*[saltapi/service/user_service.py, line 46 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYS0olDrIzILPnUlFb:-MjYS0olDrIzILPnUlFc:bb8qcnm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/service/user_service.py#L46)):*
> ```Python
>   <head></head>
>   <body>
>     <p>Dear {user_full_name[0]},</p>
> ```

user_full_name[0] ---> user_full_name
___
*[saltapi/web/schema/common.py, line 279 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYUIIr1JW3Jj_7mI0r:-MjYUIIr1JW3Jj_7mI0s:bu88vnh) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/web/schema/common.py#L279)):*
> ```Python
> 
> class Message(BaseModel):
>     message: str
> ```

```message: str```

should be

```message: str = Field(..., title="Message", description="Message")```
___
*[tests/service/test_mail_service.py, line 2 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYVMFB9frUjMA8F5K4:-MjYVMFB9frUjMA8F5K5:bv3k67t) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/tests/service/test_mail_service.py#L2)):*
> ```Python
> 
> from email.mime.multipart import MIMEMultipart
> ```

These tests need some discussion... :-)


<!-- Sent from Reviewable.io -->

2021-09-15 09:38 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: all files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[saltapi/service/mail_service.py, line 28 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYQLxz-lY5C-YD4xET:-Mjc9_n187kBHcDZ0gxt:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/service/mail_service.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are assigning a list of strings to a list of users here...
</blockquote></details>

fixed
___
*[saltapi/service/mail_service.py, line 37 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYRAyN9wODMyQx8OwX:-Mjc9ShC87UeFPQner7S:b-q3fzqt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/service/mail_service.py#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could consider using send_message rather than sendmail.
</blockquote></details>

`send_message` is hard to understand.
 
___
*[saltapi/service/mail_service.py, line 43 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYROJZ9Q5HZkncyH51:-MjcoMlL4HdVzOac5-f8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/service/mail_service.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This isn't a ValueError. 
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 25 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYRlGX3VocLD2L8W4M:-MjcDv7F8rIM654W9ggr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/service/user_service.py#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

user_full_name[0] ---> user_full_name
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 46 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYS0olDrIzILPnUlFb:-MjcDyPP4pLJIhfcceUi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/service/user_service.py#L46)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

user_full_name[0] ---> user_full_name
</blockquote></details>

Done.
___
*[saltapi/web/schema/common.py, line 279 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYUIIr1JW3Jj_7mI0r:-MjcE9BX0W3yqCGoTHg4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/saltapi/web/schema/common.py#L279)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

```message: str```

should be

```message: str = Field(..., title="Message", description="Message")```

</blockquote></details>

Done.
___
*[tests/service/test_mail_service.py, line 2 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYVMFB9frUjMA8F5K4:-MjcoNkL57GCFUJgWxp2:b-juh2p2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/tests/service/test_mail_service.py#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

These tests need some discussion... :-)
</blockquote></details>

still lost can mock but cant test anything


<!-- Sent from Reviewable.io -->

2021-09-15 12:40 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/service/mail_service.py, line 29 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjdR5BO4Qh97fqkJmfI:-MjdR5BO4Qh97fqkJmfJ:b-wn7y66) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5f7a44ecf76be4a1bc3dc1a0bb2e8dd377272d33/saltapi/service/mail_service.py#L29)):*
> ```Python
>             )
>         except Exception as e:
>             raise Exception(f'Fail to send email.\n{e}')
> ```

I'd suggest: f"Failed to send email: {e}"
___
*[tests/service/test_mail_service.py, line 2 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYVMFB9frUjMA8F5K4:-MjdT6ElEORbCVAvmfXT:b-sf5ecc) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/tests/service/test_mail_service.py#L2)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

still lost can mock but cant test anything
</blockquote></details>

Shall we have a chat about this?


<!-- Sent from Reviewable.io -->

2021-09-16 07:23 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/service/mail_service.py, line 29 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjdR5BO4Qh97fqkJmfI:-MjhUHP05rWq2Xu2bhZC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5f7a44ecf76be4a1bc3dc1a0bb2e8dd377272d33/saltapi/service/mail_service.py#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest: f"Failed to send email: {e}"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-17 11:36 UTC, hettlage requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/service/mail_service.py, line 28 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjnXToC2UCoEb65FwI_:-MjnXToC2UCoEb65FwIa:bwo2xg0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5f7a44ecf76be4a1bc3dc1a0bb2e8dd377272d33/saltapi/service/mail_service.py#L28)):*
> ```Python
> 
>             )
>         except Exception as e:
> ```

Following our recent discussion, I'd suggest not to catch exceptions here.


<!-- Sent from Reviewable.io -->

2021-09-20 10:15 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[saltapi/service/mail_service.py, line 28 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjnXToC2UCoEb65FwI_:-Mk1h-T97Md-xgxIBui2:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5f7a44ecf76be4a1bc3dc1a0bb2e8dd377272d33/saltapi/service/mail_service.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Following our recent discussion, I'd suggest not to catch exceptions here.
</blockquote></details>

Done.
___
*[tests/service/test_mail_service.py, line 2 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-MjYVMFB9frUjMA8F5K4:-MjhUJD66bZn4WtKBsF6:b-jhzqj2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3987458c7f6d959568fce3774b74368ac9c7c7c3/tests/service/test_mail_service.py#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shall we have a chat about this?
</blockquote></details>

Yes we can.


<!-- Sent from Reviewable.io -->

2021-09-20 15:02 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/service/user_service.py, line 17 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mk2iDve8B5a37rZ8aiG:-Mk2iDvf2uuKM3vY2YWX:b-lxgto8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6574ad495daa0277d4856283f3621d3d5f8795d/saltapi/service/user_service.py#L17)):*
> ```Python
>         return self.repository.get(username)
> 
>     def send_password_reset_email(self, user: User):
> ```

Should be tested.
___
*[tests/service/test_mail_service.py, line 35 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mk2hD8RAWaDUNR-r46q:-Mk2hD8RAWaDUNR-r46r:b-qsbowg) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6574ad495daa0277d4856283f3621d3d5f8795d/tests/service/test_mail_service.py#L35)):*
> ```Python
> 
> 
> def test_send_generate_email_return_correct_message(monkeypatch):
> ```

monkeypatch is not used
___
*[tests/service/test_mail_service.py, line 35 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mk2hIhMDYorz8Q8-RRN:-Mk2hIhMDYorz8Q8-RRO:b5h2mgv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6574ad495daa0277d4856283f3621d3d5f8795d/tests/service/test_mail_service.py#L35)):*
> ```Python
> 
> 
> def test_send_generate_email_return_correct_message(monkeypatch):
> ```

return ---> returns
___
*[tests/service/test_mail_service.py, line 49 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mk2gtTI2i8QGOwLWslS:-Mk2gtTJDnrrRqjh7ccK:b-ytn6tx) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6574ad495daa0277d4856283f3621d3d5f8795d/tests/service/test_mail_service.py#L49)):*
> ```Python
>     assert message["To"] == to
>     assert message["From"] == f"SALT Team <{settings.from_email}>"
>     assert message["Subject"] == subject
> ```

You don't test that the message contains the plain text and html in the correct order. So I'd suggest to test that the message as a string is of the form .* + plain_body + .* + html_body + .*


<!-- Sent from Reviewable.io -->

2021-09-27 11:38 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: 5 of 10 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[saltapi/service/user_service.py, line 17 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mk2iDve8B5a37rZ8aiG:-Mkaw0Av56FmW1wouj1w:b-v3q903) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6574ad495daa0277d4856283f3621d3d5f8795d/saltapi/service/user_service.py#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be tested.
</blockquote></details>

from out discussin I do not know what to test.
possible test are is send mail called. or generate_email called.
but failing to  mock variable `mail_service`
___
*[tests/service/test_mail_service.py, line 35 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mk2hD8RAWaDUNR-r46q:-MkaxiTBCYerpsFIQj4N:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6574ad495daa0277d4856283f3621d3d5f8795d/tests/service/test_mail_service.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

monkeypatch is not used
</blockquote></details>

Done.
___
*[tests/service/test_mail_service.py, line 35 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mk2hIhMDYorz8Q8-RRN:-MkaxkNL3-sGHm86iOYd:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6574ad495daa0277d4856283f3621d3d5f8795d/tests/service/test_mail_service.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

return ---> returns
</blockquote></details>

Done.
___
*[tests/service/test_mail_service.py, line 49 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/19#-Mk2gtTI2i8QGOwLWslS:-MkaxsmC7n_LuVrgqOY3:bb7f2mf) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c6574ad495daa0277d4856283f3621d3d5f8795d/tests/service/test_mail_service.py#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You don't test that the message contains the plain text and html in the correct order. So I'd suggest to test that the message as a string is of the form .* + plain_body + .* + html_body + .*
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-10-05 13:06 UTC, hettlage approved these changes
> Reviewed 1 of 1 files at r10, 4 of 4 files at r11, 1 of 1 files at r12, 9 of 10 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2021-10-05 13:06 UTC, merged