Update investigator's proposal approval status endpoint
saltastroops/salt-api pull request #195
Opened 2023-03-07 12:34 UTC by mofokeng-chaka

2023-03-09 09:12 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: all files reviewed, 18 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 2393 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4Jc-p1nNSmuHZtBCA:-NQ4Jc-q2LdkFecyfMNA:b-odakkg) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/repository/proposal_repository.py#L2393)):*
> ```Python
>                          FROM ProposalCode PC
>                          WHERE PC.Proposal_Code = :proposal_code) 
> AND Investigator_Id = (SELECT PU.Investigator_Id
> ```

This is not guaranteed to work, as the Investigator entry used in the proposal is not necessarily the preferred one (which is the one referenced as Investigator_Id in the PiptUser table). You rather have to join the PiptUser and Investigator table on the PiptUser_Id.

Also, you additionally have to set the `ApprovalCode` in `ProposalInvestigator` to `NULL`.
___
*[`saltapi/repository/proposal_repository.py` line 2402 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4KADjBFOEnWn6Pb7L:-NQ4KADjBFOEnWn6Pb7M:b-2dy6jw) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/repository/proposal_repository.py#L2402)):*
> ```Python
>             {
>                 "proposal_code": proposal_code,
>                 "approved": approved,
> ```

I'd suggest you are explicit regarding the type conversion: `1 if approved else 0`
___
*[`saltapi/service/permission_service.py` line 474 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4MeV12eNAg66-76l-:-NQ4MeV2DA68gWGb0gBs:b-hk13ak) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/service/permission_service.py#L474)):*
> ```Python
>         self, user: User, proposal_code: str
>     ) -> None:
>         roles = [Role.ADMINISTRATOR, Role.INVESTIGATOR]
> ```

The check
___
*[`saltapi/service/proposal_service.py` line 345 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4VDHH9F6yT8nrkDfO:-NQ4VDHH9F6yT8nrkDfP:b-qeitkf) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/service/proposal_service.py#L345)):*
> ```Python
>         proposal code.
>         """
>         allowed_status_list = ["Accept", "Reject"]
> ```

Accept > Accepted, Reject > Rejected
___
*[`saltapi/service/proposal_service.py` line 347 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4V6S6-GnaRsesLZ6w:-NQ4V6S6-GnaRsesLZ6x:b75imx3) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/service/proposal_service.py#L347)):*
> ```Python
>         allowed_status_list = ["Accept", "Reject"]
>         if status not in allowed_status_list:
>             raise AuthorizationError()
> ```

This is a ValidationError rather than AuthorizationError.
___
*[`saltapi/web/api/proposals.py` line 468 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4Lfxh2UWeJqHylGKG:-NQ4Lfxh2UWeJqHylGKH:b3xfzbm) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L468)):*
> ```Python
> 
> @router.put(
>     "/{proposal_code}/investigator-proposal-approval-status",
> ```

Can we discuss the endpoint? My feeling is that is should rather be something like `/{proposal_code}/approvals/{user_id}`.
___
*[`saltapi/web/api/proposals.py` line 476 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4WYCNBO4nE5-3XJen:-NQ4WYCNBO4nE5-3XJeo:b-nlitvk) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L476)):*
> ```Python
>         ...,
>         title="Proposal code",
>         description="Proposal code of the proposal whose status is updated.",
> ```

"Proposal code of the proposal for which an investigator approval status is updated."
___
*[`saltapi/web/api/proposals.py` line 483 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4VsTqB2BdWXsWiitv:-NQ4VsTqB2BdWXsWiitw:b-lidrxw) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L483)):*
> ```Python
>         description="Id of the user",
>     ),
>     approval_status: str = Body(
> ```

Given that there are only two possible values, you should rather use a Pydantic type.
___
*[`saltapi/web/api/proposals.py` line 486 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4WFNp2x_Ywj5ynljf:-NQ4WFNp2x_Ywj5ynljg:bdh9tc0) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L486)):*
> ```Python
>         ...,
>         alias="status",
>         title="Proposal status and (optional) status comment",
> ```

A clear case of cut-and-paste... This isn't a proposal status... :-)
___
*[`saltapi/web/api/proposals.py` line 487 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4VfheBqsO41aLS4Ss:-NQ4VfheBqsO41aLS4St:bdh9tc0) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L487)):*
> ```Python
>         alias="status",
>         title="Proposal status and (optional) status comment",
>         description="New proposal status and (optional) status comment.",
> ```

A clear case of cut-and-paste... This isn't a proposal status... :-)
___
*[`saltapi/web/api/proposals.py` line 492 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4aNqN9EskHXkXjeG3:-NQ4aNqN9EskHXkXjeG4:b-eujg2w) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L492)):*
> ```Python
> ) -> None:
>     """
>     Updates the investigator's approval status of the proposal with the given proposal
> ```

the investigator's > an investigator's

I'm not sure "with the given proposal code" is needed here.
___
*[`saltapi/web/api/proposals.py` line 499 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4WqgQ4oSabayt-E3Y:-NQ4WqgRBZ43jpxqE9le:bgpkgg8) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L499)):*
> ```Python
>     Status | Description
>     --- | ---
>     Approve | The investigator approves the proposal.
> ```

Approve > Approved
Reject > Rejected
___
*[`saltapi/web/api/proposals.py` line 510 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4X7nG6ribcZj5mDlv:-NQ4X7nG6ribcZj5mDlw:b-medy86) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L510)):*
> ```Python
>         )
>         if user.id != user_id:
>             permission_service.check_permission_to_update_user(user, user_id)
> ```

I'm not convinced that this is the correct permission function to use (just regarding the name).

Also, I think this should be handled by the `check_permission_to_update_investigator_proposal_approval_status` method.
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 9 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4YpfY41IYa8rpVWnI:-NQ4YpfY41IYa8rpVWnJ:bp8ezmy) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L9)):*
> ```Python
> PROPOSALS_URL = "/proposals"
> ```

You aren't testing that you get a 404 for a non-existing proposal code.
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 68 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4Mz8HB2obmvC041aZ:-NQ4 [...]

2023-03-09 11:29 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: 0 of 6 files reviewed, 18 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 2393 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4Jc-p1nNSmuHZtBCA:-NQ4fSmW-Q3jniiyZzfB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/repository/proposal_repository.py#L2393)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is not guaranteed to work, as the Investigator entry used in the proposal is not necessarily the preferred one (which is the one referenced as Investigator_Id in the PiptUser table). You rather have to join the PiptUser and Investigator table on the PiptUser_Id.

Also, you additionally have to set the `ApprovalCode` in `ProposalInvestigator` to `NULL`.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2402 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4KADjBFOEnWn6Pb7L:-NQ4fa-G3vGEX_fCwUDF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/repository/proposal_repository.py#L2402)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest you are explicit regarding the type conversion: `1 if approved else 0`
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 345 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4VDHH9F6yT8nrkDfO:-NQ4fhPQ6YI1lRJZmfuR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/service/proposal_service.py#L345)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Accept > Accepted, Reject > Rejected
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 347 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4V6S6-GnaRsesLZ6w:-NQ4fpup4N40rjecRVh7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/service/proposal_service.py#L347)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is a ValidationError rather than AuthorizationError.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 468 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4Lfxh2UWeJqHylGKG:-NQ4k8yu8MGa1Tou_TBG:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L468)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss the endpoint? My feeling is that is should rather be something like `/{proposal_code}/approvals/{user_id}`.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 476 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4WYCNBO4nE5-3XJen:-NQ4kFgT6UKs-YyFtqOo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L476)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Proposal code of the proposal for which an investigator approval status is updated."
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 483 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4VsTqB2BdWXsWiitv:-NQ4kHIW4_InZ_CYl7gY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L483)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that there are only two possible values, you should rather use a Pydantic type.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 486 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4WFNp2x_Ywj5ynljf:-NQ4kX6CBFNpE9yRokKV:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L486)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A clear case of cut-and-paste... This isn't a proposal status... :-)
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 487 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4VfheBqsO41aLS4Ss:-NQ4kXPr5KuWhTVMbhhM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L487)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A clear case of cut-and-paste... This isn't a proposal status... :-)
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 492 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4aNqN9EskHXkXjeG3:-NQ4kcwN0wI5XyP8zHOp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L492)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

the investigator's > an investigator's

I'm not sure "with the given proposal code" is needed here.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 499 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4WqgQ4oSabayt-E3Y:-NQ4keNX9AfDeqb6isje:b-7l83w7) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L499)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Approve > Approved
Reject > Rejected
</blockquote></details>

Done and i have changed Approved >> Accepted
___
*[`saltapi/web/api/proposals.py` line 510 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4X7nG6ribcZj5mDlv:-NQ4m6xR-FHobdY-BRgp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/web/api/proposals.py#L510)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced that this is the correct permission function to use (just regarding the name).

Also, I think this should be handled by the `check_permission_to_update_investigator_proposal_approval_status` method.
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 9 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4YpfY41IYa8rpVWnI:-NQ4n4XZAc5lmvnIPA3X:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You aren't testing that you get a 404 for a non-existing proposal code.
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 68 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4Mz8HB2obmvC041aZ:-NQ4nCYV7-Fov2bxxqhh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why would you expect a 403 error here? The user is allowed, so it should rather be a 400 or 422?
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 76 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4YGiVEl_kfH2WO1BG:-NQ4sVlM0Y7zsCzKoIYo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/tests/integration/proposa [...]

2023-03-09 11:29 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: 0 of 6 files reviewed, 18 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 474 at r1](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ4MeV12eNAg66-76l-:-NQ57RSxD0__RDDjRW-I:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d318698968ae350ac01a79377720ca764f93d9ba/saltapi/service/permission_service.py#L474)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The check
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-10 12:34 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: all files reviewed, 10 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 2392 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5PF4N0AMWI0KW-5aB:-NQ5PF4N0AMWI0KW-5aC:b-t2k1ro) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/saltapi/repository/proposal_repository.py#L2392)):*
> ```Python
> SET InvestigatorOkay=:approved,
>     ApprovalCode=NULL
> WHERE Investigator_Id = (SELECT * FROM(SELECT I.Investigator_Id
> ```

I would suggest to rename tblTmp to just tmp, and to reformat the query:

```
UPDATE ProposalInvestigator
SET InvestigatorOkay=:approved,
    ApprovalCode=NULL
WHERE Investigator_Id = (SELECT *
                         FROM (SELECT I.Investigator_Id
                               FROM Investigator I
                                        JOIN PiptUser PU ON I.PiptUser_Id = PU.PiptUser_Id
                                        JOIN ProposalInvestigator PI
                                             ON I.Investigator_Id = PI.Investigator_Id
                                        JOIN ProposalCode PC
                                             ON PI.ProposalCode_Id = PC.ProposalCode_Id
                               WHERE PC.Proposal_Code = :proposal_code
                                 AND PU.PiptUser_Id = :user_id) tmp)
```

It might also be worth adding a comment like "The temporary table tmp is necessary as the ProposalInvestigator table cannot be included in the FROM statement."
___
*[`saltapi/service/permission_service.py` line 475 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5QULsAQl4v0zwww9k:-NQ5QULsAQl4v0zwww9l:b-s239mu) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/saltapi/service/permission_service.py#L475)):*
> ```Python
>     ) -> None:
>         if user.id != user_id:
>             self.check_permission_to_view_user(user, user_id)
> ```

I'm not convinced I'd rely on that function here.
___
*[`saltapi/web/api/proposals.py` line 496 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5R64BCD2O0lv5DWei:-NQ5R64C1h9xsCUIWVVO:b-bw8dol) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/saltapi/web/api/proposals.py#L496)):*
> ```Python
> ) -> None:
>     """
>     Updates an investigator's approval status of the proposal.
> ```

Updates 
___
*[`saltapi/web/api/proposals.py` line 510 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5SQRs-yxiGOd3I3tY:-NQ5SQRs-yxiGOd3I3tZ:bl8fm8c) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/saltapi/web/api/proposals.py#L510)):*
> ```Python
> 
>         permission_service.check_permission_to_update_investigator_proposal_approval_status(
>             user, user_id, proposal_code
> ```

I'd argue that the variable names `user` and `user_id` are potentially confusing, So maybe rather say `approval_user_id`?
___
*[`saltapi/web/api/proposals.py` line 487 at r3](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQAPYOl50EYXX43vhzI:-NQAPYOl50EYXX43vhzJ:bxnct88) ([raw file](https://github.com/saltastroops/salt-api/blob/cc28b1877f6f07639bd24fc3f89f41291d8adf47/saltapi/web/api/proposals.py#L487)):*
> ```Python
>         description="Id of the user",
>     ),
>     approval_status: bool = Body(
> ```

I would suggest not to use an alias and to use the `ProposalApprovalStatus` type rather than a boolean.

In other words, the JSON should be `{ approved: true }' rather than just `true`.
___
*[`saltapi/web/api/proposals.py` line 498 at r3](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQAQVl-5pxddJnI-pvZ:-NQAQQPz7yv8LCx9rbRN:bxr0563) ([raw file](https://github.com/saltastroops/salt-api/blob/cc28b1877f6f07639bd24fc3f89f41291d8adf47/saltapi/web/api/proposals.py#L498)):*
> ```Python
>     Updates an investigator's approval status of the proposal.
> 
>     The following status values are possible.
> ```

I'm not sure the table is necessary, in particular if you change the the type from `bool` to `ProposalApprovalStatus`?
___
*[`saltapi/web/schema/proposal.py` line 24 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5TRBw8NFXuJEPRUEA:-NQ5TRBx918RHmQBYiSY:be41bme) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/saltapi/web/schema/proposal.py#L24)):*
> ```Python
> 
> 
> ProposalApprovalStatus = Literal["Accepted", "Rejected"]
> ```

"Approved" might be slightly more precise than "Accepted".

Also, note that there is an inconsistency in the API. On the one hand the approval status is returned as a boolean, on the other hand it is set as a string.

Can we discuss this?
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 117 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5Vdmn3d4YbU69RK2_:-NQ5Vdmn3d4YbU69RK2a:bfomych) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L117)):*
> ```Python
>     client: TestClient,
> ) -> None:
>     proposal_code = "2019-2-SCI-006"
> ```

Minor nit-picking perhaps,  but I'd rather login as the PC and try to change the normal investigator's approval status.
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 161 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5WltN1BcUhoxb5Aev:-NQ5WltN1BcUhoxb5Aew:b2oafej) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L161)):*
> ```Python
> 
> 
> def test_investigator_approval_proposal_status_update_for_pc(
> ```

Why is this test required?
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 212 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5NvcNAb7RwuknSKml:-NQ5NvcNAb7RwuknSKmm:b-y3rzyj) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L212)):*
> ```Python
>     investigator = [i for i in proposal["investigators"] if i["id"] == user_id]
> 
>     assert investigator[0]["has_approved_proposal"] == 0
> ```

Oh. That doesn't look right. Shouldn't the value be `False`?


<!-- Sent from Reviewable.io -->

2023-03-10 12:37 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: all files reviewed, 11 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/web/schema/proposal.py` line 24 at r3](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQAWbm6-fVF4GLUWXKm:-NQAWbm78vjDMukX29VF:b-9ct6km) ([raw file](https://github.com/saltastroops/salt-api/blob/cc28b1877f6f07639bd24fc3f89f41291d8adf47/saltapi/web/schema/proposal.py#L24)):*
> ```Python
> 
> 
> ProposalApprovalStatus = Literal["Accepted", "Rejected"]
> ```

I would suggest type like:

```
class ProposalApprovalStatus(BaseModel):
    approved: bool = Field(
        ...,
        title="Proposal approved?",
        description="Has the investigator approved the proposal?",
    )
```


<!-- Sent from Reviewable.io -->

2023-03-10 15:04 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: all files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2392 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5PF4N0AMWI0KW-5aB:-NQAwS3P-ljWMdtD4Crx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/saltapi/repository/proposal_repository.py#L2392)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest to rename tblTmp to just tmp, and to reformat the query:

```
UPDATE ProposalInvestigator
SET InvestigatorOkay=:approved,
    ApprovalCode=NULL
WHERE Investigator_Id = (SELECT *
                         FROM (SELECT I.Investigator_Id
                               FROM Investigator I
                                        JOIN PiptUser PU ON I.PiptUser_Id = PU.PiptUser_Id
                                        JOIN ProposalInvestigator PI
                                             ON I.Investigator_Id = PI.Investigator_Id
                                        JOIN ProposalCode PC
                                             ON PI.ProposalCode_Id = PC.ProposalCode_Id
                               WHERE PC.Proposal_Code = :proposal_code
                                 AND PU.PiptUser_Id = :user_id) tmp)
```

It might also be worth adding a comment like "The temporary table tmp is necessary as the ProposalInvestigator table cannot be included in the FROM statement."
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 475 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5QULsAQl4v0zwww9k:-NQAxCrH9p0PsxlILqaW:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/saltapi/service/permission_service.py#L475)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced I'd rely on that function here.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 496 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5R64BCD2O0lv5DWei:-NQB0qlM2IutlewPmQmg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/saltapi/web/api/proposals.py#L496)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Updates 
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 510 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5SQRs-yxiGOd3I3tY:-NQB0s5D6sy9epSqF4HO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/saltapi/web/api/proposals.py#L510)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd argue that the variable names `user` and `user_id` are potentially confusing, So maybe rather say `approval_user_id`?
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 487 at r3](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQAPYOl50EYXX43vhzI:-NQAxax64zb6Q3XAIxQF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cc28b1877f6f07639bd24fc3f89f41291d8adf47/saltapi/web/api/proposals.py#L487)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest not to use an alias and to use the `ProposalApprovalStatus` type rather than a boolean.

In other words, the JSON should be `{ approved: true }' rather than just `true`.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 498 at r3](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQAQVl-5pxddJnI-pvZ:-NQB0mF09E1NcuYtG52v:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cc28b1877f6f07639bd24fc3f89f41291d8adf47/saltapi/web/api/proposals.py#L498)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure the table is necessary, in particular if you change the the type from `bool` to `ProposalApprovalStatus`?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 24 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5TRBw8NFXuJEPRUEA:-NQB0toXC6Tuah7RstvW:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/saltapi/web/schema/proposal.py#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Approved" might be slightly more precise than "Accepted".

Also, note that there is an inconsistency in the API. On the one hand the approval status is returned as a boolean, on the other hand it is set as a string.

Can we discuss this?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 24 at r3](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQAWbm6-fVF4GLUWXKm:-NQAy0SA03VaZy46mLWV:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cc28b1877f6f07639bd24fc3f89f41291d8adf47/saltapi/web/schema/proposal.py#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest type like:

```
class ProposalApprovalStatus(BaseModel):
    approved: bool = Field(
        ...,
        title="Proposal approved?",
        description="Has the investigator approved the proposal?",
    )
```
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 117 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5Vdmn3d4YbU69RK2_:-NQB0j4p05Mg2xbD7i6s:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L117)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Minor nit-picking perhaps,  but I'd rather login as the PC and try to change the normal investigator's approval status.
</blockquote></details>

Done.
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 161 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5WltN1BcUhoxb5Aev:-NQB0Dlc16rj5kGfrrIF:bpmzief) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L161)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why is this test required?
</blockquote></details>

I tested for all users. But i 
___
*[`tests/integration/proposals/test_update_investigator_proposal_approval_status.py` line 212 at r2](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQ5NvcNAb7RwuknSKml:-NQB0BDMDFqLX-h9FjQL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b3e45645a98a9144af85c548048f2fd8d22a9539/tests/integration/proposals/test_update_investigator_proposal_approval_status.py#L212)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh. That doesn't look right. Shouldn't the value be `False`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-13 16:30 UTC, hettlage requested changes
> Reviewed 1 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`saltapi/service/permission_service.py` line 483 at r5](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQQliyP9KgiqMsnrPcK:-NQQliyP9KgiqMsnrPcL:bi30bmf) ([raw file](https://github.com/saltastroops/salt-api/blob/0e3469ac0817f979d74384d1d89815ba8674a709/saltapi/service/permission_service.py#L483)):*
> ```Python
>     ) -> None:
>         roles = (
>             [Role.ADMINISTRATOR] if user.id != approval_user_id else [Role.INVESTIGATOR]
> ```

I don't think the `Role.INVESTIGATOR` makes a difference. Can't you just use the following?:

```
# Investigators can always change their own approval status, but changing someone else's status requires administrator rights
if user.id != approval_user_id:
    self.check_role(user.username, roles, proposal_code)
```


<!-- Sent from Reviewable.io -->

2023-03-14 07:31 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 483 at r5](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQQliyP9KgiqMsnrPcK:-NQU-D408LFR-RKYhQzk:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/0e3469ac0817f979d74384d1d89815ba8674a709/saltapi/service/permission_service.py#L483)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the `Role.INVESTIGATOR` makes a difference. Can't you just use the following?:

```
# Investigators can always change their own approval status, but changing someone else's status requires administrator rights
if user.id != approval_user_id:
    self.check_role(user.username, roles, proposal_code)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-14 09:25 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/service/permission_service.py` line 487 at r6](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQUQznl3wq-epggTlGj:-NQUQznm4BW1cXR9xNKd:b-r3uo6e) ([raw file](https://github.com/saltastroops/salt-api/blob/c5ac0394533607f5b5d8c7dbdcccb17c8a3c764a/saltapi/service/permission_service.py#L487)):*
> ```Python
>             self.check_role(user.username, roles, proposal_code)
> 
>         self.check_role(user.username, roles, proposal_code)
> ```

Isn/'t that line obsolete now?


<!-- Sent from Reviewable.io -->

2023-03-14 11:21 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 487 at r6](https://reviewable.io/reviews/saltastroops/salt-api/195#-NQUQznl3wq-epggTlGj:-NQUqJl894qWwri900j9:b-ob8xvd) ([raw file](https://github.com/saltastroops/salt-api/blob/c5ac0394533607f5b5d8c7dbdcccb17c8a3c764a/saltapi/service/permission_service.py#L487)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn/'t that line obsolete now?
</blockquote></details>

I missed it, thanks :-)


<!-- Sent from Reviewable.io -->

2023-03-15 11:15 UTC, hettlage approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2023-03-15 11:27 UTC, hettlage approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2023-03-15 11:28 UTC, merged