Create requested data observations
saltastroops/salt-api pull request #207
Opened 2023-03-23 16:37 UTC by Eb-Zeero

2023-03-28 15:45 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207)* status: all files reviewed, 29 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/data_repository.py` line 25 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcf8V-8nJYJ_gFqILA:-NRcf8V-8nJYJ_gFqILB:b-id1141) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L25)):*
> ```Python
>         data_format_id = result.one_or_none()
>         if not data_format_id:
>             raise NotFoundError(f"Couldn't find  requested data format `{data_format}`")
> ```

Too many spaces between "find" and "requested".
___
*[`saltapi/repository/data_repository.py` line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcfQ8e4RFuEbQNqW80:-NRcfQ8fCeJTT-hfsnfC:be40x79) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L29)):*
> ```Python
>         return cast(int, data_format_id[0])
> 
>     def request_observations(
> ```

This is `request_data` rather than `request_observations`.
___
*[`saltapi/repository/data_repository.py` line 37 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcj2MjCRsW37DIrb5o:-NRcj2Mk0_Ug1us8vwfD:b-ak3lki) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L37)):*
> ```Python
>     ):
>         """
>         Create a observations data request
> ```

Create a data request,

Or:

Create an observation data request,
___
*[`saltapi/repository/data_repository.py` line 39 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcj8dt7ADMpbDkEngg:-NRcj8dt7ADMpbDkEngh:b-ra85cb) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L39)):*
> ```Python
>         Create a observations data request
>         """
>         proposal_code_id = self.proposal_repository.get_proposal_code_id(proposal_code)
> ```

You aren't handling the case of a non-existing proposal code id, data format id or user id in a user-friendly manner.
___
*[`saltapi/repository/data_repository.py` line 40 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcgHs6A-haN4fGzYKm:-NRcgHs6A-haN4fGzYKn:bctt7sl) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L40)):*
> ```Python
>         """
>         proposal_code_id = self.proposal_repository.get_proposal_code_id(proposal_code)
>         data_format_id = self._get_data_format_id("all")
> ```

You aren't handling the case of formats other than "all" and "calibration".
___
*[`saltapi/repository/data_repository.py` line 42 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRci9diENKusuWzKkg2:-NRci9diENKusuWzKkg3:b-bva6md) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L42)):*
> ```Python
>         data_format_id = self._get_data_format_id("all")
>         insert_rows = []
>         for b in block_visits_ids:
> ```

`block_visit_id` rather than `b` might be more consistent with the other variable names.
___
*[`saltapi/repository/data_repository.py` line 57 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcg4ne5VQEVghJ2eAq:-NRcg4ne5VQEVghJ2eAr:by3uksu) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L57)):*
> ```Python
>                     "block_visit_id": None,
>                     "user_id": user_id,
>                     "data_format_id": self._get_data_format_id("calibration"),
> ```

Getting the data format id in the for loop is inefficient. (You are getting the same id over and over again.)
___
*[`saltapi/repository/data_repository.py` line 70 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcgzFk-r0fGgdfikUv:-NRcgzFk-r0fGgdfikUw:bd1i3ln) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L70)):*
> ```Python
>     RequestDate
> )
> VALUES(
> ```

There should be a space between "VALUES" and "(".
___
*[`saltapi/repository/data_repository.py` line 85 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRchHDrCylLcwqr4dZd:-NRchHDrCylLcwqr4dZe:b-kw5nkv) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L85)):*
> ```Python
>         )
> 
>         if not result.rowcount:
> ```

How can the row count be 0?
___
*[`saltapi/repository/proposal_repository.py` line 2378 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcigrM5Lt0mXX399qG:-NRcigrNAsVqVeIDB9v5:bvdd5af) ([raw file](https://github.com/saltastroops/salt-api/blob/5cb9ea06789ab4e3111c1d5f0e8b4f03eaf9aaa5/saltapi/repository/proposal_repository.py#L2378)):*
> ```Python
>         return configurations
> 
>     def _get_proposal_code_id(self, proposal_code: str) -> int:
> ```

As you have made the private method public, you should check whether there is a test for it.

And add a docstring...
___
*[`saltapi/service/data_service.py` line 18 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRckRGr3cPVP1eMi5Ka:-NRckRGr3cPVP1eMi5Kb:b-ak3lki) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/service/data_service.py#L18)):*
> ```Python
>     ):
>         """
>         Create an observations data request.
> ```

Create a data request,

Or:

Create an observation data request,
___
*[`saltapi/service/data_service.py` line 20 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcjq5u6O8Qse4TfLY2:-NRcjq5u6O8Qse4TfLY3:b-7nzwe7) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/service/data_service.py#L20)):*
> ```Python
>         Create an observations data request.
>         """
>         self.repository.request_observations(
> ```

`request_data` rather than `request_observations`.
___
*[`saltapi/service/permission_service.py` line 488 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRclApK0Q4Oqow76gRV:-NRclApL-v_4kI6HBGT4:b-esi2ne) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/service/permission_service.py#L488)):*
> ```Python
>             self.check_role(user.username, roles, proposal_code)
> 
>     def check_permission_to_request_observations(self, user: User, proposal_code: str):
> ```

I see a security loophole here: What if the user tries to access a block visit
___
*[`saltapi/service/permission_service.py` line 488 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcqA-d22s86cCmw9vJ:-NRcqA-d22s86cCmw9vK:b-uk3eqo) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/service/permission_service.py#L488)):*
> ```Python
>             self.check_role(user.username, roles, proposal_code)
> 
>     def check_permission_to_request_observations(self, user: User, proposal_code: str):
> ```

request_observations > request_data
___
*[`saltapi/web/services.py` line 65 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRco77c8Vcb4B8LZIdk:-NRco77c8Vcb4B8LZIdl:bbvzyz9) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/web/services.py#L65)):*
> ```Python
> 
> def data_service(connection: Connection) -> DataService:
>     """Return a proposal service instance."""
> ```

proposal_service > data_service



_Code quote:_
```Python
def data_service(connection: Connection) -> DataService:
    """Return a prop [...]

2023-03-28 18:19 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207)* status: all files reviewed, 29 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/data_repository.py` line 25 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcf8V-8nJYJ_gFqILA:-NRcvReJ-N2PXP639zWe:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Too many spaces between "find" and "requested".
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcfQ8e4RFuEbQNqW80:-NRcvjL748zd9pX8zz9Z:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is `request_data` rather than `request_observations`.
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 37 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcj2MjCRsW37DIrb5o:-NRdRXNPArRjAmD-Wdzz:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Create a data request,

Or:

Create an observation data request,
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 39 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcj8dt7ADMpbDkEngg:-NRd-ccE4lgT1X4lqq84:b8claab) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You aren't handling the case of a non-existing proposal code id, data format id or user id in a user-friendly manner.
</blockquote></details>

handles by respective methods
___
*[`saltapi/repository/data_repository.py` line 40 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcgHs6A-haN4fGzYKm:-NRd-czX2TPOLHTRM8Zp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You aren't handling the case of formats other than "all" and "calibration".
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 42 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRci9diENKusuWzKkg2:-NRd1YtD0hWt123Mj2Qh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`block_visit_id` rather than `b` might be more consistent with the other variable names.
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 57 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcg4ne5VQEVghJ2eAq:-NRd1eXH8nb2HvL8FpQu:baew3ca) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Getting the data format id in the for loop is inefficient. (You are getting the same id over and over again.)
</blockquote></details>

no longer needed but I wasn't 
___
*[`saltapi/repository/data_repository.py` line 70 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcgzFk-r0fGgdfikUv:-NRd2G4i13gOEHn3bk1w:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be a space between "VALUES" and "(".
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 85 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRchHDrCylLcwqr4dZd:-NRd2PEz9tOZHcJfCTE8:b-na8l62) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How can the row count be 0?
</blockquote></details>

my bad
___
*[`saltapi/repository/proposal_repository.py` line 2378 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcigrM5Lt0mXX399qG:-NRd6tuH2ZrM4IS3-wqF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5cb9ea06789ab4e3111c1d5f0e8b4f03eaf9aaa5/saltapi/repository/proposal_repository.py#L2378)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As you have made the private method public, you should check whether there is a test for it.

And add a docstring...
</blockquote></details>

Done.
___
*[`saltapi/service/data_service.py` line 18 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRckRGr3cPVP1eMi5Ka:-NRd77Dd1bK646FhxXt2:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/service/data_service.py#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Create a data request,

Or:

Create an observation data request,
</blockquote></details>

Done.
___
*[`saltapi/service/data_service.py` line 20 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcjq5u6O8Qse4TfLY2:-NRd7BB93dg1HE6YSByk:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/service/data_service.py#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`request_data` rather than `request_observations`.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 488 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRclApK0Q4Oqow76gRV:-NRdIGoe-c7fzWIbi7Kf:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/service/permission_service.py#L488)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I see a security loophole here: What if the user tries to access a block visit
</blockquote></details>

fixed
___
*[`saltapi/service/permission_service.py` line 488 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcqA-d22s86cCmw9vJ:-NRdINE8BzLWteanWuCl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/service/permission_service.py#L488)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

request_observations > request_data
</blockquote></details>

Done.
___
*[`saltapi/web/services.py` line 65 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRco77c8Vcb4B8LZIdk:-NRdIhvg2cy8PAXZvkdV:b-hz85cp) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/web/services.py#L65)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

proposal_service > data_service
</blockquote></details>

I believe you mean in the comment
___
*[`saltapi/web/api/proposals.py` line 556 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcodHPDkewf2OHbW8N:-NRdIrs90qfwdWchWTJr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/web/api/proposals.py#L556)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`request-data` rather than `request-observations`.
</blockquote></details>

Done.
___
*[`saltapi [...]

2023-03-29 10:13 UTC, hettlage requested changes
> Reviewed 6 of 10 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207)* status: all files reviewed, 19 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/block_repository.py` line 884 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgH11_-B51Ld_n6jXk:-NRgH11bEqxv0JjjkkOP:bw7kqlw) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/block_repository.py#L884)):*
> ```Python
>     ) -> Set[str]:
>         """
>         Get proposal codes for block visit ids.
> ```

Get > Get the

for > for a list of
___
*[`saltapi/repository/block_repository.py` line 887 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgHXUk8VJgIj9GuML8:-NRgHXUk8VJgIj9GuML9:b-4qm1il) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/block_repository.py#L887)):*
> ```Python
>         """
>         proposal_codes = set()
>         for block_visit_id in block_visit_ids:
> ```

This is inefficient, as you make a separate query for every block visit id.
___
*[`saltapi/repository/block_repository.py` line 894 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgHswU3AlZcxtNJPQ4:-NRgHswVAcF85AY_N-DZ:b-2056lx) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/block_repository.py#L894)):*
> ```Python
>             except Exception:
>                 raise ValidationError(
>                     f"Observation id: `{block_visit_id}` doesn't exist"
> ```

f"Observation id does not exist: '{block_visit_id}'"

(Note the single quotes rather than backticks.)
___
*[`saltapi/repository/data_repository.py` line 57 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcg4ne5VQEVghJ2eAq:-NRgIhka77DTRSWBnDXB:bsi8v3l) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L57)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

no longer needed but I wasn't 
</blockquote></details>

Sorry, my bad.
___
*[`saltapi/repository/data_repository.py` line 25 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgq1Nz0YIf-67Otprm:-NRgq1Nz0YIf-67Otprn:b-dlmrlh) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/data_repository.py#L25)):*
> ```Python
>         data_format_id = result.one_or_none()
>         if not data_format_id:
>             raise NotFoundError(f"Couldn't find requested data format `{data_format}`")
> ```

Single quotes should be used rather than backticks.
___
*[`saltapi/repository/data_repository.py` line 42 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgmEI76aLQtKGg9_RL:-NRgmEI76aLQtKGg9_RM:b-28iwhu) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/data_repository.py#L42)):*
> ```Python
>         insert_rows = []
>         for data_format in data_formats:
>             data_format_id = self._get_data_format_id(data_format)
> ```

While this works, it might be good to explicitly convert "all 
___
*[`saltapi/repository/data_repository.py` line 63 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgpp4y912z83PwiE_1:-NRgpp4y912z83PwiE_2:b-dlmrlh) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/data_repository.py#L63)):*
> ```Python
>                 )
>             else:
>                 raise ValidationError(f"Data format `{data_format}` is not supported.")
> ```

Single quotes should be used rather than backticks.
___
*[`saltapi/repository/proposal_repository.py` line 2380 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgJlidCl2lGIpXlW5P:-NRgJlidCl2lGIpXlW5Q:bgyiyq1) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/proposal_repository.py#L2380)):*
> ```Python
>     def get_proposal_code_id(self, proposal_code: str) -> int:
>         """
>         Returns the proposal code id of a proposal code
> ```

Returns > Return

Full stop missing.
___
*[`saltapi/service/permission_service.py` line 498 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgLWxN8Rvaob4f5KZ9:-NRgLWxN8Rvaob4f5KZA:bfc4xxl) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/service/permission_service.py#L498)):*
> ```Python
>         ]
>         self.check_role(user.username, roles, proposal_code)
>         if not observation_ids:
> ```

I don't think the check should be done here, as it is not permission related.
___
*[`saltapi/service/permission_service.py` line 503 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgK9vE-BkJpot8FCPG:-NRgK4zcBgXoCw1zTCMJ:b-4w2zxb) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/service/permission_service.py#L503)):*
> ```Python
>             observation_ids
>         )
>         print(proposal_codes, observation_ids)
> ```

Unnecessary print statement.
___
*[`saltapi/service/permission_service.py` line 504 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgNMOZ50AgPopksQUH:-NRgNMOZ50AgPopksQUI:b-hqexz9) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/service/permission_service.py#L504)):*
> ```Python
>         )
>         print(proposal_codes, observation_ids)
>         if not proposal_codes:
> ```

Maybe add a comment like:

// As this method checks permissions, in principle there should be no validation. However,
// not ruling out observation ids of other proposals would constitute a security loophole,
// and hence we should ensure there are no such observation ids.
___
*[`saltapi/service/permission_service.py` line 505 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgKcGz3P3dPBX-isZJ:-NRgKcGz3P3dPBX-isZK:btneqto) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/service/permission_service.py#L505)):*
> ```Python
>         print(proposal_codes, observation_ids)
>         if not proposal_codes:
>             raise ValidationError(f"Can't request data for other proposals.")
> ```

The error message might be misleading, I think.

But actually there should be no way to get an empty set of proposal code ids.
___
*[`saltapi/service/permission_service.py` line 508 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgL3HN80mR1Gm0kBEY:-NRgL3HN80mR1Gm0kBEZ:b3t0sgl) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/service/permission_service.py#L508)):*
> ```Python
>         for pc in proposal_codes:
>             if pc != proposal_code:
>                 raise ValidationError(f"Can't request data for other proposals.")
> ```

It might be clearer to say:

f"Some of the observation ids belong the the proposal {proposal_code}."
___
*[`saltapi/web/services.py` line 65 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRco77c8Vcb4B8LZIdk:-NRgT0Tq7dHrPEvMuiH0:b-9bl7v0) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/web/services.py#L65)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I believe you mean in the comment
</blockquote></details>

Yes. :-) The underscores in the comment were indeed wrong.
___
*[`saltapi/web/api/proposals.py` line 565 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgTKF6-NGeUmOtbT8N:-NRgTKF6-NGeUmOtbT8O:b-46wfya) ([raw file](https://github.com/saltastroops/salt-api/blob/43 [...]

2023-03-29 19:11 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207)* status: 2 of 11 files reviewed, 19 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/block_repository.py` line 884 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgH11_-B51Ld_n6jXk:-NRh-0af1MODOr_wi4Rr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/block_repository.py#L884)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Get > Get the

for > for a list of
</blockquote></details>

Done.
___
*[`saltapi/repository/block_repository.py` line 887 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgHXUk8VJgIj9GuML8:-NRh-EBu5BBVcUk_nlM4:b-v49epq) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/block_repository.py#L887)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is inefficient, as you make a separate query for every block visit id.
</blockquote></details>

This helps me pinpoint the exact block having a problem.
And also allows me to get block visits that do not exist
___
*[`saltapi/repository/block_repository.py` line 894 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgHswU3AlZcxtNJPQ4:-NRh02Jp8H9_3EnKBGUK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/block_repository.py#L894)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

f"Observation id does not exist: '{block_visit_id}'"

(Note the single quotes rather than backticks.)
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 57 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcg4ne5VQEVghJ2eAq:-NRh0f3K5uPQj3WlZobM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/repository/data_repository.py#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, my bad.
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 25 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgq1Nz0YIf-67Otprm:-NRh0FLf3-X0yJRU5eWZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/data_repository.py#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Single quotes should be used rather than backticks.
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 42 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgmEI76aLQtKGg9_RL:-NRh0dNw442Ycwenj4Op:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/data_repository.py#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

While this works, it might be good to explicitly convert "all 
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 63 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgpp4y912z83PwiE_1:-NRh0kUm3RP8tD7J5e02:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/data_repository.py#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Single quotes should be used rather than backticks.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2380 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgJlidCl2lGIpXlW5P:-NRh0syd0UCiLCrSvfYo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/proposal_repository.py#L2380)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Returns > Return

Full stop missing.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 498 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgLWxN8Rvaob4f5KZ9:-NRh16Aa4elYlCfz2Gec:bq6ttzp) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/service/permission_service.py#L498)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the check should be done here, as it is not permission related.
</blockquote></details>

I believe it is, for the case you are only requesting calibrations.
Or I will have to skip this check and create another one for just the calibration request
___
*[`saltapi/service/permission_service.py` line 503 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgK9vE-BkJpot8FCPG:-NRh29LY67lJ70TMyXWW:b-70scjz) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/service/permission_service.py#L503)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary print statement.
</blockquote></details>

Sorry for this.
___
*[`saltapi/service/permission_service.py` line 504 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgNMOZ50AgPopksQUH:-NRh2_Iz3ctTyJyKyA9f:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/service/permission_service.py#L504)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add a comment like:

// As this method checks permissions, in principle there should be no validation. However,
// not ruling out observation ids of other proposals would constitute a security loophole,
// and hence we should ensure there are no such observation ids.
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 508 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgL3HN80mR1Gm0kBEY:-NRh2voW-mzHhOLXuOMJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/service/permission_service.py#L508)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be clearer to say:

f"Some of the observation ids belong the the proposal {proposal_code}."
</blockquote></details>

Done.
___
*[`saltapi/web/services.py` line 65 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRco77c8Vcb4B8LZIdk:-NRh3EKZ7FgAvRInWOHI:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/saltapi/web/services.py#L65)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes. :-) The underscores in the comment were indeed wrong.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 565 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgTKF6-NGeUmOtbT8N:-NRh3Q_t5Jn_Q7BnMeJi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/web/api/proposals.py#L565)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

which block > which the block
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 660 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgTZjTA93ZH4v7_ZOr:-NRh3XEB47LSnHdrLQeR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/web/schema/proposal.py#L660)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe limit these to ALL and CALIBRATION?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 661 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgmd5QErwDCgwO_JrU:-NRh3hQr5twuxTFxHZJ8:b3pfcc0) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf88 [...]

2023-03-29 19:12 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207)* status: 2 of 11 files reviewed, 19 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 505 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgKcGz3P3dPBX-isZJ:-NRimAv12xk1wmtfJx4C:b594iat) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/service/permission_service.py#L505)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The error message might be misleading, I think.

But actually there should be no way to get an empty set of proposal code ids.


</blockquote></details>

Moved and removed


<!-- Sent from Reviewable.io -->

2023-03-29 19:13 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207)* status: 2 of 11 files reviewed, 19 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/permission_service.py` line 505 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgKcGz3P3dPBX-isZJ:-NRimFVD-goToE3ShCvR:bpiuy2j) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/service/permission_service.py#L505)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Moved and removed
</blockquote></details>

it is possible if you give an invalid block visits ids


<!-- Sent from Reviewable.io -->

2023-03-30 09:45 UTC, hettlage requested changes
> Reviewed 3 of 7 files at r4, 2 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207)* status: all files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/block_repository.py` line 22 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRlbddN9huuurpKB-oI:-NRlbddN9huuurpKB-oJ:b5uskar) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/block_repository.py#L22)):*
> ```Python
>     def __init__(
>         self,
>         target_repository: TargetRepository,
> ```

There are reasons why this change might not be ideal. Can we discuss this?
___
*[`saltapi/repository/data_repository.py` line 49 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRlbqSWD8ZGik6tbzeZ:-NRlbqSWD8ZGik6tbze_:b-xsa8e9) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/saltapi/repository/data_repository.py#L49)):*
> ```Python
>             )
>         except Exception:
>             raise ValidationError()
> ```

I guess you should include the original error message when creating the `ValidationError`.
___
*[`saltapi/repository/data_repository.py` line 51 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRlsW5b8baTjJTxMiqf:-NRlsW5c60I-PnYlP0iU:b-9r7nxk) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/saltapi/repository/data_repository.py#L51)):*
> ```Python
>             raise ValidationError()
>         if block_visits_ids and not proposal_codes:
>             #  As this method checks permissions, in principle there should be no
> ```

This comment suggests the check is done in the permission service.

I think this needs some discussion.
___
*[`saltapi/repository/data_repository.py` line 55 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRlcV-XCpX77E8BYmxR:-NRlcV-XCpX77E8BYmxS:b-ys9qrp) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/saltapi/repository/data_repository.py#L55)):*
> ```Python
>             #  would constitute a security loophole, and hence we should ensure there are
>             #  no such observation ids.
>             raise ValidationError(f"Can't request data for other proposals.")
> ```

I'm not convinced the error messages correct. If there are no proposal codes, wouldn't that mean the block visits are linked to no proposal?
___
*[`saltapi/repository/data_repository.py` line 64 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRld41G9w4Uk26TWjuZ:-NRld41HA5xQ2VshONrJ:bxomv07) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/saltapi/repository/data_repository.py#L64)):*
> ```Python
>         insert_rows = []
>         for data_format in data_formats:
>             data_format_id = self._get_data_format_id("all")
> ```

This line is incorrect, or rather it should be moved into the block handling the `All` case below.
___
*[`saltapi/service/permission_service.py` line 497 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRlsmHj3MXI1uPzJ3JJ:-NRlsmHj3MXI1uPzJ3JK:b9dmqye) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/saltapi/service/permission_service.py#L497)):*
> ```Python
>             Role.PRINCIPAL_CONTACT,
>         ]
>         self.check_role(user.username, roles, proposal_code)
> ```

This method needs some discussion, I think.
___
*[`saltapi/web/schema/proposal.py` line 661 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgmd5QErwDCgwO_JrU:-NRlteft1WZXweQN1uE7:bh33itx) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/web/schema/proposal.py#L661)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

These are the names in the database
</blockquote></details>

Yes. But the API should not mirror the database.
___
*[`tests/integration/proposals/test_request_data.py` line 131 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRltxSY6M0trPlAjnXk:-NRltxSY6M0trPlAjnXl:bvvcimo) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/tests/integration/proposals/test_request_data.py#L131)):*
> ```Python
> ) -> None:
>     authenticate(find_username("Administrator"), client)
>     proposal_code = "2019-2-NOT-CODE-FFF--012-0011"
> ```

Why did you change this?
___
*[`tests/integration/proposals/test_request_observations.py` line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRcrnVX7oqkTWV4_keA:-NRltpHR9l-9_daxKnFM:b-6aqbxm) ([raw file](https://github.com/saltastroops/salt-api/blob/986e65714cbde3037b890e0a045057fa55d7d8e6/tests/integration/proposals/test_request_observations.py#L1)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I said it
</blockquote></details>

Sorry...


<!-- Sent from Reviewable.io -->

2023-03-30 12:03 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207)* status: all files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/block_repository.py` line 22 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRlbddN9huuurpKB-oI:-NRmL0u0BtIOI6iuHlqt:b-juksbo) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/repository/block_repository.py#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There are reasons why this change might not be ideal. Can we discuss this?
</blockquote></details>

yes we can
___
*[`saltapi/repository/data_repository.py` line 49 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRlbqSWD8ZGik6tbzeZ:-NRmLePG9mSM56pBaGct:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/saltapi/repository/data_repository.py#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess you should include the original error message when creating the `ValidationError`.
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 51 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRlsW5b8baTjJTxMiqf:-NRmMPDqC9Wh03tbpCv2:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/saltapi/repository/data_repository.py#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This comment suggests the check is done in the permission service.

I think this needs some discussion.
</blockquote></details>

Done.
___
*[`saltapi/repository/data_repository.py` line 55 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRlcV-XCpX77E8BYmxR:-NRmMU1x60X7DDOMAlh7:b85teu4) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/saltapi/repository/data_repository.py#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced the error messages correct. If there are no proposal codes, wouldn't that mean the block visits are linked to no proposal?
</blockquote></details>

removed tests are passing any way
___
*[`saltapi/repository/data_repository.py` line 64 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRld41G9w4Uk26TWjuZ:-NRmOg1c9_Hyy-SgalrQ:b-7mmp82) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/saltapi/repository/data_repository.py#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This line is incorrect, or rather it should be moved into the block handling the `All` case below.
</blockquote></details>

moved
___
*[`saltapi/service/permission_service.py` line 497 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRlsmHj3MXI1uPzJ3JJ:-NRmOiRA3nj658eZx2Oc:b-ulnnac) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/saltapi/service/permission_service.py#L497)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This method needs some discussion, I think.
</blockquote></details>

yes we can discuss
___
*[`saltapi/web/schema/proposal.py` line 661 at r3](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRgmd5QErwDCgwO_JrU:-NRm9G8BBqjCYx1rPt_S:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/4384f1087df70daaf884a9cd375e74e0610b9c2d/saltapi/web/schema/proposal.py#L661)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes. But the API should not mirror the database.
</blockquote></details>

fixed
___
*[`tests/integration/proposals/test_request_data.py` line 131 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRltxSY6M0trPlAjnXk:-NRmKw5k2S-z333nE_KC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/tests/integration/proposals/test_request_data.py#L131)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why did you change this?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-31 07:58 UTC, hettlage requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207)* status: all files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/data_repository.py` line 45 at r7](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRq_hG021s2du8LVB18:-NRq_hG021s2du8LVB19:bw98yjy) ([raw file](https://github.com/saltastroops/salt-api/blob/cbba0f1b909d0afce5bcaf8ad78385ef2cf0f88f/saltapi/repository/data_repository.py#L45)):*
> ```Python
>                 proposal_code
>             )
>         except Exception:
> ```

Shouldn't the caught exception jut be a NotFound one?
___
*[`saltapi/repository/data_repository.py` line 51 at r7](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRq_wO61yaVik0F5GPT:-NRq_wO61yaVik0F5GPU:b-1mdbgs) ([raw file](https://github.com/saltastroops/salt-api/blob/cbba0f1b909d0afce5bcaf8ad78385ef2cf0f88f/saltapi/repository/data_repository.py#L51)):*
> ```Python
>                 block_visits_ids
>             )
>         except Exception:
> ```

`Exception` is too broad, at least for the error message you pass on.


<!-- Sent from Reviewable.io -->

2023-03-31 17:07 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207)* status: all files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/data_repository.py` line 45 at r7](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRq_hG021s2du8LVB18:-NRscXoQ79FJwB3FAQT3:b-886gsx) ([raw file](https://github.com/saltastroops/salt-api/blob/cbba0f1b909d0afce5bcaf8ad78385ef2cf0f88f/saltapi/repository/data_repository.py#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't the caught exception jut be a NotFound one?
</blockquote></details>

Fixed
___
*[`saltapi/repository/data_repository.py` line 51 at r7](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRq_wO61yaVik0F5GPT:-NRsca1h1FT03dGFL7un:b2zwdu8) ([raw file](https://github.com/saltastroops/salt-api/blob/cbba0f1b909d0afce5bcaf8ad78385ef2cf0f88f/saltapi/repository/data_repository.py#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`Exception` is too broad, at least for the error message you pass on.
</blockquote></details>

not used anymore
___
*[`saltapi/service/permission_service.py` line 497 at r6](https://reviewable.io/reviews/saltastroops/salt-api/207#-NRlsmHj3MXI1uPzJ3JJ:-NRscfq4ANYF8vdfS59d:b-886gsx) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f1ad9bf207ec43445bfcf63ed32ebc6fc5ebe8/saltapi/service/permission_service.py#L497)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

yes we can discuss
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-03-31 17:10 UTC, Eb-Zeero reviewed
I there is a wording issue please you can fix it on my behalf :)

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207#-:-NRsdIkoEaMceqer6Gvu:b-x3wre1)* status: 5 of 11 files reviewed, 5 unresolved discussions (waiting on @hettlage)



<!-- Sent from Reviewable.io -->

2023-04-04 09:54 UTC, hettlage approved these changes
> Reviewed 6 of 6 files at r8, 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/207)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2023-04-04 10:08 UTC, merged