Update user details
saltastroops/salt-api pull request #242
Opened 2023-08-10 07:50 UTC by mofokeng-chaka

2023-08-15 08:00 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/242)* status: all files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`saltapi/repository/user_repository.py` line 287 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs7Z7r1lGrsyeAe7Zu:-Nbs7Z7s9xlQrM3mfpjW:byhb8ph) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L287)):*
> ```Python
>         Returns the new user details of a user.
> 
>         If the given user update has a non-None value for a property, that value should
> ```

This sentence doesn't seem to make sense...
___
*[`saltapi/repository/user_repository.py` line 291 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs7vYM7YW8jApR0s7t:-Nbs7vYM7YW8jApR0s7u:b-rfnf04) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L291)):*
> ```Python
>         """
>         user = self.get(user_id)
>         return UserUpdate(
> ```

I see two problems here:

1. The password shouldn't be passed around unless necessary.
2. No classes from the service level (such as `UserUpdate` should be used on the repository level.
___
*[`saltapi/repository/user_repository.py` line 641 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs8zEq9JHWF92XyDBb:-Nbs8zEq9JHWF92XyDBc:b-s77qt4) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L641)):*
> ```Python
> 
>         except IntegrityError:
>             raise NotFoundError(f"No such user id: {user_id}")
> ```

This is potentially misleading, as the problem might also be that the email exists already.
___
*[`saltapi/repository/user_repository.py` line 982 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs9UJCBArKxIUDu5Yn:-Nbs9UJCBArKxIUDu5Yo:b-mtefw8) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L982)):*
> ```Python
>             )
>         except IntegrityError:
>             raise NotFoundError(f"No such user id: {pipt_user_id}")
> ```

Are you sure therefore no other possible integrity errors?
___
*[`saltapi/service/user.py` line 80 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsAztz-gLv0wYbRdyU:-NbsAzu-2GjPX9CwvYW9:b55x5t0) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/service/user.py#L80)):*
> ```Python
>     family_name: str
>     email: str
>     alternative_emails: List[str]
> ```

Is the `alternative_emails` prvopertybactually used for anything?
___
*[`saltapi/service/user_service.py` line 126 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsCNid-IngHi37dh1X:-NbsCNid-IngHi37dh1Y:b-t85lu1) ([raw file](https://github.com/saltastroops/salt-api/blob/8b36951434ff4feb13d86235c3f48afd4f6d96f8/saltapi/service/user_service.py#L126)):*
> ```Python
> 
>     def update_user(self, user_id: int, user: UserUpdate) -> None:
>         if user.username and self._does_user_exist(user.username):
> ```

You probably want this check somewhere, though, even if it is at the repository level.
___
*[`saltapi/web/schema/user.py` line 108 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsBMXfBkLctRMcHID9:-NbsBMXfBkLctRMcHIDA:bnbnvrb) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/web/schema/user.py#L108)):*
> ```Python
>     New user details.
> 
>     A None value means that the existing value should be kept.
> ```

This comment is correct only for the password.
___
*[`tests/integration/users/test_patch_user.py` line 155 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsBgGJAAtipdPz0G4f:-NbsBgGJAAtipdPz0G4g:b-3m2uln) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/tests/integration/users/test_patch_user.py#L155)):*
> ```Python
>     other_user_id = 1593
>     authenticate(find_username("Administrator"), client)
>     user_update = _patch_data("Xola", "Ndaliso", "xola.ndaliso@gmail.com")
> ```

Maybe don't include thus email address, unless you've asked Xola?
___
*[`tests/repository/test_user_repository.py` line 240 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsC1VjESvOZJQwsnvO:-NbsC1Vk8zhYJCA2pMig:b-5bsw71) ([raw file](https://github.com/saltastroops/salt-api/blob/8b36951434ff4feb13d86235c3f48afd4f6d96f8/tests/repository/test_user_repository.py#L240)):*
> ```Python
> 
> 
> def test_patch_cannot_use_existing_username(db_connection: Connection) -> None:
> ```

How about repurposing this test into "test_patch_cannot_use_existing_email"?


<!-- Sent from Reviewable.io -->

2023-08-15 12:14 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/242)* status: all files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/repository/user_repository.py` line 287 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs7Z7r1lGrsyeAe7Zu:-NbsMFJb60I79Jm4KaIw:b-yzhmmd) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L287)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This sentence doesn't seem to make sense...
</blockquote></details>

I have updated it accordingly
___
*[`saltapi/repository/user_repository.py` line 291 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs7vYM7YW8jApR0s7t:-NbsMY8P-881Ea6SRRXP:b-n9ucf2) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L291)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I see two problems here:

1. The password shouldn't be passed around unless necessary.
2. No classes from the service level (such as `UserUpdate` should be used on the repository level.
</blockquote></details>

I have updated the code accordingly.
___
*[`saltapi/repository/user_repository.py` line 641 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs8zEq9JHWF92XyDBb:-NbsjOmT24a6ip4QBMFd:b-aim692) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L641)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is potentially misleading, as the problem might also be that the email exists already.
</blockquote></details>

I have not handled the issue of an existing email.
___
*[`saltapi/repository/user_repository.py` line 982 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs9UJCBArKxIUDu5Yn:-NbsjUCu0BIhdzkUUWqg:b-ziwfs) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L982)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are you sure therefore no other possible integrity errors?
</blockquote></details>

I have now properly handled errors handled
___
*[`saltapi/service/user.py` line 80 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsAztz-gLv0wYbRdyU:-NbsOZFs1TJWt6HBdow6:b62x9ac) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/service/user.py#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is the `alternative_emails` prvopertybactually used for anything?
</blockquote></details>

I think this comment is a separate issue and needs a new PR, because the schema is being used for registering a user not updating a user. 
___
*[`saltapi/service/user_service.py` line 126 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsCNid-IngHi37dh1X:-Nbsja_h2lSgxrZkHrbz:b70vsk1) ([raw file](https://github.com/saltastroops/salt-api/blob/8b36951434ff4feb13d86235c3f48afd4f6d96f8/saltapi/service/user_service.py#L126)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You probably want this check somewhere, though, even if it is at the repository level.
</blockquote></details>

The check is being done already in `test_patch_user`
___
*[`saltapi/web/schema/user.py` line 108 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsBMXfBkLctRMcHID9:-NbsOMp9DdXcKKGLK39B:b-pc5vaq) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/web/schema/user.py#L108)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This comment is correct only for the password.
</blockquote></details>

well spotted, thanks! I have updated the comment now.
___
*[`tests/integration/users/test_patch_user.py` line 155 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsBgGJAAtipdPz0G4f:-NbsLPkk5cEzQk9hMiWb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/tests/integration/users/test_patch_user.py#L155)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe don't include thus email address, unless you've asked Xola?
</blockquote></details>

Done.
___
*[`tests/repository/test_user_repository.py` line 240 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsC1VjESvOZJQwsnvO:-NbsjLum7Iu-YUB_gNik:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/8b36951434ff4feb13d86235c3f48afd4f6d96f8/tests/repository/test_user_repository.py#L240)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about repurposing this test into "test_patch_cannot_use_existing_email"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-18 10:46 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/242)* status: all files reviewed, 14 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`saltapi/exceptions_handling.py` line 77 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc77uJK7SAnCRrhqkac:-Nc77uJK7SAnCRrhqkad:b-mr8uwe) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/saltapi/exceptions_handling.py#L77)):*
> ```Python
>         log_message(request.method, request.url, exc)
>         return JSONResponse(
>             status_code=status.HTTP_400_BAD_REQUEST, content={"message": str(exc)}
> ```

This is somewhat dangerous. `ValueError`s might be thrown for all sorts of reasons, and yiu might not want to pass on the error message to the user.
___
*[`saltapi/repository/user_repository.py` line 291 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs7vYM7YW8jApR0s7t:-Nc7Dzz5CG-7f_SMBWAy:b-qv5axi) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L291)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have updated the code accordingly.
</blockquote></details>

You arecstill passing the password, though?
___
*[`saltapi/repository/user_repository.py` line 641 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs8zEq9JHWF92XyDBb:-Nc79kn66l5hmOelTvgK:bvrbhx8) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L641)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have not handled the issue of an existing email.
</blockquote></details>

I guess you mean "now handled" rather than "not handled"?
___
*[`saltapi/repository/user_repository.py` line 982 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs9UJCBArKxIUDu5Yn:-Nc7A2vR4P8akKw5Ff-F:bfezzw7) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L982)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have now properly handled errors handled
</blockquote></details>

Yes - but if you don't handle the error in this method, it should be private only.
___
*[`saltapi/repository/user_repository.py` line 285 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc78dDq-9pfcwU-z-ik:-Nc78dDq-9pfcwU-z-il:bslaaq3) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/saltapi/repository/user_repository.py#L285)):*
> ```Python
>             raise NotFoundError(f"Unknown user id: {user_id}")
> 
>         if self._does_email_exist(user_update["email"]):
> ```

I'd argue that effectively you make an unnecessary database query. `get_by_email` gives you all you need, so `_does_email_exist` is somewhat redundant.
___
*[`saltapi/repository/user_repository.py` line 295 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc798HjD0VMwGi-uqae:-Nc798Hk7TeU635qlOBA:b-euchvc) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/saltapi/repository/user_repository.py#L295)):*
> ```Python
>         self._update_user_details(user_id, user_update)
> 
>         self.update_user_statistic(
> ```

Shouldn't `statistic` rather be `statistics`?
___
*[`saltapi/repository/user_repository.py` line 653 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc79fkQ43P-DVRxzcwF:-Nc79fkQ43P-DVRxzcwG:b-5l9lcs) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/saltapi/repository/user_repository.py#L653)):*
> ```Python
>         )
> 
>         # try:
> ```

I'd suggest to remove the commented out lines.
___
*[`saltapi/service/user.py` line 80 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsAztz-gLv0wYbRdyU:-Nc7EK47321--5mIu5k0:bw63w0l) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/service/user.py#L80)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I think this comment is a separate issue and needs a new PR, because the schema is being used for registering a user not updating a user.
</blockquote></details>

Fair point.
___
*[`saltapi/service/user_service.py` line 126 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsCNid-IngHi37dh1X:-Nc7AfF429RqJwvJbZN5:bxjy3u1) ([raw file](https://github.com/saltastroops/salt-api/blob/8b36951434ff4feb13d86235c3f48afd4f6d96f8/saltapi/service/user_service.py#L126)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

The check is being done already in `test_patch_user`
</blockquote></details>

Why do I have the feeling that neither my comment nor your reply make perfect sense? *Scratching head*
___
*[`saltapi/web/schema/user.py` line 106 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7BWAd-1hyPm1G7Gz9:-Nc7BWAd-1hyPm1G7GzA:b-mg8o0r) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/saltapi/web/schema/user.py#L106)):*
> ```Python
> class UserUpdate(UserStatistics):
>     """
>     Update user details.
> ```

Maybe better something like:

Details for updating a user
___
*[`tests/integration/users/test_patch_user.py` line 131 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7Bqyk72YgXV--iI7N:-Nc7Bqyk72YgXV--iI7O:b-84mcii) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/tests/integration/users/test_patch_user.py#L131)):*
> ```Python
> 
> 
> def test_patch_user_should_be_idempotent(client: TestClient) -> None:
> ```

Why did you remove the test that user updates are idempotent?
___
*[`tests/repository/test_user_repository.py` line 165 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7DIyu41fSJV060DK4:-Nc7DIyu41fSJV060DK5:b-irfwb4) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/tests/repository/test_user_repository.py#L165)):*
> ```Python
>     new_family_name = "Motaung"
>     new_given_name = "Thato"
>     new_email = "motaung.thato@gmail.com"
> ```

Maybe rather use `@example.com`?
___
*[`tests/repository/test_user_repository.py` line 185 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7CTy6BFIK9PSnR6hZ:-Nc7CTy6BFIK9PSnR6h_:b-wuxmg6) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/tests/repository/test_user_repository.py#L185)):*
> ```Python
>     assert new_user_details.email == new_email
> 
>     old_user_update = {
> ```

`user_update` might be more intuitive than `old+user_update`, as the update isn't "old" really?
___
*[`tests/repository/test_user_repository.py` line 201 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7CobD-17fvOSFv9xr:-Nc7CobD-17fvOSFv9xs:b5xhp9d) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/tests/repository/test_user_repository.py#L201)):*
> ```Python
>     assert new_user_details.family_name == old_user_details.family_name
>     assert new_user_details.given_name == old_user_details.given_name
>     assert new_user_details.email == old_user_details.email
> ```

What about the other properties? You don't test that the user statistics can be updated?
___
*[`tests/repository/test_user_repository.py` line 224 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7Dj-N9bC2a1OIV9Ch:-Nc7Dj-O6IT23GAbOJ2u:bxgu9eb) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/tests/repository/t [...]

2023-08-21 10:40 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/242)* status: all files reviewed, 14 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/exceptions_handling.py` line 77 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc77uJK7SAnCRrhqkac:-NcLxoWe499BThJnVXtN:be1hjrw) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/saltapi/exceptions_handling.py#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is somewhat dangerous. `ValueError`s might be thrown for all sorts of reasons, and yiu might not want to pass on the error message to the user.
</blockquote></details>

I see your point, I have updated the error message value used.
___
*[`saltapi/repository/user_repository.py` line 291 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs7vYM7YW8jApR0s7t:-NcM-ucwDt1sVdsugkZg:b-om5y97) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L291)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You arecstill passing the password, though?
</blockquote></details>

The password is not being passed now.
___
*[`saltapi/repository/user_repository.py` line 641 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nbs8zEq9JHWF92XyDBb:-NcM0Z8R7RxBN9_k-AAs:bb77ucv) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/repository/user_repository.py#L641)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess you mean "now handled" rather than "not handled"?
</blockquote></details>

Yep.
___
*[`saltapi/repository/user_repository.py` line 285 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc78dDq-9pfcwU-z-ik:-NcLynCo5OSI8g5kM69B:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/saltapi/repository/user_repository.py#L285)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd argue that effectively you make an unnecessary database query. `get_by_email` gives you all you need, so `_does_email_exist` is somewhat redundant.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 295 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc798HjD0VMwGi-uqae:-NcLz6i_1WYPgPjcKZCX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/saltapi/repository/user_repository.py#L295)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't `statistic` rather be `statistics`?
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 653 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc79fkQ43P-DVRxzcwF:-NcM0T8YEmzGKnrAd1nX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/saltapi/repository/user_repository.py#L653)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to remove the commented out lines.
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 80 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsAztz-gLv0wYbRdyU:-NcM13pY1UZWolBC4zZp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/saltapi/service/user.py#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Fair point.
</blockquote></details>

Done.
___
*[`saltapi/service/user_service.py` line 126 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-NbsCNid-IngHi37dh1X:-NcM5E_F13YMafy_ueO6:bvv61eb) ([raw file](https://github.com/saltastroops/salt-api/blob/8b36951434ff4feb13d86235c3f48afd4f6d96f8/saltapi/service/user_service.py#L126)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do I have the feeling that neither my comment nor your reply make perfect sense? *Scratching head*
</blockquote></details>

As per our discussion, this comment should be ignored.
___
*[`saltapi/web/schema/user.py` line 106 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7BWAd-1hyPm1G7Gz9:-NcM1Kzr24sL4RmPsd8y:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/saltapi/web/schema/user.py#L106)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better something like:

Details for updating a user
</blockquote></details>

Done.
___
*[`tests/integration/users/test_patch_user.py` line 131 at r1](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7Bqyk72YgXV--iI7N:-NcM42_lCp8_nWHRFGkx:b8iaznh) ([raw file](https://github.com/saltastroops/salt-api/blob/89ea121ece90f3b7e4050596b73a7b567d90412c/tests/integration/users/test_patch_user.py#L131)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why did you remove the test that user updates are idempotent?
</blockquote></details>

I don't remember the reason why, I have added it back.
___
*[`tests/repository/test_user_repository.py` line 165 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7DIyu41fSJV060DK4:-NcM1a2LB6efvyCgrApi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/tests/repository/test_user_repository.py#L165)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe rather use `@example.com`?
</blockquote></details>

Done.
___
*[`tests/repository/test_user_repository.py` line 185 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7CTy6BFIK9PSnR6hZ:-NcM21f-1DYV8w8iKxMK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/tests/repository/test_user_repository.py#L185)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`user_update` might be more intuitive than `old+user_update`, as the update isn't "old" really?
</blockquote></details>

Done.
___
*[`tests/repository/test_user_repository.py` line 201 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7CobD-17fvOSFv9xr:-NcMf4o033vJKHNrXB9I:bn6vx7a) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/tests/repository/test_user_repository.py#L201)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about the other properties? You don't test that the user statistics can be updated?
</blockquote></details>

I have now included those checks in the test.
___
*[`tests/repository/test_user_repository.py` line 224 at r2](https://reviewable.io/reviews/saltastroops/salt-api/242#-Nc7Dj-N9bC2a1OIV9Ch:-NcM5ArzCDPCI017_5xt:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b9702f4565c0ab653af11cc36b5ac126788ca001/tests/repository/test_user_repository.py#L224)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe also check the error message?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-21 12:59 UTC, hettlage requested changes
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/242)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`saltapi/repository/user_repository.py` line 279 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN1B-lEtTRL9jOTy2y:-NcN1B-m4s6dpPWcQarL:b-22zreh) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L279)):*
> ```Python
>             user = self.get_by_email(user_update["email"])
>             if user.id != user_id:
>                 raise ValueError(f"The email {user_update['email']} exists already.")
> ```

There is a conundrum here. On the one hand, returning the error message for each and every ValueError would one problematic (so thanks for changing that). However, error messages such as this *should* be returned to the user. So maybe consider using a custom exception type?
___
*[`saltapi/repository/user_repository.py` line 307 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN25yIA_7RQ7Sz7vbd:-NcN25yIA_7RQ7Sz7vbe:b45niba) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L307)):*
> ```Python
>         """
> 
>         new_user_details = self._get_user_statistics(user_id)
> ```

Why do you need both  a `get_user_statistics` and a `_get_user_statistics` method?
___
*[`saltapi/repository/user_repository.py` line 917 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN2gz7813MXgQy5PrK:-NcN2gz7813MXgQy5PrL:b-4mprsx) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L917)):*
> ```Python
>             return self._add_gender(gender)
> 
>     def _get_gender_by_id(self, gender_id: int) -> str:
> ```

Shouldn't you have a single query for getting all the statistics details, rather than making separate queries for the lookup values?
___
*[`saltapi/repository/user_repository.py` line 942 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN3Fhz9Sd5MIDkxUgb:-NcN3Fhz9Sd5MIDkxUgc:bu6xv6u) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L942)):*
> ```Python
>             return self._add_race(race)
> 
>     def _get_race_by_id(self, race_id: int) -> str:
> ```

See previous comment.
___
*[`saltapi/repository/user_repository.py` line 964 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN3IWj9CJiCMUQXmJA:-NcN3IWkCUx1kfW5BrxT:bu6xv6u) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L964)):*
> ```Python
> 
>     def _get_legal_status_by_id(self, legal_status_id: int) -> str:
>         stmt = text(
> ```

See previous comment.
___
*[`saltapi/repository/user_repository.py` line 1016 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN3MbyDUoA14Q1NJL6:-NcN3MbyDUoA14Q1NJL7:bu6xv6u) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L1016)):*
> ```Python
> 
>     def _get_user_statistics(self, user_id: int) -> Dict[str, Any]:
>         stmt = text(
> ```

See previous comment.
___
*[`saltapi/service/user.py` line 91 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN3kaO8lxCh-m9Kibz:-NcN3kaO8lxCh-m9Kic-:b6d5fuq) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/service/user.py#L91)):*
> ```Python
>     family_name: str
>     email: str
>     password: Optional[str]
> ```

Why is the password needed in here?
___
*[`saltapi/service/user_service.py` line 108 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN5xqM9W2fptkRKhgw:-NcN5xqM9W2fptkRKhgx:b-2j388d) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/service/user_service.py#L108)):*
> ```Python
> 
>     def get_user_details(self, user_id: int) -> Dict[str, Any]:
>         user = self.repository.get_user_statistics(user_id)
> ```

There might be a naming issue here; it seems that "details" and "statistics" are used for the same data here?
___
*[`saltapi/web/schema/user.py` line 104 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN6f2X4aQZDjJKX71L:-NcN6f2X4aQZDjJKX71M:bbw7nbn) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/web/schema/user.py#L104)):*
> ```Python
> 
> 
> class UserUpdate(UserStatistics):
> ```

You might argue this is for another issue, perhaps, but UserStatisticas as the base class looks a bit odd to me.
___
*[`tests/integration/users/test_patch_user.py` line 139 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN7ZM61whodJ_S_sbS:-NcN7ZM61whodJ_S_sbT:b-ot7pj2) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/tests/integration/users/test_patch_user.py#L139)):*
> ```Python
>     expected_updated_user_details.update(user_update)
>     del expected_updated_user_details["password"]
>     del expected_updated_user_details["legal_status"]
> ```

Do you really have to delete all of these?
___
*[`tests/repository/test_user_repository.py` line 184 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN9GaPB6M3ZWj8Crhv:-NcN9GaPB6M3ZWj8Crhw:b-bv5d3m) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/tests/repository/test_user_repository.py#L184)):*
> ```Python
>     }
>     user_repository.update(user_id, user_update)
>     new_user_details = user_repository.get(user_id)
> ```

Isn't calling `get` and `get_statistics` somewhat of a duplication?
___
*[`tests/repository/test_user_repository.py` line 240 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN9SxU0Svs8LAJ1ubX:-NcN9SxU0Svs8LAJ1ubY:b8zfvmj) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/tests/repository/test_user_repository.py#L240)):*
> ```Python
>     }
> 
>     with pytest.raises(ValueError) as excinfo:
> ```

There is an easier option: `pytest.raises` accepts a  keyword argument `,atch`a for text to be matched.


<!-- Sent from Reviewable.io -->

2023-08-22 06:46 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/242)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/repository/user_repository.py` line 279 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN1B-lEtTRL9jOTy2y:-NcNJ17g-_-tljijyA0v:b-aidwgv) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L279)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a conundrum here. On the one hand, returning the error message for each and every ValueError would one problematic (so thanks for changing that). However, error messages such as this *should* be returned to the user. So maybe consider using a custom exception type?
</blockquote></details>

Done. I  am using ResourceExistsError exception.
___
*[`saltapi/repository/user_repository.py` line 307 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN25yIA_7RQ7Sz7vbd:-NcO2QGLCsCOUy1uYSWb:bu6vcj8) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L307)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need both  a `get_user_statistics` and a `_get_user_statistics` method?
</blockquote></details>

I don't actually need both :'(, my mistake. I have removed the other method now.
___
*[`saltapi/repository/user_repository.py` line 917 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN2gz7813MXgQy5PrK:-NcNIAmqCXsaDrhT6BxE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L917)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't you have a single query for getting all the statistics details, rather than making separate queries for the lookup values?
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 942 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN3Fhz9Sd5MIDkxUgb:-NcNIC0e5NxCvtnEyazw:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L942)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See previous comment.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 964 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN3IWj9CJiCMUQXmJA:-NcNICQfEdfbrMhL1EX5:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L964)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See previous comment.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1016 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN3MbyDUoA14Q1NJL6:-NcNICxuBezAel1L48KD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/repository/user_repository.py#L1016)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See previous comment.
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 91 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN3kaO8lxCh-m9Kibz:-NcO3_fWCC3GOREcRrNZ:bhyg02) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/service/user.py#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why is the password needed in here?
</blockquote></details>

It is not supposed to be there. I have removed it now.
___
*[`saltapi/service/user_service.py` line 108 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN5xqM9W2fptkRKhgw:-NcO4SWN8_AX2Jjeowos:b-hkoim4) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/service/user_service.py#L108)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There might be a naming issue here; it seems that "details" and "statistics" are used for the same data here?
</blockquote></details>

That's true. I have updated the code to use "details".
___
*[`saltapi/web/schema/user.py` line 104 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN6f2X4aQZDjJKX71L:-NcO5h7z6uS_YaxE_TCJ:b-3mrph1) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/web/schema/user.py#L104)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might argue this is for another issue, perhaps, but UserStatisticas as the base class looks a bit odd to me.
</blockquote></details>

Do you imply removing class UserStatistics and explicitly declaring these attributes in each class?
___
*[`tests/integration/users/test_patch_user.py` line 139 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN7ZM61whodJ_S_sbS:-NcOHcd-EdOlthIJmud6:b-17w27t) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/tests/integration/users/test_patch_user.py#L139)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you really have to delete all of these?
</blockquote></details>

Not all these but i have to delete some properties that are not returned by the update user endpoint.
___
*[`tests/repository/test_user_repository.py` line 184 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN9GaPB6M3ZWj8Crhv:-NcNMWB4E0b2WHQJNF35:b-odrtd1) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/tests/repository/test_user_repository.py#L184)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't calling `get` and `get_statistics` somewhat of a duplication?
</blockquote></details>

That's true, I have updated the code to only use one of them
___
*[`tests/repository/test_user_repository.py` line 240 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN9SxU0Svs8LAJ1ubX:-NcNJTL3CvjMCbW2UIq8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/tests/repository/test_user_repository.py#L240)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is an easier option: `pytest.raises` accepts a  keyword argument `,atch`a for text to be matched.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-25 16:23 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/242)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`saltapi/repository/user_repository.py` line 306 at r4](https://reviewable.io/reviews/saltastroops/salt-api/242#-NchVCcK8rHsTdr9qZ2E:-NchVCcK8rHsTdr9qZ2F:b-sk2n8g) ([raw file](https://github.com/saltastroops/salt-api/blob/842687efb269541dcbe2ce0f99116bd6360eaf07/saltapi/repository/user_repository.py#L306)):*
> ```Python
>     ) -> Dict[str, Any]:
>         """
>         Returns the updated user details of a user.
> ```

Are these really details for an _updated_ user?
___
*[`saltapi/web/schema/user.py` line 104 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN6f2X4aQZDjJKX71L:-NchTyqHEeDCXn66VqOc:b-bxrpm1) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/web/schema/user.py#L104)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Do you imply removing class UserStatistics and explicitly declaring these attributes in each class?
</blockquote></details>

Can't you define a "BaseUserDetails" class, which would include the user statistics and common properties like the name? 


<!-- Sent from Reviewable.io -->

2023-08-28 06:45 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/242)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/repository/user_repository.py` line 306 at r4](https://reviewable.io/reviews/saltastroops/salt-api/242#-NchVCcK8rHsTdr9qZ2E:-NcunzSG94IU6-VDMq2E:bocaae7) ([raw file](https://github.com/saltastroops/salt-api/blob/842687efb269541dcbe2ce0f99116bd6360eaf07/saltapi/repository/user_repository.py#L306)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are these really details for an _updated_ user?
</blockquote></details>

I have updated the docstring now.
___
*[`saltapi/web/schema/user.py` line 104 at r3](https://reviewable.io/reviews/saltastroops/salt-api/242#-NcN6f2X4aQZDjJKX71L:-NcusdfLEsAxCROzPX5Z:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4d3427a3299a76efde9be079622c3697201ef20b/saltapi/web/schema/user.py#L104)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can't you define a "BaseUserDetails" class, which would include the user statistics and common properties like the name?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-28 07:45 UTC, hettlage approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2023-08-28 07:46 UTC, merged