Saving the progress report PDF
saltastroops/salt-api pull request #267
Opened 2024-02-23 12:35 UTC by Eb-Zeero

2024-02-23 14:35 UTC, hettlage requested changes

2024-02-23 14:35 UTC, hettlage commented on saltapi/service/proposal_service.py
> +from typing import Any, Dict, List, Optional, cast, Tuple
The imports from `typing` aren't sorted properly.

2024-02-23 14:35 UTC, hettlage commented on saltapi/service/proposal_service.py
> +    @staticmethod
This method is identical to `save_additional_pdf`, isn't it?

2024-02-26 07:02 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/267)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/proposal_service.py` line 4 at r1](https://reviewable.io/reviews/saltastroops/salt-api/267#gh-1500724700:-NrZC5BcDJraUrRxxOit:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e6dccc2e3710cf9d0913619ce4023047b348dd48/saltapi/service/proposal_service.py#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The imports from `typing` aren't sorted properly.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 269 at r1](https://reviewable.io/reviews/saltastroops/salt-api/267#gh-1500743511:-NrZD9YV9JVkA17J5jcX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/e6dccc2e3710cf9d0913619ce4023047b348dd48/saltapi/service/proposal_service.py#L269)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This method is identical to `save_additional_pdf`, isn't it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-26 07:32 UTC, hettlage requested changes

2024-02-26 07:32 UTC, hettlage commented on saltapi/service/proposal_service.py
> +from typing import Any, cast, Dict, List, Optional, Tuple
This is not sorted correctly according to Ruff; `cast` must come last.

2024-02-26 07:32 UTC, hettlage commented on saltapi/service/proposal_service.py
> +    async def save_progress_report_pdf(
Looking at the code, it doesn't really matter whether the file is a pdf, so you might remove `pdf` from the function name and from the variable names within the function.

2024-02-26 08:00 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/267)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/proposal_service.py` line 4 at r2](https://reviewable.io/reviews/saltastroops/salt-api/267#gh-1502141565:-NrZQM9J9_epIeuyTtl-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/dbdda03b1ce5183c7286d9a0feb512a61632cfdd/saltapi/service/proposal_service.py#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is not sorted correctly according to Ruff; `cast` must come last.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 261 at r2](https://reviewable.io/reviews/saltastroops/salt-api/267#gh-1502143426:-NrZQMzU10vk_Eu8GVwa:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/dbdda03b1ce5183c7286d9a0feb512a61632cfdd/saltapi/service/proposal_service.py#L261)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Looking at the code, it doesn't really matter whether the file is a pdf, so you might remove `pdf` from the function name and from the variable names within the function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-26 10:17 UTC, hettlage requested changes

2024-02-26 10:17 UTC, hettlage commented on saltapi/service/proposal_service.py
> +    async def save_progress_report(
Thanks for dropping the `_pdf`. But now there is another issue: The name `save_progress_report` indicates that you save the progress report. Calling the function `save_progress_report_file` thus might be slightly better.

2024-02-26 12:37 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/267)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/proposal_service.py` line 261 at r3](https://reviewable.io/reviews/saltastroops/salt-api/267#gh-1502355271:-Nr_CTlP6LsKRquC95w_:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cd7858a824d55c4c6c04d066c67423593b9ad599/saltapi/service/proposal_service.py#L261)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thanks for dropping the `_pdf`. But now there is another issue: The name `save_progress_report` indicates that you save the progress report. Calling the function `save_progress_report_file` thus might be slightly better.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-26 12:39 UTC, hettlage approved these changes

2024-02-27 07:11 UTC, merged