Observations endpoints
saltastroops/salt-api pull request #27
Opened 2021-09-16 08:18 UTC by mofokeng-chaka

2021-09-17 11:26 UTC, hettlage requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/27)* status: all files reviewed, 15 unresolved discussions (waiting on @mofokeng-chaka)

___
*[saltapi/service/observations_service.py, line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn3-iu8pdseFay_fnb:-Mjn2osr7Rkc9qLq8xZ1:b-56k0ss) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/service/observations_service.py#L7)):*
> ```Python
> 
> 
> class ObservationService:
> ```

I don't think this should be a separate service; this probably could be included in the blocks service.

Also having both the names observation and block visit is misleading.
___
*[saltapi/service/observations_service.py, line 18 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn3tlt0f88D6JfXGG8:-Mjn3r456WmzEvJ1tVBC:bcsjhyx) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/service/observations_service.py#L18)):*
> ```Python
>         return self.block_repository.get_observations(block_visit_id)
> 
>     def get_observations_status(self, block_visit_id: int) -> BlockVisitStatus:
> ```

observations_status ---> observation_status
___
*[saltapi/service/observations_service.py, line 25 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn44T26tJocAUr_dXp:-Mjn2I--9_JJkoteSgCe:bcsjhyx) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/service/observations_service.py#L25)):*
> ```Python
>         return self.block_repository.get_observations_status(block_visit_id)
> 
>     def update_observations_status(self, block_visit_id: int, status: str) -> None:
> ```

observations_status ---> observation_status
___
*[saltapi/service/observations_service.py, line 27 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn3P_Y5-DpOP69dHrr:-Mjn3P_ZAKvE8fPVSebh:b985voy) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/service/observations_service.py#L27)):*
> ```Python
>     def update_observations_status(self, block_visit_id: int, status: str) -> None:
>         """
>         Set the observation status for a block id.
> ```

block id --> block visit id
___
*[saltapi/service/observations_service.py, line 30 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn4QQj6fbpk5Kw-_bL:-Mjn4QQj6fbpk5Kw-_bM:b9i0qtv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/service/observations_service.py#L30)):*
> ```Python
>         """
> 
>         return self.block_repository.update_observations_status(block_visit_id, status)
> ```

update_observations_status ---> update_observation_status
___
*[saltapi/web/api/observations.py, line 73 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn7cDxAJ5r2Oc7sbHd:-Mjn7cDxAJ5r2Oc7sbHe:b-pcw4km) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/web/api/observations.py#L73)):*
> ```Python
>             ..., title="Block id", description="Unique identifier for a block visit"
>         ),
>         status: BlockVisitStatus = Body(
> ```

Having observation and BlockVisitStatus is a bit misleading
___
*[saltapi/web/api/observations.py, line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn8-z51Wt5_BJ2RjHf:-Mjn8-z6-3XHlRVdHdvw:bfg02tn) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/web/api/observations.py#L78)):*
> ```Python
> ) -> Block:
>     """
>     Updates the status of observations with the given the block visit id.
> ```

Again, the issues of observation vs block_visit turns up... ;-)
___
*[tests/service/test_observation_service.py, line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn8VfZ3DEn1_VmRSui:-Mjn8VfZ3DEn1_VmRSuj:b-tv1ly7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L7)):*
> ```Python
> from saltapi.exceptions import NotFoundError
> from saltapi.repository.block_repository import BlockRepository
> from saltapi.service.observations_service import ObservationService
> ```

The observations_service module should be called observation_module.
___
*[tests/service/test_observation_service.py, line 16 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn8lph3Rzzm40jr2DX:-Mjn8lph3Rzzm40jr2DY:blcpmmy) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L16)):*
> ```Python
>     def get_observations(self, block_visit_id: int) -> List[Dict[str, Any]]:
>         if block_visit_id == BLOCK_VISIT_ID:
>             observations = [
> ```

You should have block visits here, not observation definitions. (Uh , that sounds a bit unclear. I hope you know what I mean.)

Also, there is no need to include all the details.
___
*[tests/service/test_observation_service.py, line 114 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn9dR13g5j_Q-j_Wkc:-Mjn9dR13g5j_Q-j_Wkd:bcsjhyx) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L114)):*
> ```Python
>         raise NotFoundError
> 
>     def get_observations_status(self, block_visit_id: int) -> str:
> ```

observations_status ---> observation_status
___
*[tests/service/test_observation_service.py, line 119 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn9o_X7V4KP5hlWtg8:-Mjn9o_X7V4KP5hlWtg9:bcsjhyx) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L119)):*
> ```Python
>         raise NotFoundError()
> 
>     def update_observations_status(
> ```

observations_status ---> observation_status
___
*[tests/service/test_observation_service.py, line 240 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MjnACJG4cVjDzHaef74:-MjnACJG4cVjDzHaef75:blp691u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L240)):*
> ```Python
> 
> 
> def test_get_observations_status_raises_error_for_wrong_block_id() -> None:
> ```

block_id ---> block_vvisit_id
___
*[tests/service/test_observation_service.py, line 246 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MjnUdg15iVqHC08yGNd:-MjnUdg15iVqHC08yGNe:b7tnodt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L246)):*
> ```Python
> 
> 
> def test_get_observations_status() -> None:
> ```

observations ---> observation
___
*[tests/service/test_observation_service.py, line 258 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MjnUrt77xoHvTFdNPPW:-MjnUrt77xoHvTFdNPPX:b7tnodt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L258)):*
> ```Python
>     assert old_status != "Accepted"
> 
>     observations_service.update_observations_status(BLOCK_VISIT_ID, "Accepted")
> ```

observations ---> observation
___
*[tests/service/test_observation_service.py, line 264 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MjnUy4U1eV1V3IGPd9h:-MjnUy4U1eV1V3IGPd9i:b7tnodt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L264)):*
> ```Python
> 
> 
> def test_update_observations_status_raises_error_for_wrong_block_id() -> None:
 [...]

2021-09-21 09:01 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/27)* status: 0 of 8 files reviewed, 15 unresolved discussions (waiting on @hettlage)

___
*[saltapi/service/observations_service.py, line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn3-iu8pdseFay_fnb:-Mk0uFB550WzFejE3x-r:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/service/observations_service.py#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this should be a separate service; this probably could be included in the blocks service.

Also having both the names observation and block visit is misleading.
</blockquote></details>

Done.
___
*[saltapi/service/observations_service.py, line 18 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn3tlt0f88D6JfXGG8:-Mk0uQdO1TakRcs22FeJ:b-2bcn53) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/service/observations_service.py#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

observations_status ---> observation_status
</blockquote></details>

Now changed to block visit status, as per our discussion.
___
*[saltapi/service/observations_service.py, line 25 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn44T26tJocAUr_dXp:-Mk0uRDw8Q24BEVn-oX7:b-tabvu0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/service/observations_service.py#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

observations_status ---> observation_status
</blockquote></details>

See my previous comment
___
*[saltapi/service/observations_service.py, line 27 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn3P_Y5-DpOP69dHrr:-Mk0uTzWDFkgCZG_KRWn:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/service/observations_service.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

block id --> block visit id
</blockquote></details>

Done.
___
*[saltapi/service/observations_service.py, line 30 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn4QQj6fbpk5Kw-_bL:-Mk0uUnR5X1K87H1tyG2:b-kky2me) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/service/observations_service.py#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

update_observations_status ---> update_observation_status
</blockquote></details>

Changed to update_block_visit_status
___
*[saltapi/web/api/observations.py, line 73 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn7cDxAJ5r2Oc7sbHd:-Mk1Axkd3o81tLPI6Cc9:b-hw3jre) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/web/api/observations.py#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Having observation and BlockVisitStatus is a bit misleading
</blockquote></details>

After our discussion, I stuck with BlockVisitStatus
___
*[saltapi/web/api/observations.py, line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn8-z51Wt5_BJ2RjHf:-Mk1BDh29DbFO02Ny4iJ:b-5m00rd) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/4c20ed70b0cdf081e1bb680380063a9f516cafc4/saltapi/web/api/observations.py#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Again, the issues of observation vs block_visit turns up... ;-)
</blockquote></details>

As per our discussion, observation --> block_visit
___
*[tests/service/test_observation_service.py, line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn8VfZ3DEn1_VmRSui:-Mk6YBPf1uBcxwMlJaVU:b-3obo06) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The observations_service module should be called observation_module.
</blockquote></details>

Since I no longer use a separate service for block_visit. I added these tests to the test_block_service code.
___
*[tests/service/test_observation_service.py, line 16 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn8lph3Rzzm40jr2DX:-Mk6YdiA5yNp_hqtZw_u:bafrhc4) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should have block visits here, not observation definitions. (Uh , that sounds a bit unclear. I hope you know what I mean.)

Also, there is no need to include all the details.
</blockquote></details>

It is now clear what you mean, however, I am not sure whether the get_block_visit method returns a list or a dict. Let's discuss
___
*[tests/service/test_observation_service.py, line 114 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn9dR13g5j_Q-j_Wkc:-Mk6ZPh5DspL_i_3zOQK:bbptt8s) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L114)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

observations_status ---> observation_status
</blockquote></details>

changed to block_visit_status
___
*[tests/service/test_observation_service.py, line 119 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-Mjn9o_X7V4KP5hlWtg8:-Mk6ZXywB8rxmNDNzqkR:biqa0g1) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

observations_status ---> observation_status
</blockquote></details>

changed to observation_status --> block_visit_status
___
*[tests/service/test_observation_service.py, line 240 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MjnACJG4cVjDzHaef74:-Mk6Za5eE2BhF0HzHD2J:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L240)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

block_id ---> block_vvisit_id
</blockquote></details>

Done.
___
*[tests/service/test_observation_service.py, line 246 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MjnUdg15iVqHC08yGNd:-Mk6Zahz-hNhylpRcmdu:b-3qki9u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L246)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

observations ---> observation
</blockquote></details>

observation --> block_visit
___
*[tests/service/test_observation_service.py, line 258 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MjnUrt77xoHvTFdNPPW:-Mk6Zfo-AiiHFrGXGAHv:b-3qki9u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L258)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

observations ---> observation
</blockquote></details>

observation --> block_visit
___
*[tests/service/test_observation_service.py, line 264 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MjnUy4U1eV1V3IGPd9h:-Mk6ZgMF9Od_Rer5QRha:b-3qki9u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/07bdfd4650e3c8c611ec0efb5db584a6530dfa58/tests/service/test_observation_service.py#L264)):*
<details><summa [...]

2021-09-22 08:35 UTC, hettlage requested changes
Integration tests should be added

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-:-MkBdKix91Vmvn3fYakH:bg79mg0)* status: all files reviewed, 13 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[saltapi/repository/block_repository.py, line 188 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBagky8ArLjlujdzv1:-MkBagky8ArLjlujdzv2:b-5nxqyw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/repository/block_repository.py#L188)):*
> ```Python
>     JOIN BlockVisitStatus BVS ON BV.BlockVisitStatus_Id = BVS.BlockVisitStatus_Id
> WHERE BV.BlockVisit_Id = :block_visit_id
>   AND BVS.BlockVisitStatus IN ('Accepted', 'Rejected', 'In queue');
> ```

Block visits with status Deleted should be treated as if they don't exist.
___
*[saltapi/repository/block_repository.py, line 209 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBaUp2A21XRZbpAEVe:-MkBaUp2A21XRZbpAEVf:b-5nxqyw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/repository/block_repository.py#L209)):*
> ```Python
> FROM BlockVisitStatus BVS
> JOIN BlockVisit BV ON BVS.BlockVisitStatus_Id = BV.BlockVisitStatus_Id
> WHERE BV.BlockVisit_Id = :block_visit_id;
> ```

Block visits with status Deleted should be treated as if they don't exist.
___
*[saltapi/repository/block_repository.py, line 225 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBbh_QB5MjKYeCh64k:-MkBbh_QB5MjKYeCh64l:b-5nxqyw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/repository/block_repository.py#L225)):*
> ```Python
>                                 FROM BlockVisitStatus BVS
>                                 WHERE BVS.BlockVisitStatus = :status)
> WHERE BV.BlockVisit_Id = :block_visit_id;
> ```

Block visits with status Deleted should be treated as if they don't exist.
___
*[saltapi/web/api/observations.py, line 40 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBSG9hEo-4fL2Zeng5:-MkBSG9hEo-4fL2Zeng6:b3f5lnm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/web/api/observations.py#L40)):*
> ```Python
>     with UnitOfWork() as unit_of_work:
>         block_repository = create_block_repository(unit_of_work.connection)
>         block_service = BlockService(block_repository)
> ```

Permission check missing
___
*[saltapi/web/api/observations.py, line 66 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBRggwCyi4LErJ3Nyr:-MkBRggwCyi4LErJ3Nys:b3f5lnm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/web/api/observations.py#L66)):*
> ```Python
> 
>     with UnitOfWork() as unit_of_work:
>         block_repository = create_block_repository(unit_of_work.connection)
> ```

Permission check missing
___
*[saltapi/web/api/observations.py, line 89 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBSsBUCWVRRZ9YuBBT:-MkBSsBUCWVRRZ9YuBBU:bel69i9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/web/api/observations.py#L89)):*
> ```Python
>         permission_service = PermissionService(user_repository=UserRepository(unit_of_work.connection),
>                                                proposal_repository=ProposalRepository(unit_of_work.connection))
>         if permission_service.may_update_proposal_status(user):
> ```

I think there should be a separate permission (may_update_block_visit).
___
*[tests/repository/test_block_repository.py, line 449 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBZuS99t4xnwz6ylIK:-MkBZuSA4U0ptFtYDEWp:bp98qac) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/tests/repository/test_block_repository.py#L449)):*
> ```Python
>     instrument_repository = InstrumentRepository(dbconnection)
>     block_repository = BlockRepository(target_repository, instrument_repository, dbconnection)
>     with pytest.raises(NoResultFound):
> ```

The method should rather raise a NotFoundError, not a SQLAlchemy exception.


<!-- Sent from Reviewable.io -->

2021-09-28 06:54 UTC, mofokeng-chaka reviewed
Currently working on the integration tests.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-:-MkbaxjwEy8fQxvb8mui:bb873mj)* status: 3 of 10 files reviewed, 13 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/block_repository.py, line 188 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBagky8ArLjlujdzv1:-Mkb_lviCM8V3am7D6fA:b-82q0ub) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/repository/block_repository.py#L188)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Block visits with status Deleted should be treated as if they don't exist.
</blockquote></details>

It's not clear to me what you suggesting, I think the last line of the query does this already. I switched the IN clause to NOT IN, is that what you meant?
___
*[saltapi/repository/block_repository.py, line 209 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBaUp2A21XRZbpAEVe:-Mkb_nWNEN-nQR6NFk-r:b-apayz0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/repository/block_repository.py#L209)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Block visits with status Deleted should be treated as if they don't exist.
</blockquote></details>

See my comment above.
___
*[saltapi/repository/block_repository.py, line 225 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBbh_QB5MjKYeCh64k:-Mkb_nwi0RbU6YoYXIY9:b-l2ztg2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/repository/block_repository.py#L225)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Block visits with status Deleted should be treated as if they don't exist.
</blockquote></details>

See my comment on your first comment.
___
*[tests/repository/test_block_repository.py, line 449 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBZuS99t4xnwz6ylIK:-Mkbawpc6M-wyyIwP-jZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/tests/repository/test_block_repository.py#L449)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The method should rather raise a NotFoundError, not a SQLAlchemy exception.
</blockquote></details>

Done.
___
*[saltapi/web/api/observations.py, line 40 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBSG9hEo-4fL2Zeng5:-MkbarP5CO9Oj8Px11ao:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/web/api/observations.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Permission check missing
</blockquote></details>

Done.
___
*[saltapi/web/api/observations.py, line 66 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBRggwCyi4LErJ3Nyr:-MkbarmB2izeWVoi5S-W:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/web/api/observations.py#L66)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Permission check missing
</blockquote></details>

Done.
___
*[saltapi/web/api/observations.py, line 89 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBSsBUCWVRRZ9YuBBT:-MkbauyW7Di_ek8rx5b2:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/web/api/observations.py#L89)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think there should be a separate permission (may_update_block_visit).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-07 09:32 UTC, hettlage requested changes
> Reviewed 3 of 6 files at r3, 1 of 4 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/27)* status: all files reviewed, 10 unresolved discussions (waiting on @mofokeng-chaka)

___
*[saltapi/repository/block_repository.py, line 188 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBagky8ArLjlujdzv1:-MlOqxP8Eq6HLMxHPCun:boj5mg2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/repository/block_repository.py#L188)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

It's not clear to me what you suggesting, I think the last line of the query does this already. I switched the IN clause to NOT IN, is that what you meant?
</blockquote></details>

I guess I just didn't make sense... :-/
___
*[saltapi/repository/block_repository.py, line 233 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOt9ki3-st3GFjylEB:-MlOreWv4TZx1kb2_U0D:b-rca5z6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/repository/block_repository.py#L233)):*
> ```Python
>                                 FROM BlockVisitStatus BVS
>                                 WHERE BVS.BlockVisitStatus = :status)
> WHERE BV.BlockVisit_Id = :block_visit_id;
> ```

Given that deleted blocks are ignored elsewhere, you might consider adding the following condition to the WHERE condition:

```BV.BlockVisitStatus_Id NOT IN (SELECT BVS2.BlockVisitStatus_Id FROM BlockVisitStatus AS BVS2 WHERE BVS2.BlockVisitStatus != 'Deleted');```
___
*[saltapi/service/permission_service.py, line 103 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOiEGRBd1_eFsM8ofL:-MlOiEGSAKO329GW3YOL:bi2stvt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/service/permission_service.py#L103)):*
> ```Python
>         Check whether the user may view a block visit.
> 
>         This is the case if the user is any of the following:
> ```

The comment will be potentially misleading if there are changes to proposal viewing permissions in future. I'd suggest to say:

```This is the case if the user may view the proposal for which the block visit was taken.```

More crucially, the function should take the block visit id, not the proposal code as an argument.
___
*[tests/repository/test_block_repository.py, line 449 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBZuS99t4xnwz6ylIK:-MlOutvIBDzCYpZEwp6Y:b1m9kub) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/tests/repository/test_block_repository.py#L449)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But you are still checking for NoResultFound in the test, if I see this correctly?
___
*[saltapi/web/api/block_visits.py, line 33 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOkVMK-PvrkbT_Ig-5:-MlOkVMK-PvrkbT_Ig-6:b-za1ghz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L33)):*
> ```Python
> 
> @router.get("/{block_visit_id}", summary="Get a block visit", response_model=Dict[str, Any])
> def get_block_visits(
> ```

get_block_visits ---> get_block_visit
___
*[saltapi/web/api/block_visits.py, line 38 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOkijR6yBojv7st-pN:-MlOkijR6yBojv7st-pO:benru5b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L38)):*
> ```Python
>         ),
>         user: User = Depends(get_current_user),
>         proposal_code: ProposalCode = Query(
> ```

There is no reason for passing the proposal code as a parameter. You should get it from the block visit id.
___
*[saltapi/web/api/block_visits.py, line 43 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOkJgj5JEDECZni9GX:-MlOkJgkAiEoBDOTV96c:b-ko8jno) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L43)):*
> ```Python
>             title="Proposal code",
>         ),
> ) -> Dict[str, Any]:
> ```

Should return the schema type BlockVisit, not a dict.
___
*[saltapi/web/api/block_visits.py, line 54 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlP4QaC5PsGSEuNBvPm:-MlP4QaC5PsGSEuNBvPn:b-1hs4b9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L54)):*
> ```Python
>             permission_service = PermissionService(user_repository=UserRepository(unit_of_work.connection),
>                                                    proposal_repository=ProposalRepository(unit_of_work.connection))
>             if permission_service.may_view_block_visit(user, proposal_code):
> ```

I wonder whether we shouldn't replace the may_... methods of the permission service with check_... methods which raise an exception if permission is denied. What would you think?
___
*[saltapi/web/api/block_visits.py, line 62 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOtcyX9Ff0xzzT6iiy:-MlOtcyX9Ff0xzzT6iiz:bkek1ev) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L62)):*
> ```Python
>             else:
>                 raise HTTPException(status_code=status.HTTP_403_FORBIDDEN)
>     except NotFoundError:
> ```

NotFoundError's should be handled by an error handler (which should exist already, but maybe not in this branch).
___
*[saltapi/web/api/block_visits.py, line 69 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOjBVYCQP8CG7Hbn_R:-MlOjBVYCQP8CG7Hbn_S:benru5b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L69)):*
> ```Python
>             summary="Get the status of a block visit",
>             response_model=BlockVisitStatus)
> def get_block_visit_status(
> ```

There is no reason for passing the proposal code as a parameter. You should get it from the block visit id.


<!-- Sent from Reviewable.io -->

2021-10-07 13:03 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/27)* status: 11 of 18 files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/block_repository.py, line 188 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBagky8ArLjlujdzv1:-MlPq8CM2UBgtaWDTh63:b-rg379v) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/repository/block_repository.py#L188)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess I just didn't make sense... :-/
</blockquote></details>

Is it okay to keep the code as is?
___
*[saltapi/repository/block_repository.py, line 233 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOt9ki3-st3GFjylEB:-MlPXDr825RuYybB_fui:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/repository/block_repository.py#L233)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that deleted blocks are ignored elsewhere, you might consider adding the following condition to the WHERE condition:

```BV.BlockVisitStatus_Id NOT IN (SELECT BVS2.BlockVisitStatus_Id FROM BlockVisitStatus AS BVS2 WHERE BVS2.BlockVisitStatus != 'Deleted');```
</blockquote></details>

Done.
___
*[saltapi/service/permission_service.py, line 103 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOiEGRBd1_eFsM8ofL:-MlPghL4-1yHICUYdOg8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/service/permission_service.py#L103)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The comment will be potentially misleading if there are changes to proposal viewing permissions in future. I'd suggest to say:

```This is the case if the user may view the proposal for which the block visit was taken.```

More crucially, the function should take the block visit id, not the proposal code as an argument.
</blockquote></details>

Done.
___
*[tests/repository/test_block_repository.py, line 449 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBZuS99t4xnwz6ylIK:-MlPeCHL-KmllyLpAb1B:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/tests/repository/test_block_repository.py#L449)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But you are still checking for NoResultFound in the test, if I see this correctly?
</blockquote></details>

Done.
___
*[saltapi/web/api/block_visits.py, line 33 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOkVMK-PvrkbT_Ig-5:-MlPXmK8AKw5E4PMotVK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

get_block_visits ---> get_block_visit
</blockquote></details>

Done.
___
*[saltapi/web/api/block_visits.py, line 38 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOkijR6yBojv7st-pN:-MlPge_s3kFI8YKo-T0F:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is no reason for passing the proposal code as a parameter. You should get it from the block visit id.
</blockquote></details>

Done.
___
*[saltapi/web/api/block_visits.py, line 43 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOkJgj5JEDECZni9GX:-MlPYrKZ9Hhe-DggFiXX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should return the schema type BlockVisit, not a dict.
</blockquote></details>

Done.
___
*[saltapi/web/api/block_visits.py, line 54 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlP4QaC5PsGSEuNBvPm:-MlPgEb25puhAjdRUVgD:bn7ikha) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wonder whether we shouldn't replace the may_... methods of the permission service with check_... methods which raise an exception if permission is denied. What would you think?
</blockquote></details>

I agree with you, it makes more sense to replace may_ with check_ since the method is basically checking whether a user is permitted else it raises an exception
___
*[saltapi/web/api/block_visits.py, line 62 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOtcyX9Ff0xzzT6iiy:-MlPk5Pt9D6ncOFX0Sl0:bjzb3yn) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L62)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

NotFoundError's should be handled by an error handler (which should exist already, but maybe not in this branch).
</blockquote></details>

I tried looking for the error handler in the development directory and could find it or maybe i don't understand what you mean. Can you please put this in simple terms or point me to where the error is handled in the development directory.
___
*[saltapi/web/api/block_visits.py, line 69 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOjBVYCQP8CG7Hbn_R:-MlPkFcu1WqjaOfUWxA-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is no reason for passing the proposal code as a parameter. You should get it from the block visit id.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-07 19:12 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/27)* status: all files reviewed, 12 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[saltapi/repository/block_repository.py, line 188 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBagky8ArLjlujdzv1:-MlR4WTp2SkPme-BVg3q:bj94paa) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/repository/block_repository.py#L188)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Is it okay to keep the code as is?
</blockquote></details>

Yes. :-)
___
*[saltapi/repository/proposal_repository.py, line 199 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlR5dMP8JpfqaG2qxM7:-MlR5dMP8JpfqaG2qxM8:bfngt84) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a7605ead74969250c69b05f7a0fcd595ac7efad/saltapi/repository/proposal_repository.py#L199)):*
> ```Python
>             raise NotFoundError()
> 
>     def _get_proposal_code(self, block_visit_id: int) -> ProposalCode:
> ```

I'm not sure you need two functions here (_get_proposal_code and get_proposal_code); just having get_proposal_code might be sufficient.

However, I'd suggest to rename it to something like get_proposal_code_for_block_visit_id or get_block_visit_proposal_code, and to move it to the block repository.
___
*[saltapi/service/permission_service.py, line 64 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlR5A9F964wIch2NqKX:-MlR5A9F964wIch2NqKY:b-83w1bq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a7605ead74969250c69b05f7a0fcd595ac7efad/saltapi/service/permission_service.py#L64)):*
> ```Python
>         )
> 
>     def may_deactivate_proposal(self, user: User, block_visit_id: int) -> bool:
> ```

Sorry, but here proposal_code was the correct argument.
___
*[tests/conftest.py, line 189 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlR9FrF57vvA0CAURKJ:-MlR9FrF57vvA0CAURKK:bs5wah6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a7605ead74969250c69b05f7a0fcd595ac7efad/tests/conftest.py#L189)):*
> ```Python
> 
> 
> @given("I am not authenticated")
> ```

This is BDD code...
___
*[saltapi/web/api/block_visits.py, line 43 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOkJgj5JEDECZni9GX:-MlR7_fB3G5UyK8uN3wi:b-rx86hi) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L43)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You should return the pydantic type defined in saltapi.web.schema.common -- it needs to be renamed from ExecutedObservation to BlockVisit though...

Also, executed_observations in schema/proposal.py needs got be renamed to block_visits.
___
*[saltapi/web/api/block_visits.py, line 62 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOtcyX9Ff0xzzT6iiy:-MlR8rxk0rmnSNElONjE:b-qokl3j) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L62)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I tried looking for the error handler in the development directory and could find it or maybe i don't understand what you mean. Can you please put this in simple terms or point me to where the error is handled in the development directory.
</blockquote></details>

It's in `main.py`:

```python
@app.exception_handler(NotFoundError)
async def not_found_exception_handler(request: Request, exc: NotFoundError) -> Response:
    return JSONResponse(status_code=404, content={"message": "Not Found"})
```
___
*[saltapi/web/api/block_visits.py, line 13 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlR9P4z9xQCFiuVJWHX:-MlR9P4z9xQCFiuVJWHY:b-4nxzpw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a7605ead74969250c69b05f7a0fcd595ac7efad/saltapi/web/api/block_visits.py#L13)):*
> ```Python
> from saltapi.repository.user_repository import UserRepository
> from saltapi.service.authentication_service import get_current_user
> from saltapi.service.block import BlockVisit
> ```

Unnecessary import (see comment below).


<!-- Sent from Reviewable.io -->

2021-10-07 19:15 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/27)* status: all files reviewed, 8 unresolved discussions (waiting on @mofokeng-chaka)

___
*[saltapi/repository/proposal_repository.py, line 209 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlRA472-U5eGehreBiT:-MlRA472-U5eGehreBiU:bmgq9q1) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a7605ead74969250c69b05f7a0fcd595ac7efad/saltapi/repository/proposal_repository.py#L209)):*
> ```Python
> JOIN Block B on PC.ProposalCode_Id = B.ProposalCode_Id
> JOIN BlockVisit BV on BV.Block_Id = B.Block_Id
> WHERE BV.BlockVisit_Id = :block_visit_id
> ```

It might make sense to explicitly exclude block visits with status "Deleted".


<!-- Sent from Reviewable.io -->

2021-10-08 08:53 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/27)* status: 11 of 21 files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/block_repository.py, line 188 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MkBagky8ArLjlujdzv1:-MlTCdDF3aAJ9gemJjWw:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/f0a0cf6835b866751b4c5599c5c564a942f3419e/saltapi/repository/block_repository.py#L188)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes. :-)
</blockquote></details>

Done.
___
*[saltapi/service/permission_service.py, line 64 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlR5A9F964wIch2NqKX:-MlTGKgCAFL8DhS5WBYe:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a7605ead74969250c69b05f7a0fcd595ac7efad/saltapi/service/permission_service.py#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, but here proposal_code was the correct argument.
</blockquote></details>

Done.
___
*[tests/conftest.py, line 189 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlR9FrF57vvA0CAURKJ:-MlTLgRs-UXRtmhvcdEl:bs5ay04) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a7605ead74969250c69b05f7a0fcd595ac7efad/tests/conftest.py#L189)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is BDD code...
</blockquote></details>

That's true, and I think I will remove the BDD code in the new branch I made for integration tests if that's fine with you.
___
*[saltapi/repository/proposal_repository.py, line 199 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlR5dMP8JpfqaG2qxM7:-MlTETgZ3KITiX92wkh1:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a7605ead74969250c69b05f7a0fcd595ac7efad/saltapi/repository/proposal_repository.py#L199)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure you need two functions here (_get_proposal_code and get_proposal_code); just having get_proposal_code might be sufficient.

However, I'd suggest to rename it to something like get_proposal_code_for_block_visit_id or get_block_visit_proposal_code, and to move it to the block repository.
</blockquote></details>

Done.
___
*[saltapi/repository/proposal_repository.py, line 209 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlRA472-U5eGehreBiT:-MlTEicl3MKJklDmE2R2:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a7605ead74969250c69b05f7a0fcd595ac7efad/saltapi/repository/proposal_repository.py#L209)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might make sense to explicitly exclude block visits with status "Deleted".
</blockquote></details>

Done.
___
*[saltapi/web/api/block_visits.py, line 43 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOkJgj5JEDECZni9GX:-MlTKofk6DkjCSxQvdJY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should return the pydantic type defined in saltapi.web.schema.common -- it needs to be renamed from ExecutedObservation to BlockVisit though...

Also, executed_observations in schema/proposal.py needs got be renamed to block_visits.
</blockquote></details>

Done.
___
*[saltapi/web/api/block_visits.py, line 62 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlOtcyX9Ff0xzzT6iiy:-MlTO-6d9P08zefnKKDq:b-oglosc) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d306b88a7d74d6197e0cbc7ff71e5c57b7472c59/saltapi/web/api/block_visits.py#L62)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It's in `main.py`:

```python
@app.exception_handler(NotFoundError)
async def not_found_exception_handler(request: Request, exc: NotFoundError) -> Response:
    return JSONResponse(status_code=404, content={"message": "Not Found"})
```
</blockquote></details>

Thanks, i have added it.
___
*[saltapi/web/api/block_visits.py, line 13 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlR9P4z9xQCFiuVJWHX:-MlTP3lR0_efNM0s4Gk_:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2a7605ead74969250c69b05f7a0fcd595ac7efad/saltapi/web/api/block_visits.py#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary import (see comment below).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-08 11:09 UTC, hettlage requested changes
> Reviewed 10 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/27)* status: all files reviewed, 18 unresolved discussions (waiting on @mofokeng-chaka)

___
*[saltapi/repository/block_repository.py, line 15 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUSqni57ZAi_OURo_a:-MlUSqni57ZAi_OURo_b:b95s3x6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/repository/block_repository.py#L15)):*
> ```Python
> from saltapi.service.block import Block
> from saltapi.service.proposal import ProposalCode
> from saltapi.web.schema.block import BlockVisitStatus
> ```

I don't think API (read: schema) types should be used in a repository.
___
*[saltapi/repository/block_repository.py, line 178 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUTI-X5tHYXopGhoAK:-MlUTI-X5tHYXopGhoAL:b-22b119) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/repository/block_repository.py#L178)):*
> ```Python
>             raise NotFoundError()
> 
>     def get_block_visit(self, block_visit_id: int) -> BlockVisit:
> ```

See comment above. I'd stick to Dict[str, str].
___
*[saltapi/repository/block_repository.py, line 180 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUTlyGCOFzb01XnxLW:-MlUTlyGCOFzb01XnxLX:bt2f2mt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/repository/block_repository.py#L180)):*
> ```Python
>     def get_block_visit(self, block_visit_id: int) -> BlockVisit:
>         """
>         Return the observations for a block visit id.
> ```

observations ---> block_visits
___
*[saltapi/repository/block_repository.py, line 308 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUUJSx7YRm1w4IBffQ:-MlUUJSyEPrB5aZluCXH:bgsp3qi) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/repository/block_repository.py#L308)):*
> ```Python
>         result = self.connection.execute(stmt, {"block_id": block_id})
>         block_visits = []
>         for row in result:
> ```

I'd suggest to use list comprehension rather than a for loop.
___
*[saltapi/service/block_service.py, line 6 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUUrEI6TlWPEt6FOtK:-MlUUrEI6TlWPEt6FOtL:b95s3x6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/service/block_service.py#L6)):*
> ```Python
> from saltapi.service.block import Block
> from saltapi.web.schema.block import BlockVisitStatus
> from saltapi.web.schema.common import BlockVisit
> ```

I don't think API (read: schema) types should be used in a repository.
___
*[saltapi/service/block_service.py, line 34 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUUu4c9XX-mMSpvqRs:-MlUUu4c9XX-mMSpvqRt:b-2twffm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/service/block_service.py#L34)):*
> ```Python
>         return self.block_repository.update_block_status(block_id, status, reason)
> 
>     def get_block_visit(self, block_visit_id: int) -> BlockVisit:
> ```

See comment above. I'd stick to Dict[str, Any].
___
*[saltapi/web/api/proposals.py, line 399 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUWyU3095VA3EyRZbj:-MlUWyU3095VA3EyRZbk:bt2f2mt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/api/proposals.py#L399)):*
> ```Python
> 
> @router.get(
>     "/{proposal_code}/observations",
> ```

observations ---> block_visits
___
*[saltapi/web/api/proposals.py, line 400 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUX71xEplVjx4PUvKK:-MlUX71xEplVjx4PUvKL:brrvw9i) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/api/proposals.py#L400)):*
> ```Python
> @router.get(
>     "/{proposal_code}/observations",
>     summary="List observations",
> ```

observations ---> block visits
___
*[saltapi/web/api/proposals.py, line 403 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUXBSn1-2A1NfRaiZa:-MlUXBSn1-2A1NfRaiZb:b-pio3rt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/api/proposals.py#L403)):*
> ```Python
>     response_model=List[BlockVisit],
> )
> def get_observations(
> ```

get_observations ---> get_block_visits
___
*[saltapi/web/api/proposals.py, line 423 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUXNff8PIniQyq5QrB:-MlUXNff8PIniQyq5QrC:b6n33ij) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/api/proposals.py#L423)):*
> ```Python
> ) -> List[BlockVisit]:
>     """
>     Returns the list of observations for a proposal. The list of observations can be
> ```

Throughout this description:

observation ---> block visit
___
*[saltapi/web/schema/common.py, line 8 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUY6awBIydxh0pydjT:-MlUY6axCmXtUcPCrcxm:b-o7vu81) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/schema/common.py#L8)):*
> ```Python
> from pydantic import BaseModel, Field
> 
> from saltapi.web.schema.block import BlockVisitStatus
> ```

This import might very well lead to a circular import. You should move BlockVisitStatus to this file instead..
___
*[saltapi/web/schema/common.py, line 12 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUZ5T7BfHYoSZAsHXh:-MlUZ5T7BfHYoSZAsHXi:buu2x69) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/schema/common.py#L12)):*
> ```Python
> 
> class BaseBlockVisit(BaseModel):
>     """An observation made, without block details."""
> ```

Throughout this class:

A observation made --> A block visit
___
*[saltapi/web/schema/common.py, line 15 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUZg5J1mAIS5VY0YN4:-MlUZg5J1mAIS5VY0YN5:b7ec1iy) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/schema/common.py#L15)):*
> ```Python
> 
>     id: int = Field(
>         ..., title="Observation id", description="Unique identifier of the observation"
> ```

Observation --> Block visit

observation ---> block visit
___
*[saltapi/web/schema/common.py, line 19 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUZL3U8XSrHFGOhup3:-MlUZL3U8XSrHFGOhup4:b-tp6v5e) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/schema/common.py#L19)):*
> ```Python
>     night: date = Field(
>         ...,
>         title="Observation night",
> ```

Well, maybe here "Observation" is indeed the correct word. :)
___
*[saltapi/web/schema/common.py, line 30 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUZsWG0hltsoVNQOzY:-MlUZsWG0hltsoVNQOzZ:bj89huq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/schema/common.py#L30)):*
> ```Python
>         None,
>         title="Rejection reason",
>         description="Reason why the observation has been rejected",
> ```

observation ---> block visit
___
*[saltapi/web/api/block_visits.py, line 47 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlU_XX969niII2REiXx:-MlU_XX969niII2REiXy:bbutasr) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/api/block_visits.py#L47)):*
> ```Python
>                                   [...]

2021-10-08 15:18 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/27)* status: 16 of 21 files reviewed, 18 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/block_repository.py, line 15 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUSqni57ZAi_OURo_a:-MlVPVoe4MlzVI8v5m2K:b-wz2ixn) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/repository/block_repository.py#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think API (read: schema) types should be used in a repository.
</blockquote></details>

I got confused here, i think you did mention this previously. But it is sorted out now.
___
*[saltapi/repository/block_repository.py, line 178 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUTI-X5tHYXopGhoAK:-MlVPeLJ13g7ATK3qleC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/repository/block_repository.py#L178)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment above. I'd stick to Dict[str, str].
</blockquote></details>

Done.
___
*[saltapi/repository/block_repository.py, line 180 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUTlyGCOFzb01XnxLW:-MlVPlV72KbD62J1V_lM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/repository/block_repository.py#L180)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

observations ---> block_visits
</blockquote></details>

Done.
___
*[saltapi/repository/block_repository.py, line 308 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUUJSx7YRm1w4IBffQ:-MlVQ5S076yIp6ynS6it:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/repository/block_repository.py#L308)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to use list comprehension rather than a for loop.
</blockquote></details>

Done.
___
*[saltapi/service/block_service.py, line 6 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUUrEI6TlWPEt6FOtK:-MlVQ7CXCD28On2KunjK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/service/block_service.py#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think API (read: schema) types should be used in a repository.
</blockquote></details>

Done.
___
*[saltapi/service/block_service.py, line 34 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUUu4c9XX-mMSpvqRs:-MlVQ7h9010VlfGlcYwF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/service/block_service.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment above. I'd stick to Dict[str, Any].
</blockquote></details>

Done.
___
*[saltapi/web/api/proposals.py, line 399 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUWyU3095VA3EyRZbj:-MlVQDoR-P-doy4tXCv5:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/api/proposals.py#L399)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

observations ---> block_visits
</blockquote></details>

Done.
___
*[saltapi/web/api/proposals.py, line 400 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUX71xEplVjx4PUvKK:-MlVQx_ZDbxybtyyB4Fa:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/api/proposals.py#L400)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

observations ---> block visits
</blockquote></details>

Done.
___
*[saltapi/web/api/proposals.py, line 403 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUXBSn1-2A1NfRaiZa:-MlVTRLz5Q6s_mOYDKpM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/api/proposals.py#L403)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

get_observations ---> get_block_visits
</blockquote></details>

Done.
___
*[saltapi/web/api/proposals.py, line 423 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUXNff8PIniQyq5QrB:-MlVTGeR9PkVzlbJ9zzO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/api/proposals.py#L423)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Throughout this description:

observation ---> block visit
</blockquote></details>

Done.
___
*[saltapi/web/schema/common.py, line 8 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUY6awBIydxh0pydjT:-MlVTIga1Wkfk2aKPP5e:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/schema/common.py#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This import might very well lead to a circular import. You should move BlockVisitStatus to this file instead..
</blockquote></details>

Done.
___
*[saltapi/web/schema/common.py, line 12 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUZ5T7BfHYoSZAsHXh:-MlVTLNaCiw-NTlCdFa5:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/schema/common.py#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Throughout this class:

A observation made --> A block visit
</blockquote></details>

Done.
___
*[saltapi/web/schema/common.py, line 15 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUZg5J1mAIS5VY0YN4:-MlVTLsK0CYDgdUk7Fau:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/schema/common.py#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Observation --> Block visit

observation ---> block visit
</blockquote></details>

Done.
___
*[saltapi/web/schema/common.py, line 19 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUZL3U8XSrHFGOhup3:-MlVTMqx9rcNtTvBsSOO:b-ompgh3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/schema/common.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Well, maybe here "Observation" is indeed the correct word. :)
</blockquote></details>

I agree with you.
___
*[saltapi/web/schema/common.py, line 30 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlUZsWG0hltsoVNQOzY:-MlVTPn-2ZQ3hUiawPkE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/schema/common.py#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

observation ---> block visit
</blockquote></details>

Done.
___
*[saltapi/web/api/block_visits.py, line 47 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlU_XX969niII2REiXx:-MlVQ8sH0ChVZ5GUgHwR:bwqhqqy) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/b8dec30b74e143481a55301d3ee958badca86122/saltapi/web/api/block_visits.py#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are creating the block repository twice (here and when creating the per mission service).
</blockquote></details>

I missed this, thanks.
___
*[saltapi/web/api/block_visits.py, line 81 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/27#-MlU_tXLCIhAe9fsSKcq: [...]

2021-10-11 12:27 UTC, merged