Verified users
saltastroops/salt-api pull request #272
Opened 2024-03-01 13:18 UTC by Eb-Zeero

and can only login when validated.

2024-03-04 07:51 UTC, hettlage requested changes
Tests (and linting) are missing.

2024-03-04 07:51 UTC, hettlage commented on saltapi/repository/user_repository.py
> +WHERE I.FirstName != 'Guest' AND PU.Active = 1
I do not think you should filter by the Active flag.

2024-03-04 07:51 UTC, hettlage commented on saltapi/repository/user_repository.py
> +        if not self.user_verified(user.id):
Raising an error is an option, but I don't think it should be a ValidationError.

You should also raise an error in case the user is inactive.

2024-03-04 07:51 UTC, hettlage commented on saltapi/repository/user_repository.py
> +WHERE Active = 1
I don't think you should filter by the Active value.

2024-03-04 07:51 UTC, hettlage commented on saltapi/repository/user_repository.py
> +        query = self._get_user_query + """\nAND I1.Email = :email"""
Change might be unnecessary

2024-03-04 07:51 UTC, hettlage commented on saltapi/repository/user_repository.py
> +    def user_verified(self, user_id: int) -> bool:
Wouldn't you rather store the information on the `User` object?

2024-03-04 07:51 UTC, hettlage commented on saltapi/web/api/authentication.py
> +            detail="User not verified.",
It would be user-friendly to also mention how you can get verified.

2024-03-04 07:51 UTC, hettlage commented on saltapi/web/api/authentication.py
> +            headers={"WWW-Authenticate": "Bearer"},
Why this header?

2024-03-04 07:51 UTC, hettlage commented on saltapi/web/api/authentication.py
> +    except ValidationError:
As commented elsewhere, this is probably not a ValidationError.

2024-03-04 14:57 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/272)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/user_repository.py` line 47 at r1](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1510690573:-Ns7tuyQ5NnaQ9wXTCBS:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5327b06801bdb574767a854898e0e03aa11a6479/saltapi/repository/user_repository.py#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you should filter by the Active value.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 120 at r1](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1510693211:-Ns7tw3xA0lXJmh48QoK:b7u03hh) ([raw file](https://github.com/saltastroops/salt-api/blob/5327b06801bdb574767a854898e0e03aa11a6479/saltapi/repository/user_repository.py#L120)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Change might be unnecessary
</blockquote></details>

Correct
___
*[`saltapi/repository/user_repository.py` line 152 at r1](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1510683892:-Ns7tzko7fOj82ZaH6gZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5327b06801bdb574767a854898e0e03aa11a6479/saltapi/repository/user_repository.py#L152)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I do not think you should filter by the Active flag.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 740 at r1](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1510686879:-Ns7z5CB0_2tp6jERBB9:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5327b06801bdb574767a854898e0e03aa11a6479/saltapi/repository/user_repository.py#L740)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Raising an error is an option, but I don't think it should be a ValidationError.

You should also raise an error in case the user is inactive.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 1058 at r1](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1510703397:-Ns7zA-B-dW6-bhZ1KXV:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5327b06801bdb574767a854898e0e03aa11a6479/saltapi/repository/user_repository.py#L1058)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't you rather store the information on the `User` object?
</blockquote></details>

Done.
___
*[`saltapi/web/api/authentication.py` line 120 at r1](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1510710313:-Ns82AVk8SlsjyS68UpM:b-7ql1td) ([raw file](https://github.com/saltastroops/salt-api/blob/5327b06801bdb574767a854898e0e03aa11a6479/saltapi/web/api/authentication.py#L120)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As commented elsewhere, this is probably not a ValidationError.
</blockquote></details>

fixed
___
*[`saltapi/web/api/authentication.py` line 123 at r1](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1510705976:-Ns825IgA4hsLUzJQ4WV:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5327b06801bdb574767a854898e0e03aa11a6479/saltapi/web/api/authentication.py#L123)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It would be user-friendly to also mention how you can get verified.
</blockquote></details>

Done.
___
*[`saltapi/web/api/authentication.py` line 124 at r1](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1510710217:-Ns7T2A7-xj1379TPkH-:b-y9a9h8) ([raw file](https://github.com/saltastroops/salt-api/blob/5327b06801bdb574767a854898e0e03aa11a6479/saltapi/web/api/authentication.py#L124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why this header?
</blockquote></details>

To Clear out any token that might have been set


<!-- Sent from Reviewable.io -->

2024-03-04 16:04 UTC, hettlage requested changes

2024-03-04 16:04 UTC, hettlage commented on saltapi/exceptions.py
> +class InactiveUserError(Exception):
There is an `AuthorizationError` class already, and IMHO it would make more sense to use that.

2024-03-04 16:04 UTC, hettlage commented on saltapi/repository/user_repository.py
> +                    "user_verified": True if row.user_verified == 1 else False,
The naming is inconsistent (is there san "is_" for boolean fields or not?); `is_user_verified` might be better, unless "is_" isn't used elsewhere (in which case `active` might be better).

2024-03-04 16:04 UTC, hettlage commented on saltapi/service/authentication_service.py
> +    except AuthorizationError:
The better option would be to update the `AuthorizationError` class to accept a message in its constructor abd then let the exception handler for that class do the job of handling the exception.

2024-03-04 16:04 UTC, hettlage commented on saltapi/service/user.py
> +    user_verified: bool
See comment on property names elsewhere; it should be `is_user_verified` and `is_active` or `user_verified` and `active`.

2024-03-04 16:04 UTC, hettlage commented on saltapi/service/authentication_service.py
> +                f"{get_settings().frontend_uri}/request-validation-link, to validate your account"
"User didn't" > "You haven't"

Full stop missing at the sentence end.

2024-03-04 16:04 UTC, hettlage commented on saltapi/web/api/authentication.py
> +        if not user.user_verified:
This is duplicating code, which (given this is about security) might not be ideal.

2024-03-04 16:04 UTC, hettlage commented on saltapi/web/api/authentication.py
> +        if not user.user_verified:
This is duplicating code, which (given this is about security) might not be ideal.

2024-03-04 16:04 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    response = client.post(
If this test works, there is a problem: Either the password is correct (and then there is a real password in the source code, even if it is for an inactive user only!) or you potentially reveal the existence of a username to someone who doesn't have the password. (This might sound a bit odd; I'm happy to explain what I mean in person. :) )

2024-03-04 16:04 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +def test_should_return_403_if_user_not_verified(
See my comments on the previous test, which apply here as well.

2024-03-04 16:04 UTC, hettlage commented on saltapi/repository/user_repository.py
> +       PU.Active                AS is_active,
For consistency, maybe rather use `active` as the alias?

2024-03-04 16:04 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    assert response.status_code == status.HTTP_403_FORBIDDEN
You could in addition check that you get the correct error message.

2024-03-05 10:51 UTC, Eb-Zeero reviewed
On the last test... 
getting the user from the token, that the user shouldn't have the token in the first place. so to write this test I need to force a user to log in and have a token that will be valid update the database that the user is no longer active and make the query

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/272#-:-NsDD6eG-rHSL8V7C-0-:b3f9wql)* status: 0 of 6 files reviewed, 19 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/exceptions.py` line 17 at r2](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1511347474:-NsCvV_Q0O-4ah_xcTfJ:ba3dfob) ([raw file](https://github.com/saltastroops/salt-api/blob/667271c16314a7892916dea64174f4435fcc5825/saltapi/exceptions.py#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is an `AuthorizationError` class already, and IMHO it would make more sense to use that.
</blockquote></details>

Removed
___
*[`saltapi/repository/user_repository.py` line 40 at r2](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1511401901:-NsD3QNnEr8qx2vT7797:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/667271c16314a7892916dea64174f4435fcc5825/saltapi/repository/user_repository.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency, maybe rather use `active` as the alias?
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 75 at r2](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1511354207:-NsD3ZmP9pRU70UU2jUK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/667271c16314a7892916dea64174f4435fcc5825/saltapi/repository/user_repository.py#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The naming is inconsistent (is there san "is_" for boolean fields or not?); `is_user_verified` might be better, unless "is_" isn't used elsewhere (in which case `active` might be better).
</blockquote></details>

Done.
___
*[`saltapi/service/authentication_service.py` line 92 at r2](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1511362132:-NsD7pzv1geglxhQ9duD:b-sz6h0g) ([raw file](https://github.com/saltastroops/salt-api/blob/667271c16314a7892916dea64174f4435fcc5825/saltapi/service/authentication_service.py#L92)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The better option would be to update the `AuthorizationError` class to accept a message in its constructor abd then let the exception handler for that class do the job of handling the exception. 
</blockquote></details>

converting exception to a string works fine
___
*[`saltapi/service/authentication_service.py` line 97 at r2](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1511375788:-NsD7gUd7ssmc4U3fsY8:bgu0if2) ([raw file](https://github.com/saltastroops/salt-api/blob/667271c16314a7892916dea64174f4435fcc5825/saltapi/service/authentication_service.py#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"User didn't" > "You haven't"

Full stop missing at the sentence end.
</blockquote></details>

did
"Your account has not been validated. Please visit " f"{get\_settings().frontend\_uri}/request-validation-link to validate your account."
___
*[`saltapi/service/user.py` line 64 at r2](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1511364716:-NsD84zg1mf1PnIJlTe8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/667271c16314a7892916dea64174f4435fcc5825/saltapi/service/user.py#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment on property names elsewhere; it should be `is_user_verified` and `is_active` or `user_verified` and `active`.
</blockquote></details>

Done.
___
*[`saltapi/web/api/authentication.py` line 69 at r2](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1511377540:-NsD8BLb9baqAZR7EdcZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/667271c16314a7892916dea64174f4435fcc5825/saltapi/web/api/authentication.py#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is duplicating code, which (given this is about security) might not be ideal.
</blockquote></details>

Done.
___
*[`saltapi/web/api/authentication.py` line 140 at r2](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1511380019:-NsD8S7u9jJeauIck2Df:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/667271c16314a7892916dea64174f4435fcc5825/saltapi/web/api/authentication.py#L140)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is duplicating code, which (given this is about security) might not be ideal.
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 39 at r2](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1511397696:-NsDD1JB9Uanmpielg8_:b-ubep0p) ([raw file](https://github.com/saltastroops/salt-api/blob/667271c16314a7892916dea64174f4435fcc5825/tests/integration/authentication/test_authentication.py#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If this test works, there is a problem: Either the password is correct (and then there is a real password in the source code, even if it is for an inactive user only!) or you potentially reveal the existence of a username to someone who doesn't have the password. (This might sound a bit odd; I'm happy to explain what I mean in person. :) )
</blockquote></details>

discused
___
*[`tests/integration/authentication/test_authentication.py` line 42 at r2](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1511405448:-NsDD0QfCygURroON1vj:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/667271c16314a7892916dea64174f4435fcc5825/tests/integration/authentication/test_authentication.py#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could in addition check that you get the correct error message.
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 46 at r2](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1511398608:-NsDD0ua1QxVqigCvUwY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/667271c16314a7892916dea64174f4435fcc5825/tests/integration/authentication/test_authentication.py#L46)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See my comments on the previous test, which apply here as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-05 13:39 UTC, hettlage requested changes

2024-03-05 13:39 UTC, hettlage commented on saltapi/service/authentication_service.py
> +        raise HTTPException(
The exception should be handled by the exception handler.

2024-03-05 13:39 UTC, hettlage commented on saltapi/util.py
> +        raise AuthorizationError("User account is not active. Please contact SALT Help for assistance.")
User account > Your account

2024-03-05 13:39 UTC, hettlage commented on saltapi/web/api/authentication.py
> +    except AuthorizationError as e:
The exception should be handled by the exception handler.

2024-03-05 13:39 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        endpoint, data={"username": "dod", "password": "secret"}
Please choose another name. I'll explain why.

2024-03-05 13:39 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        endpoint, data={"username": "warner", "password": "secret"}
Please choose another name. I'll explain why.

2024-03-05 13:39 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        endpoint, data={"username": "warner", "password": "secret"}
You are testing that an inactive or non-verified

* cannot login
* cannot request a token.

But from what I can see, you are *not* testing that they

* cannot perform a restricted action if they are logged in or have a token already.

2024-03-11 08:28 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/272)* status: 0 of 22 files reviewed, 25 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/util.py` line 315 at r3](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1512822913:-NsDvHuK64_jR_6u7oWe:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5a62418c60610175c6f85bf5d2fa0c6720c59e46/saltapi/util.py#L315)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

User account > Your account
</blockquote></details>

Done.
___
*[`saltapi/service/authentication_service.py` line 91 at r3](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1512673417:-NsgF95n49kS67nfPBHF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5a62418c60610175c6f85bf5d2fa0c6720c59e46/saltapi/service/authentication_service.py#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The exception should be handled by the exception handler.
</blockquote></details>

Done.
___
*[`saltapi/web/api/authentication.py` line 71 at r3](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1512823831:-NsRwipg6gHSGysEDI2o:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/5a62418c60610175c6f85bf5d2fa0c6720c59e46/saltapi/web/api/authentication.py#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The exception should be handled by the exception handler.
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 40 at r3](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1512829697:-NsDwVLM4y7-IlUsdSKh:b-m10zwx) ([raw file](https://github.com/saltastroops/salt-api/blob/5a62418c60610175c6f85bf5d2fa0c6720c59e46/tests/integration/authentication/test_authentication.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Please choose another name. I'll explain why.
</blockquote></details>

please
___
*[`tests/integration/authentication/test_authentication.py` line 52 at r3](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1512832388:-NsDwYxP-_dm6oWB-w0H:bqf5hif) ([raw file](https://github.com/saltastroops/salt-api/blob/5a62418c60610175c6f85bf5d2fa0c6720c59e46/tests/integration/authentication/test_authentication.py#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Please choose another name. I'll explain why.
</blockquote></details>

there are very few in the db
but please explain
___
*[`tests/integration/authentication/test_authentication.py` line 52 at r3](https://reviewable.io/reviews/saltastroops/salt-api/272#gh-1512839563:-Nsgc3kV2DuE37fMkNKV:b-enhxt3) ([raw file](https://github.com/saltastroops/salt-api/blob/5a62418c60610175c6f85bf5d2fa0c6720c59e46/tests/integration/authentication/test_authentication.py#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are testing that an inactive or non-verified

* cannot login
* cannot request a token.

But from what I can see, you are *not* testing that they

* cannot perform a restricted action if they are logged in or have a token already.
</blockquote></details>

Issue opened.


<!-- Sent from Reviewable.io -->

2024-03-12 15:45 UTC, hettlage requested changes
> Reviewed 1 of 7 files at r3, 20 of 20 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/272)* status: all files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/user_repository.py` line 722 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-NslkHM2Bi5zFmpq3ls0:-NslkHM2Bi5zFmpq3ls1:b-rsz3l3) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/saltapi/repository/user_repository.py#L722)):*
> ```Python
>         return secrets.compare_digest(password_hash, hashed_password)
> 
>     def find_user_with_username_and_password(
> ```

Given that all the other methods for getting a user return `None` now if the user does not exist, wouldn't it make sense to do this here as well (and raise the AuthenticationError elsewhere)?
___
*[`saltapi/repository/user_repository.py` line 729 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-Nsljz5S6AUHyN3yePHI:-Nsljz5S6AUHyN3yePHJ:bv8o431) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/saltapi/repository/user_repository.py#L729)):*
> ```Python
> 
>         If the combination of username and password is valid, then the corresponding
>         user is returned. Otherwise a NotFoundError is raised.
> ```

NotFoundError > AuthenticationError (but see the comment above regarding returning `None`)
___
*[`saltapi/service/user_service.py` line 102 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-Nsll_qe0b2hxzqKKilc:-Nsll_qe0b2hxzqKKild:b-i0glwz) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/saltapi/service/user_service.py#L102)):*
> ```Python
>             # Just in case the password hash ends up somewhere
>             user.password_hash = "***"  # nosec
>             return user
> ```

Here and in the other methods below you could simplify

```
if user:
        # Just in case the password hash ends up somewhere
        user.password_hash = "***"  # nosec
        return user
return None
```

to

```
if user:
            # Just in case the password hash ends up somewhere
            user.password_hash = "***"  # nosec
  return user
````
___
*[`tests/integration/users/test_patch_user.py` line 179 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsnHH8HB1uRIMv0HHxQ:-NsnHH8I3cAiQ8YDUkDR:bp548sr) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/tests/integration/users/test_patch_user.py#L179)):*
> ```Python
>     expected_updated_user_details = user.copy()
>     expected_updated_user_details.update(user_update)
>     _remove_untested(expected_updated_user_details)
> ```

It might be worth asking whether some of these properties actually should be included  in the user object?
___
*[`tests/repository/test_user_repository.py` line 73 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsnIahF1fHA4EFuMNBS:-NsnIahF1fHA4EFuMNBT:b-nsg0dw) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/tests/repository/test_user_repository.py#L73)):*
> ```Python
> 
> @nodatabase
> def test_get_user_by_email_returns_returns_none_if_no_user(
> ```

This is a duplicate test; see the `test_get_user_by_email_returns_none_for_non_existing_user` function below.
___
*[`tests/repository/test_user_repository.py` line 86 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsnI-l_3l4d_ZnQtLB4:-NsnI-l_3l4d_ZnQtLB5:b-38tx6n) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/tests/repository/test_user_repository.py#L86)):*
> ```Python
> 
> @nodatabase
> def test_create_user_raisers_error_if_username_exists_already(
> ```

raisers > raises
___
*[`tests/repository/test_user_repository.py` line 439 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsnJ0ZmA2SNVrmlnDYN:-NsnJ0ZmA2SNVrmlnDYO:b-qlq291) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/tests/repository/test_user_repository.py#L439)):*
> ```Python
>         user_repository.find_user_with_username_and_password(username, "some_password")
>     )
>     print(user)
> ```

Unnecessary `print` statement.


<!-- Sent from Reviewable.io -->

2024-03-13 09:11 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/272)* status: 16 of 22 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/user_repository.py` line 722 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-NslkHM2Bi5zFmpq3ls0:-Nsqgftz0WLNnYiH7TOm:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/saltapi/repository/user_repository.py#L722)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that all the other methods for getting a user return `None` now if the user does not exist, wouldn't it make sense to do this here as well (and raise the AuthenticationError elsewhere)?
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 729 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-Nsljz5S6AUHyN3yePHI:-NsqgxIQ7PQMIlSLdi8u:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/saltapi/repository/user_repository.py#L729)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

NotFoundError > AuthenticationError (but see the comment above regarding returning `None`)
</blockquote></details>

Done.
___
*[`saltapi/service/user_service.py` line 102 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-Nsll_qe0b2hxzqKKilc:-NsqhI_GB67Ora7YJVCy:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/saltapi/service/user_service.py#L102)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Here and in the other methods below you could simplify

```
if user:
        # Just in case the password hash ends up somewhere
        user.password_hash = "***"  # nosec
        return user
return None
```

to

```
if user:
            # Just in case the password hash ends up somewhere
            user.password_hash = "***"  # nosec
  return user
````
</blockquote></details>

Done.
___
*[`tests/integration/users/test_patch_user.py` line 179 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsnHH8HB1uRIMv0HHxQ:-Nsr49CTDyGyQDO0WDVh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/tests/integration/users/test_patch_user.py#L179)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be worth asking whether some of these properties actually should be included  in the user object?
</blockquote></details>

Done.
___
*[`tests/repository/test_user_repository.py` line 73 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsnIahF1fHA4EFuMNBS:-NsqhmDR9HduzYwWfzSd:b2el2td) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/tests/repository/test_user_repository.py#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is a duplicate test; see the `test_get_user_by_email_returns_none_for_non_existing_user` function below.
</blockquote></details>

not really get user_by_email and the other is fet_user _by_username
___
*[`tests/repository/test_user_repository.py` line 86 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsnI-l_3l4d_ZnQtLB4:-NsqiABnDrrOQZ2-hJGx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/tests/repository/test_user_repository.py#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

raisers > raises
</blockquote></details>

Done.
___
*[`tests/repository/test_user_repository.py` line 439 at r5](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsnJ0ZmA2SNVrmlnDYN:-NsqZo-4CCYr5dd-sAdZ:bd30ifx) ([raw file](https://github.com/saltastroops/salt-api/blob/3586b9d66115b18c7fb08db71597b368e5ea1aa0/tests/repository/test_user_repository.py#L439)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary `print` statement.
</blockquote></details>

good catch


<!-- Sent from Reviewable.io -->

2024-03-14 07:39 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/272)* status: all files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/user_repository.py` line 642 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrAAkL8-mqUImfLfxQ:-NsrAAkL8-mqUImfLfxR:bs3hw33) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/saltapi/repository/user_repository.py#L642)):*
> ```Python
>     def get_password_hash(password: str) -> str:
>         """Hash a plain text password."""
>         password = cast(str, password)
> ```

There should be no need for this line. The password *is* a `str` already.
___
*[`saltapi/repository/user_repository.py` line 734 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrASCK-p9a-G9eqnxI:-NsrASCK-p9a-G9eqnxJ:brc10nw) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/saltapi/repository/user_repository.py#L734)):*
> ```Python
>         user = self.get_by_username(username)
>         if not user:
>             return
> ```

I'd be explicit and use `return None` (as this is not a "void" method).
___
*[`saltapi/repository/user_repository.py` line 736 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrAiwQAQIZXHPMDrMe:-NsrAiwQAQIZXHPMDrMf:brc10nw) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/saltapi/repository/user_repository.py#L736)):*
> ```Python
>             return
>         if not self.verify_password(password, user.password_hash):
>             return
> ```

I'd be explicit and use `return None` (as this is not a "void" method).
___
*[`tests/integration/authentication/test_authentication.py` line 55 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrBWmZ4i62g-3OsxXA:-NsrBWmZ4i62g-3OsxXB:b-pp13wk) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/tests/integration/authentication/test_authentication.py#L55)):*
> ```Python
>     )
>     assert response.status_code == status.HTTP_403_FORBIDDEN
>     assert "Your account is not active" in response.json()["message"]
> ```

Is that message really correct? Isn't the test about verifying?

(So maybe make the correct check and skip the test for the time being?)
___
*[`tests/repository/test_user_repository.py` line 73 at r4](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrDEuy3rcI44n8JMSv:-NsrDEuy3rcI44n8JMSw:b-ot4id1) ([raw file](https://github.com/saltastroops/salt-api/blob/62e13f14cdedb8cb690ad290a8946ba62b40635d/tests/repository/test_user_repository.py#L73)):*
> ```Python
> 
> @nodatabase
> def test_get_user_by_email_returns_returns_none_if_no_user(
> ```

Maybe better: `test_get_user_by_email_returns_none_for_non_existing_user`?
___
*[`tests/repository/test_user_repository.py` line 141 at r4](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrDgaeEiOZYW3c2AGy:-NsrDgaeEiOZYW3c2AGz:b1td6g8) ([raw file](https://github.com/saltastroops/salt-api/blob/62e13f14cdedb8cb690ad290a8946ba62b40635d/tests/repository/test_user_repository.py#L141)):*
> ```Python
> 
> 
> @nodatabase
> ```

The function name should be `test_get_user_by_username_returns_none_for_non_existing_user`.
___
*[`tests/repository/test_user_repository.py` line 146 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrDu6f6uAGkjGLeRUB:-NsrDu6f6uAGkjGLeRUC:b8dk9ht) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/tests/repository/test_user_repository.py#L146)):*
> ```Python
> ) -> None:
>     user_repository = UserRepository(db_connection)
>     user = user_repository.get_by_username("invalid@email.com")
> ```

I'd suggest not using any email address for the non-existing username.
___
*[`tests/repository/test_user_repository.py` line 448 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrEWzw9YX5A_kwRNJe:-NsrEWzw9YX5A_kwRNJf:b-hy0vl4) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/tests/repository/test_user_repository.py#L448)):*
> ```Python
> 
> @nodatabase
> @pytest.mark.parametrize("username", ["idontexist", "", None])
> ```

I don't think you should check for `None`, as the tested method explicitly expects a string, doesn't it? So strictly speaking the behaviour for passing in `None` is undefined.
___
*[`tests/repository/test_user_repository.py` line 463 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrFaMg4YF65emwpMB6:-NsrFaMg4YF65emwpMB7:bm5zemw) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/tests/repository/test_user_repository.py#L463)):*
> ```Python
> @pytest.mark.parametrize(
>     "username, password",
>     [("hettlage", "wrongpassword"), ("hettlage", ""), ("hettlage", "æ����"), ],
> ```

I'm not overly convinced they you gain much by testing multiple wrong passwords.


<!-- Sent from Reviewable.io -->

2024-03-14 07:57 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/272)* status: all files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/user_repository.py` line 642 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrAAkL8-mqUImfLfxQ:-NsvuJRMCMectlIyjUv9:b-ramae8) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/saltapi/repository/user_repository.py#L642)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be no need for this line. The password *is* a `str` already.
</blockquote></details>

sorry deep mistake and thanks for catching this
___
*[`saltapi/repository/user_repository.py` line 734 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrASCK-p9a-G9eqnxI:-NsvuVL9CO2IzJ7ZILGs:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/saltapi/repository/user_repository.py#L734)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd be explicit and use `return None` (as this is not a "void" method).
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 736 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrAiwQAQIZXHPMDrMe:-NsvuVf-3KkeSOH2wod1:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/saltapi/repository/user_repository.py#L736)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd be explicit and use `return None` (as this is not a "void" method).
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 55 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrBWmZ4i62g-3OsxXA:-Nsvw78WD6nB3ZyXnEdD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/tests/integration/authentication/test_authentication.py#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is that message really correct? Isn't the test about verifying?

(So maybe make the correct check and skip the test for the time being?)
</blockquote></details>

Done.
___
*[`tests/repository/test_user_repository.py` line 73 at r4](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrDEuy3rcI44n8JMSv:-NsvwEeR6RNieOH3bL0O:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/62e13f14cdedb8cb690ad290a8946ba62b40635d/tests/repository/test_user_repository.py#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: `test_get_user_by_email_returns_none_for_non_existing_user`?
</blockquote></details>

Done.
___
*[`tests/repository/test_user_repository.py` line 141 at r4](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrDgaeEiOZYW3c2AGy:-NsvxXa744JEnz3zLBxR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/62e13f14cdedb8cb690ad290a8946ba62b40635d/tests/repository/test_user_repository.py#L141)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The function name should be `test_get_user_by_username_returns_none_for_non_existing_user`.
</blockquote></details>

Done.
___
*[`tests/repository/test_user_repository.py` line 146 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrDu6f6uAGkjGLeRUB:-Nsvx9O-DtVFyYlmglBh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/tests/repository/test_user_repository.py#L146)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest not using any email address for the non-existing username.
</blockquote></details>

Done.
___
*[`tests/repository/test_user_repository.py` line 448 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrEWzw9YX5A_kwRNJe:-NsvxqC97mrWVLH4hqWL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/tests/repository/test_user_repository.py#L448)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you should check for `None`, as the tested method explicitly expects a string, doesn't it? So strictly speaking the behaviour for passing in `None` is undefined.
</blockquote></details>

Done.
___
*[`tests/repository/test_user_repository.py` line 463 at r6](https://reviewable.io/reviews/saltastroops/salt-api/272#-NsrFaMg4YF65emwpMB6:-NsvxS4A39Ahf3sIKUji:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/345777da6a1c98957df6c57e129c3a651e444cd8/tests/repository/test_user_repository.py#L463)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not overly convinced they you gain much by testing multiple wrong passwords.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-14 10:49 UTC, hettlage approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/272)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2024-03-14 10:52 UTC, merged