Verification missing tests
saltastroops/salt-api pull request #283
Opened 2024-03-20 14:22 UTC by Eb-Zeero

2024-03-20 18:17 UTC, hettlage requested changes

2024-03-20 18:17 UTC, hettlage commented on saltapi/service/authentication_service.py
> +        raise NotFoundError("User not found.")
Maybe in this case "Could not validate token." might have been the more user-friendly error message?

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        user_repo.activate_user(user.id, False)
Okay, not really this PR, but...: Being able to _deactivate_ a user with a method called _activate_ looks a bit odd. The same is true for the verify method.

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        user = user_repo.get_by_username(username)
Can't you use the `_change_users_verify_active_status` method here?

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +def test_users_with_a_valid_token_and_are_not_active_shouldnt_make_any_request(client: TestClient,  db_connection: Connection) -> None:
test_users_with_a_valid_token_and_are_not_active_shouldnt_make_any_request > test_inactive_users_with_a_valid_token_must_not_make_any_request

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        user_repo = UserRepository(connect)
Are you using `user_repo` anywhere?

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        user_repo = UserRepository(connect)
Are you using user_repo anywhere?

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    username = find_username("Not Active User")
Not Active User > Inactive User (obviously requires some other code to change)

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    # Make user the user is valid and have a valid token
Make sure the user is valid and has a valid token

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    # Make user the user is valid and have a valid token
verify > verified (wherever it is an adjective)

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    # Make user the user is valid and have a valid token
Deactivate > Unverify

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    # Make user the user is valid and have a valid token
Unverify the user

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    # Make user the user is valid and have a valid token
Unverify the user

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    # Make user the user is valid and have a valid token
Unverify the user

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    # Make user the user is valid and have a valid token
Unverify

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    username = find_username("Not Active User")
Not Active User > Inactive User (obviously requires some other code to change)

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        _change_users_verify_active_status(user.id, verify=True, active=True, connection=connect)
Make sure the user is valid and has a valid token

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        _change_users_verify_active_status(user.id, verify=False, active=True, connection=connect)
Unverify the user

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        # Deactivate the user.
Unverify the user

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        # Reset back
Revert back

2024-03-20 18:17 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +        _change_users_verify_active_status(user.id, verify=False, active=False, connection=connect)
Maybe add a comment that you are reverting back?

2024-03-20 18:17 UTC, hettlage commented on tests/repository/test_user_repository.py
> +def test_verify_user_update_users_verification_status(db_connection: Connection) -> None:
Maybe add an empty line before the comment?

Oh, and is this part of the test actually necessary?

2024-03-20 18:17 UTC, hettlage commented on tests/repository/test_user_repository.py
> +def test_verify_user_update_users_verification_status(db_connection: Connection) -> None:
Test

2024-03-20 18:17 UTC, hettlage commented on tests/repository/test_user_repository.py
> +def test_verify_user_update_users_verification_status(db_connection: Connection) -> None:
Empty line missing before the comment.

2024-03-20 18:17 UTC, hettlage commented on tests/repository/test_user_repository.py
> +        # Set the verification status back to False
Empty line missing before the comment

2024-03-20 18:17 UTC, hettlage commented on tests/repository/test_user_repository.py
> +    def _get_user_with_updated_user_verified_status(user_id: int, verify: bool,  connection: Connection):
There is no reason why `_get_user_with_updated_user_verified_status` is defined within `test_verify_user_update_users_verification_status`, is there?

2024-03-20 18:17 UTC, hettlage commented on tests/repository/test_user_repository.py
> +    username = find_username("Not Active User")
Not Active User > Inactive User (obviously requires some other code to change)

2024-03-20 18:17 UTC, hettlage commented on tests/repository/test_user_repository.py
> +    def _get_user_with_updated_active_status(user_id: int, active: bool,  connection: Connection):
There is no reason why `_get_user_with_updated_active_status` is defined within `test_activate_user_update_users_activation_status`, is there?

2024-03-20 18:17 UTC, hettlage commented on tests/repository/test_user_repository.py
> +def test_activate_user_update_users_activation_status(db_connection: Connection) -> None:
Not Active User > Inactive User (obviously requires some other code to change)

2024-03-20 18:17 UTC, hettlage commented on tests/repository/test_user_repository.py
> +def test_activate_user_update_users_activation_status(db_connection: Connection) -> None:
Not Active User > Inactive User (obviously requires some other code to change)

I'm not sure why PyCharm is moving this comment here. It's supposed near the line with the `find_username` call.

2024-03-20 18:17 UTC, hettlage commented on tests/repository/test_user_repository.py
> +def test_activate_user_update_users_activation_status(db_connection: Connection) -> None:
Not Active User > Inactive User (obviously requires some other code to change)

2024-03-25 07:32 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/283)* status: 0 of 4 files reviewed, 30 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/authentication_service.py` line 94 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532282148:-Nt_xPuBEijIj9Hfarwb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/saltapi/service/authentication_service.py#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe in this case "Could not validate token." might have been the more user-friendly error message?
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 48 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532292774:-NtoOZHI-7w6GkLfKCvO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Okay, not really this PR, but...: Being able to _deactivate_ a user with a method called _activate_ looks a bit odd. The same is true for the verify method.
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 67 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532300701:-NtoOiKm8RQIHRvtHLhN:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can't you use the `_change_users_verify_active_status` method here?
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 206 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532305361:-NtoOuHk7dF6wQQbx5hi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L206)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

test_users_with_a_valid_token_and_are_not_active_shouldnt_make_any_request > test_inactive_users_with_a_valid_token_must_not_make_any_request
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 207 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532314592:-NtoOvMsCKwXO1-DNL9J:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L207)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Not Active User > Inactive User (obviously requires some other code to change)
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 209 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532319843:-NtoL9kZ5WnTggORW4Xb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L209)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Make sure the user is valid and has a valid token
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 209 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532324698:-NtoLJFw4Nlrvc3Ehw4D:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L209)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Deactivate > Unverify
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 209 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532329947:-NtoLR6SDikjQrouqlmW:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L209)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unverify the user
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 209 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532328131:-NtoVWrm1D0SEzSEjEUE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L209)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unverify the user
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 209 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532328924:-NtoVXnR7DxcafaB95YN:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L209)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unverify the user
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 209 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532323307:-NtoW-pE8KZQYBMCn-13:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L209)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

verify > verified (wherever it is an adjective)
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 209 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532330885:-NtoW0uF7wvj2dM7wcEh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L209)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unverify
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 211 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532307786:-NtoLkgYD5V_LKLqR-i9:b-gpnoz9) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L211)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are you using `user_repo` anywhere?
</blockquote></details>

yes to get the user
___
*[`tests/integration/authentication/test_authentication.py` line 220 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532308950:-NtoLtza5q1401q6j26n:b-mifidj) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L220)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are you using user_repo anywhere?
</blockquote></details>

sorry not this one
___
*[`tests/integration/authentication/test_authentication.py` line 226 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532335858:-NtoM2nI96Xk9Qt4yDNp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fab42b8459816e543bde2/tests/integration/authentication/test_authentication.py#L226)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Revert back
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 231 at r1](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1532333309:-NtoMVJC8EvTUEHfXrII:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/1fdb6db2eb4d0947822fa [...]

2024-03-25 11:40 UTC, hettlage requested changes

2024-03-25 11:40 UTC, hettlage commented on saltapi/exceptions_handling.py
> +            status_code=status.HTTP_401_UNAUTHORIZED, content={"message": str(exc)}
Maybe use a more generic message, such as "The authorisation token could not be parsed." ?

2024-03-25 11:40 UTC, hettlage commented on tests/repository/test_user_repository.py
> +def _get_user_with_updated_active_status(user_id: int, active: bool,  connection: Connection):
As discussed earlier, the name `_get_user_with_updated_active_status` might be a bit unfortunate.

2024-03-25 11:40 UTC, hettlage commented on tests/integration/authentication/test_authentication.py
> +    username = find_username("Inactive User")
Have you updated the test data? :-)

2024-03-26 07:56 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/283)* status: 0 of 5 files reviewed, 33 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/exceptions_handling.py` line 135 at r2](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1537209282:-NttkiYFExD-MOb5NZmg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b8ed3119a1b1c5eb60b9ea8e3949ee80d4eb7ddc/saltapi/exceptions_handling.py#L135)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe use a more generic message, such as "The authorisation token could not be parsed." ?
</blockquote></details>

Done.
___
*[`tests/integration/authentication/test_authentication.py` line 205 at r2](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1537451003:-NttijReCZZBcQ1l7UJF:b-emybez) ([raw file](https://github.com/saltastroops/salt-api/blob/b8ed3119a1b1c5eb60b9ea8e3949ee80d4eb7ddc/tests/integration/authentication/test_authentication.py#L205)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Have you updated the test data? :-)
</blockquote></details>

yes I did but forgot to push will push now
___
*[`tests/repository/test_user_repository.py` line 680 at r2](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1537443522:-Nttk5LPAdzml-j5u-tZ:b-qk54ho) ([raw file](https://github.com/saltastroops/salt-api/blob/b8ed3119a1b1c5eb60b9ea8e3949ee80d4eb7ddc/tests/repository/test_user_repository.py#L680)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As discussed earlier, the name `_get_user_with_updated_active_status` might be a bit unfortunate.
</blockquote></details>

Missed this one


<!-- Sent from Reviewable.io -->

2024-03-26 09:23 UTC, hettlage requested changes

2024-03-26 09:23 UTC, hettlage commented on tests/repository/test_user_repository.py
> +def _updated_active_status(user_id: int, active: bool,  connection: Connection):
Shouldn't this rather be `_update_active_status`?

2024-03-26 09:23 UTC, hettlage commented on saltapi/exceptions_handling.py
> +    async def exception_handle(request: Request) -> Response:
Maybe rather call this something like `generic_exception_handler`, given its a handler rather than handle?

2024-03-27 07:21 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/283)* status: 0 of 5 files reviewed, 35 unresolved discussions (waiting on @hettlage)

*[a discussion](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1538795691:-Ntym7UI7ccvNyFgblHT:bs9b6c9) (no related file):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/saltastroops/salt-api/pull/283#discussion_r1538795691) to the right spot — sorry!)*

Shouldn't this rather be `_update_active_status`?
</blockquote></details>

this comment can't be mapped but it is fixed now

___
___
*[`saltapi/exceptions_handling.py` line 53 at r4](https://reviewable.io/reviews/saltastroops/salt-api/283#gh-1538863992:-NtylTWq6TSxYe-7BckR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4e68133a191e4ce716c3da3653224b5a9f31915d/saltapi/exceptions_handling.py#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe rather call this something like `generic_exception_handler`, given its a handler rather than handle?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-27 14:42 UTC, hettlage commented on saltapi/exceptions_handling.py
> +    async def exception_handle(request: Request) -> Response:
"handler", not "handle"...

2024-03-27 14:45 UTC, hettlage commented
The issue raised in the _update_active_status comment doesn't seem to be fixed yet.

2024-03-27 14:56 UTC, hettlage approved these changes

2024-03-27 14:57 UTC, merged