Pools Backend
saltastroops/salt-api pull request #322
Opened 2024-07-30 13:39 UTC by Eb-Zeero

2024-07-31 11:29 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322)* status: all files reviewed, 22 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2688 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37MlV35dDRHraMqeE-:-O37MlV35dDRHraMqeE0:b-8pelwf) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2688)):*
> ```Python
>         if not result.rowcount:
>             raise NotFoundError()
> ```

I don't think that "allocations" is an ideal name here, and I don't think the used times should be passed.
___
*[`saltapi/repository/proposal_repository.py` line 2689 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37PIBV9PoA-5A5rHpa:-O37PIBV9PoA-5A5rHpb:bkyasz0) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2689)):*
> ```Python
>             raise NotFoundError()
> 
>     def _get_pools_allocations(self, pool_id: int, summed_used_time: List[Dict[str, any]]):
> ```

Why "any"? And shouldn't it be "Any"?
___
*[`saltapi/repository/proposal_repository.py` line 2689 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37PZ8w5s0_Ghko4gYm:-O37PZ8xEOH0OVVu6oED:bexn216) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2689)):*
> ```Python
>             raise NotFoundError()
> 
>     def _get_pools_allocations(self, pool_id: int, summed_used_time: List[Dict[str, any]]):
> ```

The method name suggests the methods deals with more than pool... Also, "allocations" might not be the ideal term.
___
*[`saltapi/repository/proposal_repository.py` line 2723 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37NfZLCRqQJC2kb3mJ:-O37NfZLCRqQJC2kb3mK:b-yakqsu) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2723)):*
> ```Python
>     P.Pool_Id           AS id,
>     P.Pool_Name         AS name,
>     PRS.X1              AS wait,
> ```

Calling this wait is not ideal.
___
*[`saltapi/repository/proposal_repository.py` line 2730 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Ny56-JmHVA933EyQ:-O37Ny56-JmHVA933EyR:b-scl024) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2730)):*
> ```Python
>     JOIN PoolRuleSet PRS ON P.Pool_Id = PRS.Pool_Id
>     JOIN PoolRule PR ON PRS.PoolRule_Id = PR.PoolRule_Id
> WHERE PC.Proposal_Code = :proposal_code AND CONCAT(S.Year, '-', S.Semester) = :semester
> ```

Wouldn't this query include pools which aren't included in the most recent version of the proposal any longer?

Also, yiou don;t handle the case that there are multiple pool rules for a pool.
___
*[`saltapi/repository/proposal_repository.py` line 2751 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37QHDY1J3V4U2u1RSM:-O37QHDY1J3V4U2u1RSN:b-kysneh) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2751)):*
> ```Python
>                     total_times_per_priority[priority] += total_time
>                 else:
>                     total_times_per_priority[priority] = total_time
> ```

This works, but you could have used a `defaultdict`.
___
*[`saltapi/repository/proposal_repository.py` line 2759 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Y7pD6dVUAtWlMF5X:-O37Y7pD6dVUAtWlMF5Y:b-8iorx2) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2759)):*
> ```Python
>                     "name": row.name,
>                     "wait": row.wait,
>                     "description": row.description,
> ```

I'd suggest you in the pool rules rather than creating a description.
___
*[`saltapi/repository/proposal_repository.py` line 2760 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37OXVc2pcOsLp0gAi5:-O37OXVc2pcOsLp0gAi6:bgl6avw) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2760)):*
> ```Python
>                     "wait": row.wait,
>                     "description": row.description,
>                     "allocations": self._get_pools_allocations(row.id, summed_blocks),
> ```

I don't think "allocations" is the correct term here.
___
*[`saltapi/repository/proposal_repository.py` line 2785 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Qt4F1IEylj4VHi9W:-O37Qt4F1IEylj4VHi9X:bzik1y) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2785)):*
> ```Python
>         return 0
> 
>     def _get_pool_block(self, block_id: int, block_observable_tonight: Dict[int, int]) -> Dict[str, any]:
> ```

This is highly inefficient, as the method is called for every block.

Also, I'm not convinced the observability information should be passed.

Finally, arguably the method name is a bit misleading, as the method is lott concerned about pools.
___
*[`saltapi/repository/proposal_repository.py` line 2808 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37RVP47r6VXyXGhchV:-O37RVP47r6VXyXGhchW:b599ntl) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2808)):*
> ```Python
>             },
>         )
>         block = result.one_or_none()
> ```

Won't you get a null pointer exception if there is no block?
___
*[`saltapi/repository/proposal_repository.py` line 2830 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37SHTBC5tlLoTNDvFE:-O37SHTBC5tlLoTNDvFF:b-4lx5pi) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2830)):*
> ```Python
> SELECT BP.Block_Id      AS block_id
> FROM BlockPool  BP
> WHERE BP.Pool_Id = :pool_id
> ```

Don't you have to take the block status into account? (Do you really want to include deleted and superseded blocks?)
___
*[`saltapi/repository/proposal_repository.py` line 2839 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Sc717m8QPdcJ90QJ:-O37Sc717m8QPdcJ90QK:bzf7tg9) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2839)):*
> ```Python
>         blocks = []
>         for row in self.connection.execute(stmt, {"pool_id": pool_id}):
>             blocks.append(self._get_pool_block(row.block_id, block_observable_tonight))
> ```

Can't the query in `_get_pool_block` be incorporated intro this method's query, making `_get_pool_block` obsolete?
___
*[`saltapi/web/api/proposals.py` line 199 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37T9G21gQztrnFfcZm:-O37T9G21gQztrnFfcZn:b-qrss2j) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/api/proposals.py#L199)):*
> ```Python
> @router.get(
>     "/{proposal_code}/pools",
>     summary="Get a proposal",
> ```

Get the pools in a proposal
___
*[`saltapi/web/api/proposals.py` line 206 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37TK66EIEA28Lk9BEZ:-O37TK66EIEA28Lk9BE_:b-zdnnin) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/api/proposals.py#L206)):*
> ```Python
>             ...,
>             title="Proposal code",
>             description="Proposal code of the proposal whose progress report  [...]

2024-07-31 13:15 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322)* status: all files reviewed, 22 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2689 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37PIBV9PoA-5A5rHpa:-O37vSANBU4VGTZE6C9T:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2689)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why "any"? And shouldn't it be "Any"?
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2759 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Y7pD6dVUAtWlMF5X:-O37v5cg8IgYN4pGMY7i:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2759)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest you in the pool rules rather than creating a description.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 199 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37T9G21gQztrnFfcZm:-O37ut1Y-iDKvKIJduI4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/api/proposals.py#L199)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Get the pools in a proposal
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 206 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37TK66EIEA28Lk9BEZ:-O37umWa660CSVhXGPFJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/api/proposals.py#L206)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

progress report is > pools are
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposals.py` line 210 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37TQw61Y2oMuh0aCET:-O37umtzEa0UDJ4bYigE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/api/proposals.py#L210)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

returned proposal > proposal
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 63 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37TrpF4-YLWMYr9vun:-O37uNzG3JRehJz51CQz:b-n3bwep) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/schema/pool.py#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think "PoolAllocation" is the ideal name. Also, a pool has no priority as such.
</blockquote></details>

Please Explain more
___
*[`saltapi/web/schema/pool.py` line 67 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37TkqP4AOCE1aLbPcc:-O37uMCt1qemH0UD6hWF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/schema/pool.py#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Incorrect title and description
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 77 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37X5_yACqaP9wGIXNi:-O37u2UEEfwX8Bh4dbiQ:b-7rkfcc) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/schema/pool.py#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about the parameter
</blockquote></details>

What Parameter? Please Explain
___
*[`saltapi/web/schema/pool.py` line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37UFZOCoIluoaeoAte:-O37u-Dd8T3RtCig0pKW:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/schema/pool.py#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Incorrect docstring
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 93 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Wfs48rpNtbP_276d:-O37to7iAnBbMxlE360m:b-9wflr) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/schema/pool.py#L93)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should
</blockquote></details>

Done. I believe you mean to rename description
___
*[`saltapi/web/schema/pool.py` line 98 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37UPVqDJKSxCqNsjw5:-O37tEWw7d1tbukq_aAa:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/schema/pool.py#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Incorrect title and description
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-01 13:59 UTC, hettlage requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322)* status: all files reviewed, 21 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2689 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37PIBV9PoA-5A5rHpa:-O3DBj5gAANmgKksiqU5:by8pr4n) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2689)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change?
___
*[`saltapi/repository/proposal_repository.py` line 2759 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Y7pD6dVUAtWlMF5X:-O3DC7MY2oNsNxIMBqi-:b-wr8tyo) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2759)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This doesn't entirely address the concern.
___
*[`saltapi/web/schema/pool.py` line 93 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Wfs48rpNtbP_276d:-O3DD2ck9STUzRHDWXye:bbuvea3) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/schema/pool.py#L93)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done. I believe you mean to rename description
</blockquote></details>

Oops, sorry. But there is more to it than just renaming.
___
*[`saltapi/web/schema/pool.py` line 67 at r2](https://reviewable.io/reviews/saltastroops/salt-api/322#-O3DCcLP5SOnJciCgWPt:-O3DCcLP5SOnJciCgWPu:b-70dr97) ([raw file](https://github.com/saltastroops/salt-api/blob/dae392011f77bd3eea0428d7e595b96fe5faac25/saltapi/web/schema/pool.py#L67)):*
> ```Python
>     assigned_time: float = Field(
>         ...,
>         title="Assigned time to pool",
> ```

I'd just say "Assigned time" 
___
*[`saltapi/web/schema/pool.py` line 68 at r2](https://reviewable.io/reviews/saltastroops/salt-api/322#-O3DCrvC9S6tReZKJrTV:-O3DCrvC9S6tReZKJrTW:bw54r2u) ([raw file](https://github.com/saltastroops/salt-api/blob/dae392011f77bd3eea0428d7e595b96fe5faac25/saltapi/web/schema/pool.py#L68)):*
> ```Python
>         ...,
>         title="Assigned time to pool",
>         description="The time assigned to this pool",
> ```

Maybe: this > the
___
*[`saltapi/web/schema/pool.py` line 78 at r2](https://reviewable.io/reviews/saltastroops/salt-api/322#-O3DCzc13qqweBx_PkMM:-O3DCzc13qqweBx_PkMN:b-3bz69f) ([raw file](https://github.com/saltastroops/salt-api/blob/dae392011f77bd3eea0428d7e595b96fe5faac25/saltapi/web/schema/pool.py#L78)):*
> ```Python
> 
> class Pool(BaseModel):
>     """Proposal's pool."""
> ```

Pool in a proposal
___
*[`saltapi/web/schema/pool.py` line 98 at r2](https://reviewable.io/reviews/saltastroops/salt-api/322#-O3DDC4QC19SWeIGIfe_:-O3DDC4QC19SWeIGIfea:b-u71ni3) ([raw file](https://github.com/saltastroops/salt-api/blob/dae392011f77bd3eea0428d7e595b96fe5faac25/saltapi/web/schema/pool.py#L98)):*
> ```Python
>     blocks: List[PoolBlock] = Field(
>         ...,
>         title="Pool's blocks",
> ```

Pool blocks
___
*[`saltapi/web/schema/pool.py` line 99 at r2](https://reviewable.io/reviews/saltastroops/salt-api/322#-O3DDK9A8fT8Uk0xg_4w:-O3DDK9A8fT8Uk0xg_4x:b1wnqow) ([raw file](https://github.com/saltastroops/salt-api/blob/dae392011f77bd3eea0428d7e595b96fe5faac25/saltapi/web/schema/pool.py#L99)):*
> ```Python
>         ...,
>         title="Pool's blocks",
>         description="The pool's blocks",
> ```

The blocks in the pool


<!-- Sent from Reviewable.io -->

2024-08-12 10:34 UTC, Eb-Zeero reviewed
I will have to bring this back to you.

Been trying to figure out Block availability, I have some available blocks and the old WM show unavailable, and vice versa

Example proposal: 2024-1-MLT-006 -> Pool - Sw...44 And Pool - XM...05

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322#-:-O457PPf9zuLJjG25CE6:b-u52xxi)* status: all files reviewed, 21 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2688 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37MlV35dDRHraMqeE-:-O44RH87987EHje9fC39:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2688)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that "allocations" is an ideal name here, and I don't think the used times should be passed.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2689 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37PIBV9PoA-5A5rHpa:-O44RLkgBc0k9R3GnvuU:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2689)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see a change?
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2689 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37PZ8w5s0_Ghko4gYm:-O44RP4NDueANAdD9wPR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2689)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The method name suggests the methods deals with more than pool... Also, "allocations" might not be the ideal term.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2723 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37NfZLCRqQJC2kb3mJ:-O44UWnO3Sek4OU9lVj_:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2723)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Calling this wait is not ideal.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2730 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Ny56-JmHVA933EyQ:-O452TRE2jTRuyGfdJUv:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2730)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't this query include pools which aren't included in the most recent version of the proposal any longer?

Also, yiou don;t handle the case that there are multiple pool rules for a pool.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2751 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37QHDY1J3V4U2u1RSM:-O44eQ2l-YK_N_kxLTAC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2751)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This works, but you could have used a `defaultdict`.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2759 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Y7pD6dVUAtWlMF5X:-O452Y2FAo9zkC_o-Grz:b-hw2y19) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2759)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This doesn't entirely address the concern.
</blockquote></details>

now pool_rules which is a list
___
*[`saltapi/repository/proposal_repository.py` line 2760 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37OXVc2pcOsLp0gAi5:-O44jaU6Dt1-vvsRo7fJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2760)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think "allocations" is the correct term here.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2785 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Qt4F1IEylj4VHi9W:-O44jhOd66fdZNXkFn03:b-b7ftru) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2785)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is highly inefficient, as the method is called for every block.

Also, I'm not convinced the observability information should be passed.

Finally, arguably the method name is a bit misleading, as the method is lott concerned about pools.
</blockquote></details>

Method removed
___
*[`saltapi/repository/proposal_repository.py` line 2808 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37RVP47r6VXyXGhchV:-O44iXd26DMn1agpvKC6:b-il8smc) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2808)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Won't you get a null pointer exception if there is no block?
</blockquote></details>

no longer applicable removed
___
*[`saltapi/repository/proposal_repository.py` line 2830 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37SHTBC5tlLoTNDvFE:-O44icPX4iiIQB2VksLm:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2830)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Don't you have to take the block status into account? (Do you really want to include deleted and superseded blocks?)
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2839 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Sc717m8QPdcJ90QJ:-O44ifHOENfLk7NLhTrt:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2839)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can't the query in `_get_pool_block` be incorporated intro this method's query, making `_get_pool_block` obsolete?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 93 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37Wfs48rpNtbP_276d:-O44jn5F1XKW22EWhhaM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/schema/pool.py#L93)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oops, sorry. But there is more to it than just renaming.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 101 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37UW0yEPYngk1wbhJ_:-O44jN3YAKtq1CGjT0t3:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/web/schema/pool.py#L101)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think allocations is the ideal term.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 67 at r2](https://reviewable.io/reviews/saltastroops/salt-api/322#-O3DCcLP5SOnJciCgWPt:-O44j0SuD86iQX1Ck_se:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/dae392011f77bd3eea0428d7e595b96fe5faac25/saltapi/web/sch [...]

2024-08-16 10:48 UTC, hettlage requested changes
The old WM is using the Choice column in the BlockPool table for deciding whether a block is available.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322#-:-O4PnGza1BF-t7jpQyxJ:b736pq)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2689 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37PZ8w5s0_Ghko4gYm:-O4PetPv1UlrtfKIUVcc:bhllvey) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2689)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The method name still contains "pools"  as a plural, but isn't the method concerned with a single pool only? So shouldn't the method be called `_get_pool_times`?
___
*[`saltapi/repository/proposal_repository.py` line 2831 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PjOnJAZ3MM35UoDIZ:-O4PjOnJAZ3MM35UoDI_:bt77876) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/repository/proposal_repository.py#L2831)):*
> ```Python
>                 total_observed_time = block["total_observed_time"]
>                 total_times_per_priority[priority] += total_observed_time
>             summed_blocks = [{"priority": priority, "total_time": total_time} for priority, total_time in dict(total_times_per_priority).items()]
> ```

Maybe "priority_times" would be a bit clearer than "summed_blocks".

Also, I don't see why you convert the dict into a list, given that the `_get_pools_times`method would work better with a dict anyway.
___
*[`saltapi/web/schema/pool.py` line 67 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PlsTd6Z3fOfBcJ4yD:-O4PlsTd6Z3fOfBcJ4yE:bfda6nv) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L67)):*
> ```Python
>     assigned_time: float = Field(
>         ...,
>         title="Assigned time ",
> ```

Obsolete space after "time".
___
*[`saltapi/web/schema/pool.py` line 78 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PmOFf0Y2SgOdlF-qd:-O4PmOFf0Y2SgOdlF-qe:b-xfsbqq) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L78)):*
> ```Python
> 
> class PoolRule(BaseModel):
>     pool_rule: str = Field(
> ```

Maybe better: pool_rule > rule 
___
*[`saltapi/web/schema/pool.py` line 80 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4Pm4Hp4nnrhcX0x75Z:-O4Pm4Hp4nnrhcX0x75_:b-rj1ytg) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L80)):*
> ```Python
>     pool_rule: str = Field(
>         ...,
>         title="Pool short rule",
> ```

I'd just say "Pool rule", not least there is no long rule anywhere.
___
*[`saltapi/web/schema/pool.py` line 81 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PmXks8-wrX_mNOpiO:-O4PmXks8-wrX_mNOpiP:b72v9nt) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L81)):*
> ```Python
>         ...,
>         title="Pool short rule",
>         description="The pool's short rule",
> ```

I don't think "short" is necessary here.
___
*[`saltapi/web/schema/pool.py` line 83 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PmenYE0pTn806Awgl:-O4PmenYE0pTn806Awgm:bf1fceq) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L83)):*
> ```Python
>         description="The pool's short rule",
>     )
>     pool_rule_parameter: Optional[int] = Field(
> ```

Maybe better: pool_rule_parameter > rule_parameter
___
*[`saltapi/web/schema/pool.py` line 85 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4Pmq6p0aZeM2ABD1-o:-O4Pmq6p0aZeM2ABD1-p:b-h9jpck) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L85)):*
> ```Python
>     pool_rule_parameter: Optional[int] = Field(
>         ...,
>         title="Argument applied to this rule",
> ```

Maybe better: Parameter for the rule
___
*[`saltapi/web/schema/pool.py` line 86 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4Pmy8f4Lg6huuse5Ef:-O4Pmy8f4Lg6huuse5Eg:b-tejmyt) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L86)):*
> ```Python
>         ...,
>         title="Argument applied to this rule",
>         description="The argument applied to this rule"
> ```

Maybe better: The parameter for the rule


<!-- Sent from Reviewable.io -->

2024-08-16 12:23 UTC, Eb-Zeero reviewed
I believe you said you would check this with Encarni.. Still waiting on you

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322#-:-O4Q7JNzC-QUz0HpOuMm:b-ftp5n7)* status: all files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2689 at r1](https://reviewable.io/reviews/saltastroops/salt-api/322#-O37PZ8w5s0_Ghko4gYm:-O4Q3AZx5ykKIaN9i0Wn:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/2e06135f39554d95cf3ea7be7d0dc68962fb6d71/saltapi/repository/proposal_repository.py#L2689)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The method name still contains "pools"  as a plural, but isn't the method concerned with a single pool only? So shouldn't the method be called `_get_pool_times`?
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2831 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PjOnJAZ3MM35UoDIZ:-O4Q5kpw4fkq_Ty8vVGy:b7j8sm9) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/repository/proposal_repository.py#L2831)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe "priority_times" would be a bit clearer than "summed_blocks".

Also, I don't see why you convert the dict into a list, given that the `_get_pools_times`method would work better with a dict anyway.
</blockquote></details>

having this will make the schema complicated, at most it will be like this: 
{
   0: null | 0,          || priority_0: null | 0
   1: 100,
   2: null | 0,
   3: null | 0,
   4: null | 0,
}
which will be different from rather schemas when it comes to priority
___
*[`saltapi/web/schema/pool.py` line 67 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PlsTd6Z3fOfBcJ4yD:-O4Q3osAAEdDVf8zXrqI:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Obsolete space after "time".
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 78 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PmOFf0Y2SgOdlF-qd:-O4Q45i47xexewYZ4crr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: pool_rule > rule
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 80 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4Pm4Hp4nnrhcX0x75Z:-O4Q4InY-m4Rg2EPkdOu:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd just say "Pool rule", not least there is no long rule anywhere.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 81 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PmXks8-wrX_mNOpiO:-O4Q4OAZ5oP2TjxhJmxj:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L81)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think "short" is necessary here.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 83 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PmenYE0pTn806Awgl:-O4Q4ZqB1KZpRF1Pqhs4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: pool_rule_parameter > rule_parameter
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 85 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4Pmq6p0aZeM2ABD1-o:-O4Q4kCI1V-Qv437JZ6k:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: Parameter for the rule
</blockquote></details>

Done.
___
*[`saltapi/web/schema/pool.py` line 86 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4Pmy8f4Lg6huuse5Ef:-O4Q4nhH32pyWh_Z7BfG:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/web/schema/pool.py#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: The parameter for the rule
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-19 07:39 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2831 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PjOnJAZ3MM35UoDIZ:-O4dZEUiA56MvLFfR0Ni:b-n767g6) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/repository/proposal_repository.py#L2831)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

having this will make the schema complicated, at most it will be like this: 
{
   0: null | 0,          || priority_0: null | 0
   1: 100,
   2: null | 0,
   3: null | 0,
   4: null | 0,
}
which will be different from rather schemas when it comes to priority
</blockquote></details>

I wasn't talking about the schema but about the data structure within this method and `_get_pools_times`.
___
*[`saltapi/repository/proposal_repository.py` line 2812 at r4](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4dYLfZ4Y3K72m89efx:-O4dYLfZ4Y3K72m89efy:b-55unug) ([raw file](https://github.com/saltastroops/salt-api/blob/d0ee722da7aef6570a182ab2f638f63267ae7ec6/saltapi/repository/proposal_repository.py#L2812)):*
> ```Python
> WHERE PC.Proposal_Code = :proposal_code
>     AND CONCAT(S.Year, '-', S.Semester) = :semester
>     AND P.Current = 1
> ```

This query assumes that every submission creates new pool entries in the database. But that is not the case, and hence limiting the query to the current proposal implies that you may miss pools. This can be seen, for example, for 2021-2-LSP-001.


<!-- Sent from Reviewable.io -->

2024-08-22 09:13 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2831 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PjOnJAZ3MM35UoDIZ:-O4pF7XZ-2vnS9PlcEBA:b-bpfilh) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/repository/proposal_repository.py#L2831)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wasn't talking about the schema but about the data structure within this method and `_get_pools_times`.
</blockquote></details>

This more like conveting from {p0: 100, p1:0, ....} to [{priority: 0, total_time: 100 }, ...]

the reason I don't want to query the blocks twice chance I manipulate them here and pass only the results I need to the  _get_pool_times method
___
*[`saltapi/repository/proposal_repository.py` line 2812 at r4](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4dYLfZ4Y3K72m89efx:-O4pHMX72pHn1r_ighiE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d0ee722da7aef6570a182ab2f638f63267ae7ec6/saltapi/repository/proposal_repository.py#L2812)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This query assumes that every submission creates new pool entries in the database. But that is not the case, and hence limiting the query to the current proposal implies that you may miss pools. This can be seen, for example, for 2021-2-LSP-001.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-22 15:03 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2831 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PjOnJAZ3MM35UoDIZ:-O4ub72g79GZxsqu8LPe:bv7ql8v) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/repository/proposal_repository.py#L2831)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

This more like conveting from {p0: 100, p1:0, ....} to [{priority: 0, total_time: 100 }, ...]

the reason I don't want to query the blocks twice chance I manipulate them here and pass only the results I need to the  _get_pool_times method
</blockquote></details>

I had another look and I'm not convinced. Let's discuss tomorrow.
___
*[`saltapi/repository/proposal_repository.py` line 2834 at r5](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4u_emJ05MA9J5AjkLc:-O4u_emJ05MA9J5AjkLd:b-ks2fo3) ([raw file](https://github.com/saltastroops/salt-api/blob/499698b02b2f4dad523001f5fdcb6b9e71b4edef/saltapi/repository/proposal_repository.py#L2834)):*
> ```Python
>                 for priority, total_time in dict(total_times_per_priority).items()
>             ]
>             print(row.id)
> ```

Unnecessary print statement
___
*[`saltapi/web/api/users.py` line 98 at r5](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4u_t1M3iIx6fLziKAm:-O4u_t1M3iIx6fLziKAn:bxeshcr) ([raw file](https://github.com/saltastroops/salt-api/blob/499698b02b2f4dad523001f5fdcb6b9e71b4edef/saltapi/web/api/users.py#L98)):*
> ```Python
>             pipt_user_id, f"{user.family_name} {user.given_name}", user.email
>         )
>         # unit_of_work.commit()
> ```

Why did you comment this line out?


<!-- Sent from Reviewable.io -->

2024-08-26 11:20 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2831 at r3](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4PjOnJAZ3MM35UoDIZ:-O5DPWnZ88Ws_-45939W:b-3gkrav) ([raw file](https://github.com/saltastroops/salt-api/blob/386f2bf81b732489f92ca20f569a001f3ab58a4d/saltapi/repository/proposal_repository.py#L2831)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I had another look and I'm not convinced. Let's discuss tomorrow.
</blockquote></details>

please lets discuss
___
*[`saltapi/repository/proposal_repository.py` line 2834 at r5](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4u_emJ05MA9J5AjkLc:-O5DPUqYBg2VhMPYLlgk:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/499698b02b2f4dad523001f5fdcb6b9e71b4edef/saltapi/repository/proposal_repository.py#L2834)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary print statement
</blockquote></details>

removed
___
*[`saltapi/web/api/users.py` line 98 at r5](https://reviewable.io/reviews/saltastroops/salt-api/322#-O4u_t1M3iIx6fLziKAm:-O5DPNTfEtsZWBWwwBCv:b8xwn39) ([raw file](https://github.com/saltastroops/salt-api/blob/499698b02b2f4dad523001f5fdcb6b9e71b4edef/saltapi/web/api/users.py#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why did you comment this line out?
</blockquote></details>

thanks for picking it up from a wrong stash


<!-- Sent from Reviewable.io -->

2024-08-28 15:10 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2689 at r6](https://reviewable.io/reviews/saltastroops/salt-api/322#-O5OX4qo6MJHPxgwH7f6:-O5OX4qp8QUQnipXJeO5:bwyw3km) ([raw file](https://github.com/saltastroops/salt-api/blob/4c2a48f90af21677d6528828625b88900a72735d/saltapi/repository/proposal_repository.py#L2689)):*
> ```Python
>             raise NotFoundError()
> 
>     def _get_pool_times(self, pool_id: int, total_times_per_priority: Dict[str, int]):
> ```

Is the priority really a string?


<!-- Sent from Reviewable.io -->

2024-08-28 16:34 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2689 at r6](https://reviewable.io/reviews/saltastroops/salt-api/322#-O5OX4qo6MJHPxgwH7f6:-O5Op_4U9t1qlWWrRzAK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4c2a48f90af21677d6528828625b88900a72735d/saltapi/repository/proposal_repository.py#L2689)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is the priority really a string?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-29 07:52 UTC, hettlage approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/322)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2024-08-29 07:53 UTC, merged