P1 instrument configuration
saltastroops/salt-api pull request #327
Opened 2024-10-11 07:45 UTC by Eb-Zeero

2024-10-11 09:40 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/327)* status: all files reviewed, 15 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2461 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uprX09OPokEt-3MLa:-O8uprX09OPokEt-3MLb:bcc8u46) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2461)):*
> ```Python
>         return simulations
> 
>     def _get_p1_bvit_filter(self, bvit_id: int):
> ```

filter > filters
___
*[`saltapi/repository/proposal_repository.py` line 2501 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uqq4N1zW6CxXKYorX:-O8uqq4N1zW6CxXKYorY:b-ea7ccf) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2501)):*
> ```Python
>         )
>         result = self.connection.execute(stmt, {"proposal_code": proposal_code})
>         return [
> ```

You are missing the MOS mask description (as per the MosDescription column in the P1RssMask table).
___
*[`saltapi/repository/proposal_repository.py` line 2511 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uq-392wvi-aKztFGE:-O8uq-3A79q5n-lMIeWH:bcc8u46) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2511)):*
> ```Python
>         ]
> 
>     def _get_p1_scam_filter(self, scam_id: int):
> ```

filter > filters
___
*[`saltapi/repository/proposal_repository.py` line 2570 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8urZVd8tzhLF9tmJhD:-O8urZVd8tzhLF9tmJhE:brvbt0c) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2570)):*
> ```Python
>             filters = []
>             if row.bvit:
>                 configuration_number = row.bvit
> ```

I don't think the configuration number (which rather is configuration _id_) adds much value. and I wouldn't include it.
___
*[`saltapi/repository/proposal_repository.py` line 2591 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8usAM81Uu_cW39JF57:-O8usAM81Uu_cW39JF58:biayb0v) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2591)):*
> ```Python
>                 detector_mode = row.rss_detector_mode
>                 simulations = self._get_rss_simulations(proposal_code)
>                 rss_p1_configurations = self._get_p1_rss_config(proposal_code)
> ```

The name `rss_p1_configurations` is too general. This is rather an `rss_mode_configuration` (and it  is only _one_, isn't it?).
___
*[`saltapi/repository/rss_repository.py` line 159 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uv5bvBU1iFo95u8v3:-O8uv5bvBU1iFo95u8v4:b-pld3ai) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/rss_repository.py#L159)):*
> ```Python
>         return None
> 
>     def _mos_mask(self, row: Any) -> Optional[Dict[str, Any]]:
> ```

I don't think there have to be separate functions.
___
*[`saltapi/repository/rss_repository.py` line 184 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uunk58aRwVmKH903s:-O8uunk58aRwVmKH903t:br9fol2) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/rss_repository.py#L184)):*
> ```Python
>             "filter": row.filter,
>             "mask": self._mask(row),
>             "mos_mask": self._mos_mask(row),
> ```

As noted elsewhere, I don't think "mask" and "mos_mask" should be separate.
___
*[`saltapi/web/api/proposals.py` line 195 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uvIsz5PxLaryUJcug:-O8uvIt-1mkSzlOrZ8dU:blqmq4g) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/api/proposals.py#L195)):*
> ```Python
>             return P1Proposal(**proposal)
>         if proposal["phase"] == 2:
>             return P1Proposal(**proposal)
> ```

Shouldn't that be "P2"?
___
*[`saltapi/web/schema/p1_proposal.py` line 38 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uvVLv2rL1s8ZDbPyI:-O8uvVLw4f1ImeRs_5XD:b-xnks9z) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L38)):*
> ```Python
>         ..., title="ToO reason", description="Reason for ToO flag"
>     )
> class RssP1Configuration(BaseModel):
> ```

Shouldn't this be called "P1RssConfiguration"?
___
*[`saltapi/web/schema/p1_proposal.py` line 45 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uvd033m95KUXiZ_tB:-O8uvd033m95KUXiZ_tC:b-jqs7ir) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L45)):*
> ```Python
>         ..., title="Mask type", description="The mask type"
>     )
>     pattern_name: Optional[str] = Field(
> ```

It is unclear what pattern this is? (I guess it is the polarimetry pattern?)
___
*[`saltapi/web/schema/p1_proposal.py` line 49 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uvsUd05MEjquxWUxa:-O8uvsUd05MEjquxWUxb:b2mld1h) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L49)):*
> ```Python
>     )
>     fabry_perot_mode: Optional[str] = Field(
>         ..., title="Fabry perot mode", description="The fabry perot mode"
> ```

Fabry perot > Fabry-Pérot

fabry perot > Fabry-Pérot
___
*[`saltapi/web/schema/p1_proposal.py` line 75 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uwVqNA4HQ54_WNIFZ:-O8uwVqNA4HQ54_WNIF_:b-yn6zni) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L75)):*
> ```Python
>         ..., title="Simulations", description="The simulations for the proposal."
>     )
>     rss_p1_configurations: List[RssP1Configuration] = Field(
> ```

Isn't this the RSS mode configuration rather? And can there really be more than one?

Also, I don't think the "P1" should be included in the name.
___
*[`saltapi/web/schema/p1_proposal.py` line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uwbZJDC-TqerbNAVB:-O8uwbZJDC-TqerbNAVC:btoyv3x) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L78)):*
> ```Python
>         ..., title="RSS P1 Configurations", description="The RSS P1 Configurations"
>     )
>     configuration_number: int = Field(
> ```

I don't think the configuration number is required.
___
*[`saltapi/web/schema/rss.py` line 170 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8utASk5jsXhbLXM3uT:-O8utASk5jsXhbLXM3uU:b-u0w30s) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/rss.py#L170)):*
> ```Python
>         ..., title="Slit mask", description="Slit mask"
>     )
>     mos_mask: Optional[RssMosMask] = Field(
> ```

I don't think this change is correct; as now you could have both a mask and a MOS mask.
___
*[`saltapi/web/schema/rss.py` line 171 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8utQhx39NVOIf3BQWi:-O8utQhx39NVOIf3BQWj:bu351ob) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/rss.py#L171)):*
> ```Python
>     )
>     mos_mask: Optional[RssMosMask] = Field(
>         ..., title="Mos slit mask", description="Mos slit mask"
> ```

Mos > MOS


<!-- Sent from Reviewable.io -->

2024-10-11 09:45 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/327)* status: all files reviewed, 16 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/schema/p1_proposal.py` line 38 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uvVLv2rL1s8ZDbPyI:-O8uxg185PViNiu8E11c:b1riylf) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be called "P1RssConfiguration"?
</blockquote></details>

Also isn't this the "P1RssModeConfiguration"  rather?
___
*[`saltapi/web/schema/p1_proposal.py` line 38 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uxqSwA-tp9khs5XPp:-O8uxqSwA-tp9khs5XPq:btms0t9) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L38)):*
> ```Python
>         ..., title="ToO reason", description="Reason for ToO flag"
>     )
> class RssP1Configuration(BaseModel):
> ```

A general concern: Should all the different instruments really be lumped together into a single configuration type?


<!-- Sent from Reviewable.io -->

2024-10-11 09:50 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/327)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/web/schema/p1_proposal.py` line 64 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uyuDBAtbiZaSOtJgD:-O8uyuDBAtbiZaSOtJgE:b-xf3d6c) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L64)):*
> ```Python
>         title="Configuration mode",
>         description=(
>             "The configuration mode. This is the filter for BVIT, the exposure mode for"
> ```

This comment is a rather good motivation for splitting this type into instrument-specific ones...


<!-- Sent from Reviewable.io -->

2024-10-15 13:03 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/327)* status: all files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2549 at r2](https://reviewable.io/reviews/saltastroops/salt-api/327#-O9FFRpZ8t2fxhHs_bCf:-O9FFRpZ8t2fxhHs_bCg:b-tnof6a) ([raw file](https://github.com/saltastroops/salt-api/blob/c0fd8ceb7fa8ed0f3df5e3704c11382ed9b11152/saltapi/repository/proposal_repository.py#L2549)):*
> ```Python
>         for row in self.connection.execute(stmt, {"proposal_code": proposal_code}):
>             if row.bvit:
>                 configurations.append({
> ```

I don't think this is optional. Each configuration should be an instrument rather than a dictionary of instruments.
___
*[`saltapi/web/schema/p1_proposal.py` line 87 at r2](https://reviewable.io/reviews/saltastroops/salt-api/327#-O9FGGyI8xd81DJe7_xl:-O9FGGyI8xd81DJe7_xm:b-njyu8b) ([raw file](https://github.com/saltastroops/salt-api/blob/c0fd8ceb7fa8ed0f3df5e3704c11382ed9b11152/saltapi/web/schema/p1_proposal.py#L87)):*
> ```Python
> 
> 
> class ScienceConfiguration(BaseModel):
> ```

I think the science configuration should be a union of the instrument types.


<!-- Sent from Reviewable.io -->

2024-10-17 10:54 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/327)* status: 3 of 5 files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2461 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uprX09OPokEt-3MLa:-O99Nz_KDKqquaiC1sO5:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2461)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

filter > filters
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2501 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uqq4N1zW6CxXKYorX:-O99V8rm-m6Pp3W6AmKx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2501)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are missing the MOS mask description (as per the MosDescription column in the P1RssMask table).
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2511 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uq-392wvi-aKztFGE:-O99OBkK7f4GF3tp6OPK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2511)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

filter > filters
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2570 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8urZVd8tzhLF9tmJhD:-O99VMY6CmGaDgQNZgiX:b-z7qbr0) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2570)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the configuration number (which rather is configuration _id_) adds much value. and I wouldn't include it.
</blockquote></details>

the ID is a combination of keys from different tables
this number determines the configuration order.
___
*[`saltapi/repository/proposal_repository.py` line 2591 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8usAM81Uu_cW39JF57:-O99OI7n8HQFlXDCf2eT:bppsgvl) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2591)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name `rss_p1_configurations` is too general. This is rather an `rss_mode_configuration` (and it  is only _one_, isn't it?).
</blockquote></details>

yes it is but db allows many
___
*[`saltapi/repository/proposal_repository.py` line 2549 at r2](https://reviewable.io/reviews/saltastroops/salt-api/327#-O9FFRpZ8t2fxhHs_bCf:-O9P6CvSC1RpY0fUMPYO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c0fd8ceb7fa8ed0f3df5e3704c11382ed9b11152/saltapi/repository/proposal_repository.py#L2549)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this is optional. Each configuration should be an instrument rather than a dictionary of instruments.
</blockquote></details>

Done.
___
*[`saltapi/repository/rss_repository.py` line 159 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uv5bvBU1iFo95u8v3:-O9F6ojj7nkN6nDzhqV8:b4xbfkz) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/rss_repository.py#L159)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think there have to be separate functions.
</blockquote></details>

ve could say the same with other configurations as they are from the same row.
___
*[`saltapi/repository/rss_repository.py` line 184 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uunk58aRwVmKH903s:-O9F6yXR5AuU-I3pnlQd:balfoqc) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/rss_repository.py#L184)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As noted elsewhere, I don't think "mask" and "mos_mask" should be separate.
</blockquote></details>

they are two different things to what I can see
___
*[`saltapi/web/schema/p1_proposal.py` line 38 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uvVLv2rL1s8ZDbPyI:-O99PhQA7azKe88ww0i6:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Also isn't this the "P1RssModeConfiguration"  rather?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/p1_proposal.py` line 38 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uxqSwA-tp9khs5XPp:-O9F75-l2oXmhEb5UGst:b-tz2jv2) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A general concern: Should all the different instruments really be lumped together into a single configuration type?
</blockquote></details>

now separated
___
*[`saltapi/web/schema/p1_proposal.py` line 45 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uvd033m95KUXiZ_tB:-O99XxhO2IgjYlZY4WrV:b-a0fkin) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It is unclear what pattern this is? (I guess it is the polarimetry pattern?)
</blockquote></details>

yes it is
___
*[`saltapi/web/schema/p1_proposal.py` line 49 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uvsUd05MEjquxWUxa:-O99R8XmA0oQRVH8Djse:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Fabry perot > Fabry-Pérot

fabry perot > Fabry-Pérot
</blockquote></details>

Done.
___
*[`saltapi/web/schema/p1_proposal.py` line 64 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uyuDBAtbiZaSOtJgD:-O9F5zSaB1kgF9BCApki:b2filjo) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This comment is a rather good motivation for splitting this type into instrument-specific ones...
</blockquote></details>

splited
___
*[`saltapi/web/schema/p1_proposal.py` line 75 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uwVqNA4HQ54_WNIFZ:-O9P6OK36iDl_FHBRT8D:b-886gsx) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't this the RSS mode configuration rather? And can there really be more than one?

Also, I don't think the "P1" should be included in the name.
</blockquote></details>

Fixed
___
*[`saltapi/web/schema/p1_proposal.py` line 78 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uwbZJDC-TqerbNAVB:-O9F6adM18mmDSrGTsez:b-hfpv0l) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/p1_proposal.py#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the configuration number is required.
</blockquote></details>

removed
___
*[`saltapi/web/schema/p1_proposal.py` line [...]

2024-10-18 10:12 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/327)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 2570 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8urZVd8tzhLF9tmJhD:-O9U4ltL4A9BZdvq6czO:bqh9a98) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2570)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

the ID is a combination of keys from different tables
this number determines the configuration order.
</blockquote></details>

I think the comment is moot now, given that the configuration id seems to have been removed? :-)
___
*[`saltapi/repository/proposal_repository.py` line 2591 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8usAM81Uu_cW39JF57:-O9U57voCC_c4ExXLgc0:b-eaqesb) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2591)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

yes it is but db allows many
</blockquote></details>

I think this comment is moot now?
___
*[`saltapi/repository/rss_repository.py` line 159 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uv5bvBU1iFo95u8v3:-O9U5U-TDbNT7ytJmsAt:b8exo57) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/rss_repository.py#L159)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

ve could say the same with other configurations as they are from the same row.
</blockquote></details>

I think this is closely linked whether to have separate fields for "masks" and "MOS masks".
___
*[`saltapi/repository/rss_repository.py` line 184 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uunk58aRwVmKH903s:-O9U5f_t0W4snMxnlaRR:b-ec7l2n) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/rss_repository.py#L184)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

they are two different things to what I can see
</blockquote></details>

Not quite, because logically every MOS mask is a mask.
___
*[`saltapi/web/schema/p1_proposal.py` line 102 at r3](https://reviewable.io/reviews/saltastroops/salt-api/327#-O9U1i6R0W2IojVUbc5f:-O9U1i6S8IdGaN80wube:bnab6g8) ([raw file](https://github.com/saltastroops/salt-api/blob/e064821e933389a074b820ebc6825d5fbb5d62d4/saltapi/web/schema/p1_proposal.py#L102)):*
> ```Python
> 
> 
> class ScienceConfiguration(BaseModel):
> ```

I don't think this type is necessary any longer.
___
*[`saltapi/web/schema/rss.py` line 170 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8utASk5jsXhbLXM3uT:-O9U1u890nKbc8z_gLnM:b-tq43og) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/rss.py#L170)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this comes from a different PR, somehow slipped in. 
And it is still valid the mos slit mask and the slit mask are completely different and  they need to be done like so.

if you don't mind I would like to keep it here as this will be the only change on the backend to fix the frontend on the PR we need to discuss which is not yet opened
</blockquote></details>

While I don't object to dealing with this later, I still think that having separate fields for "masks" and "MOS masks" is ideal. 


<!-- Sent from Reviewable.io -->

2024-10-29 13:58 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/327)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 2570 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8urZVd8tzhLF9tmJhD:-OANWrBMDVaTKDe1XH2t:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2570)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the comment is moot now, given that the configuration id seems to have been removed? :-)
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 2591 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8usAM81Uu_cW39JF57:-OANWsLVDqSUd_r0Zx9g:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/proposal_repository.py#L2591)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this comment is moot now?
</blockquote></details>

Done.
___
*[`saltapi/repository/rss_repository.py` line 159 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uv5bvBU1iFo95u8v3:-OANWxMI3cPyuEWGOCeS:b2eryqr) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/rss_repository.py#L159)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this is closely linked whether to have separate fields for "masks" and "MOS masks".
</blockquote></details>

Can I deal with this comment on different PR it will not affect anything on this PR
___
*[`saltapi/repository/rss_repository.py` line 184 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uunk58aRwVmKH903s:-OANY5L4DWYtu0E3I_-D:b-tajpy1) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/rss_repository.py#L184)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Not quite, because logically every MOS mask is a mask.
</blockquote></details>

Can I please Address this on a different PR.
work on this from a different PR
___
*[`saltapi/web/schema/p1_proposal.py` line 102 at r3](https://reviewable.io/reviews/saltastroops/salt-api/327#-O9U1i6R0W2IojVUbc5f:-OANYT3eCIg2IaL0Y56H:b-l9tgnp) ([raw file](https://github.com/saltastroops/salt-api/blob/e064821e933389a074b820ebc6825d5fbb5d62d4/saltapi/web/schema/p1_proposal.py#L102)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this type is necessary any longer.
</blockquote></details>

I am lost why do you say so
___
*[`saltapi/web/schema/rss.py` line 170 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8utASk5jsXhbLXM3uT:-OANYd8K730PmIJYQN-r:b-jmgmeq) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/web/schema/rss.py#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

While I don't object to dealing with this later, I still think that having separate fields for "masks" and "MOS masks" is ideal.
</blockquote></details>

reverting back


<!-- Sent from Reviewable.io -->

2024-10-29 14:03 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/327)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/rss_repository.py` line 159 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uv5bvBU1iFo95u8v3:-OANZoGy35bf13oMXBF6:bqnn4s0) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/rss_repository.py#L159)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Can I deal with this comment on different PR it will not affect anything on this PR
</blockquote></details>

reverting back doesn't belong to this PR
___
*[`saltapi/repository/rss_repository.py` line 184 at r1](https://reviewable.io/reviews/saltastroops/salt-api/327#-O8uunk58aRwVmKH903s:-OANZwhbB0AeNceN2ql-:bnkp8hd) ([raw file](https://github.com/saltastroops/salt-api/blob/a16c1356bb32f6eb8093d98582b56cdc89ba0a02/saltapi/repository/rss_repository.py#L184)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Can I please Address this on a different PR.
work on this from a different PR
</blockquote></details>

reverting back Doesnt belong to this PR


<!-- Sent from Reviewable.io -->

2024-10-30 07:20 UTC, hettlage approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/327)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2024-11-01 07:22 UTC, merged