Mos page data
saltastroops/salt-api pull request #40
Opened 2022-02-09 16:34 UTC by Eb-Zeero

2022-02-10 10:29 UTC, hettlage requested changes
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: 8 of 9 files reviewed, 8 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/util.py, line 136 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvXcaw9AjLd_YX9kVvw:-MvXcaw9AjLd_YX9kVvx:b-heptsj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/util.py#L136)):*
> ```Python
> 
> 
> def list_search(array: List, value: any, key: str):
> ```

I don't think this function is necessary; you can achieve the same with the built-in `index` method for lists.
___
*[saltapi/repository/mos_repository.py, line 91 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY9ARNBjXjFMdlo8yN:-MvY9ARNBjXjFMdlo8yO:b-36lint) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/repository/mos_repository.py#L91)):*
> ```Python
>         return mask
> 
>     def _get_mask_in_magazine(self):
> ```

This isn't really a MOS function, as it is for RSS masks in general. (And we should discuss how to deal with it... ;-))
___
*[saltapi/repository/mos_repository.py, line 109 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY0F7UBbn5K2-Xtxup:-MvY0F7UBbn5K2-Xtxuq:blaob9e) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/repository/mos_repository.py#L109)):*
> ```Python
>             self,
>             semester: str,
>             include_next_semester: Optional[bool],
> ```

I think it would make more sense to pass a list of semesters instead.
___
*[saltapi/service/mos_service.py, line 12 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY15WNCZDaQI8xJpcD:-MvY15WNCZDaQI8xJpcE:blaob9e) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/service/mos_service.py#L12)):*
> ```Python
>     def get_mos_data(
>             self,
>             semester: str,
> ```

I think it would make more sense to pass a list of semesters instead.
___
*[saltapi/web/api/mos.py, line 24 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY5AfrEX2otCfiajNt:-MvY5AfrEX2otCfiajNu:b-q02m5s) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/web/api/mos.py#L24)):*
> ```Python
>     user: User = Depends(get_current_user),
>     semester: Semester = Body(..., title="Semester", description="Semester"),
>     include_next_semester: Optional[bool] = Body(..., title="Next semester", description="Is next semester included"),
> ```

I think it would make more sense to pass a list of semesters instead.

See [https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#query-parameter-list-multiple-values](https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#query-parameter-list-multiple-values).
___
*[saltapi/web/schema/mos.py, line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvXaMao4PWqR-qx5aHs:-MvXaMao4PWqR-qx5aHt:b-z34tj7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/web/schema/mos.py#L10)):*
> ```Python
>     proposal_id: int = Field(..., title="Proposal id", description="The proposal id")
>     proposal_code: str = Field(..., title="Proposal code", description="The proposal code")
>     proposal_code_id: int = Field(..., title="Proposal code id", description="The proposal code id")
> ```

This might need discussion, as most of the properties don't belong to a slit mask.
___
*[saltapi/web/schema/mos.py, line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY8b3eChra3LVvCDmr:-MvY8b3eChra3LVvCDms:b-ghnrg6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/web/schema/mos.py#L29)):*
> ```Python
>     """Mos Data."""
> 
>     mos_data: List[SlitMask] = Field(
> ```

Might need discussion.
___
*[tests/test_util.py, line 97 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvXczfD767mn03ahY0W:-MvXczfD767mn03ahY0X:bnfyxw7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/tests/test_util.py#L97)):*
> ```Python
> 
> 
> def test_list_search_return_correct_results() -> None:
> ```

See my comment on util.py.


<!-- Sent from Reviewable.io -->

2022-02-14 09:04 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: 1 of 9 files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[saltapi/util.py, line 136 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvXcaw9AjLd_YX9kVvw:-MvrD1uA3YKXngYoqSZB:b-dmxihp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/util.py#L136)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this function is necessary; you can achieve the same with the built-in `index` method for lists.
</blockquote></details>

we dicussed
___
*[saltapi/repository/mos_repository.py, line 91 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY9ARNBjXjFMdlo8yN:-Mvr5VJi2igiTYE7wPw1:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/repository/mos_repository.py#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This isn't really a MOS function, as it is for RSS masks in general. (And we should discuss how to deal with it... ;-))
</blockquote></details>

Done.
___
*[saltapi/repository/mos_repository.py, line 109 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY0F7UBbn5K2-Xtxup:-MvrCia40U-GU-U_jIYM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/repository/mos_repository.py#L109)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think it would make more sense to pass a list of semesters instead.
</blockquote></details>

Done.
___
*[saltapi/service/mos_service.py, line 12 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY15WNCZDaQI8xJpcD:-MvrCkGp6JpiHOC2cajP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/service/mos_service.py#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think it would make more sense to pass a list of semesters instead.
</blockquote></details>

Done.
___
*[saltapi/web/api/mos.py, line 24 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY5AfrEX2otCfiajNt:-MvrCmDe0Dxnz5xtcqL7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/web/api/mos.py#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think it would make more sense to pass a list of semesters instead.

See [https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#query-parameter-list-multiple-values](https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#query-parameter-list-multiple-values).
</blockquote></details>

Done.
___
*[saltapi/web/schema/mos.py, line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvXaMao4PWqR-qx5aHs:-MvrCqWW0Jo_H_TccOLG:byrfnmw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/web/schema/mos.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This might need discussion, as most of the properties don't belong to a slit mask.
</blockquote></details>

Calling ir MosBLock now
___
*[saltapi/web/schema/mos.py, line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY8b3eChra3LVvCDmr:-MvrCw0UBr8n3gACGW5t:boftma7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/web/schema/mos.py#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might need discussion.
</blockquote></details>

now mos block
___
*[tests/test_util.py, line 97 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvXczfD767mn03ahY0W:-MvrCzXuCKm0URVbbLx-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/tests/test_util.py#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See my comment on util.py.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-14 11:10 UTC, hettlage requested changes
> Reviewed 2 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: all files reviewed, 18 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/repository/mos_repository.py, line 67 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrXeQ17LwxBf8MalJD:-MvrXeQ2EOK85EzepGso:b-2l1h2t) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L67)):*
> ```Python
>             proposal_code_ids.append(row.proposal_code_id)
> 
>         qsla = text("""
> ```

"qsla" might be a bit of a cryptic variable name...
___
*[saltapi/repository/mos_repository.py, line 77 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrYgKS4Nh4nwiwGzTC:-MvrYgKS4Nh4nwiwGzTD:bwa7kd3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L77)):*
> ```Python
>         """)
>         results = self.connection.execute(qsla, {"proposal_code_ids": tuple(proposal_code_ids)})
>         liaison_astronomers = [dict(row) for row in results]
> ```

Wouldn't it make more sense to create a dictionary of proposal code ids and liaison astronomers?
___
*[saltapi/repository/mos_repository.py, line 81 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrY1kmBRbK6NmCnzu8:-MvrY1kmBRbK6NmCnzu9:b-fc9abv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L81)):*
> ```Python
>         mask = []
>         for m in mask_data:
>             la = next((x for x in liaison_astronomers if x["proposal_code_id"] == m["proposal_code_id"]), [None])
> ```

Why do you return a list if no astronomer is found?
___
*[saltapi/repository/mos_repository.py, line 82 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrZG0c8n0VzR_Gkk6f:-MvrZG0c8n0VzR_Gkk6g:b-t7i66n) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L82)):*
> ```Python
>         for m in mask_data:
>             la = next((x for x in liaison_astronomers if x["proposal_code_id"] == m["proposal_code_id"]), [None])
>             m["liaison_astronomers"] = la["surname"]
> ```

I guess this will fall over if there is no liaison astronomer.
___
*[saltapi/web/api/mos.py, line 23 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrsRfO3tW8ImGODbLQ:-MvrsRfP1iXYNclcugJq:by2uwk8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/api/mos.py#L23)):*
> ```Python
> def get_mos_data(
>     user: User = Depends(get_current_user),
>     semesters: List[Semester] = Body(..., title="Semester", description="Semester", embed=True)
> ```

Wouldn't you rather pass the semesters as query parameters?
___
*[saltapi/web/api/mos.py, line 26 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvrscee4014YvYAqvhn:-Mvrscee4014YvYAqvho:b-fgpoua) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/api/mos.py#L26)):*
> ```Python
> ) -> List[MosBlock]:
>     """
>     Get MOS block.
> ```

Get a list of blocks using MOS.
___
*[saltapi/web/api/mos.py, line 36 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvrsrqm4x-y7w4J1H1L:-Mvrsrqm4x-y7w4J1H1M:bin15ah) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/api/mos.py#L36)):*
> ```Python
>         mos_service = services.mos_service(unit_of_work.connection)
>         mos_data = mos_service.get_mos_data(semesters)
>         return [MosBlock(**i) for i in mos_data]
> ```

Why `i`, given its associated with looping over integers?
___
*[saltapi/web/schema/mos.py, line 8 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvrt8WT8Dwm55wJFtV6:-Mvrt8WU5cPU26Zr7PW_:b-e0k7k7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L8)):*
> ```Python
> 
> class MosBlock(BaseModel):
>     """MOS data."""
> ```

MOS data for a block.
___
*[saltapi/web/schema/mos.py, line 14 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrtfPDEMrxAbJY3UXX:-MvrtfPDEMrxAbJY3UXY:b-lbcyb4) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L14)):*
> ```Python
>     pi_surname: str = Field(..., title="Principal investigator's surname", description="The principal investigator's surname")
>     block_status: str = Field(..., title="Block status", description="The block status")
>     status: str = Field(..., title="Status", description="The status")
> ```

The "status" of what?
___
*[saltapi/web/schema/mos.py, line 19 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrtqBb2LzdZvafPbGl:-MvrtqBb2LzdZvafPbGm:b-46bm61) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L19)):*
> ```Python
>     n_visits: int = Field(..., title="Number of visits", description="The number of visits")
>     n_done: int = Field(..., title="Number of completed visits", description="The number of completed visits")
>     mask_id: int = Field(..., title="Mask id", description="The mask id")
> ```

Is the mask_id really needed?
___
*[saltapi/web/schema/mos.py, line 21 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrtK9nBfzWqdS3IynR:-MvrtK9nBfzWqdS3IynS:bx3qxhf) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L21)):*
> ```Python
>     mask_id: int = Field(..., title="Mask id", description="The mask id")
>     barcode: str = Field(..., title="Barcode", description="The slit mask barcode")
>     ra_centre: float = Field(..., title="?", description="The ?")
> ```

Maybe better ra_center?

title="Right ascension of the mask centre, in degrees" [But please check it really is in degrees...]
___
*[saltapi/web/schema/mos.py, line 22 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvru6Jg8u4oJhXOLG7_:-Mvru6Jg8u4oJhXOLG7a:b-qgod6s) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L22)):*
> ```Python
>     barcode: str = Field(..., title="Barcode", description="The slit mask barcode")
>     ra_centre: float = Field(..., title="?", description="The ?")
>     cut_by: Optional[str] = Field(..., title="Cut date", description="The slit mask cut date")
> ```

title="Cutting person" description="The name of the person who cut the slit mask"
___
*[saltapi/web/schema/mos.py, line 23 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvrud7l6OEa1HsaNmus:-Mvrud7l6OEa1HsaNmut:b-9784zz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L23)):*
> ```Python
>     ra_centre: float = Field(..., title="?", description="The ?")
>     cut_by: Optional[str] = Field(..., title="Cut date", description="The slit mask cut date")
>     cut_date: Optional[date] = Field(..., title="Cut date ", description="The slit mask cut date ")
> ```

Maybe: description="The date when the slit mask was cry"
___
*[saltapi/web/schema/mos.py, line 24 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvruuqo3n5LPAXTUpYX:-Mvruuqo3n5LPAXTUpYY:b-oqcz6z) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L24)):*
> ```Python
>     cut_by: Optional[str] = Field(..., title="Cut date", description="The slit mask cut date")
>    [...]

2022-02-14 11:19 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: all files reviewed, 19 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/repository/mos_repository.py, line 6 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrxEpu-SDtYGjyplbN:-MvrxEpu-SDtYGjyplbO:bj4ipcm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L6)):*
> ```Python
> from sqlalchemy.engine import Connection
> 
> from saltapi.util import list_search
> ```

Obsolete import statement


<!-- Sent from Reviewable.io -->

2022-02-14 13:11 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: all files reviewed, 19 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/mos_repository.py, line 6 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrxEpu-SDtYGjyplbN:-Mvs8udc1dlML0f5C4Cz:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Obsolete import statement
</blockquote></details>

Done.
___
*[saltapi/repository/mos_repository.py, line 67 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrXeQ17LwxBf8MalJD:-Mvs97pTEZh3j_9IyvCi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"qsla" might be a bit of a cryptic variable name...
</blockquote></details>

Done.
___
*[saltapi/repository/mos_repository.py, line 77 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrYgKS4Nh4nwiwGzTC:-MvsA3yF0UO2Vdk1Cmv0:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't it make more sense to create a dictionary of proposal code ids and liaison astronomers?
</blockquote></details>

Done.
___
*[saltapi/repository/mos_repository.py, line 81 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrY1kmBRbK6NmCnzu8:-MvsA4H5BuY9Us-P78FY:b-cwx5ng) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L81)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you return a list if no astronomer is found?
</blockquote></details>

statement removed.
___
*[saltapi/repository/mos_repository.py, line 82 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrZG0c8n0VzR_Gkk6f:-MvsA95p5ePwhvRSt_CY:bwzzk98) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess this will fall over if there is no liaison astronomer.
</blockquote></details>

how? and why?
___
*[saltapi/web/api/mos.py, line 23 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrsRfO3tW8ImGODbLQ:-MvsJEEQ5i_HO64bpFSl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/api/mos.py#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't you rather pass the semesters as query parameters?
</blockquote></details>

Done.
___
*[saltapi/web/api/mos.py, line 26 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvrscee4014YvYAqvhn:-MvsJWxm0ZAxEeWfIsuO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/api/mos.py#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Get a list of blocks using MOS.
</blockquote></details>

Done.
___
*[saltapi/web/api/mos.py, line 36 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvrsrqm4x-y7w4J1H1L:-MvsJXS24Ivia4dGrH03:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/api/mos.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why `i`, given its associated with looping over integers?
</blockquote></details>

Done.
___
*[saltapi/web/schema/mos.py, line 8 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvrt8WT8Dwm55wJFtV6:-MvsJfRH4XX7TSGGW73n:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

MOS data for a block.
</blockquote></details>

Done.
___
*[saltapi/web/schema/mos.py, line 14 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrtfPDEMrxAbJY3UXX:-MvsJxLm6-TDGLfgkfQr:b49ebd0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The "status" of what?
</blockquote></details>

the original query have it  iam not sure where it is used and i didn't use it
So removed
___
*[saltapi/web/schema/mos.py, line 19 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrtqBb2LzdZvafPbGl:-MvsK9249OybIj3FmPtk:b-gnsl1n) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is the mask_id really needed?
</blockquote></details>

the same goes to the proposal_id why is it needed to be displays
___
*[saltapi/web/schema/mos.py, line 21 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrtK9nBfzWqdS3IynR:-MvsKqlKEzDmO-kLI60S:b-uf6db5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better ra_center?

title="Right ascension of the mask centre, in degrees" [But please check it really is in degrees...]
</blockquote></details>

displayed in H:M:S.s and yes it is in degress
___
*[saltapi/web/schema/mos.py, line 22 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvru6Jg8u4oJhXOLG7_:-MvsLYarDYasmg3U8xTO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

title="Cutting person" description="The name of the person who cut the slit mask"
</blockquote></details>

Done.
___
*[saltapi/web/schema/mos.py, line 23 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvrud7l6OEa1HsaNmus:-MvsLyZX4NgMXXJq_oMs:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe: description="The date when the slit mask was cry"
</blockquote></details>

Done.
___
*[saltapi/web/schema/mos.py, line 24 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-Mvruuqo3n5LPAXTUpYX:-MvsLy077TqmaYPgnE4l:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better:

```
mask_comment:Optional[str] = Field(..., title="Slit mask comment", description="A comment on the slit mask")
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-14 14:13 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/repository/mos_repository.py, line 67 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrXeQ17LwxBf8MalJD:-MvsUTt55l1GAc9dJHl0:b-h2yqwk) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L67)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. Thinking of it, the fact that there are two SQL statements in this function suggests that maybe there should be _two_ functions.
___
*[saltapi/repository/mos_repository.py, line 82 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrZG0c8n0VzR_Gkk6f:-MvsVAIA0A3xMPEiAEpW:blwizod) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L82)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

how? and why?
</blockquote></details>

For the old code: If there is no astronomer, you get `[None]`, and then you try to access it as a dictionary.

For the new code: You are trying to access a dictionary item with a key which does not exist.
___
*[saltapi/repository/mos_repository.py, line 79 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvsVmFwBpJXCv03n1rb:-MvsVmFwBpJXCv03n1rc:b-x1adk6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/9e7f53b693b86cbcf5162a7bf90859c01337493c/saltapi/repository/mos_repository.py#L79)):*
> ```Python
>         mask = []
>         for m in mask_data:
>             m["liaison_astronomers"] = liaison_astronomers[m["proposal_code_id"]]
> ```

`m["liaison_astronomers"]` > `m["liaison_astronomer"]` -- there is only one astronomer. 
___
*[saltapi/web/api/mos.py, line 24 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY5AfrEX2otCfiajNt:-MvsWLti9tD2kO2P7sKH:buj1e97) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/web/api/mos.py#L24)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh. I hadn't noticed the HTTP verb "post" rather than "get". Thanks for changing it!
___
*[saltapi/web/api/mos.py, line 26 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvsWkRw5q-X-CJj0Kpr:-MvsWkRw5q-X-CJj0Kps:bfhlvsw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/9e7f53b693b86cbcf5162a7bf90859c01337493c/saltapi/web/api/mos.py#L26)):*
> ```Python
> ) -> List[MosBlock]:
>     """
>     GGet a list of blocks using MOS.
> ```

GGet > Get

And I think (my bad!) "the list" might be better than "a list".
___
*[saltapi/web/schema/mos.py, line 19 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrtqBb2LzdZvafPbGl:-MvsX0JG3t6CAxquSC-H:bjcetyg) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L19)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

the same goes to the proposal_id why is it needed to be displays
</blockquote></details>

If the block has been deleted, you would need something like the proposal id to view the proposal (submission) with that block. I'm not sure we'll ever support this, and I'd suggest to remove it.
___
*[saltapi/web/schema/mos.py, line 21 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrtK9nBfzWqdS3IynR:-MvsXgKA6awFnjoGs3cs:bzbuyq9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L21)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

displayed in H:M:S.s and yes it is in degress
</blockquote></details>

You mean displayed on the frontend?


<!-- Sent from Reviewable.io -->

2022-02-14 16:04 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/repository/mos_repository.py, line 67 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrXeQ17LwxBf8MalJD:-MvsxkoP4AZQvDet-iIE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thanks. Thinking of it, the fact that there are two SQL statements in this function suggests that maybe there should be _two_ functions.
</blockquote></details>

Done.
___
*[saltapi/web/api/mos.py, line 24 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvY5AfrEX2otCfiajNt:-MvsxyYyADaKQlK0DIpH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/2537d51f6199b782433b0fa1ec935528bef85270/saltapi/web/api/mos.py#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh. I hadn't noticed the HTTP verb "post" rather than "get". Thanks for changing it!
</blockquote></details>

Done.
___
*[saltapi/web/api/mos.py, line 26 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvsWkRw5q-X-CJj0Kpr:-Mvsy30VCt6X-2BfrdwL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/9e7f53b693b86cbcf5162a7bf90859c01337493c/saltapi/web/api/mos.py#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

GGet > Get

And I think (my bad!) "the list" might be better than "a list".
</blockquote></details>

Done.
___
*[saltapi/web/schema/mos.py, line 21 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrtK9nBfzWqdS3IynR:-MvsybHs6jOcPCxKI8uQ:btp9e78) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/web/schema/mos.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You mean displayed on the frontend?
</blockquote></details>

yes on the frontend


<!-- Sent from Reviewable.io -->

2022-02-14 17:54 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: 6 of 9 files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/repository/mos_repository.py, line 79 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvsVmFwBpJXCv03n1rb:-MvtMkjM64y5Tan2T5Q6:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/9e7f53b693b86cbcf5162a7bf90859c01337493c/saltapi/repository/mos_repository.py#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`m["liaison_astronomers"]` > `m["liaison_astronomer"]` -- there is only one astronomer. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 08:28 UTC, hettlage requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: all files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/repository/mos_repository.py, line 11 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvwMWUi6UI70tO8_d_0:-MvwMWUi6UI70tO8_d_1:b-h6yiby) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/47f903984faa6f758dcabcf2513180627b9656eb/saltapi/repository/mos_repository.py#L11)):*
> ```Python
>         self.connection = connection
> 
>     def _get_liaison_astronomers(self, proposal_code_ids: List[int]) -> Dict[int, str]:
> ```

This (orb something similar to it) looks like a useful method to have in the _proposal_ repository, perhaps...

(But as long as we don't have a use case, you could argue there is no need.)
___
*[saltapi/repository/mos_repository.py, line 11 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvwTJ0EDM7uq2fOCGQl:-MvwTJ0F2KD53Ici3Ase:busydy1) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/47f903984faa6f758dcabcf2513180627b9656eb/saltapi/repository/mos_repository.py#L11)):*
> ```Python
>         self.connection = connection
> 
>     def _get_liaison_astronomers(self, proposal_code_ids: List[int]) -> Dict[int, str]:
> ```

It might make more sense to pass a set of proposal code ids.
___
*[saltapi/repository/mos_repository.py, line 75 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvwNes_A06U_whWQbwF:-MvwNes_A06U_whWQbwG:bus4inw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/47f903984faa6f758dcabcf2513180627b9656eb/saltapi/repository/mos_repository.py#L75)):*
> ```Python
> 
>         proposal_code_ids = []
>         mos_block = []
> ```

mos_block > mos_blocks
___
*[saltapi/repository/mos_repository.py, line 80 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvwO32yEZ6J-4LIU2VT:-MvwO32yEZ6J-4LIU2VU:b-jtopvg) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/47f903984faa6f758dcabcf2513180627b9656eb/saltapi/repository/mos_repository.py#L80)):*
> ```Python
>             proposal_code_ids.append(row.proposal_code_id)
> 
>         liaison_astronomers = self._get_liaison_astronomers(proposal_code_ids)
> ```

Maybe slightly more succinct:

```
mos_blocks = []
for row in results:
        mos_block.append(dict(row))

proposal_code_ids = set(m[proposal_code_id] for m in mos_blocks])
liaison_astronomers = self._get_liaison_astronomers(proposal_code_ids)
for m in mos_blocks:
    proposal_code_id = m["proposal_code_id"]
    liaison_astronomer = liaison_astronomers[proposal_code_id] if proposal_code_id in liaison_astronomers else None
    m["liaison_astronomer"] = liaison_astronomer
```


<!-- Sent from Reviewable.io -->

2022-02-15 09:34 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: all files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/mos_repository.py, line 82 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvrZG0c8n0VzR_Gkk6f:-MvwimP8DZFly8Ll0_gU:b-1cyu7w) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/dc006de3eb945c6cefb7a04da9f9f8dc08037c28/saltapi/repository/mos_repository.py#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For the old code: If there is no astronomer, you get `[None]`, and then you try to access it as a dictionary.

For the new code: You are trying to access a dictionary item with a key which does not exist.
</blockquote></details>

thank you
___
*[saltapi/repository/mos_repository.py, line 11 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvwMWUi6UI70tO8_d_0:-MvwaM5g3iyqMAqKZvcl:bty8k9g) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/47f903984faa6f758dcabcf2513180627b9656eb/saltapi/repository/mos_repository.py#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This (orb something similar to it) looks like a useful method to have in the _proposal_ repository, perhaps...

(But as long as we don't have a use case, you could argue there is no need.)
</blockquote></details>

and also I would have to inject the proposal_repository here which for now it is not necessary.
___
*[saltapi/repository/mos_repository.py, line 11 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvwTJ0EDM7uq2fOCGQl:-Mvwg9ae88vnPDSnGY_i:b-ef8km2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/47f903984faa6f758dcabcf2513180627b9656eb/saltapi/repository/mos_repository.py#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might make more sense to pass a set of proposal code ids.
</blockquote></details>

I think passing a set will mean more work and there actually no big gain from it
___
*[saltapi/repository/mos_repository.py, line 75 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvwNes_A06U_whWQbwF:-MvwgQXnD8jJlp64A6Nk:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/47f903984faa6f758dcabcf2513180627b9656eb/saltapi/repository/mos_repository.py#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

mos_block > mos_blocks
</blockquote></details>

Done.
___
*[saltapi/repository/mos_repository.py, line 80 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvwO32yEZ6J-4LIU2VT:-MvwifwTAdhSXJE8Sd0-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/47f903984faa6f758dcabcf2513180627b9656eb/saltapi/repository/mos_repository.py#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe slightly more succinct:

```
mos_blocks = []
for row in results:
        mos_block.append(dict(row))

proposal_code_ids = set(m[proposal_code_id] for m in mos_blocks])
liaison_astronomers = self._get_liaison_astronomers(proposal_code_ids)
for m in mos_blocks:
    proposal_code_id = m["proposal_code_id"]
    liaison_astronomer = liaison_astronomers[proposal_code_id] if proposal_code_id in liaison_astronomers else None
    m["liaison_astronomer"] = liaison_astronomer
```



</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 12:28 UTC, hettlage requested changes
General remark: black needs to be run, and both mypy and pytest fail.

Also, tests are missing. So you should at least raise an issue that tests need to be added, and address them soon. :-)

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-:-MvxL10y5iM5MYmF82hS:b-uka8cv)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/repository/mos_repository.py, line 11 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvwTJ0EDM7uq2fOCGQl:-MvxKBGP-o4uQBNleDMs:b-1ytqzp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/47f903984faa6f758dcabcf2513180627b9656eb/saltapi/repository/mos_repository.py#L11)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I think passing a set will mean more work and there actually no big gain from it
</blockquote></details>

But I see you still made the change... :-)


<!-- Sent from Reviewable.io -->

2022-02-15 13:53 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/mos_repository.py, line 11 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/40#-MvwTJ0EDM7uq2fOCGQl:-MvxdqpoBZIYrHG2CFLf:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/47f903984faa6f758dcabcf2513180627b9656eb/saltapi/repository/mos_repository.py#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But I see you still made the change... :-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 20:18 UTC, hettlage approved these changes
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2022-02-16 17:36 UTC, merged