Submitting MOS mask details
saltastroops/salt-api pull request #50
Opened 2022-03-02 10:47 UTC by Eb-Zeero

2022-03-03 08:08 UTC, hettlage requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/main.py, line 25 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDjLZj0ZFoDbiYTk3e:-MxDjLZj0ZFoDbiYTk3f:b9o3290) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/main.py#L25)):*
> ```Python
> 
> settings = Settings()
> origins = [settings.frontend_uri, "http://localhost:4200"]
> ```

If you hardcode localhost, it be worth adding http://127.0.0.1:4200 as well?

I'm not entirely sure about the hardcoding, though...
___
*[saltapi/repository/instrument_repository.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDlreYAGAlI06mWi6K:-MxDlreYAGAlI06mWi6L:b-ynkn4t) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/instrument_repository.py#L44)):*
> ```Python
> 
>     def update_slit_mask(self, slit_mask: dict[str, Any]) -> dict[str, Any]:
>         """Add or update slit mask cut information"""
> ```

This method is only for updating (and the comment should reflect this).

cut information > information
___
*[saltapi/repository/rss_repository.py, line 515 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDmPOd3-geZdYwFFTz:-MxDmPOd3-geZdYwFFU-:b-kjiyfj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/rss_repository.py#L515)):*
> ```Python
>         self.connection.execute(stmt, slit_mask)
> 
>         return slit_mask
> ```

It might be safer to get this from the database?
___
*[saltapi/repository/user_repository.py, line 460 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDnlcGD_lZw_RPsR3_:-MxDnlcGD_lZw_RPsR3a:bve3tjb) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/user_repository.py#L460)):*
> ```Python
>         return cast(int, result.scalar()) > 0
> 
>     @staticmethod
> ```

This shouldn't be a static method, as it will require database access.
___
*[saltapi/repository/user_repository.py, line 463 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDn9vuCeGFyRVK5tLy:-MxDn9vuCeGFyRVK5tLz:br2l578) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/user_repository.py#L463)):*
> ```Python
>     def is_engineer() -> bool:
>         """
>         Method not implemented.
> ```

Should rather be a TODO.
___
*[saltapi/repository/user_repository.py, line 464 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDnJgs2e_7bYcOUGG1:-MxDnJgs2e_7bYcOUGG2:bclx3tq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/user_repository.py#L464)):*
> ```Python
>         """
>         Method not implemented.
>         Should check if the user is an engineer
> ```

Should check if  > Check whether
___
*[saltapi/service/instrument_service.py, line 20 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDoCdz4KBEykWCJ0RD:-MxDoCdz4KBEykWCJ0RE:b-ynkn4t) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/service/instrument_service.py#L20)):*
> ```Python
> 
>     def update_slit_mask(self, slit_mask: Dict[str, Any]) -> Dict[str, Any]:
>         """Add or update slit mask cut information"""
> ```

This method is only for updating (and the comment should reflect this).

cut information > information
___
*[saltapi/service/permission_service.py, line 287 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDoWyv5tmYUp7RSDeB:-MxDoWyv5tmYUp7RSDeC:b-1m0bcb) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/service/permission_service.py#L287)):*
> ```Python
>     def check_permission_to_update_mos_slit_mask(self, user):
>         """
>         Check whether the user can update or add a slit mask.
> ```

update or add > update
___
*[saltapi/web/api/instruments.py, line 53 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDkTVoEeu8EZ294_mW:-MxDkTVoEeu8EZ294_mX:b-4brpqg) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/web/api/instruments.py#L53)):*
> ```Python
> 
> 
> @router.post(
> ```

From a REST perspective,

* This should be a PUT request
* The mask id (well, the barcode) should be a path parameter
* The status code should not be 201, as no new resource is created

Of course you should check that the barcode in the endpoint and in the body are the same...


<!-- Sent from Reviewable.io -->

2022-03-07 13:31 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: 2 of 8 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/instrument_repository.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDlreYAGAlI06mWi6K:-MxZ65bsBvOt2polujZF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/instrument_repository.py#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This method is only for updating (and the comment should reflect this).

cut information > information
</blockquote></details>

Done.
___
*[saltapi/repository/rss_repository.py, line 515 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDmPOd3-geZdYwFFTz:-MxZQBYw7DuGVrTWa0Ke:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/rss_repository.py#L515)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be safer to get this from the database?
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 460 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDnlcGD_lZw_RPsR3_:-MxZQjsHEZaU4exQ8P9P:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/user_repository.py#L460)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This shouldn't be a static method, as it will require database access.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 463 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDn9vuCeGFyRVK5tLy:-MxZUKRY8K7KyJapOZsm:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/user_repository.py#L463)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should rather be a TODO.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 464 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDnJgs2e_7bYcOUGG1:-MxZUPQb8xBbw7SOGbid:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/user_repository.py#L464)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should check if  > Check whether
</blockquote></details>

Done.
___
*[saltapi/service/instrument_service.py, line 20 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDoCdz4KBEykWCJ0RD:-MxZV39r1Iw9P4v2z0Xq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/service/instrument_service.py#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This method is only for updating (and the comment should reflect this).

cut information > information
</blockquote></details>

Done.
___
*[saltapi/service/permission_service.py, line 287 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDoWyv5tmYUp7RSDeB:-MxZVg2EDDefUbhV84Uv:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/service/permission_service.py#L287)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

update or add > update
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 53 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDkTVoEeu8EZ294_mW:-MxZY3u-EsH8yFh7PSlK:b-vmxoq9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/web/api/instruments.py#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

From a REST perspective,

* This should be a PUT request
* The mask id (well, the barcode) should be a path parameter
* The status code should not be 201, as no new resource is created

Of course you should check that the barcode in the endpoint and in the body are the same...
</blockquote></details>

But the barcode  as a path in this case is not very impotant since it will requre more implementation bot on the back and the frontend 
___
*[saltapi/main.py, line 25 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDjLZj0ZFoDbiYTk3e:-MxZ5iQzE9rnrY3CzWf3:bs0lizu) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/main.py#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you hardcode localhost, it be worth adding http://127.0.0.1:4200 as well?

I'm not entirely sure about the hardcoding, though...
</blockquote></details>

Sorry forgot to remove this


<!-- Sent from Reviewable.io -->

2022-03-07 15:07 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/repository/instrument_repository.py, line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZknPCAimX2Fh2MT2z:-MxZknPCAimX2Fh2MT3-:bfx62ly) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/instrument_repository.py#L35)):*
> ```Python
>         return self.bvit_repository.get(bvit_id)
> 
>     def get_mos_mask_in_magazine(self) -> List[str]:
> ```

mos_mask > mos_masks
___
*[saltapi/repository/instrument_repository.py, line 43 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZkg2kE9RvZUxBGfhr:-MxZkg2kE9RvZUxBGfhs:b-jljg2t) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/instrument_repository.py#L43)):*
> ```Python
>         return self.rss_repository.get_mos_blocks(semesters)
> 
>     def update_slit_mask(self, slit_mask: dict[str, Any]) -> dict[str, Any]:
> ```

See the comment on function names in the RSS repository file..
___
*[saltapi/repository/rss_repository.py, line 515 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZiU7l947yOPK1gUDA:-MxZiU7mByY1mGO1gnYi:bog9sht) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/86ab294d2e964d5c6a9fc9dee1126ad88a16e621/saltapi/repository/rss_repository.py#L515)):*
> ```Python
>         self.connection.execute(insert_stmt, slit_mask)
> 
>         query_stmt = text(
> ```

You might have seen this comment coming.... The query for getting the mos mask details should ve handled by its own method (`get_slit_mask`?).

Now `get_slit_mask` sounds odd. Maybe it's rather `get_slit_mask_metadata` (and also `update_)slit_mask_metadata` instead of `update_slit_mask`)? 

Actually, it would probably be `get_mos_mask_metadata` and `update_mos_mask_metadata`, given that the function is only concerned with MOS masks.

Oh... and this leads to questioning the MOS block names as well. This clearly needs discussion...
___
*[saltapi/service/instrument_service.py, line 19 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZjqi65OSSMLRAMaFB:-MxZjqi65OSSMLRAMaFC:b-iynqkt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/service/instrument_service.py#L19)):*
> ```Python
>         return self.instrument_repository.get_mos_blocks(semesters)
> 
>     def update_slit_mask(self, slit_mask: Dict[str, Any]) -> Dict[str, Any]:
> ```

See the comment on function names in the RSS repository file.
___
*[saltapi/web/api/instruments.py, line 53 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDkTVoEeu8EZ294_mW:-MxZnL829etMk1VNwSSx:bajc32v) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/web/api/instruments.py#L53)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

But the barcode  as a path in this case is not very impotant since it will requre more implementation bot on the back and the frontend 
</blockquote></details>

Can we talk about this?
___
*[saltapi/web/api/instruments.py, line 59 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZog9g9KVx-BDrnEVk:-MxZog9g9KVx-BDrnEVl:bwt9a1m) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/86ab294d2e964d5c6a9fc9dee1126ad88a16e621/saltapi/web/api/instruments.py#L59)):*
> ```Python
>     status_code=200,
> )
> def update_slit_mask(
> ```

The comment on function names applies here as well.
___
*[saltapi/web/api/instruments.py, line 60 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZnj422n6FuzSMbbob:-MxZnj422n6FuzSMbboc:b-kgtv95) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/86ab294d2e964d5c6a9fc9dee1126ad88a16e621/saltapi/web/api/instruments.py#L60)):*
> ```Python
> )
> def update_slit_mask(
>     slit_mask: SlitMask = Body(..., title="The Slit mask", description="Semester"),
> ```

Looking at it... isn't `SlitMask` really `MosMaskMetadata`?
___
*[saltapi/web/api/instruments.py, line 64 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZp3I04GOuUXRreKTy:-MxZp3I04GOuUXRreKTz:bib93wp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/86ab294d2e964d5c6a9fc9dee1126ad88a16e621/saltapi/web/api/instruments.py#L64)):*
> ```Python
> ) -> SlitMask:
>     """
>     Update MOS slit mask.
> ```

MOS slit mask > MOS mask


<!-- Sent from Reviewable.io -->

2022-03-10 09:24 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: 2 of 8 files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/repository/instrument_repository.py, line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZknPCAimX2Fh2MT2z:-Mxming15yL80iWiE9Mw:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/instrument_repository.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

mos_mask > mos_masks
</blockquote></details>

Done.
___
*[saltapi/repository/instrument_repository.py, line 43 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZkg2kE9RvZUxBGfhr:-MxmmHCj-vbkT30QbwPX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/instrument_repository.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See the comment on function names in the RSS repository file..
</blockquote></details>

Done.
___
*[saltapi/service/instrument_service.py, line 19 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZjqi65OSSMLRAMaFB:-Mxmlvj34htt9We1o_6f:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/service/instrument_service.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See the comment on function names in the RSS repository file.
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 59 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZog9g9KVx-BDrnEVk:-Mxmm2s34Jd5qatWNPgQ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/86ab294d2e964d5c6a9fc9dee1126ad88a16e621/saltapi/web/api/instruments.py#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The comment on function names applies here as well.
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 60 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZnj422n6FuzSMbbob:-Mxmm8wdCKyyU-kB9RYa:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/86ab294d2e964d5c6a9fc9dee1126ad88a16e621/saltapi/web/api/instruments.py#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Looking at it... isn't `SlitMask` really `MosMaskMetadata`?
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 64 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZp3I04GOuUXRreKTy:-MxmmCAS--A47J5CXDKw:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/86ab294d2e964d5c6a9fc9dee1126ad88a16e621/saltapi/web/api/instruments.py#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

MOS slit mask > MOS mask
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-10 14:13 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 22 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[saltapi/repository/instrument_repository.py, line 36 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxnbR8k3-viyV9iAvP3:-MxnbR8k3-viyV9iAvP4:ba2w854) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/instrument_repository.py#L36)):*
> ```Python
> 
>     def get_masks_in_magazine(self, mask_type: Optional[str]) -> List[str]:
>         """The list of MOS masks in the magazine."""
> ```

MOS masks > masks
___
*[saltapi/repository/instrument_repository.py, line 40 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxnbXcHATcmtQ_DW2jw:-MxnbXcHATcmtQ_DW2jx:b-z35m7u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/instrument_repository.py#L40)):*
> ```Python
> 
>     def get_mos_mask_matadata(self, semesters: List[str]) -> List[Dict[str, Any]]:
>         """The list of MOS blocks."""
> ```

blocks > metadata
___
*[saltapi/repository/instrument_repository.py, line 43 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxnbdNK4VBeo8MKHRgD:-MxnbdNK4VBeo8MKHRgE:b-9ehfbp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/instrument_repository.py#L43)):*
> ```Python
>         return self.rss_repository.get_mos_mask_matadata(semesters)
> 
>     def update_most_mask_matadata(self, mos_mask_matadata: dict[str, Any]) -> dict[str, Any]:
> ```

most > mos

dict > Dict
___
*[saltapi/repository/rss_repository.py, line 515 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZiU7l947yOPK1gUDA:-Mxncj7x2W677FHm_zHK:b-uozbem) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/86ab294d2e964d5c6a9fc9dee1126ad88a16e621/saltapi/repository/rss_repository.py#L515)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might have seen this comment coming.... The query for getting the mos mask details should ve handled by its own method (`get_slit_mask`?).

Now `get_slit_mask` sounds odd. Maybe it's rather `get_slit_mask_metadata` (and also `update_)slit_mask_metadata` instead of `update_slit_mask`)? 

Actually, it would probably be `get_mos_mask_metadata` and `update_mos_mask_metadata`, given that the function is only concerned with MOS masks.

Oh... and this leads to questioning the MOS block names as well. This clearly needs discussion...
</blockquote></details>

I still think that splitting up the function would be a good idea.
___
*[saltapi/repository/rss_repository.py, line 405 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxnc834CUcK_PjxbHGv:-Mxnc834CUcK_PjxbHGw:b-k82jkj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/rss_repository.py#L405)):*
> ```Python
>     def get_mask_in_magazine(self, mask_type: Optional[str]) -> List[str]:
>         """
>         The list of masks in the magazine.
> ```

The list of masks in the magazine. > The list of masks in the magazine, optionally filtered by a mask type.
___
*[saltapi/service/instrument_service.py, line 10 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxnczllACsnz_zgtQPx:-MxnczllACsnz_zgtQPy:beffqfq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/service/instrument_service.py#L10)):*
> ```Python
>         self.instrument_repository = instrument_repository
> 
>     def get_mask_in_magazine(self, mask_type: Optional[str]) -> List[str]:
> ```

get_mask > get_masks
___
*[saltapi/service/instrument_service.py, line 15 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxndDrbDSU1zqiBsE5U:-MxndDrbDSU1zqiBsE5V:b-z35m7u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/service/instrument_service.py#L15)):*
> ```Python
> 
>     def get_mos_mask_matadata(self, semesters: List[str]) -> List[Dict[str, Any]]:
>         """The list of MOS blocks."""
> ```

blocks > metadata
___
*[saltapi/service/instrument_service.py, line 21 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxndJVZCSVXD97sB68v:-MxndJVZCSVXD97sB68w:b-c175d5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/service/instrument_service.py#L21)):*
> ```Python
>     def update_mos_mask_matadata(self, mos_mask_matadata: Dict[str, Any]) -> Dict[str, Any]:
>         """Update slit mask information"""
>         return self.instrument_repository.update_most_mask_matadata(mos_mask_matadata)
> ```

most > mos
___
*[saltapi/service/permission_service.py, line 287 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDoWyv5tmYUp7RSDeB:-MxZkEYB926W12yEpqYs:bocxtk7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/service/permission_service.py#L287)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the change?
___
*[saltapi/web/api/instruments.py, line 19 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxnd_kB1l3ktTk7LAV5:-Mxnd_kB1l3ktTk7LAV6:b-b6ttze) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L19)):*
> ```Python
>     response_model=List[str]
> )
> def get_mask_in_magazine(
> ```

mask > masks
___
*[saltapi/web/api/instruments.py, line 24 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxndgye88L9SjD5koue:-MxndgyfEVfMe76OsX0P:b-2gd91u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L24)):*
> ```Python
> ) -> List[str]:
>     """
>     Returns the list of masks that are currently on the magazine.
> ```

Returns the list of masks in the magazine. > Returns the list of masks in the magazine, optionally filtered by mask type.
___
*[saltapi/web/api/instruments.py, line 33 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxneXH15VKsWNAxV-_7:-MxneXH15VKsWNAxV-_8:bt9vpr6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L33)):*
> ```Python
> 
> @router.get(
>     "/rss/mos",
> ```

I think the endpoint should be renamed to something like /rss/mos-mask-metadata
___
*[saltapi/web/api/instruments.py, line 47 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxne1Wk8QvEXkppPygO:-Mxne1Wk8QvEXkppPygP:b2aeye8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L47)):*
> ```Python
>     with UnitOfWork() as unit_of_work:
>         permission_service = services.permission_service(unit_of_work.connection)
>         permission_service.check_permission_to_view_mos_data(user)
> ```

mos_dara > mos_metadata
___
*[saltapi/web/api/instruments.py, line 55 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxnf6WG5MDunmIcXHb9:-Mxnf6WH-qZbFJu9-VB4:bfqkwn5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L55)):*
> ```Python
> 
> @router.put(
>     "/rss/update-slit-mask",
> ```

The endpoint should rather be called /rss/mos-mask-metadata/:barcode.
___
*[saltapi/web/api/instruments.py, line 56 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxne7mY7j2Mc4k9H-rp:-Mxne7mY7j2Mc4k9H-rq:b-kwh6v8) ([raw file](https://github [...]

2022-03-31 07:23 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: 5 of 8 files reviewed, 22 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/instrument_repository.py, line 36 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxnbR8k3-viyV9iAvP3:-MzTl9YN1D-tNRXOpchl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/instrument_repository.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

MOS masks > masks
</blockquote></details>

Done.
___
*[saltapi/repository/instrument_repository.py, line 40 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxnbXcHATcmtQ_DW2jw:-MzTlBdl1TEZqePLQSOT:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/instrument_repository.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

blocks > metadata
</blockquote></details>

Done.
___
*[saltapi/repository/instrument_repository.py, line 43 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxnbdNK4VBeo8MKHRgD:-MzTlQB5-KGfDjOwBPMf:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/instrument_repository.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

most > mos

dict > Dict
</blockquote></details>

Done.
___
*[saltapi/repository/rss_repository.py, line 515 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZiU7l947yOPK1gUDA:-MzTqrJ7BxJqZXr7xo_g:b-z8bk3c) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/86ab294d2e964d5c6a9fc9dee1126ad88a16e621/saltapi/repository/rss_repository.py#L515)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I still think that splitting up the function would be a good idea.
</blockquote></details>

it is done
___
*[saltapi/repository/rss_repository.py, line 405 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxnc834CUcK_PjxbHGv:-MzTl_AED5XrzO6bAStD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/rss_repository.py#L405)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The list of masks in the magazine. > The list of masks in the magazine, optionally filtered by a mask type.
</blockquote></details>

Done.
___
*[saltapi/service/instrument_service.py, line 10 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxnczllACsnz_zgtQPx:-MzTlpn59EuEMuH_477Q:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/service/instrument_service.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

get_mask > get_masks
</blockquote></details>

Done.
___
*[saltapi/service/instrument_service.py, line 15 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxndDrbDSU1zqiBsE5U:-MzTlrHvB_B_-R9K39c1:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/service/instrument_service.py#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

blocks > metadata
</blockquote></details>

Done.
___
*[saltapi/service/instrument_service.py, line 21 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxndJVZCSVXD97sB68v:-MzTluRQ7AyTRLBidU4j:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/service/instrument_service.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

most > mos
</blockquote></details>

Done.
___
*[saltapi/service/permission_service.py, line 287 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDoWyv5tmYUp7RSDeB:-MzTm3JQ4cPIIS2UWIV0:bn1827e) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/service/permission_service.py#L287)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see the change?
</blockquote></details>

sorry done
___
*[saltapi/web/api/instruments.py, line 53 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxDkTVoEeu8EZ294_mW:-MzTq1uFBmIupz3ytZZJ:b-jjuexn) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/web/api/instruments.py#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we talk about this?
</blockquote></details>

no need to check the barcore not part of the body any more
___
*[saltapi/web/api/instruments.py, line 19 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxnd_kB1l3ktTk7LAV5:-MzTmQLR2bZHLLmoStbm:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

mask > masks
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 24 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxndgye88L9SjD5koue:-MzTmWKB3j19OH7zmNsv:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Returns the list of masks in the magazine. > Returns the list of masks in the magazine, optionally filtered by mask type.
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 33 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxneXH15VKsWNAxV-_7:-MzTme-b9Ch7r7gEMnwI:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the endpoint should be renamed to something like /rss/mos-mask-metadata
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 47 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxne1Wk8QvEXkppPygO:-MzTmqfs9DjLj73m4Y04:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

mos_dara > mos_metadata
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 55 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxnf6WG5MDunmIcXHb9:-MzTnPqJ95xp9EDGgw6C:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The endpoint should rather be called /rss/mos-mask-metadata/:barcode.
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 56 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mxne7mY7j2Mc4k9H-rp:-MzTnPPH4rIwZTNRzn2T:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L56)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

a MOS > MOS
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 62 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxnfR_K9eXlNtP0FZLP:-MzTp3UvAbUiJoUtS4WU:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L62)):*
<details><sum [...]

2022-04-01 10:16 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 8 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/repository/instrument_repository.py, line 43 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZkg2kE9RvZUxBGfhr:-MzZ_hDWBRGf3Oi5ydwt:bk3j19o) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/instrument_repository.py#L43)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see an issue with the way MOS mask metadata currently is handled. But given it is working without changes, I have raised an issue and will accept the PR without any further changes in this regard.
___
*[saltapi/repository/instrument_repository.py, line 40 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxnbXcHATcmtQ_DW2jw:-MzZXTvrB1gt0jIvvfub:by8pr4n) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/instrument_repository.py#L40)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change?
___
*[saltapi/repository/instrument_repository.py, line 44 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZXiTY0xRz6435nZ7v:-MzZXiTY0xRz6435nZ7w:b-k4qoo7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/instrument_repository.py#L44)):*
> ```Python
> 
>     def update_most_mask_matadata(self, mos_mask_matadata: dict[str, Any]) -> dict[str, Any]:
>         """Update MOS mask metadata"""
> ```

Why did you remove MOS from the comment?
___
*[saltapi/repository/rss_repository.py, line 515 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZiU7l947yOPK1gUDA:-MzZaKoxBHvK4hDS-kWE:b8am6z0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/86ab294d2e964d5c6a9fc9dee1126ad88a16e621/saltapi/repository/rss_repository.py#L515)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

it is done
</blockquote></details>

I'm not convinced it is done... :) But as pointed out elsewhere, I'll accept the PR without changes in this regard.
___
*[saltapi/repository/rss_repository.py, line 507 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZY73b93P9ibZ0Uti4:-MzZY73b93P9ibZ0Uti5:bsxorod) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/rss_repository.py#L507)):*
> ```Python
> 
>     def update_mos_mask_matadata(self, mos_mask_matadata: Dict[str, Any]) -> Dict[str, Any]:
>         """Update slit mask information"""
> ```

Update slit mask information > Update MOS mask metadata
___
*[saltapi/web/api/instruments.py, line 58 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZbk6U1iaoTQsWwm4c:-MzZbk6U1iaoTQsWwm4d:b-kh2j5f) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L58)):*
> ```Python
>     summary="Update a MOS mask matadata",
>     response_model=MosMaskMatadata,
>     status_code=200,
> ```

No, I think 200 is correct, as you are not creating a resource.
___
*[saltapi/web/api/instruments.py, line 60 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZbsZN9oCW9rBLJxML:-MzZbsZN9oCW9rBLJxMM:b-hxumnz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L60)):*
> ```Python
>     status_code=200,
> )
> def update_mos_mask_matadata(
> ```

matadata > metadata
___
*[saltapi/web/api/instruments.py, line 47 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZayURBCLMaYQZkmg2:-MzZayURBCLMaYQZkmg3:b-hxumnz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/80f23f91eabd0471141d432f1d5315b5b764ee77/saltapi/web/api/instruments.py#L47)):*
> ```Python
>     with UnitOfWork() as unit_of_work:
>         permission_service = services.permission_service(unit_of_work.connection)
>         permission_service.check_permission_to_view_mos_matadata(user)
> ```

matadata > metadata
___
*[saltapi/web/api/instruments.py, line 56 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZbDJQ5aosS99mE7Qm:-MzZbDJQ5aosS99mE7Qn:b-hxumnz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/80f23f91eabd0471141d432f1d5315b5b764ee77/saltapi/web/api/instruments.py#L56)):*
> ```Python
> @router.put(
>     "/rss/mos-mask-metadata/{barcode}",
>     summary="Update MOS mask matadata",
> ```

matadata > metadata


<!-- Sent from Reviewable.io -->

2022-04-01 11:32 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/instrument_repository.py, line 43 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZkg2kE9RvZUxBGfhr:-MzZtQQG5oX9fpZttdCe:bs4rp19) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/ff48e8903d851c246fdd07dbd93b740f2a54bf0d/saltapi/repository/instrument_repository.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I still see an issue with the way MOS mask metadata currently is handled. But given it is working without changes, I have raised an issue and will accept the PR without any further changes in this regard.
</blockquote></details>

please do. :)
___
*[saltapi/repository/instrument_repository.py, line 40 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxnbXcHATcmtQ_DW2jw:-MzZp09N47zHXi3x3Hfz:biyq1vr) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/instrument_repository.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see a change?
</blockquote></details>

I fixed something else
___
*[saltapi/repository/instrument_repository.py, line 44 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZXiTY0xRz6435nZ7v:-MzZpG0a1rbM0KMae23E:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/instrument_repository.py#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why did you remove MOS from the comment?
</blockquote></details>

Done.
___
*[saltapi/repository/rss_repository.py, line 515 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MxZiU7l947yOPK1gUDA:-MzZrHkA1ave3nqB29YE:b4rsxux) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/86ab294d2e964d5c6a9fc9dee1126ad88a16e621/saltapi/repository/rss_repository.py#L515)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced it is done... :) But as pointed out elsewhere, I'll accept the PR without changes in this regard.
</blockquote></details>

I beleive I mixed up methods
___
*[saltapi/repository/rss_repository.py, line 507 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZY73b93P9ibZ0Uti4:-MzZpS7F9oHfV5WVLnq-:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/repository/rss_repository.py#L507)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Update slit mask information > Update MOS mask metadata
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 58 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZbk6U1iaoTQsWwm4c:-MzZtAyT1azHD5GWELGi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L58)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No, I think 200 is correct, as you are not creating a resource.
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 60 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZbsZN9oCW9rBLJxML:-MzZtBV21U4yyeIcDPqM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/5aedbeaabff047b275309adb16bef605f298ced0/saltapi/web/api/instruments.py#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

matadata > metadata
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 47 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZayURBCLMaYQZkmg2:-MzZtDovDApyfjSftlmb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/80f23f91eabd0471141d432f1d5315b5b764ee77/saltapi/web/api/instruments.py#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

matadata > metadata
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 56 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzZbDJQ5aosS99mE7Qm:-MzZt842-TLQEunHt9a9:bbz7a8h) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/80f23f91eabd0471141d432f1d5315b5b764ee77/saltapi/web/api/instruments.py#L56)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

matadata > metadata
</blockquote></details>

fixed every where


<!-- Sent from Reviewable.io -->

2022-04-01 12:41 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/repository/instrument_repository.py, line 39 at r8](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mz_68uE2FiToE5WgLbm:-Mz_68uE2FiToE5WgLbn:b-zbel1i) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/feafd3b8211d3d5c7bfe99efd12b7559f14f4641/saltapi/repository/instrument_repository.py#L39)):*
> ```Python
>         return self.rss_repository.get_mask_in_magazine(mask_type)
> 
>     def get_mos_mask_metadata(self, semesters: List[str]) -> List[Dict[str, Any]]:
> ```

get_mos_mask_metadata > get_mos_masks_metadata
___
*[saltapi/repository/instrument_repository.py, line 40 at r8](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mz_6xGv6nRTfGTWPW9m:-Mz_6xGv6nRTfGTWPW9n:b-m1rh62) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/feafd3b8211d3d5c7bfe99efd12b7559f14f4641/saltapi/repository/instrument_repository.py#L40)):*
> ```Python
> 
>     def get_mos_mask_metadata(self, semesters: List[str]) -> List[Dict[str, Any]]:
>         """The list of MOS metadata."""
> ```

MOS metadata > MOS masks metadata


<!-- Sent from Reviewable.io -->

2022-04-04 11:51 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/instrument_repository.py, line 39 at r8](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mz_68uE2FiToE5WgLbm:-MzoPdVg8mZ6JLI1HzP6:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/feafd3b8211d3d5c7bfe99efd12b7559f14f4641/saltapi/repository/instrument_repository.py#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

get_mos_mask_metadata > get_mos_masks_metadata
</blockquote></details>

Done.
___
*[saltapi/repository/instrument_repository.py, line 40 at r8](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mz_6xGv6nRTfGTWPW9m:-MzoPdGKBTTBIlGIaVxr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/feafd3b8211d3d5c7bfe99efd12b7559f14f4641/saltapi/repository/instrument_repository.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

MOS metadata > MOS masks metadata
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-05 09:42 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/repository/rss_repository.py, line 546 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mzt4H3g3hBhAYc18GFW:-Mzt4H3g3hBhAYc18GFX:b-phizk3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/saltapi/repository/rss_repository.py#L546)):*
> ```Python
>         mask_in_magazine = self.get_mask_in_magazine(mask_type)
>         needed_masks = []
>         for m in self.get_mos_masks_metadata(from_semester, to_semester):
> ```

This code is specific to MOS Masks.

The other problem is whether "obsolete" should really depend on a semester...
___
*[saltapi/web/api/instruments.py, line 48 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mzt4veTBUBwtddYidH8:-Mzt4veTBUBwtddYidH9:b-d571u6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/saltapi/web/api/instruments.py#L48)):*
> ```Python
>         "2000-1",
>         alias="from",
>         description="Only include proposals for this semester and later.",
> ```

proposals > MOS masks
___
*[saltapi/web/api/instruments.py, line 54 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mzt58Px6bkeXPMxD9cJ:-Mzt58Px6bkeXPMxD9cK:b-d571u6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/saltapi/web/api/instruments.py#L54)):*
> ```Python
>         "2099-2",
>         alias="to",
>         description="Only include proposals for this semester and earlier.",
> ```

proposals > MOS masks
___
*[saltapi/web/api/instruments.py, line 109 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mzt5EeB1j1snGuWsIli:-Mzt5EeB1j1snGuWsIlj:bm2ct7l) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/saltapi/web/api/instruments.py#L109)):*
> ```Python
>         "2000-1",
>         alias="from",
>         description="Only include proposals for this semester and later.",
> ```

proposals > masks
___
*[saltapi/web/api/instruments.py, line 115 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mzt5Jwj1_KLX4GPRO9H:-Mzt5Jwj1_KLX4GPRO9I:bm2ct7l) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/saltapi/web/api/instruments.py#L115)):*
> ```Python
>         "2099-2",
>         alias="to",
>         description="Only include proposals for this semester and earlier.",
> ```

proposals > masks


<!-- Sent from Reviewable.io -->

2022-04-05 14:43 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

___
*[tests/zanele.js, line 0 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzuANBYCslGX5r2_XFr:-MzuANBZD4mp3ppjeLAP:bas3q1n) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/tests/zanele.js#L0)):*
This file should be removed... :-)


<!-- Sent from Reviewable.io -->

2022-04-06 18:04 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[saltapi/repository/instrument_repository.py, line 49 at r10](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-N---t8MB2qe2O1gpZFT:-N---t8MB2qe2O1gpZFU:b-s044yh) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c60e0d111f817245db47a0285e9a3c00e5ec9e50/saltapi/repository/instrument_repository.py#L49)):*
> ```Python
>         return self.rss_repository.update_mos_mask_metadata(mos_mask_metadata)
> 
>     def get_mos_obsolete_masks_in_magazine(self):
> ```

get_mos_obsolete_masks_in_magazine > get_obsolete_mos_masks_in_magazine(
___
*[saltapi/repository/instrument_repository.py, line 51 at r10](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-N--0-3YBNi6rImoyy6x:-N--0-3YBNi6rImoyy6y:b3ogdwh) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c60e0d111f817245db47a0285e9a3c00e5ec9e50/saltapi/repository/instrument_repository.py#L51)):*
> ```Python
>     def get_mos_obsolete_masks_in_magazine(self):
>         """The list of MOS obsolete masks."""
>         return self.rss_repository.get_mos_obsolete_masks_in_magazine()
> ```

get_mos_obsolete_masks_in_magazine > get_obsolete_mos_masks_in_magazine
___
*[saltapi/repository/rss_repository.py, line 547 at r10](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-N--19hE21pd5UXh7TXT:-N--19hE21pd5UXh7TXU:be8hwp0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c60e0d111f817245db47a0285e9a3c00e5ec9e50/saltapi/repository/rss_repository.py#L547)):*
> ```Python
>         """
>         stmt = """
> SELECT DISTINCT 
> ```

I don't see why you would have to limit this to MOS masks. Maybe we can have a brief chat about it?


<!-- Sent from Reviewable.io -->

2022-04-06 19:33 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/instrument_repository.py, line 49 at r10](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-N---t8MB2qe2O1gpZFT:-N--L8BBBvFRVkYKrrxh:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c60e0d111f817245db47a0285e9a3c00e5ec9e50/saltapi/repository/instrument_repository.py#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

get_mos_obsolete_masks_in_magazine > get_obsolete_mos_masks_in_magazine(
</blockquote></details>

Done.
___
*[saltapi/repository/instrument_repository.py, line 51 at r10](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-N--0-3YBNi6rImoyy6x:-N--L8h62wGvMxr5xGnD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c60e0d111f817245db47a0285e9a3c00e5ec9e50/saltapi/repository/instrument_repository.py#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

get_mos_obsolete_masks_in_magazine > get_obsolete_mos_masks_in_magazine
</blockquote></details>

Done.
___
*[saltapi/repository/rss_repository.py, line 546 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mzt4H3g3hBhAYc18GFW:-N--MTTP0Mz2knov9p2n:b-tt4ofi) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/saltapi/repository/rss_repository.py#L546)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This code is specific to MOS Masks.

The other problem is whether "obsolete" should really depend on a semester...
</blockquote></details>

can we chat about this.
___
*[saltapi/repository/rss_repository.py, line 547 at r10](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-N--19hE21pd5UXh7TXT:-N--MNwU2zh6O-AI38Zp:b2nign6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c60e0d111f817245db47a0285e9a3c00e5ec9e50/saltapi/repository/rss_repository.py#L547)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see why you would have to limit this to MOS masks. Maybe we can have a brief chat about it?
</blockquote></details>

yes
___
*[saltapi/web/api/instruments.py, line 48 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mzt4veTBUBwtddYidH8:-MzzIwuS3ore-Bk_lk-P:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/saltapi/web/api/instruments.py#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

proposals > MOS masks
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 54 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mzt58Px6bkeXPMxD9cJ:-MzzIxDh3B9VfAVWtyoW:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/saltapi/web/api/instruments.py#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

proposals > MOS masks
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 109 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mzt5EeB1j1snGuWsIli:-MzzHpx16kWUxfleLeBe:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/saltapi/web/api/instruments.py#L109)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

proposals > masks
</blockquote></details>

Done.
___
*[saltapi/web/api/instruments.py, line 115 at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-Mzt5Jwj1_KLX4GPRO9H:-MzzHpfSE40Kxkc3O6vL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/saltapi/web/api/instruments.py#L115)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

proposals > masks
</blockquote></details>

Done.
___
*[tests/zanele.js, line  at r9](https://reviewable.io/reviews/saltastroops/salt-api-2021/50#-MzuANBYCslGX5r2_XFr:-MzzI1Co3psATkSfi8sD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fd843f2d84d31321c2a2b359d70a8b313b104d2f/tests/zanele.js#L)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This file should be removed... :-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-06 21:30 UTC, hettlage reviewed
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)



<!-- Sent from Reviewable.io -->

2022-04-07 10:30 UTC, hettlage reviewed
> Reviewed 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)



<!-- Sent from Reviewable.io -->

2022-04-07 10:51 UTC, hettlage approved these changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2022-04-07 10:52 UTC, merged