edit-contact-information
saltastroops/salt-api pull request #57
Opened 2022-04-11 12:49 UTC by mofokeng-chaka

Added endpoints for getting user(s) information and the respective schemas

2022-04-12 08:35 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: all files reviewed, 9 unresolved discussions (waiting on @mofokeng-chaka)

___
*[saltapi/util.py, line 50 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-Ri0sQ9GWlQxh74rzk:-N-Ri0sR49iO-afF3NVm:b-qz9g2u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/util.py#L50)):*
> ```Python
>     """
>     regex = re.compile(
>         r"([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+"
> ```

Validating emails is tricky, and a regex doesn't catch all the problems. See https://mailtrap.io/blog/python-validate-email/ for alternative solutions.
___
*[saltapi/repository/user_repository.py, line 54 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RsJaxEho3XtSQejyn:-N-RsJaxEho3XtSQejyo:bjxeen0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/repository/user_repository.py#L54)):*
> ```Python
>         return User(**user, roles=self.get_user_roles(username))
> 
>     def get_user_info(self, username: str) -> UserInfo:
> ```

This needs discussion. :-)
___
*[saltapi/repository/user_repository.py, line 83 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RsOw3AvbrOEef-QQS:-N-RsOw3AvbrOEef-QQT:bk709d2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/repository/user_repository.py#L83)):*
> ```Python
>         return UserInfo(**user_details)
> 
>     def get_users_info(self) -> List[Dict[str, Any]]:
> ```

This needs discussion.
___
*[saltapi/repository/user_repository.py, line 85 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RtHzh4soSTNGN3-hj:-N-RtHzh4soSTNGN3-hk:b2m6fit) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/repository/user_repository.py#L85)):*
> ```Python
>     def get_users_info(self) -> List[Dict[str, Any]]:
>         """
>         Returns a list of users information
> ```

I'd think that list has to contain the names and ids only.
___
*[saltapi/repository/user_repository.py, line 87 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RtBfVCKnFqIL36c2M:-N-RtBfW4vOvSz6GZOHb:bbbs4f1) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/repository/user_repository.py#L87)):*
> ```Python
>         Returns a list of users information
> 
>         If the username does not exist, a NotFoundError is raised.
> ```

I think this sentence isn;'t necessary? :-)
___
*[saltapi/service/user.py, line 22 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RsYZzDzuVNzN5RoCR:-N-RsYZzDzuVNzN5RoCS:bwq9yvc) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/service/user.py#L22)):*
> ```Python
> 
> @dataclass()
> class UserInfo(ContactDetails):
> ```

This needs discussion
___
*[saltapi/web/api/users.py, line 91 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RtXQS463PBnxnXi8V:-N-RtXQS463PBnxnXi8W:b9os8u5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/web/api/users.py#L91)):*
> ```Python
> 
> @router.get(
>     "/users-info", summary="Get users information", response_model=List[Dict[str, Any]]
> ```

There should be a dedicated type for the response model. Also, shouldn't the endpoint be `/users`?
___
*[saltapi/web/api/users.py, line 118 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-Ru2uiDKPh_FUGfwyt:-N-Ru2uiDKPh_FUGfwyu:b-xonsd9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/web/api/users.py#L118)):*
> ```Python
> 
> 
> @router.get("/{username}/info", summary="Get user information", response_model=UserInfo)
> ```

I'm doubtful of the need for a separate endpoint, but let's discuss this.
___
*[saltapi/web/schema/user.py, line 33 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RuIWA0gi2q_Df-lYk:-N-RuIWA0gi2q_Df-lYl:b-ghnrg6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/web/schema/user.py#L33)):*
> ```Python
> 
> 
> class UserInfo(ProposalUser):
> ```

Might need discussion.


<!-- Sent from Reviewable.io -->

2022-04-14 09:45 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: all files reviewed, 25 unresolved discussions (waiting on @mofokeng-chaka)

___
*[saltapi/repository/user_repository.py, line 46 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b9VvpEg2c0Sg6NPLO:-N-b9VvpEg2c0Sg6NPLP:b-gu5h1e) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L46)):*
> ```Python
>        `IN`.InstituteName_Name  AS institute
> FROM PiptUser AS PU
>          JOIN Investigator AS I ON (PU.Investigator_Id = I.Investigator_Id)
> ```

The query only gives you one affiliation, but there can be multiple affiliations. If you want to get all the affiliations for a user, you have to use the `PiptUser_Id` in the `Investigator` table.
___
*[saltapi/repository/user_repository.py, line 70 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bAUVpDEW9azJKlvUz:-N-bAUVqDIETumDjXmvw:b-algman) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L70)):*
> ```Python
>     def get_affiliations(self) -> List[AffiliationListItem]:
>         """
>         Returns a list of affiliations
> ```

This is a list of institutions rather, and there should be a separate repository for that. Also, the department is missing.
___
*[saltapi/repository/user_repository.py, line 91 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bCOZoAf1_UYXcDgph:-N-bCOZoAf1_UYXcDgpi:b-wq7fd6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L91)):*
> ```Python
>             AffiliationListItem(**affiliation).asdict() for affiliation in affiliations
>         ]
>         return affiliations
> ```

You are returning a dictionary (which is probably correct), but the type hint claims you are returning a AffiliationListItem.

Do you actually need the UserListItem type?
___
*[saltapi/repository/user_repository.py, line 93 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bCzyw6SJzfGAVnkNU:-N-bCzyw6SJzfGAVnkNV:b-vch545) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L93)):*
> ```Python
>         return affiliations
> 
>     def get_users(self) -> List[UserListItem]:
> ```

It might make sense to move this after the get_by_email method, so that the methods for returning a single user are grouped together.
___
*[saltapi/repository/user_repository.py, line 119 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bBxqtBJygr7wMfUoh:-N-bBxqtBJygr7wMfUoi:b-mfhlun) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L119)):*
> ```Python
>             for row in result
>         ]
>         users = [UserListItem(**user).asdict() for user in users]
> ```

You are returning a dictionary (which is probably correct), but the type hint claims you are returning a UserListItem.

Do you actually need the UserListItem type?
___
*[saltapi/repository/user_repository.py, line 141 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bDNDYAUQ-VY9ppU8c:-N-bDNDYAUQ-VY9ppU8d:b-gu5h1e) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L141)):*
> ```Python
>          JOIN Investigator AS I ON (PU.Investigator_Id = I.Investigator_Id)
>          JOIN Institute I2 ON I.Institute_Id = I2.Institute_Id
>          JOIN Partner P ON I2.Partner_Id = P.Partner_Id
> ```

The query only gives you one affiliation, but there can be multiple affiliations. If you want to get all the affiliations for a user, you have to use the `PiptUser_Id` in the `Investigator` table.
___
*[saltapi/repository/user_repository.py, line 180 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bDRgb08iLR29A4PrE:-N-bDRgb08iLR29A4PrF:b-gu5h1e) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L180)):*
> ```Python
>          JOIN Investigator AS I ON (PU.Investigator_Id = I.Investigator_Id)
>          JOIN Institute I2 ON I.Institute_Id = I2.Institute_Id
>          JOIN Partner P ON I2.Partner_Id = P.Partner_Id
> ```

The query only gives you one affiliation, but there can be multiple affiliations. If you want to get all the affiliations for a user, you have to use the `PiptUser_Id` in the `Investigator` table.
___
*[saltapi/service/user.py, line 32 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b3nDTAfr4W09mg4ak:-N-b3nDUASPUS6Ph5VkJ:b-kzxrr9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/service/user.py#L32)):*
> ```Python
> 
> @dataclass()
> class AffiliationListItem:
> ```

I'd suggest an affiliation has oner partner and *one* institute.

And why do you call the type `AffiliationListItem` rather than just `Affiliation`?
___
*[saltapi/service/user.py, line 54 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b443cA74GC6_EWj8o:-N-b443d5NHKQILgiJYk:b-l1wul9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/service/user.py#L54)):*
> ```Python
>     family_name: str
>     password_hash: str
>     affiliation: Affiliation
> ```

A user can have more than one affiliation.
___
*[saltapi/service/user_service.py, line 101 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bPqea-eny-jDU-20b:-N-bPqet5SN0kCFYj7Op:bjt0xst) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/service/user_service.py#L101)):*
> ```Python
>         return users_details
> 
>     def get_affiliations(self) -> List[AffiliationListItem]:
> ```

See comments elsewhere -- this is get_institutions more than get_affiliations, and it should be in another file, as it is not user-related.
___
*[saltapi/service/user_service.py, line 105 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bQKD56kmAQ_ITWXxY:-N-bQKDABvFlA1bbMCAc:bg3d57s) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/service/user_service.py#L105)):*
> ```Python
>         return affiliations
> 
>     def get_user_by_email(self, email: str) -> User:
> ```

Maybe be put this after the get_user method, so that methods for getting a single user are grouped together?
___
*[saltapi/web/api/users.py, line 9 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b5Ntz6lx8SZv1t8P-:-N-b5Nu-AqYwdZ2JKG2f:bx6bghl) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/web/api/users.py#L9)):*
> ```Python
> from saltapi.repository.unit_of_work import UnitOfWork
> from saltapi.service.authentication_service import get_current_user
> from saltapi.service.user import AffiliationListItem as _AffiliationListItem
> ```

The API should not use types from the service package (imagine your type in the service package has a password attached -- this then would be passed on).
___
*[saltapi/web/api/users.py, line 93 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b7eRJ4NtftkvOn7fy:-N-b7eRJ4NtftkvOn7fz:bwp290c) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/web/api/users.py#L93)):*
> ```Python
> 
> @router.get(
>     "/users", summary="Get users information", response_model=List[UserListItem]
> ```

The endpoint should just be `/`.
___
*[saltapi/web/api/users.py, line 104 at r2](https://re [...]

2022-04-14 11:59 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: all files reviewed, 25 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[saltapi/repository/user_repository.py, line 54 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RsJaxEho3XtSQejyn:-N-Y5xxd1qHgwQkaHCke:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/repository/user_repository.py#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This needs discussion. :-)
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 83 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RsOw3AvbrOEef-QQS:-N-Y5yRa4mpQmnYbbHBb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/repository/user_repository.py#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This needs discussion.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 85 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RtHzh4soSTNGN3-hj:-N-Y5yrh0jCOLekt8JCr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/repository/user_repository.py#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd think that list has to contain the names and ids only.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 87 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RtBfVCKnFqIL36c2M:-N-Y5zI2D9GFtMX9axNj:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/repository/user_repository.py#L87)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this sentence isn;'t necessary? :-)
</blockquote></details>

Done.
___
*[saltapi/service/user.py, line 22 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RsYZzDzuVNzN5RoCR:-N-Y6-180_QiGJjx-VcT:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/service/user.py#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This needs discussion
</blockquote></details>

Done.
___
*[saltapi/web/api/users.py, line 91 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RtXQS463PBnxnXi8V:-N-Y62YTDJSeaPBzyRHE:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/web/api/users.py#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be a dedicated type for the response model. Also, shouldn't the endpoint be `/users`?
</blockquote></details>

Done.
___
*[saltapi/web/api/users.py, line 118 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-Ru2uiDKPh_FUGfwyt:-N-Y63_R58trB7Rvbqc_:b32ncgh) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/web/api/users.py#L118)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm doubtful of the need for a separate endpoint, but let's discuss this.
</blockquote></details>

Removed now
___
*[saltapi/web/schema/user.py, line 33 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RuIWA0gi2q_Df-lYk:-N-Y65ZZ4aIii90jPxKl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/web/schema/user.py#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might need discussion.
</blockquote></details>

Done.
___
*[saltapi/util.py, line 50 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-Ri0sQ9GWlQxh74rzk:-N-Wt4n2A_btAQCEnuQb:b-3dchm7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/util.py#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Validating emails is tricky, and a regex doesn't catch all the problems. See https://mailtrap.io/blog/python-validate-email/ for alternative solutions.
</blockquote></details>

This is no longer needed. It will be useful to verify the email when the user updates their contact information.


<!-- Sent from Reviewable.io -->

2022-04-15 05:24 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: 1 of 16 files reviewed, 25 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[saltapi/repository/user_repository.py, line 46 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b9VvpEg2c0Sg6NPLO:-N-cT-jJ0syTeeu3TerN:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L46)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The query only gives you one affiliation, but there can be multiple affiliations. If you want to get all the affiliations for a user, you have to use the `PiptUser_Id` in the `Investigator` table.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 70 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bAUVpDEW9azJKlvUz:-N-cTEKR3T6dKjgSUKZ9:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is a list of institutions rather, and there should be a separate repository for that. Also, the department is missing.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 91 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bCOZoAf1_UYXcDgph:-N-dRQrA1CDgdZgqIc3R:b-nbq90i) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are returning a dictionary (which is probably correct), but the type hint claims you are returning a AffiliationListItem.

Do you actually need the UserListItem type?
</blockquote></details>

I think you mean the AffiliationListItem, and to answer you no I don't need it. I used it because mypy was complaining about some return types. But it is no longer needed now that I changed the return type.



_Code quote:_
```Python
 AffiliationListItem
```
___
*[saltapi/repository/user_repository.py, line 93 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bCzyw6SJzfGAVnkNU:-N-cVVBLDFiBiTLvHXqO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L93)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might make sense to move this after the get_by_email method, so that the methods for returning a single user are grouped together.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 119 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bBxqtBJygr7wMfUoh:-N-dRrS5AIkiI3Tjnsz6:boitoo6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are returning a dictionary (which is probably correct), but the type hint claims you are returning a UserListItem.

Do you actually need the UserListItem type?
</blockquote></details>

No, I don't need it. I used it because mypy was complaining about some return types. But it is no longer needed now that I changed the return type.
___
*[saltapi/repository/user_repository.py, line 141 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bDNDYAUQ-VY9ppU8c:-N-cfeJ21BWS0a9J9JHY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L141)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The query only gives you one affiliation, but there can be multiple affiliations. If you want to get all the affiliations for a user, you have to use the `PiptUser_Id` in the `Investigator` table.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 180 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bDRgb08iLR29A4PrE:-N-cffTK3jqYbm1a__l8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/repository/user_repository.py#L180)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The query only gives you one affiliation, but there can be multiple affiliations. If you want to get all the affiliations for a user, you have to use the `PiptUser_Id` in the `Investigator` table.
</blockquote></details>

Done.
___
*[saltapi/service/user.py, line 32 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b3nDTAfr4W09mg4ak:-N-cf1tHE7uYALe97xVM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/service/user.py#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest an affiliation has oner partner and *one* institute.

And why do you call the type `AffiliationListItem` rather than just `Affiliation`?
</blockquote></details>

Done.
___
*[saltapi/service/user.py, line 54 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b443cA74GC6_EWj8o:-N-cexe14Bt99weLE_ku:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/service/user.py#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A user can have more than one affiliation.
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 101 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bPqea-eny-jDU-20b:-N-ceTCV5TlyzehNgJe3:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/service/user_service.py#L101)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comments elsewhere -- this is get_institutions more than get_affiliations, and it should be in another file, as it is not user-related.
</blockquote></details>

Done.



_Code quote (from saltapi/web/api/users.py):_
```Python
from saltapi.service.user import User as _User
```
___
*[saltapi/service/user_service.py, line 105 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-bQKD56kmAQ_ITWXxY:-N-cXsF10NsNFENT_J_K:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/service/user_service.py#L105)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe be put this after the get_user method, so that methods for getting a single user are grouped together?
</blockquote></details>

Done.
___
*[saltapi/web/api/users.py, line 9 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b5Ntz6lx8SZv1t8P-:-N-dPwQJ4MMbDQ-MQcxD:b3ash0z) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/web/api/users.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The API should not use types from the service package (imagine your type in the service package has a password attached -- this then would be passed on).
</blockquote></details>

I get your point, I just followed what was done for other services. So does this apply to all services or only this one? Does this imply the next three lines should also be changed because they are using types from the service package?
___
*[saltapi/web/api/users.py, line 93 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b7eRJ4NtftkvOn7fy:-N-cZheZCvK-gTYVD5qc:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6 [...]

2022-04-15 05:25 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: 1 of 16 files reviewed, 25 unresolved discussions (waiting on @hettlage)

___
*[saltapi/web/api/users.py, line 104 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b6pfh5n9bmXc1FWTA:-N-cEmB50VXE9NPXgn1_:bb6un1j) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/web/api/users.py#L104)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

From what I can seem this isn't a list of users' affiliations, but rather a list of institutions. As such it should not be part of the `users.py` file, but rather have its own file. (Note at so e point you will need GET, POST and PUT for institutions -- so there will be enough content for that file. :-)) The endpoint then could be `/institutions`.

Obviously the comment and responses model type would have to change accordingly.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-04-19 17:53 UTC, hettlage requested changes
> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: all files reviewed, 29 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[saltapi/repository/institution_repository.py, line 28 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N014Tfz2eSwygIsYsal:-N014Tfz2eSwygIsYsam:b83p3sc) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/institution_repository.py#L28)):*
> ```Python
>         )
>         result = self.connection.execute(stmt, {"separator": separator})
>         affiliations = [
> ```

Sorry, I might have missed that last time. But the logic of an institution is as follows:

- A partner has a list of institutes
- Every institute has a name and (optionally) a department.
___
*[saltapi/repository/institution_repository.py, line 28 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N014nAjCM3fB8OsZj1P:-N014nAjCM3fB8OsZj1Q:bbjc29t) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/institution_repository.py#L28)):*
> ```Python
>         )
>         result = self.connection.execute(stmt, {"separator": separator})
>         affiliations = [
> ```

These are institutions, not affiliations.
___
*[saltapi/repository/user_repository.py, line 31 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N016DVtEBsHG7lu1BvN:-N016DVtEBsHG7lu1BvO:b-bn0ki) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/user_repository.py#L31)):*
> ```Python
>         stmt = text(
>             """
> SELECT PU.PiptUser_Id           AS id,
> ```

This query has two problems:

* There is no GROUP BY condition.
* Assuming you want to group, you'd only get one email (and quite possibly a warning from MySQL as the email isn't guaranteed to be unique).

You might consider splitting the query into two.
___
*[saltapi/repository/user_repository.py, line 38 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N015fFL-RsNLiFZVLRR:-N015fFL-RsNLiFZVLRS:b964qh9) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/user_repository.py#L38)):*
> ```Python
>        Username                 AS username,
>        GROUP_CONCAT(DISTINCT P.Partner_Name ORDER BY P.Partner_Name SEPARATOR :separator) AS partners,
>        GROUP_CONCAT(DISTINCT `IN`.InstituteName_Name ORDER BY P.Partner_Name SEPARATOR :separator) AS institutes,
> ```

Maybe choose a name other than "IN", such as "I"?
___
*[saltapi/repository/user_repository.py, line 39 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N015Ous2Ud6QeD8yOFY:-N015Ous2Ud6QeD8yOFZ:bcw4g9z) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/user_repository.py#L39)):*
> ```Python
>        GROUP_CONCAT(DISTINCT P.Partner_Name ORDER BY P.Partner_Name SEPARATOR :separator) AS partners,
>        GROUP_CONCAT(DISTINCT `IN`.InstituteName_Name ORDER BY P.Partner_Name SEPARATOR :separator) AS institutes,
>        GROUP_CONCAT(DISTINCT I2.Institute_Id ORDER BY P.Partner_Name SEPARATOR :separator) AS institutes_ids,
> ```

institutes_ids > institute_ids ?
___
*[saltapi/repository/user_repository.py, line 91 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01760V4qOkt3F7SO0h:-N01760W5yGxUhsmx42h:b-otilcs) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/user_repository.py#L91)):*
> ```Python
>        Password                 AS password_hash,
>        Username                 AS username,
>        GROUP_CONCAT(DISTINCT P.Partner_Name ORDER BY P.Partner_Name SEPARATOR :separator) AS partners,
> ```

See comment above.
___
*[saltapi/repository/user_repository.py, line 145 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N017GDH90JJA45-JXDs:-N017GDH90JJA45-JXDt:b-otilcs) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/user_repository.py#L145)):*
> ```Python
>        Password                 AS password_hash,
>        Username                 AS username,
>        GROUP_CONCAT(DISTINCT P.Partner_Name ORDER BY P.Partner_Name SEPARATOR :separator) AS partners,
> ```

See comment above.
___
*[saltapi/service/user.py, line 36 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01J94p3lPX5cpyL16J:-N01J94p3lPX5cpyL16K:bgebe3u) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/service/user.py#L36)):*
> ```Python
> 
> @dataclass()
> class PartnerInstitutes:
> ```

It seems "institute" and "institution" is used for the same thing in the API (my fault, i guess). Only one or the other should be used.
___
*[saltapi/service/user.py, line 37 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01JPS6EhveOw6uCdpc:-N01JPS75YHFR82inNuc:bummx6e) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/service/user.py#L37)):*
> ```Python
> @dataclass()
> class PartnerInstitutes:
>     partners: str
> ```

partners > partner
___
*[saltapi/service/user.py, line 49 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01JbBFCqqkbs9ZqaHx:-N01JbBFCqqkbs9ZqaHy:b-iahk9m) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/service/user.py#L49)):*
> ```Python
>     family_name: str
>     password_hash: str
>     institutions: List[PartnerInstitutes]
> ```

institutions > affiliations

I'm not convinced that grouping by partner makes much sense for a user.
___
*[saltapi/web/api/users.py, line 9 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b5Ntz6lx8SZv1t8P-:-N01KK9X7-QYH5Furmvm:blnlhhe) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/web/api/users.py#L9)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I get your point, I just followed what was done for other services. So does this apply to all services or only this one? Does this imply the next three lines should also be changed because they are using types from the service package?
</blockquote></details>

Yes, it applies to all services. And yes, the next three lines should also be changed, at least if their classes are used as response models.
___
*[saltapi/web/api/users.py, line 92 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01KhB7D0qCV30jQPbN:-N01KhB7D0qCV30jQPbO:b-zfrrf0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/api/users.py#L92)):*
> ```Python
> def get_users(
>     user: _User = Depends(get_current_user),
> ) -> list[dict[str, Any]]:
> ```

list > List (I think that how it is done elsewhere in the code. From what I remember, list was made generic in Python only very recently.)
___
*[saltapi/web/api/users.py, line 102 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01LEsK0L4CvWdYpL0I:-N01LEsK0L4CvWdYpL0J:bytgxw2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/api/users.py#L102)):*
> ```Python
>     user_id: int = Path(
>         ...,
>         alias="user_id",
> ```

Why do you define an alias if it is the same as the parameter name?

But more importantly, I'm not convinced it is a good idea to have the same endpoint twice (once with user id, once with username).
___
*[saltapi/web/schema/institution.py, line 12 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/5 [...]

2022-04-21 11:44 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: 5 of 17 files reviewed, 29 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/institution_repository.py, line 28 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N014Tfz2eSwygIsYsal:-N0As7LbBip8n_rz7IhX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/institution_repository.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, I might have missed that last time. But the logic of an institution is as follows:

- A partner has a list of institutes
- Every institute has a name and (optionally) a department.
</blockquote></details>

Done.
___
*[saltapi/repository/institution_repository.py, line 28 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N014nAjCM3fB8OsZj1P:-N0AsNcBEiqioQg10aHl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/institution_repository.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

These are institutions, not affiliations.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 31 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N016DVtEBsHG7lu1BvN:-N05fKw822GLs4Vmgx9K:b-rc1hd6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/user_repository.py#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This query has two problems:

* There is no GROUP BY condition.
* Assuming you want to group, you'd only get one email (and quite possibly a warning from MySQL as the email isn't guaranteed to be unique).

You might consider splitting the query into two.
</blockquote></details>

I have added a GROUP BY condition now. However, I could only group by id and username because the are cases where the user has different entries for either email, family_name and/or given_name. Also, I ended up adding another GROUP_CONCAT command for the email to get all the emails for the user. 

I think splitting the query is no longer required since we are getting a list of emails for each user.
___
*[saltapi/repository/user_repository.py, line 38 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N015fFL-RsNLiFZVLRR:-N05jtae8GmMaSKMvPkc:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/user_repository.py#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe choose a name other than "IN", such as "I"?
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 39 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N015Ous2Ud6QeD8yOFY:-N05k40VCYzczNht6iaH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/user_repository.py#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

institutes_ids > institute_ids ?
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 91 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01760V4qOkt3F7SO0h:-N05k98u2tLIUiHKiBLg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/user_repository.py#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment above.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 145 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N017GDH90JJA45-JXDs:-N05k8hg8Q8X09ATaCzR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/repository/user_repository.py#L145)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment above.
</blockquote></details>

Done.
___
*[saltapi/service/user.py, line 36 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01J94p3lPX5cpyL16J:-N0AtA0w5q_D-lGfadRj:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/service/user.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems "institute" and "institution" is used for the same thing in the API (my fault, i guess). Only one or the other should be used.
</blockquote></details>

Done.
___
*[saltapi/service/user.py, line 37 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01JPS6EhveOw6uCdpc:-N05l-5zCYGvxG6ZFpeC:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/service/user.py#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

partners > partner
</blockquote></details>

Done.
___
*[saltapi/service/user.py, line 49 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01JbBFCqqkbs9ZqaHx:-N0At_SA0EGhbcHGSEt-:b-eiz5qf) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/service/user.py#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

institutions > affiliations

I'm not convinced that grouping by partner makes much sense for a user.
</blockquote></details>

I have removed a partner field from this schema and added partner code as per our discussion.
___
*[saltapi/web/api/users.py, line 9 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-b5Ntz6lx8SZv1t8P-:-N05quCa5nMHtdkrt2Wx:b4wkp3g) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/c426b80d676830f5b48f70cfa9466a0c7ad6bcc2/saltapi/web/api/users.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes, it applies to all services. And yes, the next three lines should also be changed, at least if their classes are used as response models.
</blockquote></details>

Noted, thanks! No changes were applied, all response models are using types from the schema package.
___
*[saltapi/web/api/users.py, line 92 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01KhB7D0qCV30jQPbN:-N05qRke5iQ6pgZWBUnl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/api/users.py#L92)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

list > List (I think that how it is done elsewhere in the code. From what I remember, list was made generic in Python only very recently.)
</blockquote></details>

Done.
___
*[saltapi/web/api/users.py, line 102 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01LEsK0L4CvWdYpL0I:-N0AtqVD3bHIW6hDmxJh:b-cvcyfa) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/api/users.py#L102)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you define an alias if it is the same as the parameter name?

But more importantly, I'm not convinced it is a good idea to have the same endpoint twice (once with user id, once with username).
</blockquote></details>

I agree with you, I tried merging the two by adding the user-id as a path parameter to the other method, and then making a request based on the supplied parameter. However, this didn't work out because it appears that one can't have optional path parameters in fastapi and so the method ends up requiring both the username and user-id. 

Any suggestions on how to go about it? Maybe we should have a chat about this.
___
*[saltapi/web/schema/institution.py, line 12 at r3](https:/ [...]

2022-04-21 18:09 UTC, hettlage requested changes
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: all files reviewed, 14 unresolved discussions (waiting on @mofokeng-chaka)

___
*[saltapi/repository/institution_repository.py, line 9 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0BY_aFEJhZfTl6yDuI:-N0BY_aFEJhZfTl6yDuJ:bs0471p) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/repository/institution_repository.py#L9)):*
> ```Python
> 
> 
> def get_department(departments_list: list[str], index: int) -> str:
> ```

Why do you need this method?
___
*[saltapi/repository/institution_repository.py, line 36 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0BZ6wr54MftzORsEAp:-N0BZ6wr54MftzORsEAq:bfuyh4v) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/repository/institution_repository.py#L36)):*
> ```Python
>         stmt = text(
>             """
> SELECT P.Partner_Code   AS partner_code,
> ```

I think in this case you should do the grouping in Python rather than in the database query.
___
*[saltapi/repository/user_repository.py, line 54 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N-RsJaxEho3XtSQejyn:-N0CFcVsBivZx1zaHdae:byucmid) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/e7a34fb30aabebd4c552e58689fe11037c85d364/saltapi/repository/user_repository.py#L54)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, but I think this still needs discussion. :(
___
*[saltapi/repository/user_repository.py, line 100 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CFirz-a_966Q1Qo3c:-N0CFirz-a_966Q1Qo3d:b-8tzqt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/repository/user_repository.py#L100)):*
> ```Python
>          JOIN InstituteName I ON I2.InstituteName_Id = I.InstituteName_Id
> WHERE PU.PiptUser_Id = :pipt_user_id
> GROUP BY id, username
> ```

It would be enough to either group by id or by username.
___
*[saltapi/service/user.py, line 36 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01J94p3lPX5cpyL16J:-N0CFymB1NYUzjut3iRy:b-tnq0w3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/service/user.py#L36)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, I think this is still an issue...
___
*[saltapi/service/user.py, line 38 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CGFUHDAH1yirbUJf2:-N0CGFUHDAH1yirbUJf3:b-grz5us) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/service/user.py#L38)):*
> ```Python
> 
> @dataclass()
> class PartnerInstitutes(Institute):
> ```

Couldn't you just add the partner to the Institute type?

And the type would be "PartnerInstitute", I think.
___
*[saltapi/service/user_service.py, line 64 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CGpOS2IEU5KKTZKum:-N0CGpOS2IEU5KKTZKun:b4y8avb) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/service/user_service.py#L64)):*
> ```Python
>             subject="SALT Web Manager password reset",
>         )
>         mail_service.send_email(to=[user.emails[0]], message=message)
> ```

This isn't guaranteed to be the user's preferred email address.
___
*[saltapi/web/api/users.py, line 102 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01LEsK0L4CvWdYpL0I:-N0CHBPE09v4MMY2wAHf:b9ls05g) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/api/users.py#L102)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I agree with you, I tried merging the two by adding the user-id as a path parameter to the other method, and then making a request based on the supplied parameter. However, this didn't work out because it appears that one can't have optional path parameters in fastapi and so the method ends up requiring both the username and user-id. 

Any suggestions on how to go about it? Maybe we should have a chat about this.
</blockquote></details>

Yes, let's chat about this.
___
*[saltapi/web/api/users.py, line 124 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CHN0c0__Ys-jsqoOi:-N0CHN0c0__Ys-jsqoOj:b5yh64d) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/api/users.py#L124)):*
> ```Python
>     with UnitOfWork() as unit_of_work:
>         permission_service = services.permission_service(unit_of_work.connection)
>         permission_service.check_permission_to_view_user(user, username)
> ```

Why have you removed the permission check?
___
*[saltapi/web/schema/institution.py, line 19 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01wnjO2UzdjxbQJrw5:-N0CHZDSEmIumXfqf3Gk:bl643tl) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/schema/institution.py#L19)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

See my comment(s) on the corresponding type above.
___
*[saltapi/web/schema/institution.py, line 30 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01wcx-3zb76MTFK_db:-N0CHkelCJOLvZKgExt5:b-ahgrzy) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/schema/institution.py#L30)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Might still need discussion.
___
*[saltapi/web/schema/institution.py, line 45 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CHd9w9YSH47pI7eFK:-N0CHd9w9YSH47pI7eFL:bolrcwl) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/web/schema/institution.py#L45)):*
> ```Python
> 
>     partner_code: str = Field(
>         ..., title="Partner institution code", description="Partner institution code"
> ```

Partner institution code > Partner code
___
*[saltapi/web/schema/proposal.py, line 43 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CHrQiAK3y-PPJjDxR:-N0CHrQiAK3y-PPJjDxS:b-x227ok) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/web/schema/proposal.py#L43)):*
> ```Python
>         ..., title="Family name", description='Family ("last") name'
>     )
>     emails: List[EmailStr] = Field(
> ```

The preferred email might need discussion.
___
*[saltapi/web/schema/user.py, line 40 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CIHBPAm9tkw4_Wrr4:-N0CIHBPAm9tkw4_Wrr5:bk420fw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/web/schema/user.py#L40)):*
> ```Python
>     """List of affiliations of the users."""
> 
>     username: str = Field(..., title="Username", description="Username.")
> ```

This looks odd... Shouldn't at least the affiliations ne part of the ProposalUser type?
___
*[tests/repository/test_user_repository.py, line 83 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CIiIJ5FfmxVqTBxJE:-N0CIe-b4syospars5tZ:b-hvcnzg) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/tests/repository/test_user_repository.py#L83)):*
> ```Python
>     new_user_details = NewUserDeta [...]

2022-04-24 05:25 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: 4 of 17 files reviewed, 14 unresolved discussions (waiting on @hettlage)

___
*[saltapi/repository/institution_repository.py, line 9 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0BY_aFEJhZfTl6yDuI:-N0F3Lj3-kRUzAHpEglE:blqi78z) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/repository/institution_repository.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need this method?
</blockquote></details>

For some weird reason when I loop over departments I get an index out of range error.
___
*[saltapi/repository/institution_repository.py, line 36 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0BZ6wr54MftzORsEAp:-N0P-fygCDBWOEqUZmNn:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/repository/institution_repository.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think in this case you should do the grouping in Python rather than in the database query.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 100 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CFirz-a_966Q1Qo3c:-N0FAHqjD5wszWupgyzu:bzbegzm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/repository/user_repository.py#L100)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It would be enough to either group by id or by username.
</blockquote></details>

The grouping is no longer necessary because the resultant query is grouped in python.
___
*[saltapi/service/user.py, line 36 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01J94p3lPX5cpyL16J:-N0P-mK660Kan0Rt3sg7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/service/user.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No, I think this is still an issue...
</blockquote></details>

Done.
___
*[saltapi/service/user.py, line 38 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CGFUHDAH1yirbUJf2:-N0P-nAV4ZxH623wmchx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/service/user.py#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Couldn't you just add the partner to the Institute type?

And the type would be "PartnerInstitute", I think.
</blockquote></details>

Done.
___
*[saltapi/service/user_service.py, line 64 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CGpOS2IEU5KKTZKum:-N0P-okpDoXC8ul1v8II:b-m53odo) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/service/user_service.py#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This isn't guaranteed to be the user's preferred email address.
</blockquote></details>

This should be solved now because we have a separate field for primary and alternative emails
___
*[saltapi/web/api/users.py, line 102 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01LEsK0L4CvWdYpL0I:-N0P-pnn1PLz2HigWxAn:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/api/users.py#L102)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes, let's chat about this.
</blockquote></details>

Done.
___
*[saltapi/web/api/users.py, line 124 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CHN0c0__Ys-jsqoOi:-N0F8ydS9Dtmzd6bmzOx:b1o3ezf) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/api/users.py#L124)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why have you removed the permission check?
</blockquote></details>

It was a mistake, I may have removed it when I was trying to merge the two endpoints and I forgot to add it back when I was undoing the changes
___
*[saltapi/web/schema/institution.py, line 19 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01wnjO2UzdjxbQJrw5:-N0P-qvh7fXNm4uQ-Exx:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/schema/institution.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See my comment(s) on the corresponding type above.
</blockquote></details>

Done.
___
*[saltapi/web/schema/institution.py, line 30 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01wcx-3zb76MTFK_db:-N0P-s3_9HpJXlruOrFg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/schema/institution.py#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might still need discussion.
</blockquote></details>

Done.
___
*[saltapi/web/schema/institution.py, line 45 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CHd9w9YSH47pI7eFK:-N0P-rIs9x52FhL56D5I:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/web/schema/institution.py#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Partner institution code > Partner code
</blockquote></details>

Done.
___
*[saltapi/web/schema/user.py, line 40 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CIHBPAm9tkw4_Wrr4:-N0P-w_97_NLf2YLKlKE:bayvutw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/web/schema/user.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This looks odd... Shouldn't at least the affiliations ne part of the ProposalUser type?
</blockquote></details>

As per our discussion, we've agreed to keep the affiliations as part of the User type.
___
*[tests/repository/test_user_repository.py, line 83 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CIiIJ5FfmxVqTBxJE:-N0FB_xMBGFAPHMxCHMH:bbr8xpd) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/tests/repository/test_user_repository.py#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need the `EmailStr`?
</blockquote></details>

It is because mypy was complaining about types not matching.
___
*[saltapi/web/schema/proposal.py, line 43 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0CHrQiAK3y-PPJjDxR:-N0P-toE6LfaHHCfd0wK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/web/schema/proposal.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The preferred email might need discussion.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-25 08:27 UTC, hettlage requested changes
> Reviewed 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: all files reviewed, 25 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`saltapi/repository/institution_repository.py` line 9 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0BY_aFEJhZfTl6yDuI:-N0Ub_1V2O51lwAfPVpW:b-gmv9ay) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/repository/institution_repository.py#L9)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

For some weird reason when I loop over departments I get an index out of range error.
</blockquote></details>

The method is not used any longer.
___
*[`saltapi/repository/institution_repository.py` line 22 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UbvH293Ttm1fPCSIz:-N0UbvH293Ttm1fPCSJ-:b22aj2a) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/institution_repository.py#L22)):*
> ```Python
>         Returns a list of institutions
>         """
>         separator = "::::"
> ```

The separator is not necessary any longer
___
*[`saltapi/repository/institution_repository.py` line 34 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Uc2oM1pL5lf2H9UWE:-N0Uc2oN-MGnN_i6Ar7z:b22aj2a) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/institution_repository.py#L34)):*
> ```Python
>             """
>         )
>         result = self.connection.execute(stmt, {"separator": separator})
> ```

The separator is not necessary any longer
___
*[`saltapi/repository/user_repository.py` line 22 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UexR_2pi-qTXalpoa:-N0UexRa1Ky8ortx0ToA:bi2ivut) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L22)):*
> ```Python
>         self.connection = connection
> 
>     def get(self, username: str) -> User:
> ```

get, get_by_id and get_by_email are essentially the same, aren't they? You might consider moving most of their functionality into a helper function.

Also, given that users are now identified by id (aren't they?), `get` should be `get_by_username` and `get_by_id` should bet `get`.
___
*[`saltapi/repository/user_repository.py` line 28 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UfYuHB8zmBUMrV-f2:-N0UfYuHB8zmBUMrV-f3:b18jt2k) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L28)):*
> ```Python
>         If the username does not exist, a NotFoundError is raised.
>         """
>         separator = "::::"
> ```

The separator is not used any longer
___
*[`saltapi/repository/user_repository.py` line 33 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Ud811BSxLVcLPf3Fu:-N0Ud811BSxLVcLPf3Fv:b4qzzb8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L33)):*
> ```Python
> SELECT PU.PiptUser_Id           AS id,
>        I1.Email                 AS email,
>        I0.Email                 AS alternative_emails,
> ```

alternative_emails is arguably misleading for two reasons:

1. It is only one email per row
2. It may very well be the primary email

So maybe rather calk this column email and the other primary_email?
___
*[`saltapi/repository/user_repository.py` line 43 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UcN6ZCb9ykr46eOLh:-N0UcN6ZCb9ykr46eOLi:b-zd1cmt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L43)):*
> ```Python
>        I2.Department            AS department
> FROM PiptUser AS PU
>          JOIN Investigator AS I0 ON (PU.PiptUser_Id = I0.PiptUser_Id)
> ```

Unnecessary parentheses
___
*[`saltapi/repository/user_repository.py` line 52 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UfbTNA-yXaVGZ4kNA:-N0UfbTNA-yXaVGZ4kNB:b18jt2k) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L52)):*
> ```Python
>         )
>         result = self.connection.execute(
>             stmt, {"separator": separator, "username": username}
> ```

The separator is not used any longer
___
*[`saltapi/repository/user_repository.py` line 64 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Udc5dELunfkeVroD_:-N0Udc5dELunfkeVroDa:bi177a8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L64)):*
> ```Python
>                     "email": row.email,
>                     "alternative_emails": [
>                         row.alternative_emails
> ```

You shouldn't include empty strings in the list, so you could rather use:

```
[row.alternative_emails] if row.alternative_emails != row.email else []
```
___
*[`saltapi/repository/user_repository.py` line 79 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Udz_l9qLGj4kG3dO6:-N0Udz_l9qLGj4kG3dO7:bui1xus) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L79)):*
> ```Python
>                 }
>             else:
>                 user["alternative_emails"].append(
> ```

You shouldn't include empty strings in the list, so you could rather use:

```
if row.alternative_emails != row.email:
    user["alternative_emails"].append(row.alternative_emails )
```
___
*[`saltapi/service/user.py` line 31 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Ug_TB0Y_ehuYj2G81:-N0Ug_TB0Y_ehuYj2G82:bc5cnku) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/service/user.py#L31)):*
> ```Python
> 
> @dataclass()
> class PartnerInstitutes:
> ```

Shouldn't this type be called `Institution`?
___
*[`saltapi/service/user.py` line 32 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Uge2EChRgdLeiEUsQ:-N0Uge2EChRgdLeiEUsR:b-4zoo6v) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/service/user.py#L32)):*
> ```Python
> @dataclass()
> class PartnerInstitutes:
>     institute_id: int
> ```

Shouldn't this be `institution_id`?
___
*[`saltapi/service/user.py` line 43 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UglOX0QESWq2G7gKJ:-N0UglOX0QESWq2G7gKK:bxcfp5n) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/service/user.py#L43)):*
> ```Python
>     username: str
>     email: str
>     alternative_emails: Optional[List[str]]
> ```

I don;'t think the list has to be optional. If there is no email address, the list can just be empty.
___
*[`saltapi/web/api/users.py` line 102 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01LEsK0L4CvWdYpL0I:-N0UhZdHAUtEquLK2UI9:b-thekyx) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/api/users.py#L102)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But there are still two endpoints...?
___
*[`saltapi/web/api/users.py` line 78 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UhEOHB26x5720pCmh:-N0UhEOHB26x5720pCmi:b58vy8s) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/web/ap [...]

2022-04-25 11:49 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: 5 of 23 files reviewed, 20 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/institution_repository.py` line 9 at r4](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0BY_aFEJhZfTl6yDuI:-N0UsxDm0sDnqmeqdUL6:b-v6s1op) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/0aa220a4fb8f931e8e38c7b8faca4d810bd31bf3/saltapi/repository/institution_repository.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The method is not used any longer.
</blockquote></details>

Removed.
___
*[`saltapi/repository/institution_repository.py` line 22 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UbvH293Ttm1fPCSIz:-N0Ut7iU9Di0glaX2W-O:bss4a2b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/institution_repository.py#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The separator is not necessary any longer
</blockquote></details>

Removed.
___
*[`saltapi/repository/institution_repository.py` line 34 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Uc2oM1pL5lf2H9UWE:-N0UtC8_2042AD2cxL_2:bss4a2b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/institution_repository.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The separator is not necessary any longer
</blockquote></details>

Removed.
___
*[`saltapi/repository/user_repository.py` line 22 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UexR_2pi-qTXalpoa:-N0V3H7p6KL8Qkodpy4E:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

get, get_by_id and get_by_email are essentially the same, aren't they? You might consider moving most of their functionality into a helper function.

Also, given that users are now identified by id (aren't they?), `get` should be `get_by_username` and `get_by_id` should bet `get`.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 28 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UfYuHB8zmBUMrV-f2:-N0UuH9iDY1l6RMX_-1P:bss4a2b) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The separator is not used any longer
</blockquote></details>

Removed.
___
*[`saltapi/repository/user_repository.py` line 33 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Ud811BSxLVcLPf3Fu:-N0VUtcg8ZgjEao6rGEZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

alternative_emails is arguably misleading for two reasons:

1. It is only one email per row
2. It may very well be the primary email

So maybe rather calk this column email and the other primary_email?
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 43 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UcN6ZCb9ykr46eOLh:-N0V3Qlk6FtthEQJR3GA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary parentheses
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 52 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UfbTNA-yXaVGZ4kNA:-N0Uu_Ae2Tr9tOG3IlQw:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The separator is not used any longer
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 64 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Udc5dELunfkeVroD_:-N0V3UB-AD5PfNxO9fCB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You shouldn't include empty strings in the list, so you could rather use:

```
[row.alternative_emails] if row.alternative_emails != row.email else []
```
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 79 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Udz_l9qLGj4kG3dO6:-N0V3UsGDIj9pKOGW2m_:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You shouldn't include empty strings in the list, so you could rather use:

```
if row.alternative_emails != row.email:
    user["alternative_emails"].append(row.alternative_emails )
```
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 31 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Ug_TB0Y_ehuYj2G81:-N0VUwP77urPoPsTE12r:bwza6ve) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/service/user.py#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this type be called `Institution`?
</blockquote></details>

I have used the `Affiliation` type from the proposal schema
___
*[`saltapi/service/user.py` line 32 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Uge2EChRgdLeiEUsQ:-N0VWZfi9dLG8UTWLUtG:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/service/user.py#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be `institution_id`?
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 43 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UglOX0QESWq2G7gKJ:-N0VW_lv1EV_m-z3enjn:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/service/user.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don;'t think the list has to be optional. If there is no email address, the list can just be empty.
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 102 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N01LEsK0L4CvWdYpL0I:-N0VWdw0B_8GVSzUGaUf:b-buesbn) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/753cf0a7aee059ba3aa50cb47d385c2992d22c79/saltapi/web/api/users.py#L102)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But there are still two endpoints...?
</blockquote></details>

Have removed the other endpoint now
___
*[`saltapi/web/api/users.py` line 78 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UhEOHB26x5720pCmh:-N0VWclh2UBz8poqdMyM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/web/api/users.py#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about the alternative emails?
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 109 at r5](https://reviewable.io/reviews/saltastroops/sa [...]

2022-04-25 16:55 UTC, hettlage requested changes
> Reviewed 18 of 18 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: all files reviewed, 16 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/institution_repository.py` line 30 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WAlalA1c2Hh-MZ87L:-N0WAlalA1c2Hh-MZ87M:bw9dzrv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/repository/institution_repository.py#L30)):*
> ```Python
>             {
>                 "institution_id": row.institution_id,
>                 "institution": row.institute,
> ```

Shouldn't this be `row.institution`?
___
*[`saltapi/repository/proposal_repository.py` line 504 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WB7z2C0YFpUwSlkLM:-N0WB7z2C0YFpUwSlkLN:b8stxme) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/repository/proposal_repository.py#L504)):*
> ```Python
>         return info
> 
>     def _investigators(self, proposal_code: str) -> List[Dict[str, Any]]:
> ```

Shouldn't institute be institution throughout this method?
___
*[`saltapi/repository/user_repository.py` line 22 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UexR_2pi-qTXalpoa:-N0WcyU13Y1zXf6fHkjF:bjfsaxt) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L22)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You might even consider reusing the SQL statements -- they differ only in the WHERE condition, don't they?
___
*[`saltapi/repository/user_repository.py` line 33 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Ud811BSxLVcLPf3Fu:-N0WcbbG9c2WC8if15Xz:b-4wub15) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L33)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ahhh, this is where the new type field names come from. But my comments was referring to the SQL statement, not to the type fields... :-/
___
*[`saltapi/repository/user_repository.py` line 31 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WBlN_24ZRO_toihZJ:-N0WBlN_24ZRO_toihZK:b8ubqkm) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/repository/user_repository.py#L31)):*
> ```Python
>                     "family_name": row.family_name,
>                     "given_name": row.given_name,
>                     "primary_email": row.email,
> ```

I think the original names (email and alternative_emails) were better.
___
*[`saltapi/repository/user_repository.py` line 32 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WC51cC-NJJR2Fxy9u:-N0WC51d5QzxbHhf6938:b-blohdy) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/repository/user_repository.py#L32)):*
> ```Python
>                     "given_name": row.given_name,
>                     "primary_email": row.email,
>                     "email": [row.alternative_emails]
> ```

alternative_emails should be alternative_email, as there is only one (per row).
___
*[`saltapi/repository/user_repository.py` line 85 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WCbPM71k8z1vQ81rz:-N0WCbPM71k8z1vQ81s-:bg4dim8) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/repository/user_repository.py#L85)):*
> ```Python
>          JOIN Partner P ON I2.Partner_Id = P.Partner_Id
>          JOIN InstituteName I ON I2.InstituteName_Id = I.InstituteName_Id
> AND PU.Username = :username
> ```

Did you mean `WHERE` rather than `AND`?
___
*[`saltapi/service/user.py` line 31 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Ug_TB0Y_ehuYj2G81:-N0WDIKrBiniAItE8IEC:bqfv3fq) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/service/user.py#L31)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have used the `Affiliation` type from the proposal schema
</blockquote></details>

But it really is an Institution -- I'd say the schema needs to change.
___
*[`saltapi/service/user.py` line 20 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WD0S30hZGtYOaezu8:-N0WD0S30hZGtYOaezu9:bqh481e) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/service/user.py#L20)):*
> ```Python
>     given_name: str
>     family_name: str
>     primary_email: EmailStr
> ```

As indicated above, I'd rather say:

primary_email > email
email > alternative_emails
___
*[`saltapi/service/user.py` line 57 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0W_Qdv8Yav3mHQIMMY:-N0W_Qdv8Yav3mHQIMMZ:b-pnzdo7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/service/user.py#L57)):*
> ```Python
>     family_name: str
>     primary_email: EmailStr
>     email: List[str]
> ```

Shouldn't that be `List[EmailStr]`?
___
*[`saltapi/web/api/institutions.py` line 9 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0W_e7j5vAYuWoFxiIg:-N0W_e7j5vAYuWoFxiIh:b59cigj) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/web/api/institutions.py#L9)):*
> ```Python
> from saltapi.service.user import User as _User
> from saltapi.web import services
> from saltapi.web.schema.common import Affiliation
> ```

Maybe `Institution` rather than `Affiliation`?
___
*[`saltapi/web/api/users.py` line 133 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WaG715KUPv518iGlc:-N0WaG715KUPv518iGld:blj03pp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/web/api/users.py#L133)):*
> ```Python
>         )
>         user_service = services.user_service(unit_of_work.connection)
>         user_service.update_user(user.username, _user_update)
> ```

I guess the update_user method should identify a user by id...
___
*[`saltapi/web/api/users.py` line 136 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Wa8D84vAgcERBjcJp:-N0Wa8D9-cvJkfGDbubu:bhqg6sp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/web/api/users.py#L136)):*
> ```Python
>         unit_of_work.commit()
> 
>         new_username = user_update.username if user_update.username else user.username
> ```

Why don't you get the user by id?
___
*[`saltapi/web/schema/institution.py` line 27 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UhnKFCNJCCsxRl-PA:-N0WdDFS06vxSkJHVUn1:b-7h3gsz) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/web/schema/institution.py#L27)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change?

(And isn't this the same as the Affiliation type elsewhere?)
___
*[`saltapi/web/schema/proposal.py` line 21 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WbYrsEJFuhKexsya8:-N0WbYrsEJFuhKexsya9:b-tegbnb) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/web/schema/proposal.py#L21)):*
> ```Python
> 
> 
> class ProposalUser(Usernames):
> ```

Maybe this type can be called Investigator now?
___
*[`salta [...]

2022-04-26 08:23 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: 8 of 23 files reviewed, 16 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/institution_repository.py` line 30 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WAlalA1c2Hh-MZ87L:-N0Zgz_fBiPe-_SZdQTK:b-65vzx5) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/repository/institution_repository.py#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be `row.institution`?
</blockquote></details>

It should be well spotted. Thanks!
___
*[`saltapi/repository/proposal_repository.py` line 504 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WB7z2C0YFpUwSlkLM:-N0Zj2BKBNZUC258p4Mu:bscdkx2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/repository/proposal_repository.py#L504)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't institute be institution throughout this method?
</blockquote></details>

It should and I have fixed it now.
___
*[`saltapi/repository/user_repository.py` line 33 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Ud811BSxLVcLPf3Fu:-N0ZrrEL5lD1PpJTrOsE:b3ar1bb) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ahhh, this is where the new type field names come from. But my comments was referring to the SQL statement, not to the type fields... :-/
</blockquote></details>

I guess I read too much into your comments sometimes :'(
___
*[`saltapi/repository/user_repository.py` line 31 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WBlN_24ZRO_toihZJ:-N0ZpKrLA_rvmguLxuPD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/repository/user_repository.py#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the original names (email and alternative_emails) were better.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 32 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WC51cC-NJJR2Fxy9u:-N0ZpLe28cPm4lXXYX1V:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/repository/user_repository.py#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

alternative_emails should be alternative_email, as there is only one (per row).
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 85 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WCbPM71k8z1vQ81rz:-N0ZlI2z37HVBW-vTkuc:b-t9x8jk) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/repository/user_repository.py#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Did you mean `WHERE` rather than `AND`?
</blockquote></details>

Yep, well spotted, thanks! And have changed it now.
___
*[`saltapi/service/user.py` line 31 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Ug_TB0Y_ehuYj2G81:-N0ZnrEA3kNQuDIAts0L:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/service/user.py#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But it really is an Institution -- I'd say the schema needs to change.
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 20 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WD0S30hZGtYOaezu8:-N0ZlplfCGT5FECTb5XA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/service/user.py#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As indicated above, I'd rather say:

primary_email > email
email > alternative_emails
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 57 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0W_Qdv8Yav3mHQIMMY:-N0ZlvNw2i3pC0K1P-yY:bvjn5iv) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/service/user.py#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't that be `List[EmailStr]`?
</blockquote></details>

I agree and I did try it, and I always get pydantic errors because of `None` values in the email and/or empty lists.
___
*[`saltapi/web/api/institutions.py` line 9 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0W_e7j5vAYuWoFxiIg:-N0Znw8V7q0V61zIl_zS:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/web/api/institutions.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe `Institution` rather than `Affiliation`?
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 133 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WaG715KUPv518iGlc:-N0ZrD_cAhdS7PbR6qNT:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/web/api/users.py#L133)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess the update_user method should identify a user by id...
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 136 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Wa8D84vAgcERBjcJp:-N0Zrg5GCHQy0V-O9MZz:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/web/api/users.py#L136)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you get the user by id?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/institution.py` line 27 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UhnKFCNJCCsxRl-PA:-N0Zo2eWCTBVKjHZ1eQc:b-ox420l) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/web/schema/institution.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see a change?

(And isn't this the same as the Affiliation type elsewhere?)
</blockquote></details>

That's true and I should have removed this schema because it is no longer being used.
___
*[`saltapi/web/schema/proposal.py` line 21 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WbYrsEJFuhKexsya8:-N0ZoX1F3bpcaRIRIY3M:b-pbc7rp) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/web/schema/proposal.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe this type can be called Investigator now?
</blockquote></details>

Investigator type already exists in this file
___
*[`saltapi/web/schema/user.py` line 36 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0WadRx7oKIg73BSuPL:-N0Zp3n09bzRM_aFY7cy:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/web/schema/user.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Usernames > FullName (or something like that)
</blockquote></details>

Done.
___
*[`saltapi/web/schema/user.py` line 47 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0Wb-n096KUISkltavv:-N0ZpFHb9HOgnMhe2v1V:b-ybw447) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533cacc [...]

2022-04-26 09:29 UTC, hettlage requested changes
> Reviewed 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: all files reviewed, 8 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/user_repository.py` line 32 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_8rJeBkEadBmQb5B9:-N0_8rJeBkEadBmQb5BA:b-kxnsit) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/repository/user_repository.py#L32)):*
> ```Python
>                     "given_name": row.given_name,
>                     "email": row.email,
>                     "alternative_email": [row.alternative_email]
> ```

Shouldn't this be `alternative_emails`, given it is a list?
___
*[`saltapi/service/user.py` line 57 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0W_Qdv8Yav3mHQIMMY:-N0_C3mz3erlI3pIclfs:bz0l11s) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/service/user.py#L57)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I agree and I did try it, and I always get pydantic errors because of `None` values in the email and/or empty lists.
</blockquote></details>

Can you show me? :-)
___
*[`saltapi/service/user.py` line 21 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_9LDU-SsmmgQpw4EJ:-N0_9LDVDLq1GCQxCg7X:b-kxnsit) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/service/user.py#L21)):*
> ```Python
>     family_name: str
>     email: EmailStr
>     alternative_email: List[str]
> ```

Shouldn't this be `alternative_emails`, given it is a list?
___
*[`saltapi/service/user.py` line 45 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_9PEFCKki1FcoafhT:-N0_9PEFCKki1FcoafhU:b-kxnsit) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/service/user.py#L45)):*
> ```Python
>     family_name: str
>     email: EmailStr
>     alternative_email: List[str]
> ```

Shouldn't this be `alternative_emails`, given it is a list?
___
*[`saltapi/service/user.py` line 57 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_9RhK4a8atGEqyMns:-N0_9RhK4a8atGEqyMnt:b-kxnsit) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/service/user.py#L57)):*
> ```Python
>     family_name: str
>     email: EmailStr
>     alternative_email: List[str]
> ```

Shouldn't this be `alternative_emails`, given it is a list?
___
*[`saltapi/web/api/users.py` line 79 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_9imN872OYe3DO9kZ:-N0_9imN872OYe3DO9k_:b-kxnsit) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/web/api/users.py#L79)):*
> ```Python
>                 password=user.password,
>                 email=user.email,
>                 alternative_email=[],
> ```

Shouldn't this be `alternative_emails`, given it is a list?
___
*[`saltapi/web/schema/institution.py` line 10 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_AB2XD0y_XcS-mS1Z:-N0_AB2XD0y_XcS-mS1_:bdtli28) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/web/schema/institution.py#L10)):*
> ```Python
> 
> class Institution(BaseModel):
>     """An institute affiliation."""
> ```

An institute affiliation > An institution
___
*[`saltapi/web/schema/institution.py` line 14 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_AHqt-jfsFfKZYj0z:-N0_AHqt-jfsFfKZYj1-:b-57gqwd) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/web/schema/institution.py#L14)):*
> ```Python
>     institution_id: int = Field(
>         ...,
>         title="Institute id",
> ```

Throughout the method:

institute > institution


<!-- Sent from Reviewable.io -->

2022-04-26 11:30 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: 12 of 23 files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/user_repository.py` line 22 at r5](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0UexR_2pi-qTXalpoa:-N0_cjVKEQU4tY1QIOM7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/fec58d547936e7a28755bdd6e499f136b7a20e9b/saltapi/repository/user_repository.py#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might even consider reusing the SQL statements -- they differ only in the WHERE condition, don't they?
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 32 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_8rJeBkEadBmQb5B9:-N0_DjQP8kIgKkloB8El:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/repository/user_repository.py#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be `alternative_emails`, given it is a list?
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 57 at r6](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0W_Qdv8Yav3mHQIMMY:-N0_Fz1E5hrNp1j3NvM_:bofxh3p) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/3533caccd3f85178bbd5c6cc59325e562f18fc8b/saltapi/service/user.py#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can you show me? :-)
</blockquote></details>

Oh, I stand corrected. It is actually working :-). It wasn't working previously because I was appending empty values to the array.
___
*[`saltapi/service/user.py` line 21 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_9LDU-SsmmgQpw4EJ:-N0_Dl3t6TlX2v7VXGST:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/service/user.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be `alternative_emails`, given it is a list?
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 45 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_9PEFCKki1FcoafhT:-N0_E2CF0QOEPHahVn7U:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/service/user.py#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be `alternative_emails`, given it is a list?
</blockquote></details>

Done.
___
*[`saltapi/service/user.py` line 57 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_9RhK4a8atGEqyMns:-N0_G7t3DtFrbnCr0XCw:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/service/user.py#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be `alternative_emails`, given it is a list?
</blockquote></details>

Done.
___
*[`saltapi/web/api/users.py` line 79 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_9imN872OYe3DO9kZ:-N0_GBPI8WnijYoIQoTv:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/web/api/users.py#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be `alternative_emails`, given it is a list?
</blockquote></details>

Done.
___
*[`saltapi/web/schema/institution.py` line 10 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_AB2XD0y_XcS-mS1Z:-N0_GQ1UCbT-qOL1aKbO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/web/schema/institution.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

An institute affiliation > An institution
</blockquote></details>

Done.
___
*[`saltapi/web/schema/institution.py` line 14 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_AHqt-jfsFfKZYj0z:-N0_GQORC5j--ZIAe0td:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/web/schema/institution.py#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Throughout the method:

institute > institution
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-26 12:23 UTC, hettlage requested changes
> Reviewed 11 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: all files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/user_repository.py` line 85 at r8](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_nqu_1ZIVETdHeLvs:-N0_nqu_1ZIVETdHeLvt:b-pv5muw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/97a0161e304847ee4747a300a355ec1b7ccccf5f/saltapi/repository/user_repository.py#L85)):*
> ```Python
>         If the username does not exist, a NotFoundError is raised.
>         """
>         query = self._get_user_query + """WHERE PU.Username = '%s'""" % username
> ```

This approach is dangerous, as it doesn't guarantee that your variable is properly escaped.
___
*[`saltapi/repository/user_repository.py` line 97 at r8](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_o8LS5VGxXzqBKeU3:-N0_o8LT3HOu1E6bjNhc:b-pv5muw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/97a0161e304847ee4747a300a355ec1b7ccccf5f/saltapi/repository/user_repository.py#L97)):*
> ```Python
>         If there is no such user, a NotFoundError is raised.
>         """
>         query = self._get_user_query + """\nWHERE PU.PiptUser_Id = %s""" % user_id
> ```

This approach is dangerous, as it doesn't guarantee that your variable is properly escaped.
___
*[`saltapi/repository/user_repository.py` line 109 at r8](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_oA0k8Dv5qQ_YlyVQ:-N0_oA0k8Dv5qQ_YlyVR:b-pv5muw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/97a0161e304847ee4747a300a355ec1b7ccccf5f/saltapi/repository/user_repository.py#L109)):*
> ```Python
>         If there is no such user, a NotFoundError is raised.
>         """
>         query = self._get_user_query + """\nWHERE I1.Email = '%s'""" % email
> ```

This approach is dangerous, as it doesn't guarantee that your variable is properly escaped.
___
*[`saltapi/web/schema/institution.py` line 10 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_AB2XD0y_XcS-mS1Z:-N0_oVCZ98Wnl4Wl_8W_:b-8kj5cw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/web/schema/institution.py#L10)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I actually really meant "An institution", not "An institution affiliation"... :-)


<!-- Sent from Reviewable.io -->

2022-04-26 12:44 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: 21 of 23 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/user_repository.py` line 85 at r8](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_nqu_1ZIVETdHeLvs:-N0_thVm8WlNPZYo6HhL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/97a0161e304847ee4747a300a355ec1b7ccccf5f/saltapi/repository/user_repository.py#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This approach is dangerous, as it doesn't guarantee that your variable is properly escaped.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 97 at r8](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_o8LS5VGxXzqBKeU3:-N0_thwy5xxGIwjr28hJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/97a0161e304847ee4747a300a355ec1b7ccccf5f/saltapi/repository/user_repository.py#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This approach is dangerous, as it doesn't guarantee that your variable is properly escaped.
</blockquote></details>

Done.
___
*[`saltapi/repository/user_repository.py` line 109 at r8](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_oA0k8Dv5qQ_YlyVQ:-N0_tiPX7jbjhHCHkEbZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/97a0161e304847ee4747a300a355ec1b7ccccf5f/saltapi/repository/user_repository.py#L109)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This approach is dangerous, as it doesn't guarantee that your variable is properly escaped.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/institution.py` line 10 at r7](https://reviewable.io/reviews/saltastroops/salt-api-2021/57#-N0_AB2XD0y_XcS-mS1Z:-N0_s9cWC6zuyShb9Nqc:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/d83b4b584137978d6978749053cf21b5318990b0/saltapi/web/schema/institution.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I actually really meant "An institution", not "An institution affiliation"... :-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-28 08:05 UTC, hettlage approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2022-04-28 08:07 UTC, merged