finder-charts-endpoint
saltastroops/salt-api pull request #84
Opened 2022-07-07 13:05 UTC by mofokeng-chaka

Finder charts endpoint

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/salt-api-2021/84)

2022-07-07 17:33 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/84)* status: all files reviewed, 17 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/settings.py` line 98 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6O_wX6B4TU1oL1xQg9:-N6O_wX6B4TU1oL1xQgA:b-vws29s) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/settings.py#L98)):*
> ```Python
> 
>     # Finding charts directory
>     finding_charts_dir: str
> ```

This seems to be the same as the proposals_dir env variable.
___
*[`saltapi/repository/finder_chart_repository.py` line 15 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Oe4ee7UUuFmpkUXoX:-N6Oe4ee7UUuFmpkUXoY:b8a9euo) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/repository/finder_chart_repository.py#L15)):*
> ```Python
>         self.connection = connection
> 
>     def get(self, finder_chart_id: int) -> Any:
> ```

Why Any?
___
*[`saltapi/repository/finder_chart_repository.py` line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OeEXhAzo4NvNEBcaw:-N6OeEXhAzo4NvNEBcax:bqltkae) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/repository/finder_chart_repository.py#L35)):*
> ```Python
>             raise NotFoundError()
> 
>     def get_proposal_code_for_finder_chart_id(
> ```

Can't you just tweak the query in the `get` method so that it returns both the proposal code and path?
___
*[`saltapi/repository/finder_chart_repository.py` line 57 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OezZw6hvj3BwRlbPp:-N6OezZx0fwEnBoDgt82:blfhn62) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/repository/finder_chart_repository.py#L57)):*
> ```Python
> 
>         try:
>             proposal_codes = result.fetchall()
> ```

Why fetch all? Wouldn't one work, possibly with a UNIQUE in the query?
___
*[`saltapi/service/finder_chart_service.py` line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6ObEZP4nTDNcA39fPU:-N6ObEZP4nTDNcA39fPV:b9ahc1j) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/service/finder_chart_service.py#L10)):*
> ```Python
>         self.finder_chart_repository = finder_chart_repository
> 
>     def get_finder_chart(self, finder_chart_id: int) -> Any:
> ```

Why Any?

As noted elsewhere, this service should return the full absolute path, using the  setting for the base dir.

(The repository should still return what it does currently, I'd say.)
___
*[`saltapi/service/finder_chart_service.py` line 13 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Og3ZV6J-Z0uMhclYA:-N6Og3ZV6J-Z0uMhclYB:b-psycg2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/service/finder_chart_service.py#L13)):*
> ```Python
> 
>         """
>         Return a finder chart for a given id
> ```

Return the proposal code and path of a finder chart with a given id.
___
*[`saltapi/web/api/finder_charts.py` line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Oaq8-3lGRVo_1rzbv:-N6Oaq8-3lGRVo_1rzbw:b-ivacc7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/web/api/finder_charts.py#L1)):*
> ```Python
> import os.path as osp
> ```

Rather use the pathlib library. (And I wouldn't use an alias here.)
___
*[`saltapi/web/api/finder_charts.py` line 15 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OaL2XCamMjlJHPfaj:-N6OaL2XCamMjlJHPfak:b-tll65q) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/web/api/finder_charts.py#L15)):*
> ```Python
> router = APIRouter(prefix="/finder-charts", tags=["Finding charts"])
> 
> finder_charts_directory = get_settings().finding_charts_dir
> ```

I don't think a global variable is necessary for this.
___
*[`saltapi/web/api/finder_charts.py` line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6ObIpg-V-txET6e5fN:-N6ObIpg-V-txET6e5fO:b-h0vj13) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/web/api/finder_charts.py#L29)):*
> ```Python
>         finding_chart_service = services.finder_chart_service(unit_of_work.connection)
> 
>         [proposal_code, finder_chart_path] = finding_chart_service.get_finder_chart(
> ```

Maybe better just `proposal_code, finder_chart_path`, without the brackets?
___
*[`saltapi/web/api/finder_charts.py` line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OaSOq9-Gn8mrInlO9:-N6OaSOq9-Gn8mrInlOA:bnlnuw4) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/web/api/finder_charts.py#L35)):*
> ```Python
>         permission_service.check_permission_to_view_proposal(user, proposal_code)
> 
>         filename = osp.join(finder_charts_directory, proposal_code, finder_chart_path)
> ```

I think it should be up to the service to create and return the absolute file path for the finder chart,
___
*[`tests/integration/test_finder_charts.py` line 20 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6ObdKzD8sXFDmkicEk:-N6ObdL-8NDjRy8UaKeS:bpzjgwh) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/integration/test_finder_charts.py#L20)):*
> ```Python
> 
> 
> def test_get_finder_chart_returns_403_for_non_permitted_user(
> ```

Maybe better: non_authorised_user
___
*[`tests/integration/test_finder_charts.py` line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OhTzW7q08WNUlGAex:-N6OhTzW7q08WNUlGAey:bvukwg3) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/integration/test_finder_charts.py#L29)):*
> ```Python
> 
> 
> def test_get_returns_finder_chart_for_permitted_user(client: TestClient) -> None:
> ```

Maybe better: authorised_user
___
*[`tests/integration/test_finder_charts.py` line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OhVxZ5U-qqgOqCjsf:-N6OhVxZ5U-qqgOqCjsg:bdln8wf) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/integration/test_finder_charts.py#L29)):*
> ```Python
> 
> 
> def test_get_returns_finder_chart_for_permitted_user(client: TestClient) -> None:
> ```

This test is problematic -- the finder chart file generally won't exist and the test will fail.

The slightly tacky solution might be to catch FileNotFound exceptions and to check that their error message contains the correct path.
___
*[`tests/repository/test_finder_chart_repository.py` line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Od1-i0L03CjI_PA_1:-N6Od1-i0L03CjI_PA_2:bhqyuf2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/repository/test_finder_chart_repository.py#L7)):*
> ```Python
> 
> 
> def test_get_finding_chart_returns_content(db_connection: Connection) -> None:
> ```

returns_content > returns_correct_content
___
*[`tests/repository/test_finder_chart_repository.py` line 12 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Od6Oo4E3xuL36pa4s:-N6Od6Oo4E3xuL36pa4t:bcsaerw) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/repository/test_finder_chart_repository.py#L12)):*
> ```Python
>     finding_chart_repository = FinderChartRepository(db_connection)
>     finding_chart = finding_chart_repository.get(finding_chart_id [...]

2022-07-08 09:46 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/84)* status: 3 of 9 files reviewed, 17 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/settings.py` line 98 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6O_wX6B4TU1oL1xQg9:-N6RXa5K5AzgK8jtPCHB:b-gpqml2) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/settings.py#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This seems to be the same as the proposals_dir env variable.
</blockquote></details>

That's true, 
___
*[`saltapi/repository/finder_chart_repository.py` line 15 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Oe4ee7UUuFmpkUXoX:-N6SASlV60tLxNi5j3eR:b3vwm31) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/repository/finder_chart_repository.py#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why Any?
</blockquote></details>

Now changed to a proper type.
___
*[`saltapi/repository/finder_chart_repository.py` line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OeEXhAzo4NvNEBcaw:-N6RgnDL2rtJSwN0icYg:b4ecot) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/repository/finder_chart_repository.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can't you just tweak the query in the `get` method so that it returns both the proposal code and path?
</blockquote></details>

You're right, I tweaked the query and so now it returns both the proposal code and path.
___
*[`saltapi/repository/finder_chart_repository.py` line 57 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OezZw6hvj3BwRlbPp:-N6RgbC9-wMAXMwO3l1u:b-1iv1dg) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/repository/finder_chart_repository.py#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why fetch all? Wouldn't one work, possibly with a UNIQUE in the query?
</blockquote></details>

I used `DISITINCT` and it does work.
___
*[`saltapi/service/finder_chart_service.py` line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6ObEZP4nTDNcA39fPU:-N6SAI-Y1x5x75DRy3ID:bgpp26k) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/service/finder_chart_service.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why Any?

As noted elsewhere, this service should return the full absolute path, using the  setting for the base dir.

(The repository should still return what it does currently, I'd say.)
</blockquote></details>

I have changed Any to a proper type.
___
*[`saltapi/service/finder_chart_service.py` line 13 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Og3ZV6J-Z0uMhclYA:-N6RhzugDyp6cQlJQRhQ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/service/finder_chart_service.py#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Return the proposal code and path of a finder chart with a given id.
</blockquote></details>

Done.
___
*[`saltapi/web/api/finder_charts.py` line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Oaq8-3lGRVo_1rzbv:-N6RjpEp47RamB5E3HUN:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/web/api/finder_charts.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Rather use the pathlib library. (And I wouldn't use an alias here.)
</blockquote></details>

Done.
___
*[`saltapi/web/api/finder_charts.py` line 15 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OaL2XCamMjlJHPfaj:-N6RjoeDAoDDcEc9XjqF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/web/api/finder_charts.py#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think a global variable is necessary for this.
</blockquote></details>

Done.
___
*[`saltapi/web/api/finder_charts.py` line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6ObIpg-V-txET6e5fN:-N6Ro4C0AuGzLgtm-FTb:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/web/api/finder_charts.py#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better just `proposal_code, finder_chart_path`, without the brackets?
</blockquote></details>

Done.
___
*[`saltapi/web/api/finder_charts.py` line 35 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OaSOq9-Gn8mrInlO9:-N6Ro7I_9GyGAOXsUz0r:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/web/api/finder_charts.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think it should be up to the service to create and return the absolute file path for the finder chart,
</blockquote></details>

Done.
___
*[`tests/integration/test_finder_charts.py` line 20 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6ObdKzD8sXFDmkicEk:-N6RpNLQ3dQYtQ2Eb6Cp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/integration/test_finder_charts.py#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: non_authorised_user
</blockquote></details>

Done.
___
*[`tests/integration/test_finder_charts.py` line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OhTzW7q08WNUlGAex:-N6RpS6C4C-YGgoDs6kB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/integration/test_finder_charts.py#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: authorised_user
</blockquote></details>

Done.
___
*[`tests/integration/test_finder_charts.py` line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OhVxZ5U-qqgOqCjsf:-N6Rs6tA8kSdwIQQ_GmL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/integration/test_finder_charts.py#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This test is problematic -- the finder chart file generally won't exist and the test will fail.

The slightly tacky solution might be to catch FileNotFound exceptions and to check that their error message contains the correct path.
</blockquote></details>

Done.
___
*[`tests/repository/test_finder_chart_repository.py` line 7 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Od1-i0L03CjI_PA_1:-N6RpvPVAjoQbmKapbfM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/repository/test_finder_chart_repository.py#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

returns_content > returns_correct_content
</blockquote></details>

Done.
___
*[`tests/repository/test_finder_chart_repository.py` line 12 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Od6Oo4E3xuL36pa4s:-N6Rpvj17Fy82VoKFzs8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/repository/test_finder_chart_repository.py#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This line can be removed.
</blockquote></details>

Done.
___
*[`tests/rep [...]

2022-07-08 11:47 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/84)* status: all files reviewed, 9 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/settings.py` line 98 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6O_wX6B4TU1oL1xQg9:-N6ScSah9XOACXhxPdT4:b-cdxt8i) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/settings.py#L98)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

That's true, 
</blockquote></details>

It seems you haven't removed the `finding_charts_dir` variable?
___
*[`saltapi/repository/finder_chart_repository.py` line 57 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OezZw6hvj3BwRlbPp:-N6Sby3H7VHpMKownSDC:bkmzzy6) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/repository/finder_chart_repository.py#L57)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I used `DISITINCT` and it does work.
</blockquote></details>

Yes, sorry, it is `DISTINCT, of course.
___
*[`saltapi/repository/finder_chart_repository.py` line 14 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SYITh2G1TowuiMaY1:-N6SYITh2G1TowuiMaY2:b6miry) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/15fcd59cfe7592af561675043b0a16839b96e28c/saltapi/repository/finder_chart_repository.py#L14)):*
> ```Python
>         self.connection = connection
> 
>     def get(self, finder_chart_id: int) -> List[str]:
> ```

Shouldn't this better be `Tuple[str, Path]` ?

And maybe the path should come first, as it is sort of more "finder chart-like"?

Or maybe you should return a dictionary rather?

Okay okay, you probably don't want to refactor all the code... But you should at least use `Tuple[str, Path]` as the return type then.
___
*[`saltapi/repository/finder_chart_repository.py` line 17 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SYRnJEnWDpIZZZy91:-N6SYRnJEnWDpIZZZy92:b-r0avtd) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/15fcd59cfe7592af561675043b0a16839b96e28c/saltapi/repository/finder_chart_repository.py#L17)):*
> ```Python
>         stmt = text(
>             """
> SELECT DISTINCT PC.Proposal_code AS proposa_code,
> ```

proposa_code > proposal_code
___
*[`saltapi/repository/finder_chart_repository.py` line 29 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SYjwaAuEm_De31yna:-N6SYjwaAuEm_De31ynb:bbmivl0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/15fcd59cfe7592af561675043b0a16839b96e28c/saltapi/repository/finder_chart_repository.py#L29)):*
> ```Python
>             result = self.connection.execute(stmt, {"finder_chart_id": finder_chart_id})
> 
>             finding_chart_path: List[str] = result.one()
> ```

The name finding_chart_path is a bit misleading, given that it's more than a path... Maybe better finder_chart_details?
___
*[`saltapi/service/finder_chart_service.py` line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6ObEZP4nTDNcA39fPU:-N6SZGpuA9PhoAKVfRC-:b-v4cl3x) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/service/finder_chart_service.py#L10)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have changed Any to a proper type.
</blockquote></details>

See the type comment for the repository method.
___
*[`saltapi/service/finder_chart_service.py` line 21 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SZx8m7ae5OfOPTR-V:-N6SZx8m7ae5OfOPTR-W:b-jgjct7) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/15fcd59cfe7592af561675043b0a16839b96e28c/saltapi/service/finder_chart_service.py#L21)):*
> ```Python
>             finder_chart_id
>         )
>         finder_chart_relative_path = Path(proposals_directory).joinpath(
> ```

Easier way to get the full path:

`proposals_directory / proposal_code / finder_chart_path`
___
*[`tests/integration/test_finder_charts.py` line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Sa_7J0v5il8YXcONO:-N6Sa_7KEiLt8Xr46vtm:bgqqc4v) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/integration/test_finder_charts.py#L1)):*
> ```Python
> from fastapi.testclient import TestClient
> ```

For consistency, the test should be in its own directory.
___
*[`tests/integration/test_finder_charts.py` line 43 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SaosI2NLRaq4HZFw7:-N6SaosI2NLRaq4HZFw8:b-ozlzr0) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/15fcd59cfe7592af561675043b0a16839b96e28c/tests/integration/test_finder_charts.py#L43)):*
> ```Python
>         assert response.status_code == status.HTTP_200_OK
>         assert response.content.__sizeof__() > 0
>     except NotFoundError as excinfo:
> ```

You don't get a `NotFoundError`; a `RuntimeError` is raised.


<!-- Sent from Reviewable.io -->

2022-07-08 12:00 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/84)* status: 3 of 10 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/settings.py` line 98 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6O_wX6B4TU1oL1xQg9:-N6Sd5SV6XfohfCqHIKp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/settings.py#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems you haven't removed the `finding_charts_dir` variable?
</blockquote></details>

Done.
___
*[`saltapi/repository/finder_chart_repository.py` line 57 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6OezZw6hvj3BwRlbPp:-N6SdkaC2CD3sUAOzcLc:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/repository/finder_chart_repository.py#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes, sorry, it is `DISTINCT, of course.
</blockquote></details>

Done.
___
*[`saltapi/repository/finder_chart_repository.py` line 14 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SYITh2G1TowuiMaY1:-N6SdPI40KpruASqcGw4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/15fcd59cfe7592af561675043b0a16839b96e28c/saltapi/repository/finder_chart_repository.py#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this better be `Tuple[str, Path]` ?

And maybe the path should come first, as it is sort of more "finder chart-like"?

Or maybe you should return a dictionary rather?

Okay okay, you probably don't want to refactor all the code... But you should at least use `Tuple[str, Path]` as the return type then.
</blockquote></details>

Done.
___
*[`saltapi/repository/finder_chart_repository.py` line 17 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SYRnJEnWDpIZZZy91:-N6Sdbr0A8qqibnd0COQ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/15fcd59cfe7592af561675043b0a16839b96e28c/saltapi/repository/finder_chart_repository.py#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

proposa_code > proposal_code
</blockquote></details>

Done.
___
*[`saltapi/repository/finder_chart_repository.py` line 29 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SYjwaAuEm_De31yna:-N6Sdiw2ArNxesq4Xo7I:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/15fcd59cfe7592af561675043b0a16839b96e28c/saltapi/repository/finder_chart_repository.py#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name finding_chart_path is a bit misleading, given that it's more than a path... Maybe better finder_chart_details?
</blockquote></details>

Done.
___
*[`saltapi/service/finder_chart_service.py` line 10 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6ObEZP4nTDNcA39fPU:-N6Se0LTD5TZZMkSxH1Y:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/saltapi/service/finder_chart_service.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See the type comment for the repository method.
</blockquote></details>

Done.
___
*[`saltapi/service/finder_chart_service.py` line 21 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SZx8m7ae5OfOPTR-V:-N6Se9fk4zpY4kMU-rlG:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/15fcd59cfe7592af561675043b0a16839b96e28c/saltapi/service/finder_chart_service.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Easier way to get the full path:

`proposals_directory / proposal_code / finder_chart_path`
</blockquote></details>

Done.
___
*[`tests/integration/test_finder_charts.py` line 1 at r1](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6Sa_7J0v5il8YXcONO:-N6SefBI4Y_YmCR9E9Dc:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/46391ce058a277d5c01e5c6674b9baf5527e704a/tests/integration/test_finder_charts.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency, the test should be in its own directory.
</blockquote></details>

Done.
___
*[`tests/integration/test_finder_charts.py` line 43 at r2](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SaosI2NLRaq4HZFw7:-N6Sep6k3kIcpNv2vRVV:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/15fcd59cfe7592af561675043b0a16839b96e28c/tests/integration/test_finder_charts.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You don't get a `NotFoundError`; a `RuntimeError` is raised.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-08 12:34 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/84)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/finder_chart_repository.py` line 30 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SlVO79KEgoGjbe6oj:-N6SlVO79KEgoGjbe6ok:b-vg119j) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/aef4ebe2034d982480c71850bdbd088689f86918/saltapi/repository/finder_chart_repository.py#L30)):*
> ```Python
>             result = self.connection.execute(stmt, {"finder_chart_id": finder_chart_id})
> 
>             finding_chart_details: Tuple[str, Path] = result.one()
> ```

results.one()[1] is a string; you still have to create the Path object...
___
*[`saltapi/service/finder_chart_service.py` line 21 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SlthjDpOAqs07sKkv:-N6SlthjDpOAqs07sKkw:bvhseha) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/aef4ebe2034d982480c71850bdbd088689f86918/saltapi/service/finder_chart_service.py#L21)):*
> ```Python
>             finder_chart_id
>         )
>         finder_chart_relative_path = (
> ```

finder_chart_relative_path > full_finder_chart_path


<!-- Sent from Reviewable.io -->

2022-07-08 12:41 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/84)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/finder_chart_repository.py` line 30 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SlVO79KEgoGjbe6oj:-N6SoFpe9ENiwK_RzEHq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/aef4ebe2034d982480c71850bdbd088689f86918/saltapi/repository/finder_chart_repository.py#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

results.one()[1] is a string; you still have to create the Path object...
</blockquote></details>

Done.
___
*[`saltapi/service/finder_chart_service.py` line 21 at r3](https://reviewable.io/reviews/saltastroops/salt-api-2021/84#-N6SlthjDpOAqs07sKkv:-N6SoGK33CchWUdDh45D:b-896fix) ([raw file](https://github.com/saltastroops/salt-api-2021/blob/aef4ebe2034d982480c71850bdbd088689f86918/saltapi/service/finder_chart_service.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

finder_chart_relative_path > full_finder_chart_path
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-08 12:42 UTC, hettlage approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api-2021/84)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2022-07-08 12:43 UTC, merged