progress-report-pdf
saltastroops/salt-api pull request #86
Opened 2022-07-20 05:08 UTC by mofokeng-chaka

Handling progress report pdf files

2022-08-22 07:39 UTC, hettlage requested changes
> Reviewed 1 of 10 files at r1, 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/86)* status: 9 of 10 files reviewed, 22 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 1582 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3MvSu5VlTNmhrUIj2:-NA3MvSu5VlTNmhrUIj3:b74iyh9) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/repository/proposal_repository.py#L1582)):*
> ```Python
>         return prp
> 
>     def list_of_progress_reports_pdfs(self, proposal_code: str) -> Dict[str, Any]:
> ```

Maybe better: `list_of_progress_report_pdfs`?
___
*[`saltapi/repository/proposal_repository.py` line 1586 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3KaOeEZsKb8kWn1T_:-NA3KaOeEZsKb8kWn1Ta:bj68c1c) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/repository/proposal_repository.py#L1586)):*
> ```Python
>         stmt = text(
>             """
> SELECT
> ```

I don't see why you would need CONCAT /COALESCE in this query. Can't you just loop over rows?
___
*[`saltapi/repository/proposal_repository.py` line 1614 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3MYr8BIMPer1Z7xzp:-NA3MYr8BIMPer1Z7xzq:bngxpu1) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/repository/proposal_repository.py#L1614)):*
> ```Python
>         return progress_reports_pdfs
> 
>     def get_progress_report_pdf(self, proposal_code: str, semester: str) -> str:
> ```

Isn't this covered by the `get_progress_report` method already?
___
*[`saltapi/repository/proposal_repository.py` line 1725 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3Mdnp1bjswBl4kTva:-NA3MdnqBFvG2OhWSQEO:bngxpu1) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/repository/proposal_repository.py#L1725)):*
> ```Python
>             }
> 
>     def get_supplementary_progress_report_pdf(
> ```

Isn't this covered by the `get_progress_report` method already?
___
*[`saltapi/service/proposal_service.py` line 121 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3N3oiByjSYzI9AMPp:-NA3N3oiByjSYzI9AMPq:b74iyh9) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/service/proposal_service.py#L121)):*
> ```Python
>         )
> 
>     def list_of_progress_reports_pdfs(
> ```

Maybe better: `list_of_progress_report_pdfs`?
___
*[`saltapi/service/proposal_service.py` line 134 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3OBm900NoFvuuI_lQ:-NA3OBmA143XILAcE6Il:b-oik05d) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/service/proposal_service.py#L134)):*
> ```Python
> 
>         progress_reports_list = {
>             k: v for k, v in progress_reports_list.items() if v != "NULL"
> ```

`None` should be used instead of a string if there is no pdf.
___
*[`saltapi/service/proposal_service.py` line 138 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3OON74L3G3qpaD5aR:-NA3OON74L3G3qpaD5aS:b-9les0h) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/service/proposal_service.py#L138)):*
> ```Python
> 
>         progress_reports_list = {
>             key: urllib.parse.quote(
> ```

The path should not be included in the URL.
___
*[`saltapi/service/proposal_service.py` line 161 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3PBgn3Jj5qX_uv7rt:-NA3PBgn3Jj5qX_uv7ru:b9y5q7) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/service/proposal_service.py#L161)):*
> ```Python
>         )
> 
>         progress_report_pdf_path = (
> ```

The path should not be included in the URL.

Also, is there a really need for a method just returning the supplementary file URL?
___
*[`saltapi/service/proposal_service.py` line 185 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3Odn81JpcMIbrVS_N:-NA3Odn81JpcMIbrVS_O:b9y5q7) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/service/proposal_service.py#L185)):*
> ```Python
>         )
> 
>         progress_report_pdf_path = (
> ```

The path should not be included in the URL.

Also, is there a really need for a method just returning the supplementary file URL?
___
*[`saltapi/web/api/proposal_progress.py` line 178 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3Q2wV3SX-uNDxTXcE:-NA3Q2wV3SX-uNDxTXcF:bw0xkut) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/api/proposal_progress.py#L178)):*
> ```Python
>         )
> 
>         pdf_path = urllib.parse.unquote(urllib.parse.unquote(progress_report_pdf_path))
> ```

As said elsewhere, you shouldn't include the file path ini the URL -- rather get it from there database.
___
*[`saltapi/web/api/proposal_progress.py` line 181 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3Qarp108SEbHmwoM1:-NA3Qarp108SEbHmwoM2:b-vmel8v) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/api/proposal_progress.py#L181)):*
> ```Python
> 
>         return FileResponse(
>             pdf_path, media_type="application/pdf", filename=pathlib.Path(pdf_path).name
> ```

The name should be something human-friendly like `ProgressReport.pdf` or `ProgressReport_2022-1.pdf`, I'd suggest.
___
*[`saltapi/web/api/proposal_progress.py` line 186 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3QLcY-n039dAfa8vU:-NA3QLcY-n039dAfa8vV:b-nsxfh9) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/api/proposal_progress.py#L186)):*
> ```Python
> 
> @router.get(
>     "/{proposal_code}/{semester}/supplementary-report.pdf",
> ```

Maybe better `supplementary-file.pdf. (This applies in other places as well.)
___
*[`saltapi/web/api/proposal_progress.py` line 207 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3R3p_AbLg1Y0d3iJb:-NA3R3pa0UajzFLCZQd-:bw0xkut) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/api/proposal_progress.py#L207)):*
> ```Python
>         proposal_service = services.proposal_service(unit_of_work.connection)
> 
>         progress_report_pdf_path = (
> ```

As said elsewhere, you shouldn't include the file path ini the URL -- rather get it from there database.
___
*[`saltapi/web/api/proposal_progress.py` line 216 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3Qwy-33NZjrKQcW-F:-NA3Qwy-33NZjrKQcW-G:b-vmel8v) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/api/proposal_progress.py#L216)):*
> ```Python
> 
>         return FileResponse(
>             pdf_path, media_type="application/pdf", filename=pathlib.Path(pdf_path).name
> ```

The name should be something human-friendly like `ProgressReport.pdf` or `ProgressReport_2022-1.pdf`, I'd suggest.
___
*[`saltapi/web/schema/proposal.py` line 556 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3RMUO52eBWtefwX6-:-NA3RMUO52eBWtefwX60:b-g3pnoa) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/schema/proposal.py#L556)):*
> ```Python
>     )
> 
>     proposal_progress_pdf: Optional[pathlib.Path] = Field(
> ```

This should be a URL, not a path.
___
*[`saltapi/web/schema/proposal.py` line 562 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3RTyH0d6PuUnFkzXu:-NA3RTyH0d6PuUnFkzXv:b-g3pnoa) ([raw file](https://githu [...]

2022-08-23 09:36 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/86)* status: 4 of 10 files reviewed, 22 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1582 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3MvSu5VlTNmhrUIj2:-NA3wMkQBJHYMgkj6Pa_:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/repository/proposal_repository.py#L1582)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: `list_of_progress_report_pdfs`?
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1586 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3KaOeEZsKb8kWn1T_:-NA3xv1fABonxgk7U5B6:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/repository/proposal_repository.py#L1586)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see why you would need CONCAT /COALESCE in this query. Can't you just loop over rows?
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1614 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3MYr8BIMPer1Z7xzp:-NA4LjnD9_4mqy-H3Eex:brondlt) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/repository/proposal_repository.py#L1614)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't this covered by the `get_progress_report` method already?
</blockquote></details>

That's true. It is now removed.
___
*[`saltapi/repository/proposal_repository.py` line 1725 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3Mdnp1bjswBl4kTva:-NA4LuwAACyYiMplg8J8:brondlt) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/repository/proposal_repository.py#L1725)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't this covered by the `get_progress_report` method already?
</blockquote></details>

That's true. It is now removed.
___
*[`saltapi/service/proposal_service.py` line 121 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3N3oiByjSYzI9AMPp:-NA4M-T7286Bbt7N0JYN:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/service/proposal_service.py#L121)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: `list_of_progress_report_pdfs`?
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 134 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3OBm900NoFvuuI_lQ:-NA4da5S8_wDK8QsZfjN:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/service/proposal_service.py#L134)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`None` should be used instead of a string if there is no pdf.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 138 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3OON74L3G3qpaD5aR:-NA7jUQp-kADTJuiYdJg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/service/proposal_service.py#L138)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The path should not be included in the URL.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 161 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3PBgn3Jj5qX_uv7rt:-NA8dbGp5mybmGmLyDok:b-saqpit) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/service/proposal_service.py#L161)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The path should not be included in the URL.

Also, is there a really need for a method just returning the supplementary file URL?
</blockquote></details>

The file path is removed from the URL.

No, there is no need for the method you mentioned. I have removed it accordingly.
___
*[`saltapi/service/proposal_service.py` line 185 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3Odn81JpcMIbrVS_N:-NA8eO5N6YPLMENiq2Nw:b-saqpit) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/service/proposal_service.py#L185)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The path should not be included in the URL.

Also, is there a really need for a method just returning the supplementary file URL?
</blockquote></details>

The file path is removed from the URL.

No, there is no need for the method you mentioned. I have removed it accordingly.
___
*[`saltapi/web/api/proposal_progress.py` line 178 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3Q2wV3SX-uNDxTXcE:-NA4N2kX-qyPvoj_kir_:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/api/proposal_progress.py#L178)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As said elsewhere, you shouldn't include the file path ini the URL -- rather get it from there database.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 181 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3Qarp108SEbHmwoM1:-NA4N3PL2lgkuzUMtUM8:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/api/proposal_progress.py#L181)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name should be something human-friendly like `ProgressReport.pdf` or `ProgressReport_2022-1.pdf`, I'd suggest.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 186 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3QLcY-n039dAfa8vU:-NA4N4GkDHaqGAwaL4en:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/api/proposal_progress.py#L186)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better `supplementary-file.pdf. (This applies in other places as well.)
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 207 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3R3p_AbLg1Y0d3iJb:-NA4N56t-KooEHRLFJMl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/api/proposal_progress.py#L207)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As said elsewhere, you shouldn't include the file path ini the URL -- rather get it from there database.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 216 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3Qwy-33NZjrKQcW-F:-NA4N5iN0TaDzp_JsAsz:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/api/proposal_progress.py#L216)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name should be something human-friendly like `ProgressReport.pdf` or `ProgressReport_2022-1.pdf`, I'd suggest.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 556 at r2](https://reviewable.io/reviews/saltastroops/salt-api/86#-NA3RMUO52eBWtefwX6-:-NA4N79Q9c49-oddFru7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/78157ab1919d31c0d225807690a4e193c8ab99b8/saltapi/web/schema/proposal.py#L556)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be a URL, not a path.
</blockquote></details>

Done.
___
* [...]

2022-09-06 08:49 UTC, hettlage requested changes
> Reviewed 1 of 9 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/86)* status: all files reviewed, 23 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 1582 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGx0AB0dn-_19n2TYc:-NBGx0AC0v5oNUjs_VDh:b-gm00ij) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/repository/proposal_repository.py#L1582)):*
> ```Python
>         return prp
> 
>     def list_of_progress_report_pdfs(self, proposal_code: str) -> List[str]:
> ```

The name is misleading; the function returns semesters, not progress report pdfs.
___
*[`saltapi/repository/proposal_repository.py` line 1603 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGx90g4l8Ij1Osnptd:-NBGx90g4l8Ij1Osnpte:bh5d3a6) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/repository/proposal_repository.py#L1603)):*
> ```Python
> 
>         semesters = []
>         for row in result:
> ```

Easier with a list comprehension:

```
return [row["semester"] for row in result]
```

___
*[`saltapi/service/proposal_service.py` line 120 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGyFui7hmiiDzpl7xR:-NBGyFui7hmiiDzpl7xS:b-gm00ij) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/service/proposal_service.py#L120)):*
> ```Python
>         )
> 
>     def list_of_progress_report_pdfs(self, proposal_code: ProposalCode) -> List[str]:
> ```

The name is misleading; the function returns semesters, not progress report pdfs.
___
*[`saltapi/service/proposal_service.py` line 128 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGyLFh3n148fCiz36F:-NBGyLFh3n148fCiz36G:b-2alxrm) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/service/proposal_service.py#L128)):*
> ```Python
> 
>         if current_semester in progress_report_semester_list:
>             progress_report_semester_list.remove(current_semester)
> ```

Why do you remove the current semester?
___
*[`saltapi/service/proposal_service.py` line 162 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGyeZjAgA3abDwH_0r:-NBGyeZjAgA3abDwH_0s:b-h4ic9g) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/service/proposal_service.py#L162)):*
> ```Python
>         )
> 
>         progress_report["proposal_progress_pdf"] = progress_report_pdf_path
> ```

Shouldn't this be the URL rather than the file path?
___
*[`saltapi/service/proposal_service.py` line 164 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGywrpAsuJmIoxjhYn:-NBGywrpAsuJmIoxjhYo:b-h4ic9g) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/service/proposal_service.py#L164)):*
> ```Python
>         progress_report["proposal_progress_pdf"] = progress_report_pdf_path
> 
>         progress_report["additional_pdf"] = additional_progress_report_pdf_path
> ```

Shouldn't this be the URL rather than the file path?
___
*[`saltapi/web/api/proposal_progress.py` line 34 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBByS1z2f_6wptcij4d:-NBByS1z2f_6wptcij4e:b-9h3hxi) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L34)):*
> ```Python
>     "/{proposal_code}/",
>     summary="Get a list proposal progress reports pdfs",
> )
> ```

Maybe add a response model?
___
*[`saltapi/web/api/proposal_progress.py` line 45 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBlVT05T362PL51nkc:-NBBlVT05T362PL51nkd:b-vwobw1) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L45)):*
> ```Python
> ) -> Dict[str, Any]:
>     """
>     Returns a list of progress reports pdf for a proposal.
> ```

Maybe better: Return the list of URLs of the progress report pdfs for a proposal.
___
*[`saltapi/web/api/proposal_progress.py` line 61 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBlB_mAUhp5rRHku-e:-NBBlB_p9He10jjsA6n1:bgdivci) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L61)):*
> ```Python
> 
>             progress_report_path_list[semester] = {
>                 "proposal_progress_pdf": "http://{}:{}{}".format(
> ```

http should not be hardcoded -- it might be https after all.

Also, this code might make more sense in a service (and it should not be duplicated for the single progress report -- rather use a helper function).
___
*[`saltapi/web/api/proposal_progress.py` line 70 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBlIKA0cz3JQs0-onu:-NBBlIKA0cz3JQs0-onv:b8mkt5w) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L70)):*
> ```Python
>                     ),
>                 ),
>                 "additional_pdf": "http://{}:{}{}".format(
> ```

I don't think the additional pdf should be included.
___
*[`saltapi/web/api/proposal_progress.py` line 70 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBlPLt7JLX9MEIB4lq:-NBBlPLt7JLX9MEIB4lr:b-b6kbqg) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L70)):*
> ```Python
>                     ),
>                 ),
>                 "additional_pdf": "http://{}:{}{}".format(
> ```

http should not be hardcoded.
___
*[`saltapi/web/api/proposal_progress.py` line 86 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBz4Wa6jDld_yNyUVL:-NBBz4Wa6jDld_yNyUVM:b6dsiki) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L86)):*
> ```Python
> @router.get(
>     "/{proposal_code}/{semester}",
>     summary="Get a proposal progress report",
> ```

Maybe add a response model?

(Otherwise you might end up returning the pdf file paths, which you probably don't want to.)
___
*[`saltapi/web/api/proposal_progress.py` line 97 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBz7C_3JbymoRb9g7S:-NBBz7C_3JbymoRb9g7T:bx3ckmo) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L97)):*
> ```Python
>     semester: Semester = Path(..., title="Semester", description="Semester"),
>     user: User = Depends(get_current_user),
> ) -> Any:
> ```

Could at least be a Dict rather than Any?
___
*[`saltapi/web/api/proposal_progress.py` line 116 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBzE822jV1o_6PXYoM:-NBBzE822jV1o_6PXYoN:bbc1kva) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L116)):*
> ```Python
>         progress_report = proposal_service.get_progress_report(proposal_code, semester)
> 
>         progress_report["proposal_progress_pdf"] = (
> ```

This should be set by the service.
___
*[`saltapi/web/api/proposal_progress.py` line 130 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBzHjM7wHTpXwEUirA:-NBBzHjM7wHTpXwEUirB:bbc1kva) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L130)):*
> ```Python
>         )
> 
>         progress_report["additional_pdf"] = (
> ```

This should be set by the service.
___
*[`saltapi/web/api/proposal_progress.py` line 204 at r4](https://reviewable.io/reviews/saltastroops/salt-api/8 [...]

2022-09-08 09:52 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/86)* status: 6 of 10 files reviewed, 23 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1582 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGx0AB0dn-_19n2TYc:-NBQhDOo0hZlsmEHsrCc:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/repository/proposal_repository.py#L1582)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name is misleading; the function returns semesters, not progress report pdfs.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1603 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGx90g4l8Ij1Osnptd:-NBQhJqoDIiM9CBZu0im:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/repository/proposal_repository.py#L1603)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Easier with a list comprehension:

```
return [row["semester"] for row in result]
```

</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 120 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGyFui7hmiiDzpl7xR:-NBQhdLEDcrqnqqaF9ks:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/service/proposal_service.py#L120)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name is misleading; the function returns semesters, not progress report pdfs.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 128 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGyLFh3n148fCiz36F:-NBRNdDm8-ge9QJ4Tgum:b-fxycyu) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/service/proposal_service.py#L128)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you remove the current semester?
</blockquote></details>

I thought it would make sense to remove it here since it is also returned by the `get_progress_report` method. 

Anyway, I have added it back to the list.
___
*[`saltapi/service/proposal_service.py` line 162 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGyeZjAgA3abDwH_0r:-NBQiq7J2Wi2uvjHrVez:btb55vg) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/service/proposal_service.py#L162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be the URL rather than the file path?
</blockquote></details>

That's true, and I have updated the service now to return URLs rather than a file paths.
___
*[`saltapi/service/proposal_service.py` line 164 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBGywrpAsuJmIoxjhYn:-NBQlRN9-EokNLzhDb0m:bijcr4e) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/service/proposal_service.py#L164)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be the URL rather than the file path?
</blockquote></details>

That's true, and I have updated the service now to return URLs rather than file path.
___
*[`saltapi/web/api/proposal_progress.py` line 34 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBByS1z2f_6wptcij4d:-NBQzNFp4aU7XooEAXYe:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add a response model?
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 45 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBlVT05T362PL51nkc:-NBQrAew4Pk08AP8thgP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: Return the list of URLs of the progress report pdfs for a proposal.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 61 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBlB_mAUhp5rRHku-e:-NBQuQWNB0Dfwo37eqhA:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

http should not be hardcoded -- it might be https after all.

Also, this code might make more sense in a service (and it should not be duplicated for the single progress report -- rather use a helper function).
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 70 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBlIKA0cz3JQs0-onu:-NBQx8qd0Y3DY5nTumXX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the additional pdf should be included.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 70 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBlPLt7JLX9MEIB4lq:-NBQx9Pa572xPEAoyp1V:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

http should not be hardcoded.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 86 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBz4Wa6jDld_yNyUVL:-NBQxWVT26yymNqoWXQH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add a response model?

(Otherwise you might end up returning the pdf file paths, which you probably don't want to.)
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 97 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBz7C_3JbymoRb9g7S:-NBQxc8H1NP-Wgv4AfTP:b-5v2hgo) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Could at least be a Dict rather than Any?
</blockquote></details>

Even better, `ProposalProgress`. 
___
*[`saltapi/web/api/proposal_progress.py` line 116 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBzE822jV1o_6PXYoM:-NBQxp5v4aeAHXOCjWjP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L116)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be set by the service.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 130 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBBzHjM7wHTpXwEUirA:-NBQxpuvDYXYIRynfykL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/saltapi/web/api/proposal_progress.py#L130)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be set by the service.
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 204 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBC-hRE3wMOhrpx7wz-:-NBQy4R15oUV5dx5MBVV:b1notlw) ([r [...]

2022-10-05 14:19 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/86)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 1674 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc2AqiAW3xX6tFIabW:-NDc2AqiAW3xX6tFIabX:b-ov85cg) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/repository/proposal_repository.py#L1674)):*
> ```Python
>                     ),
>                 }
>         except (ValidationError, AttributeError):
> ```

Neither a ValidationError nor an AttributeError are a certain sign of a missing progress report, really. Also, I'm not convinced Pydantic should have a role to play in this file.
___
*[`saltapi/service/proposal_service.py` line 16 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc3JXYEi0W6NlN-J1I:-NDc3JXYEi0W6NlN-J1J:b-m61wl0) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L16)):*
> ```Python
> from saltapi.web.schema.common import ProposalCode, Semester
> 
> proposals_dir = pathlib.Path(get_settings().proposals_dir)
> ```

Shouldn't the proposal_dir setting be a `Path`?
___
*[`saltapi/service/proposal_service.py` line 19 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc4E5T3d7mZXgV60Ux:-NDc4E5T3d7mZXgV60Uy:bfnxsyy) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L19)):*
> ```Python
> 
> 
> def generate_route_url(request: Request, router_path: URLPath) -> AnyUrl:
> ```

I'm not convinced Pedantic should be used in this file,
___
*[`saltapi/service/proposal_service.py` line 134 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc4j5_5HJrovOUorEC:-NDc4j5a6EcwyNsbH7Cq:b-481z3p) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L134)):*
> ```Python
>         semesters = self.repository.list_of_semesters(proposal_code)
> 
>         progress_report_path_list = dict()
> ```

I know it's nit-picking,. but this is a dict, not a list. (Maybe just call the variable `progress_report_paths`?)

And why do you speak of `paths` rather than `urls`?
___
*[`saltapi/service/proposal_service.py` line 158 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc8EzJDxVM47ouqLSn:-NDc8EzJDxVM47ouqLSo:b58khlw) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L158)):*
> ```Python
>         progress_report = self.repository.get_progress_report(proposal_code, semester)
> 
>         progress_report_pdf_path = (
> ```

The progress report path is not needed.
___
*[`saltapi/service/proposal_service.py` line 170 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc8KEz-WFNGZN1TKnf:-NDc8KF-EarwNBTgsxVm:bcynp5f) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L170)):*
> ```Python
>             else None
>         )
>         additional_progress_report_pdf_path = (
> ```

The additional progress report path is not needed.
___
*[`saltapi/service/proposal_service.py` line 190 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc8VYK9XtF6mn4q1VH:-NDc8VYK9XtF6mn4q1VI:b-s27l2r) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L190)):*
> ```Python
>         progress_report["proposal_progress_pdf"] = (
>             generate_route_url(request, progress_pdf_url)
>             if progress_report_pdf_path
> ```

Rather check that `progress_report["proposal_progress_pdf"]` is truthy,
___
*[`saltapi/service/proposal_service.py` line 201 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc8mV6BiOynelQzcn1:-NDc8mV6BiOynelQzcn2:byxyyww) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L201)):*
> ```Python
>         progress_report["additional_pdf"] = (
>             generate_route_url(request, additional_progress_pdf_url)
>             if additional_progress_report_pdf_path
> ```

Rather check that `progress_report["additional_pdf"]` is truthy,
___
*[`saltapi/web/api/proposal_progress.py` line 53 at r3](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc9kTn7-YXl6hmEFbe:-NDc9kTn7-YXl6hmEFbf:b-ildeou) ([raw file](https://github.com/saltastroops/salt-api/blob/d3b30124ac714b37c13011b110828fa257fd7de8/saltapi/web/api/proposal_progress.py#L53)):*
> ```Python
>         proposal_service = services.proposal_service(unit_of_work.connection)
> 
>         progress_reports_semester_list = proposal_service.list_of_progress_report_pdfs(
> ```

This is a dict, not a list...
___
*[`saltapi/web/api/proposal_progress.py` line 163 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDcPI3t3EFrfW1jtd2q:-NDcPI3t3EFrfW1jtd2r:bbg1hsb) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/web/api/proposal_progress.py#L163)):*
> ```Python
>         )
> 
>         pdf_path = urllib.parse.urlparse(progress_report["proposal_progress_pdf"]).path
> ```

This looks odd. Surely the URL does not include the file path?
___
*[`saltapi/web/api/proposal_progress.py` line 197 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDcOvgm4H16My6aXzje:-NDcOvgm4H16My6aXzjf:bbg1hsb) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/web/api/proposal_progress.py#L197)):*
> ```Python
>         )
> 
>         pdf_path = urllib.parse.urlparse(progress_report["additional_pdf"]).path
> ```

This looks odd. Surely the URL does not include the file path?
___
*[`tests/integration/progress_report/test_get_progress_report.py` line 80 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBC2_x95wC4OjGdDFLy:-NDcQ3Ul9UJzD7vj-Fk8:b-mr0klm) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/tests/integration/progress_report/test_get_progress_report.py#L80)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm, it seems I was wrong, though?


<!-- Sent from Reviewable.io -->

2022-10-06 13:31 UTC, mofokeng-chaka reviewed
Added regression testing

> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/86#-:-NDhUWd_09Ywqnerc65C:btfnrli)* status: 5 of 22 files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1674 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc2AqiAW3xX6tFIabW:-NDgi5CsCZFn0IWrpiOu:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/repository/proposal_repository.py#L1674)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Neither a ValidationError nor an AttributeError are a certain sign of a missing progress report, really. Also, I'm not convinced Pydantic should have a role to play in this file.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 16 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc3JXYEi0W6NlN-J1I:-NDgiFPeB7HKfpuUlYIz:b-nbyg6c) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't the proposal_dir setting be a `Path`?
</blockquote></details>

It is, and I have fixed the code.
___
*[`saltapi/service/proposal_service.py` line 19 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc4E5T3d7mZXgV60Ux:-NDgssBC-C-pzZgBW1Rp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced Pedantic should be used in this file,
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 134 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc4j5_5HJrovOUorEC:-NDgtmCV58VIcCGcvT5H:b-5ay4f) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L134)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I know it's nit-picking,. but this is a dict, not a list. (Maybe just call the variable `progress_report_paths`?)

And why do you speak of `paths` rather than `urls`?
</blockquote></details>

Renamed `paths` to `urls` progress_report_paths
___
*[`saltapi/service/proposal_service.py` line 158 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc8EzJDxVM47ouqLSn:-NDgtuLk3Gb1XfVePBd1:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L158)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The progress report path is not needed.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 170 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc8KEz-WFNGZN1TKnf:-NDgu280DOz7FrqokI_v:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The additional progress report path is not needed.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 190 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc8VYK9XtF6mn4q1VH:-NDgu3EG8dRCzNyjxGWO:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L190)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Rather check that `progress_report["proposal_progress_pdf"]` is truthy,
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 201 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc8mV6BiOynelQzcn1:-NDgu3rx1XhDkNBoGLk_:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/service/proposal_service.py#L201)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Rather check that `progress_report["additional_pdf"]` is truthy,
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 53 at r3](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDc9kTn7-YXl6hmEFbe:-NDgu9FHBirRZ0x9f512:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/d3b30124ac714b37c13011b110828fa257fd7de8/saltapi/web/api/proposal_progress.py#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is a dict, not a list...
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 163 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDcPI3t3EFrfW1jtd2q:-NDhP7wi3ZH8MTjnlgOF:b-9czbwh) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/web/api/proposal_progress.py#L163)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This looks odd. Surely the URL does not include the file path?
</blockquote></details>

That is true, the URL does not include the file path. I made a mistake.
___
*[`saltapi/web/api/proposal_progress.py` line 197 at r5](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDcOvgm4H16My6aXzje:-NDhPLoN7ozGNay2KrWM:b-9czbwh) ([raw file](https://github.com/saltastroops/salt-api/blob/f1460e10b91ebb48266391aa6425997ed205b135/saltapi/web/api/proposal_progress.py#L197)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This looks odd. Surely the URL does not include the file path?
</blockquote></details>

That is true, the URL does not include the file path. I made a mistake.
___
*[`tests/integration/progress_report/test_get_progress_report.py` line 80 at r4](https://reviewable.io/reviews/saltastroops/salt-api/86#-NBC2_x95wC4OjGdDFLy:-NDgUbjT4RWlTVwCMdec:b-y0gmuz) ([raw file](https://github.com/saltastroops/salt-api/blob/b07ce24a55bb31b26ee161ec428a214c471beb7f/tests/integration/progress_report/test_get_progress_report.py#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Hmm, it seems I was wrong, though?
</blockquote></details>

I agree I am checking for correct pdfs here.


<!-- Sent from Reviewable.io -->

2022-10-07 12:21 UTC, hettlage requested changes
> Reviewed 17 of 17 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/86)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 1456 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDlZaZcAsRLCkavQQGE:-NDlZaZcAsRLCkavQQGF:bz9f6mx) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/repository/proposal_repository.py#L1456)):*
> ```Python
>     def _get_latest_observing_conditions(
>         self, proposal_code: str, semester: str
>     ) -> Union[Dict[str, Any], None]:
> ```

How about using `Optional` rather than `Union[..., None]`? :-)
___
*[`saltapi/repository/proposal_repository.py` line 1585 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDlaRU9Ci5rTLSWTeIT:-NDlaRU9Ci5rTLSWTeIU:b-5gjzjq) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/repository/proposal_repository.py#L1585)):*
> ```Python
>         # request for the semester under consideration, we store that request.
> 
>         # Exclude partners (actually proposal types) which mught not have Phase 1 proposals
> ```

It might be better to exclude these partners in the SQL query already, which you can do by only including partners for which the `Virtual` column is not 0.
___
*[`saltapi/service/proposal_service.py` line 175 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmHlqB0uQWsXmtFZ_a:-NDmHlqB0uQWsXmtFZ_b:b-xfjrqe) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/service/proposal_service.py#L175)):*
> ```Python
>             )
> 
>             progress_report["proposal_progress_pdf"] = progress_report[
> ```

I guess

```
progress_report["proposal_progress_pdf"] = progress_report["additional_pdf"]
```

should just be

```
progress_report["additional_pdf"]
```

?
___
*[`saltapi/service/proposal_service.py` line 194 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmISap5CXuWUF29DE6:-NDmISap5CXuWUF29DE7:b-lbii3c) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/service/proposal_service.py#L194)):*
> ```Python
>             )
>             return progress_report
>         else:
> ```

Given the `if` and `else` are quite distant from each other, it might be better to handle the else part fist so rot speak:

```
if not progress_report:
    raise NotFoundError("...")

...
```    
___
*[`saltapi/service/proposal_service.py` line 196 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmItJd8aup2Nx0TRKh:-NDmItJd8aup2Nx0TRKi:bru91ca) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/service/proposal_service.py#L196)):*
> ```Python
>         else:
>             raise NotFoundError(
>                 "No progress report for proposal {}".format(proposal_code)
> ```

Why don't you use `f"... {proposal_code}"`?
___
*[`saltapi/service/proposal_service.py` line 199 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmJ7lQ0trmd_DwMSBv:-NDmJ7lQ0trmd_DwMSBw:b-zdtule) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/service/proposal_service.py#L199)):*
> ```Python
>             )
> 
>     def get_proposal_progress_report_pdf(
> ```

You are making the same database query twice (once for the report, once for the supplementary). Wouldn't it make sense to combine the two?


<!-- Sent from Reviewable.io -->

2022-10-07 13:04 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/86)* status: 19 of 22 files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1456 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDlZaZcAsRLCkavQQGE:-NDmRO5f7Gb1V3DmdWsk:b-ah83xv) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/repository/proposal_repository.py#L1456)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about using `Optional` rather than `Union[..., None]`? :-)
</blockquote></details>

Oh yes, it slipped my mind. Thanks!
___
*[`saltapi/repository/proposal_repository.py` line 1585 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDlaRU9Ci5rTLSWTeIT:-NDmTxII7Ac5hcivxYHN:b-gio7a9) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/repository/proposal_repository.py#L1585)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be better to exclude these partners in the SQL query already, which you can do by only including partners for which the `Virtual` column is not 0.
</blockquote></details>

Thanks! By the way, i had to include partners for which `Virtual` is not 1.
___
*[`saltapi/service/proposal_service.py` line 175 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmHlqB0uQWsXmtFZ_a:-NDmR_q44ytcB3FsHmgW:b-hs1ap6) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/service/proposal_service.py#L175)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess

```
progress_report["proposal_progress_pdf"] = progress_report["additional_pdf"]
```

should just be

```
progress_report["additional_pdf"]
```

?







</blockquote></details>

Actually, the right hand side should be `progress_report["proposal_progress_pdf"]`
___
*[`saltapi/service/proposal_service.py` line 194 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmISap5CXuWUF29DE6:-NDmUYKy2mE8Rt0fDlFQ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/service/proposal_service.py#L194)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given the `if` and `else` are quite distant from each other, it might be better to handle the else part fist so rot speak:

```
if not progress_report:
    raise NotFoundError("...")

...
```    
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 196 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmItJd8aup2Nx0TRKh:-NDmUdaWAevqjBpPbChq:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/service/proposal_service.py#L196)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you use `f"... {proposal_code}"`?
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 199 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmJ7lQ0trmd_DwMSBv:-NDmWlLt4fG1uyRO-eDK:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/service/proposal_service.py#L199)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are making the same database query twice (once for the report, once for the supplementary). Wouldn't it make sense to combine the two?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-07 15:08 UTC, hettlage requested changes
> Reviewed 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/86)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero, @hettlage, and @mofokeng-chaka)

___
*[`saltapi/repository/proposal_repository.py` line 1585 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDlaRU9Ci5rTLSWTeIT:-NDmx7DbDInxuK9CqksB:bp40kfm) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/repository/proposal_repository.py#L1585)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Thanks! By the way, i had to include partners for which `Virtual` is not 1.
</blockquote></details>

Ah, sorry, of course that's right.
___
*[`saltapi/service/proposal_service.py` line 175 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmHlqB0uQWsXmtFZ_a:-NDmyW9s-LUTbYp5o72_:b-texy3k) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/service/proposal_service.py#L175)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Actually, the right hand side should be `progress_report["proposal_progress_pdf"]`
</blockquote></details>

But then I guess

```
progress_report["proposal_progress_pdf"] = progress_report[
                "proposal_progress_pd"
            ]
```

should just be

```
progress_report["proposal_progress_pdf"] 
```

?
___
*[`saltapi/service/proposal_service.py` line 172 at r7](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmxJEJ5Tr6gDorbCxj:-NDmxJEJ5Tr6gDorbCxk:b-o3bwfu) ([raw file](https://github.com/saltastroops/salt-api/blob/57e19c20e1cdd730f627748690bc1b6867e4bbdc/saltapi/service/proposal_service.py#L172)):*
> ```Python
>                 f"No progress report for proposal {proposal_code}"
>             )
>         else:
> ```

More nitpicking: You don't need the `else`, as you won't get here if there is no progress report.


<!-- Sent from Reviewable.io -->

2022-10-10 05:51 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/86)* status: 20 of 22 files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/service/proposal_service.py` line 175 at r6](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmHlqB0uQWsXmtFZ_a:-NE-RQy6ByQRi8DcLOaL:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/c2f2770b6ed0f7be01091d099e118635326c7f67/saltapi/service/proposal_service.py#L175)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But then I guess

```
progress_report["proposal_progress_pdf"] = progress_report[
                "proposal_progress_pd"
            ]
```

should just be

```
progress_report["proposal_progress_pdf"] 
```

?
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 172 at r7](https://reviewable.io/reviews/saltastroops/salt-api/86#-NDmxJEJ5Tr6gDorbCxj:-NE-R4g0BCuT96gCxgdZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/57e19c20e1cdd730f627748690bc1b6867e4bbdc/saltapi/service/proposal_service.py#L172)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

More nitpicking: You don't need the `else`, as you won't get here if there is no progress report.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-10 09:54 UTC, hettlage approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/86)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2022-10-10 09:55 UTC, merged