updating proposal progress
saltastroops/salt-api pull request #92
Opened 2022-09-15 15:34 UTC by Eb-Zeero

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/salt-api/92)

2022-10-06 17:10 UTC, hettlage requested changes
> Reviewed 3 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/92)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero)

___
*[`pyproject.toml` line 33 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiG-vO7vI2iIxaskwX:-NDiG-vO7vI2iIxaskwY:bvdfpa) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/pyproject.toml#L33)):*
> ```TOML
> PyPDF2 = "^2.11.0"
> glop = "^0.1.1"
> ```

What is glop used for?
___
*[`saltapi/util.py` line 157 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhtU2q0QKxasF9hkiq:-NDhtU2q0QKxasF9hkir:blt9v4j) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/util.py#L157)):*
> ```Python
> def as_form(cls: Type[BaseModel]):
>     """
>     Adds an as_form class method to decorated models. The as_form class method
> ```

I don't see what this decorator is for exactly. So a bit more of an explanation might help.

Also, was this copied from somewhere? If so, a reference would be good.
___
*[`saltapi/repository/proposal_repository.py` line 1334 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhu_1v0vhhhlTQ-MiH:-NDhu_1v0vhhhlTQ-MiI:bbtuzlc) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/repository/proposal_repository.py#L1334)):*
> ```Python
>     @staticmethod
>     def generate_proposal_progress_filename(
>             file_content: str,
> ```

Given my comment regarding the use of the function elsewhere, the `file_content` should be `bytes` rather than `str`.
___
*[`saltapi/repository/proposal_repository.py` line 1699 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhwO4u8rRFqgvMlaTE:-NDhwO4u8rRFqgvMlaTF:bm5n4pb) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/repository/proposal_repository.py#L1699)):*
> ```Python
>             }
> 
>     def put_proposal_progress(
> ```

I'm puzzled by the fact why a PUT method INSERTs into database, rather than making INSERTs or UPDATEs?

Also, the name insert_proposal_progress might be a bit misleading?
___
*[`saltapi/repository/proposal_repository.py` line 1707 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhvJok7SOLb-KVp2QU:-NDhvJol2-5cuD1wVKl0:b9xs4g1) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/repository/proposal_repository.py#L1707)):*
> ```Python
>     ) -> None:
>         """
>         Insert the proposal progress to the database
> ```

to > into ?
___
*[`saltapi/service/permission_service.py` line 305 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhxADG08-EiN3i9olo:-NDhxADG08-EiN3i9olp:bj2elx0) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/service/permission_service.py#L305)):*
> ```Python
>         """
>         may_update = (
>             self.user_repository.is_administrator(user.username)
> ```

I guess the Principal Contact should have the permission as well?
___
*[`saltapi/service/proposal_service.py` line 145 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiEJe570nMxv__ENyv:-NDiEJe637y1_MYMECBq:bavvlg8) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/service/proposal_service.py#L145)):*
> ```Python
>                         "observed_time": ot["observed_time"]
>                     })
>         cpp = create_proposal_progress_html(
> ```

cpp might be a slightly unfortunately named -- why not use "html" or "html_content"?
___
*[`saltapi/service/proposal_service.py` line 169 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiEf31Bxoia_h0CZcD:-NDiEf31Bxoia_h0CZcE:b-2nfkg3) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/service/proposal_service.py#L169)):*
> ```Python
>                 str(additional_pdf.file.read()), is_supplementary=True
>             )
>             open(base_dir + additional_pdf_filename, "wb").write(additional_pdf.file.read())
> ```

You aren't explicitly closing the file... So you should either use a `with` block or the use `Path` and its relevant method for writing bytes.
___
*[`saltapi/web/api/proposal_progress.py` line 85 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiFFH84Nmu4uKPX67K:-NDiFFH84Nmu4uKPX67L:b-zi3xwm) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/web/api/proposal_progress.py#L85)):*
> ```Python
>     """
>     with UnitOfWork() as unit_of_work:
>         # permission_service = services.permission_service(unit_of_work.connection)
> ```

Why are these lines commented out?
___
*[`saltapi/web/api/proposal_progress.py` line 95 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiFQMFEfGr7AUJ_2pH:-NDiFQMFEfGr7AUJ_2pI:bwsb6sw) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/web/api/proposal_progress.py#L95)):*
> ```Python
>             additional_pdf
>         )
>         # TODO Commit to the database when no error is raised.
> ```

Is the TODO still relevant?
___
*[`saltapi/web/schema/proposal.py` line 546 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiDClH0iuPKWj-j339:-NDiDClH0iuPKWj-j33A:b-txr9u8) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/web/schema/proposal.py#L546)):*
> ```Python
>         ...,
>         title="Partner",
>         description="The partner requesting time from.",
> ```

The partner from which time is requested.
___
*[`saltapi/web/schema/proposal.py` line 572 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiFo-7AOoTXtnwXiz6:-NDiFo-7AOoTXtnwXiz7:b2higuh) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/web/schema/proposal.py#L572)):*
> ```Python
> 
> @as_form
> class ProposalProgressReport(ProgressReport):
> ```

The names ProgressReport, ProposalProgress and ProposalProgressReport might need discussion...


<!-- Sent from Reviewable.io -->

2022-10-07 09:17 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/92)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[`pyproject.toml` line 33 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiG-vO7vI2iIxaskwX:-NDlYs894M40qRrFRydJ:b-xkfw0z) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/pyproject.toml#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What is glop used for?
</blockquote></details>

not used forgot to remove
___
*[`saltapi/util.py` line 157 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhtU2q0QKxasF9hkiq:-NDl_t4RCiKI4_LrB6ZZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/util.py#L157)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see what this decorator is for exactly. So a bit more of an explanation might help.

Also, was this copied from somewhere? If so, a reference would be good.
</blockquote></details>

Done.



_Code quote:_
```Python
as_form(cls: Type[BaseModel]):
```
___
*[`saltapi/repository/proposal_repository.py` line 1334 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhu_1v0vhhhlTQ-MiH:-NDladIm8_Qm4GJN51_z:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/repository/proposal_repository.py#L1334)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given my comment regarding the use of the function elsewhere, the `file_content` should be `bytes` rather than `str`.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1699 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhwO4u8rRFqgvMlaTE:-NDliiqx-yNVmrKFQisc:bu9zql) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/repository/proposal_repository.py#L1699)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm puzzled by the fact why a PUT method INSERTs into database, rather than making INSERTs or UPDATEs?

Also, the name insert_proposal_progress might be a bit misleading?
</blockquote></details>

I named it post_proposal_progress
___
*[`saltapi/repository/proposal_repository.py` line 1707 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhvJok7SOLb-KVp2QU:-NDlazlrA35EWnCZ_IM0:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/repository/proposal_repository.py#L1707)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

to > into ?
</blockquote></details>

Done.
___
*[`saltapi/service/permission_service.py` line 305 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhxADG08-EiN3i9olo:-NDlbQ6d0LpQlug47lbF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/service/permission_service.py#L305)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess the Principal Contact should have the permission as well?
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 145 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiEJe570nMxv__ENyv:-NDlbYjj1S2JCInJupAr:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/service/proposal_service.py#L145)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

cpp might be a slightly unfortunately named -- why not use "html" or "html_content"?
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 169 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiEf31Bxoia_h0CZcD:-NDlbnZp0V_pqRbmg7s8:b-3h87rt) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/service/proposal_service.py#L169)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You aren't explicitly closing the file... So you should either use a `with` block or the use `Path` and its relevant method for writing bytes.
</blockquote></details>

using with
___
*[`saltapi/web/api/proposal_progress.py` line 85 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiFFH84Nmu4uKPX67K:-NDlbqlT8sJ3djNoOJfo:b-g17iml) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/web/api/proposal_progress.py#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why are these lines commented out?
</blockquote></details>

Nice catch forgot to uncomment.
___
*[`saltapi/web/api/proposal_progress.py` line 95 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiFQMFEfGr7AUJ_2pH:-NDlhh7Z6q31Ry2Gg8sa:b7b9ddq) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/web/api/proposal_progress.py#L95)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is the TODO still relevant?
</blockquote></details>

Yes, I need to add the commit message.
Added.
___
*[`saltapi/web/schema/proposal.py` line 546 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiDClH0iuPKWj-j339:-NDli0812W_utOTkhyVM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/web/schema/proposal.py#L546)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The partner from which time is requested.
</blockquote></details>

Done.
___
*[`saltapi/web/schema/proposal.py` line 572 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDiFo-7AOoTXtnwXiz6:-NDlitOg4sMlEfIX3jAz:b-4ipuqk) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/web/schema/proposal.py#L572)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The names ProgressReport, ProposalProgress and ProposalProgressReport might need discussion...
</blockquote></details>

Yes we can discuss 


<!-- Sent from Reviewable.io -->

2022-10-07 14:47 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/92)* status: all files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`saltapi/util.py` line 158 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmroDu3mEP--izgxrQ:-NDmroDu3mEP--izgxrR:b-90desc) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/util.py#L158)):*
> ```Python
>     """
>     Adds an as_form class method to decorated models. The as_form class method
>     can be used with FastAPI endpoints. The as_form decorator will convert the BaseModel to FormData
> ```

(Full stop missing at the end.)
___
*[`saltapi/util.py` line 160 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmrtCI5ROzSd0B-0is:-NDmrtCI5ROzSd0B-0it:b-928nld) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/util.py#L160)):*
> ```Python
>     can be used with FastAPI endpoints. The as_form decorator will convert the BaseModel to FormData
> 
>     reference:
> ```

reference > Reference
___
*[`saltapi/repository/proposal_repository.py` line 1699 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhwO4u8rRFqgvMlaTE:-NDms4Oo0Q0RIPsZW0c4:bsmuwet) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/repository/proposal_repository.py#L1699)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I named it post_proposal_progress
</blockquote></details>

Ah, but this might not be a naming issue. What happens if you resubmit a progress report? (And post arguably is incorrect, as you have an id for the progress report already...)
___
*[`saltapi/service/proposal_service.py` line 153 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmt_Rx2RGLVYU1UTvY:-NDmt_Rx2RGLVYU1UTvZ:b-r0adr) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/service/proposal_service.py#L153)):*
> ```Python
>         )
>         base_dir = f"{get_settings().proposals_dir}/{proposal_code}/Included/"
>         proposal_progress_filename = self.repository.generate_proposal_progress_filename(html_content)
> ```

I'd argue that the filename should be based on the pdf content, not the html.
___
*[`saltapi/service/proposal_service.py` line 167 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmtmkL2cAptDnUSl-s:-NDmtmkL2cAptDnUSl-t:bskhqfp) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/service/proposal_service.py#L167)):*
> ```Python
>         if additional_pdf:
>             additional_pdf_filename = self.repository.generate_proposal_progress_filename(
>                 additional_pdf.file.read(), is_supplementary=True
> ```

I see two problems here:

1. You are not awaiting `additional_pdf.file.read()`.
2. You are reading the file content twice. This is like to fail (or give an empty string the second time), unless yiu "rewound' after the first read. But this is likely to be impossible.
___
*[`saltapi/service/proposal_service.py` line 170 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmu5sa84JvvGs5b8Uv:-NDmu5sa84JvvGs5b8Uw:bu6xv6u) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/service/proposal_service.py#L170)):*
> ```Python
>             )
>             with open(base_dir + additional_pdf_filename, "wb") as f:
>                 f.write(additional_pdf.file.read())
> ```

See previous comment.


<!-- Sent from Reviewable.io -->

2022-10-11 09:35 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/92)* status: 5 of 9 files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/util.py` line 158 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmroDu3mEP--izgxrQ:-NE-eZ-K5I0XAIzg9PPf:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/util.py#L158)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

(Full stop missing at the end.)
</blockquote></details>

Done.
___
*[`saltapi/util.py` line 160 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmrtCI5ROzSd0B-0is:-NE-eZPhCP-7T4A-pZs4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/util.py#L160)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

reference > Reference
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1699 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhwO4u8rRFqgvMlaTE:-NE5OQu45I17NM2wh_Du:b3fd6s8) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/repository/proposal_repository.py#L1699)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, but this might not be a naming issue. What happens if you resubmit a progress report? (And post arguably is incorrect, as you have an id for the progress report already...)
</blockquote></details>

getting lost is it put like now
___
*[`saltapi/service/proposal_service.py` line 153 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmt_Rx2RGLVYU1UTvY:-NE1DC_R2LNXjT2e-DBo:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/service/proposal_service.py#L153)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd argue that the filename should be based on the pdf content, not the html.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 167 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmtmkL2cAptDnUSl-s:-NE5LN0G09_6GnKDsBjd:bo94v4x) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/service/proposal_service.py#L167)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I see two problems here:

1. You are not awaiting `additional_pdf.file.read()`.
2. You are reading the file content twice. This is like to fail (or give an empty string the second time), unless yiu "rewound' after the first read. But this is likely to be impossible.
</blockquote></details>

now awaiting
file now is opened once
___
*[`saltapi/service/proposal_service.py` line 170 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmu5sa84JvvGs5b8Uv:-NE5LWFwAvIo90VPRQDm:b-2kigy4) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/service/proposal_service.py#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See previous comment.
</blockquote></details>

fixed.

Point to discuss.

the temp file generated for the content is always a new file may be the date created changed...
can we discuss this aswell


<!-- Sent from Reviewable.io -->

2022-10-19 09:50 UTC, hettlage requested changes
> Reviewed 1 of 5 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/92)* status: all files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/repository/proposal_repository.py` line 1699 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhwO4u8rRFqgvMlaTE:-NEjZtRxEv-vg0Tjkf0O:b5ksx2a) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/repository/proposal_repository.py#L1699)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

getting lost is it put like now
</blockquote></details>

When I made the comment, you were inserting, but not updating existing details (as you do now).
___
*[`saltapi/repository/proposal_repository.py` line 1707 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjZlUn7IlXBIexhGTf:-NEjZlUn7IlXBIexhGTg:b-i27md8) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/repository/proposal_repository.py#L1707)):*
> ```Python
>     ) -> None:
>         """
>         Insert the proposal progress into the database
> ```

Maybe better:

Insert the proposal progress into the database, or update the existing one.
___
*[`saltapi/repository/proposal_repository.py` line 1382 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjZMqM-0MarQ79qACG:-NEjZMqM-0MarQ79qACH:bgc4c88) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/repository/proposal_repository.py#L1382)):*
> ```Python
>     :supplementary_path,
>     NOW()
> )ON DUPLICATE KEY UPDATE 
> ```

Space between ")" and "ON".
___
*[`saltapi/repository/proposal_repository.py` line 1434 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjZUp_CP9jk4C2xBnQ:-NEjZUp_CP9jk4C2xBnR:bgc4c88) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/repository/proposal_repository.py#L1434)):*
> ```Python
>     :requested_time_percent,
>     :requested_time_amount
> ) ON DUPLICATE KEY UPDATE
> ```

Space between ")" and "ON".
___
*[`saltapi/repository/proposal_repository.py` line 1477 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjZVsC91i17LEd5Um4:-NEjZVsC91i17LEd5Um5:bgc4c88) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/repository/proposal_repository.py#L1477)):*
> ```Python
>     (SELECT Transparency_Id FROM Transparency WHERE Transparency = :transparency),
>     :observing_conditions_description
> )ON DUPLICATE KEY UPDATE 
> ```

Space between ")" and "ON".
___
*[`saltapi/service/proposal_service.py` line 170 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmu5sa84JvvGs5b8Uv:-NEjcrK627GpardMrDVR:b64bs26) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/service/proposal_service.py#L170)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

fixed.

Point to discuss.

the temp file generated for the content is always a new file may be the date created changed...
can we discuss this aswell

</blockquote></details>

Sure, we can discuss if you want.
___
*[`saltapi/service/proposal_service.py` line 198 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjaOcrC2U70Bd9cQLt:-NEjaOcrC2U70Bd9cQLu:bixmbss) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/service/proposal_service.py#L198)):*
> ```Python
>         )
>         base_dir = f"{get_settings().proposals_dir}/{proposal_code}/Included/"
>         with NamedTemporaryFile() as tmp:
> ```

I'm not convinced you need this temporary file, see below.
___
*[`saltapi/service/proposal_service.py` line 209 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjaWNiAcFp0uZ0zS9l:-NEjaWNiAcFp0uZ0zS9m:b-3h0v1g) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/service/proposal_service.py#L209)):*
> ```Python
>             }
>             tmp_filename = tmp.name
>             open(tmp_filename, "w").write(html_content)
> ```

From what I can see, you write the HTML content to the temporary file, and then you read it from the file to pass it on to `generate_proposal_progress_filename`. Why don't you just pass in the content directly, making the temporary file unnecessary?
___
*[`saltapi/service/proposal_service.py` line 216 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjbtjWEVKZnJe4trcE:-NEjbtjWEVKZnJe4trcF:b-hvdwpw) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/service/proposal_service.py#L216)):*
> ```Python
>         additional_pdf_filename = None
>         if additional_pdf:
>             with NamedTemporaryFile() as tmp:
> ```

I don't think this temporary file is necessary? You are just reading the content of an empty file?
___
*[`saltapi/service/proposal_service.py` line 223 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjcRHG8fc2RexTKpMy:-NEjcRHG8fc2RexTKpMz:bm58xnz) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/service/proposal_service.py#L223)):*
> ```Python
>                     )
>                     with open(base_dir + additional_pdf_filename, 'wb+') as out_file:
>                         out_file.write(content)  # async write
> ```

I don't think the write is async?
___
*[`saltapi/web/api/proposal_progress.py` line 32 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjd6VaDwpITXNicLFM:-NEjd6VaDwpITXNicLFN:b9zjabh) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/web/api/proposal_progress.py#L32)):*
> ```Python
>             ...,
>             title="Proposal code",
>             description="Proposal code of the proposal whose progress reports pdfs are requested.",
> ```

progress reports pdfs > progress report pdf URLs


<!-- Sent from Reviewable.io -->

2022-10-19 11:20 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/92)* status: all files reviewed, 11 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/repository/proposal_repository.py` line 1699 at r2](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDhwO4u8rRFqgvMlaTE:-NEjtkmtA7fl4NwnAOYU:b-k73z76) ([raw file](https://github.com/saltastroops/salt-api/blob/f16835dbf91c6ddfac67dd112db9f371388c050d/saltapi/repository/proposal_repository.py#L1699)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

When I made the comment, you were inserting, but not updating existing details (as you do now).
</blockquote></details>

thanks
___
*[`saltapi/repository/proposal_repository.py` line 1707 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjZlUn7IlXBIexhGTf:-NEjtuor2wGF86V0Iqxp:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/repository/proposal_repository.py#L1707)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better:

Insert the proposal progress into the database, or update the existing one.
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1382 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjZMqM-0MarQ79qACG:-NEjtVi337UCRe_wnJ8H:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/repository/proposal_repository.py#L1382)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Space between ")" and "ON".
</blockquote></details>

Done.
___
*[`saltapi/repository/proposal_repository.py` line 1434 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjZUp_CP9jk4C2xBnQ:-NEjtW91-tR_CbgLLLll:b-a8hxbj) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/repository/proposal_repository.py#L1434)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Space between ")" and "ON".
</blockquote></details>

there is space
___
*[`saltapi/repository/proposal_repository.py` line 1477 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjZVsC91i17LEd5Um4:-NEjtgTc9yMg4r1aKC7Q:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/repository/proposal_repository.py#L1477)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Space between ")" and "ON".
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 170 at r3](https://reviewable.io/reviews/saltastroops/salt-api/92#-NDmu5sa84JvvGs5b8Uv:-NEjxCrI9du1zBjLXLry:b-vsa09r) ([raw file](https://github.com/saltastroops/salt-api/blob/4cd9e93e941b27f4913d8eedaae7f4f0100eb31b/saltapi/service/proposal_service.py#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sure, we can discuss if you want.
</blockquote></details>

We discussed this already it should be fixed now
___
*[`saltapi/service/proposal_service.py` line 198 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjaOcrC2U70Bd9cQLt:-NEjw2K01avL5Jhc2EH4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/service/proposal_service.py#L198)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced you need this temporary file, see below.
</blockquote></details>

Done.
___
*[`saltapi/service/proposal_service.py` line 209 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjaWNiAcFp0uZ0zS9l:-NEjw4_r9L8FW0yoENl9:b-408qmq) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/service/proposal_service.py#L209)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

From what I can see, you write the HTML content to the temporary file, and then you read it from the file to pass it on to `generate_proposal_progress_filename`. Why don't you just pass in the content directly, making the temporary file unnecessary?
</blockquote></details>

this was done somehow not fixed anymore.
done now
___
*[`saltapi/service/proposal_service.py` line 216 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjbtjWEVKZnJe4trcE:-NEjwbwX6uC3t_Hvnj8q:b-jujlbz) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/service/proposal_service.py#L216)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this temporary file is necessary? You are just reading the content of an empty file?
</blockquote></details>

Also, this past was fixed as well.
done now
___
*[`saltapi/service/proposal_service.py` line 223 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjcRHG8fc2RexTKpMy:-NEjy6L12hIUqxQd_I3M:bo67sc0) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/service/proposal_service.py#L223)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the write is async?
</blockquote></details>

This might have fixed itself.
please double check.
___
*[`saltapi/web/api/proposal_progress.py` line 32 at r5](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjd6VaDwpITXNicLFM:-NEjxrHr3Nvzu8dp7JrQ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/9e798190551e7833b500c48c380b4bb3668e589b/saltapi/web/api/proposal_progress.py#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

progress reports pdfs > progress report pdf URLs
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-19 11:29 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/92)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`saltapi/service/proposal_service.py` line 138 at r6](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjzBIB-Dw93IpujZDb:-NEjzBIB-Dw93IpujZDc:b-amkm77) ([raw file](https://github.com/saltastroops/salt-api/blob/cb52a5a2fad2b0f35d8ec92305fe369795d3e30e/saltapi/service/proposal_service.py#L138)):*
> ```Python
>         return self.repository.get_progress_report(proposal_code, semester)
> 
>     def get_proposal_progress_report_pdf(
> ```

Shouldn't this method be called `get_proposal_progress_report_pdfs`?
___
*[`saltapi/web/api/proposal_progress.py` line 219 at r6](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEk-6s6-cLd1u_iYOiC:-NEk-6s6-cLd1u_iYOiD:b-4w2zxb) ([raw file](https://github.com/saltastroops/salt-api/blob/cb52a5a2fad2b0f35d8ec92305fe369795d3e30e/saltapi/web/api/proposal_progress.py#L219)):*
> ```Python
> 
>         filename = "ProgressReportSupplement_{}.pdf".format(semester)
>         print("CCC: ", additional_pdf_path)
> ```

Unnecessary print statement.


<!-- Sent from Reviewable.io -->

2022-10-19 12:53 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/92)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`saltapi/service/proposal_service.py` line 138 at r6](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEjzBIB-Dw93IpujZDb:-NEkIRJbDyicLg3vr2OP:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/cb52a5a2fad2b0f35d8ec92305fe369795d3e30e/saltapi/service/proposal_service.py#L138)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this method be called `get_proposal_progress_report_pdfs`?
</blockquote></details>

Done.
___
*[`saltapi/web/api/proposal_progress.py` line 219 at r6](https://reviewable.io/reviews/saltastroops/salt-api/92#-NEk-6s6-cLd1u_iYOiC:-NEkIWpABJBdJlxHb7jV:b-7jc0aw) ([raw file](https://github.com/saltastroops/salt-api/blob/cb52a5a2fad2b0f35d8ec92305fe369795d3e30e/saltapi/web/api/proposal_progress.py#L219)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary print statement.
</blockquote></details>

sorry


<!-- Sent from Reviewable.io -->

2022-10-19 13:46 UTC, hettlage approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2022-10-19 13:47 UTC, merged